### ISSUE TITLE
PrometheusCollector is not filtering application metrics

### ISSUE THREAD

**Issue by jszczepkowski** [google/cadvisor#1005]
If you configure prometheus collector for application metrics, all metrics exposed on the endpoint will be collected. Filtering metrics by name on a base of `metrics_config` is not implemented.

**Comment by jszczepkowski** [comment]
According to https://github.com/google/cadvisor/blob/master/docs/application_metrics.md, if you provide the following config:
```
{
  "endpoint" : "http://localhost:8000/metrics",
  "metrics_config" : [
    {
      "scheduler_binding_latency",
      "scheduler_e2e_scheduling_latency",
      "scheduling_algorithm_latency"
    }
  ]
}
```
only `scheduler_binding_latency`, `scheduler_e2e_scheduling_latency` and `scheduling_algorithm_latency` metrics should be exposed. However, in practice, all metrics from `http://localhost:8000/metrics` are exposed.

BTW: the documentation is also broken. The sample config file should be:
```
{
  "endpoint" : "http://localhost:8080/metrics",
  "metrics_config" : [
      "scheduler_binding_latency",
      "scheduler_e2e_scheduling_latency",
      "scheduling_algorithm_latency"
  ]
}
```
and the docker label pointing to the file for Prometheus collector should be named `io.cadvisor.metric.prometheus`.

**Comment by DirectXMan12** [comment]
I can take a look at fixing this.
