### ISSUE TITLE
Delay when pushing data to influxDB

### ISSUE THREAD

**Issue by mboussaa** [google/cadvisor#1024]
I am using a java http client that sends sql queries via http to influxdb in order to get runtime metrics that cadvisor keep pushing to the TSDB.

something like this:
```
//Thread.sleep(30000);
HttpGet httpGet = new HttpGet("http://10.0.0.22:8086/db/cadvisorDB/series?u=root&p=root&q=select%20max(memory_usage)%20from%20stats%20where%20container_name%20%3D%27execution_container%")
CloseableHttpResponse requestResponse = httpclient.execute(httpGet);
```

I run first cadvisor and influxdb then, I run a sample stress container. After that, I execute this http request to get the max memory usage but I got an empty response. The problem is that I have to wait around 30 seconds before executing this request. by doing so, I can get needed information (max memory usage). 

It seems like when cadvisor is dumping data to influxdb, there is a small delay until the values are stored.

Is there a way to accelerate the process of sending runtime metrics to influxDB ? 

Thanks in advance

**Comment by vishh** [comment]
https://github.com/google/cadvisor/blob/master/storage/common_flags.go#L28

**Comment by mboussaa** [comment]
@vishh  +1. Thank you. It would be great to add that to the storage documentation. You can close this issue.
