### ISSUE TITLE
Docker Hub Image Push On Every Release Cut?

### ISSUE THREAD

**Issue by amcrn** [google/cadvisor#1025]
Is there any chance that on a new cadvisor release (https://github.com/google/cadvisor/releases), said version gets automatically pushed to the public Docker Hub (https://hub.docker.com/r/google/cadvisor/tags/) ?

At the moment it looks to be on-demand. Example: the latest non-canary image on the public Docker Hub is 0.19.3. Releases 0.19.4, 0.19.5, 0.20.0, and 0.20.1 are not available.

Thanks!

**Comment by vishh** [comment]
@pwittrock: Can we update the cAdvisor canary jenkins job to push images whenever a new tag is created?

**Comment by pwittrock** [comment]
Yeah I will start looking into how to do this

**Comment by laurikimmel** [comment]
+1 - it would be nice
 
Version 0.20.5 was released 3 days ago. Latest release available in Docker Hub is still 0.20.4.

**Comment by amcrn** [comment]
This looks to have been solved (Docker Hub is up to date as of now). Closing.
