### ISSUE TITLE
Is it necessary for cadvisor to add the label-selector mechanism ? 

### ISSUE THREAD

**Issue by wangzhezhe** [google/cadvisor#1034]
Hi !
I want to know if  it is necessary for cadvisor to add the label-selector mechanism ? It seems we do not need to monitor all the containers on the machine , because the containers come and go so fast just as [this article](https://www.datadoghq.com/blog/the-docker-monitoring-problem/) mentioned.

**Comment by vishh** [comment]
On Tue, Jan 5, 2016 at 2:27 AM, wangzhezhe <notifications@github.com> wrote:

> Hi !
> I want to know if it is necessary for cadvisor to add the label-selector
> mechanism ?
>
Sure. If your nodes have a lot of containers (cgroups) that can be helpful
or if you want to run multiple cadvisor instances.

> It seems we do need to monitor all the containers on the machine , because
> the containers come and go so fast just as this article
> <https://wwwdatadoghqcom/blog/the-docker-monitoring-problem/> mentioned
>
The churn issue can be solved by pushing metrics from cadvisor instead of
polling.
