### ISSUE TITLE
cAdvisor and RPI docker images

### ISSUE THREAD

**Issue by mboussaa** [google/cadvisor#1042]
Is cadvisor capable of gathering performance data even for RPI docker containers running in Raspberry devices?

like in http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/

**Comment by vishh** [comment]
As long as the standard Linux APIs are available, cAdvisor should work on
Rasberry devices as well.
I assume the docker APIs don't change on those devices. If so, cAdvisor's
docker integration should also work.
I don't have a Rasberry device to validate my claims though.

**Comment by mboussaa** [comment]
So I have to run a cadvisor container within Rasberry device. it is not possible to gather performance of rasberry containers from my host machine?

**Comment by vishh** [comment]
Are you referring to *remote* monitoring? If so, that is not possible. cAdvisor should be able to run as a standalone process on most flavors of Linux.

**Comment by mboussaa** [comment]
Yes I mean from my linux machine is it possible to monitor RPI containers ?

**Comment by vishh** [comment]
Remote monitoring is not possible

**Comment by jimmidyson** [comment]
You will need to re-build cadvisor specific to the RPI arch as it's an ARM processor I believe. We only provide x86_64 arch builds I'm afraid.
