### ISSUE TITLE
Add support for Hyper

### ISSUE THREAD

**Issue by feiskyer** [google/cadvisor#1050]
This issues tracks cAdvisor support for [Hyper](hyper.sh), works including:
- make cAdvisor container runtime general
- pod level APIs
- hyper pod stats
- hyper container stats

CC @vishh @yifan-gu   

Ref https://github.com/google/cadvisor/issues/858 https://github.com/google/cadvisor/pull/1049

**Comment by vishh** [comment]
cc @timstclair

**Comment by feiskyer** [comment]
CC @resouer.

**Comment by euank** [comment]
Just to throw in a contrarian note: cAdvisor today works with cgroups, as do docker and rkt (for most stage1s). The rkt integration does not handle the case of a hypervisor stage1 (at least not at an app level) either afaik.

I imagine hyper integration would just have to look like 1) linking a chain of cadvisor processes together (one running in the virt, one running with the kubelet) 2) simply querying the hypervisor for metrics somehow and taking them as truth, or 3) the hypervisor mocking out a cgroup-like filesystem for cadvisor to consume.

I'd argue that if it's the 2nd option, which I suspect it is, that it should not be cadvisor's place to integrate with that runtime, but rather kubelet's place to do so.

I feel like I've run into such discussion of whether cadvisor should actually be responsible for non-cgroup stats ever, but I can't find it now, so if anyone has a link to that or a conclusion from it, that would be helpful.

At the very least, I'd like to hear a little more detail about what the planned integration would look like if there's any idea yet.

**Comment by yujuhong** [comment]
I agree that we need to determine how runtime should integrate with kubelet when it comes to metrics (via cadvisor, provides metrics directly in CRI, or some form of hybrid solution?) Let's move the discussion to https://github.com/kubernetes/kubernetes/issues/27097.
