### ISSUE TITLE
Fix flaky gcloud auth failures for e2e tests

### ISSUE THREAD

**Issue by pwittrock** [google/cadvisor#1056]
cadvisor integration tests frequently fail due to gcloud auth failures.  The failures appear to be flaky.  When running 6 integration test targets in parallel, only 50% may fail with a message about missing user credentials, while the other 50% will pass, successfully finding the credentials.

> 10:40:51 F0115 18:40:51.267490   25726 runner.go:246] Error 0: failed to make remote testing directory: command "gcloud" ["compute" "ssh" "--zone" "us-central1-f" "_xxxxxxxxxxxxxx_" "--" "mkdir" "-p" "/tmp/cadvisor-25726"] failed with error: exit status 1 and output: "ERROR: (gcloud.compute.ssh) Your current active account [_xxxxxxxxxx@xxxxxxxx_] does not have any valid credentials\nPlease run:\n\n  $ gcloud auth login\n\nto obtain new credentials, or if you have already logged in with a\ndifferent account:\n\n  $ gcloud config set account ACCOUNT\n\nto select an already authenticated account to use. \n"

We should
1. Reduce the number of flaky test failures because they are causing false positive PR tests to failures and continuous build failures
2. Fix the root cause by configuring gcloud to prevent this, or stop using gcloud altogether and using ssh directly

**Comment by vishh** [comment]
Thanks for tackling this @pwittrock

**Comment by pwittrock** [comment]
#1108
