### ISSUE TITLE
Incorrect handling of docker container cgroup

### ISSUE THREAD

**Issue by dqminh** [google/cadvisor#1062]
cadvisor seems to mishandling the containers cgroup in a systemd host ( at least with 1.10-dev ). Given a host that has the following cgroup layout

```
/sys/fs/cgroup
-> /cpu
  -> /docker
    -> /2eedaaf84987b9297c012a2acb2aa114029b924d3216562653affba409f16333
  -> /system.slice
-> /systemd
```

This is the layout created when we are on a systemd host, but use the fs cgroup and set cgroup-parent to docker, and is the default setting. This setup will make `UseSystemd` returns true, while containers are actually in a different cgroup, so we miss the docker container data.

Perhaps we should just remove `UseSystemd` as running on a systemd host doesnt mean that it uses the systemd cgroup approach, or maybe docker should tell us which cgroup driver it is using via /info so we can check for it in `UseSystemd`

ping @vishh

**Comment by vishh** [comment]
We added a flag recently to disable systemd assumption. IIRC, the flag was
`--nosystemd=true`.

**Comment by dqminh** [comment]
Makes sense. Its sad that there isnt a nice way to auto-detect this though

**Comment by vishh** [comment]
Does docker expose the cgroupfs driver uses?

**Comment by dqminh** [comment]
It isnt, but i think it should. There's already a flag to choose the cgroupfs driver explicitly so it makes sense to expose it as the daemon's info. Meanwhile i will close this since we have a workaround.
