### ISSUE TITLE
Cadvisor scraping support for Docker TLS daemon enabled

### ISSUE THREAD

**Issue by sanguinius69** [google/cadvisor#1064]
Hi,

I don't know if my problem is relevant or not but I don't find any info about Cadvisor working with a docker daemon protected by TLS auth. Cadvisor can scrape some data but not the containers names or images, which is pretty annoying for monitoring. 
So I have the nice docker logs cadvisor: "[E0119 07:00:26.936595 00001 manager.go:201] Docker container factory registration failed: unable to communicate with docker daemon: dial unix /var/run/docker.sock: connection refused."
And same when trying to see the images for example at localhost:8080/docker/ I've got a nice "dial unix /var/run/docker.sock: connection refused"
So do you know where I can put my TLS keys (in the code/ in a flag/ wherever) ?
Thanks a lot and sorry if this an already treated topic but I couldn't find any direct topic related to this.
Cheers

**Comment by jimmidyson** [comment]
I don't think that tls is used for the unix socket - that's for TCP only. Are you running cadvisor as root or as a privileged container with docker socket mounted into container?

**Comment by sanguinius69** [comment]
Hi, thanks for the fast answer. No root I'm running it as a privileged container (run --volume=/:/rootfs:ro   --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8080:8080 --detach=true --name=cadvisor --privileged=true  google/cadvisor:latest)
I am wondering if this is not an issue with my docker configuration...as I was trying also sysdig cloud for monitoring, I had the same problem: no container names... their support suggested that I added to my docker OPTS (in /etc/default/docker to start as a service) "-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock" and it is working... even with only "-H unix:///var/run/docker.sock" working but as I want super tight security wondering if this is not a security flaw ?
Right now I am running my docker with only opts "-H=0.0.0.0:2376" as recommended here:
https://docs.docker.com/engine/articles/https/
Sorry I know this a bit out of Cadvisor scope..
Thanks again for the help.

**Comment by sanguinius69** [comment]
Just in case, indeed Cadvisor need the unix socket to scrape the names of containers. Thanks jimmydyson, I'll close the issue !
