### ISSUE TITLE
cAdvisor can not get other subcontainers' cpu metrics except cAdvisor container

### ISSUE THREAD

**Issue by wziyong** [google/cadvisor#1067]
I try to use cAdvisor to monitor the containers.And I set up cAdvisor according to the instruction.Everything seems OK.Then I start to check if it works well.
    What makes me puzzled is the following:
- The monitor page of cAdvisor container looks well,and the graphs of cpu/mem/net keep updating.
  Howerver,the monitor pages of other subcontainers seem something wrong,the graph of cpu keeps unchanged. 
#### My experimental facilities
- Docker Version:1.8.2-el7.centos
- Docker Execution Driver: native-0.2
- Kernel Version: 4.3.3-1.el7.elrepo.x86_64
- Operating System: CentOS Linux 7 (Core)
- CPUs: 16
- Total Memory: 15.66 GiB
#### The screenshot  of cAdvisor  monitor page.Everything works well.

The graph below is the screenshot of the monitor page of cAdvisor container.I started the job in the container named 'Master3'_(Master3 runs with [--privileged=true](https://github.com/google/cadvisor/blob/master/docs/running.md) and no resource limited)_ at about 12:20.From the graph we can see the cpu usage gets higher.
![qq 20160120122225](https://cloud.githubusercontent.com/assets/3320697/12439912/2a19fb4e-bf71-11e5-92b3-4a7016ad1a2b.png)
#### The screenshot  of other container named _Master3_ monitor page.

Howerver,when I view the monitor page of _Master3_,the graph of cpu keeps unchanged.but the graph of memory updates.
###### The memory graph

At about 12:20,the usage of memory gets higher.That seems fine.
![qq 20160120122247](https://cloud.githubusercontent.com/assets/3320697/12440157/8e736d8a-bf73-11e5-967a-d62677171cb1.png)
###### The cpu graph

_**The monitor curve keeps unchanged.Because the chart of memory usage looks well,I think that my configuration is right.So,I think that is a bug or something else.What's more,in my opinion,if we run a container with --cpuset-cpus,the graph of cpu usage should show the cores usage that set to the container rather than all of the cores. If someone could help me with this problem, I will be very grateful for that! :+1:**_
![qq 20160120122255](https://cloud.githubusercontent.com/assets/3320697/12440184/d75467de-bf73-11e5-805d-bcfded7c5b6a.png)

**Comment by dashpole** [comment]
Sorry for the lack of a timely response.  If you are still experiencing issues, please reopen this issue and provide the cadvisor log.
