### ISSUE TITLE
How to set storage_driver_buffer_duration shorter than 1 minute?

### ISSUE THREAD

**Issue by dmehra** [google/cadvisor#1074]
I'm running cadvisor-canary:latest build, sending data to InfluxDB, and trying to set -storage_driver_buffer_duration to a lower value than the default 1 minute, so I'd be able to chart current data from influx rather than having a delay. I thought that was working when I ran a release build in Nov-Dec with influx v0.8, setting `-storage_driver_buffer_duration=2s`. 

The reason I'm now running canary is to have influx v0.9 support, since that's what I need. When I tried setting the duration to 2s, the actual delay I saw was 2 minutes. That seems to match the setting to `60*time.Second` [in this code](https://github.com/google/cadvisor/blob/master/storage/common_flags.go) unless I'm misreading it. Trying a fractional value `-storage_driver_buffer_duration=0.1` resulted in not seeing data in influxdb for several minutes (then i stopped waiting). 

I'm now running with `-storage_driver_buffer_duration=1m` but would like a shorter delay.

This is the exact command line in my docker-compose file:

```
  image: google/cadvisor-canary:latest
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086 -logtostderr=true -v=9 -stderrthreshold=9 -storage_driver_buffer_duration=1m
```

**Comment by vishh** [comment]
AFAIK, you can set that flag to a shorter duration. Is that not working for
you?

**Comment by dmehra** [comment]
Correct, when I set `-storage_driver_buffer_duration=2s` the actual delay is 2 minutes, not seconds.

**Comment by vishh** [comment]
Do the logs give any clues?

**Comment by dmehra** [comment]
When I tried running again with `-storage_driver_buffer_duration=2s` on a newer canary build, it worked as expected, doing writes to influx every 2 seconds. I cannot explain the earlier behavior; closing this issue as not reproducible.
