### ISSUE TITLE
Problem with container in a network

### ISSUE THREAD

**Issue by damianopezzotti** [google/cadvisor#1076]
Hi,
I have some containers running on an isolated network (not on bridge). The network is created using docker 1.9 new networking feature.
On cAdvisor UI I'm not able to see network section. I also tried to connect cAdvisor container to the container network, but nothing is changed.

Can you help me?

Thanks
Damiano

**Comment by jimmidyson** [comment]
Can you share how to recreate the issue please? Not sure we support the new networking feature properly yet but shouldn't be too hard to add in.

**Comment by damianopezzotti** [comment]
To reproduce the scenario you have to use Docker 1.9.1.

Create a new network
`docker network create test_cAdvisor`

Create a container attached to the network
`docker run -it --rm --name=myContainer --net=test_cAdvisor debian:latest bash`
And perform a lot of network traffic using curl or wget

If you inspect the network (`docker network inspect test_cAdvisor`) or inspect the container (`docker inspect myContainer`)
You can see that container is attached to the network.

Thanks
Damy

**Comment by damianopezzotti** [comment]
It works!

**Comment by jimmidyson** [comment]
Thanks for reporting back @damianopezzotti!

**Comment by damianopezzotti** [comment]
When will you release the fix on the docker hub?

2016-01-27 10:01 GMT+01:00 Jimmi Dyson <notifications@github.com>:

> Thanks for reporting back @damianopezzotti
> <https://github.com/damianopezzotti>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/cadvisor/issues/1076#issuecomment-175494856>.
>



-- 
Damiano Pezzotti
...................................... . .
Software Architect | Alambitco
mobile +39 333 2116258
fax +39 02 700432209
email damy@alambitco.com
web www.alambitco.com
flickr www.flickr.com/photos/damianopezzotti
linkedin www.linkedin.com/in/damianopezzotti
pgp id 0x12DFD989

**Comment by jimmidyson** [comment]
just waiting for another runc tag & update godeps with that & i will release ASAP after that - not too long i hope.

**Comment by damianopezzotti** [comment]
Great.
Thanks

2016-01-27 10:07 GMT+01:00 Jimmi Dyson <notifications@github.com>:

> just waiting for another runc tag & update godeps with that & i will
> release ASAP after that - not too long i hope.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/cadvisor/issues/1076#issuecomment-175497358>.
>



-- 
Damiano Pezzotti
...................................... . .
Software Architect | Alambitco
mobile +39 333 2116258
fax +39 02 700432209
email damy@alambitco.com
web www.alambitco.com
flickr www.flickr.com/photos/damianopezzotti
linkedin www.linkedin.com/in/damianopezzotti
pgp id 0x12DFD989
