### ISSUE TITLE
Build broken on HEAD

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#1086]
cc @jimmidyson 

I'm unable to build from HEAD. 

$ godep go build ./...
container/raw/handler.go:38:2: no buildable Go source files in /tmp/godeps/src/github.com/google/cadvisor/Godeps/_workspace/src/golang.org/x/exp/inotify
godep: go exit status 1

**Comment by jimmidyson** [comment]
Does `make build` work for you? Confused how this can't work if it works on CI...

**Comment by vishh** [comment]
Nope. `make build` doesn't work either.

**Comment by jimmidyson** [comment]
I can only think this is something in your environment - just cloned cadvisor to clean GOPATH, run make build & it works fine.

**Comment by jimmidyson** [comment]
Are you building this on non-linux platform?

**Comment by vishh** [comment]
Nope. Building on linux only. AFAIK @timstclair has issues building as well.

**Comment by jimmidyson** [comment]
But there are buildable sources in there... for Linux at least - `inotify_linux.go`.

Also this hasn't changed in a long time.

**Comment by vishh** [comment]
Err. Broken godeps :( Sorry for the confusion. I need to get back to switching over to glide.
