### ISSUE TITLE
cadvisor doesn't identify Docker 1.10 containers correctly when running with systemd

### ISSUE THREAD

**Issue by jimmidyson** [google/cadvisor#1091]
Container names have changed it seems so can't identify Docker containers properly.

**Comment by timothysc** [comment]
:-(

**Comment by dqminh** [comment]
hmm is it about cadvisor needs to run with `nosystemd` when using the cgroupfs ( the default ) https://github.com/google/cadvisor/issues/1062 ?

**Comment by vishh** [comment]
I think #1095 fixed this issue. `nosytemd`flag should no longer be a necessity.

**Comment by dashpole** [comment]
closed via #1095
