### ISSUE TITLE
FS usage tracked using du even with devicemapper

### ISSUE THREAD

**Issue by jimmidyson** [google/cadvisor#1093]
Throws lots of errors. This should be disabled if devicemapper storage driver until we support devicemapper container usage.

@vishh This is changed in some recent changes you've made. Can you please fix this up so we don't run du for devicemapper storage driver?

**Comment by jimmidyson** [comment]
Fixing this up now.

**Comment by timstclair** [comment]
I believe this was fixed by https://github.com/google/cadvisor/pull/1097. Please reopen if that is not correct.
