### ISSUE TITLE
Integration tests broken

### ISSUE THREAD

**Issue by jimmidyson** [google/cadvisor#1096]
Most (all?) PRs are timing out with `Test killed with quit: ran too long`. Some are falsely reporting success even with this error.

No PRs should be merged until this problem is fixed.

@pwittrock @vishh I have no access to environment so could one of you please take a look & figure out what's up?

**Comment by pwittrock** [comment]
The tests not properly reporting failure should have been fixed by #1107.  If it hasn't we will need to dig in some more.  Looking at the last few cadvisor pr builder test runs, I don't see any "Test killed with quit" messages in the logs.  Perhaps that was a transient issue?

**Comment by timstclair** [comment]
Obsolete.
