### ISSUE TITLE
Long startup time

### ISSUE THREAD

**Issue by lucevers** [google/cadvisor#1114]
Actions:

  Build cadvisor -> oke
  $ sudo ./cadvisor

  http//ip:8080/
       - Takes minutes to start.  (server 10 cores , 32Gb ram)

  On the website press Docker Containers, again a lot of time before opening the web page.

**Comment by lucevers** [comment]
Problem Found:

   I see that the webtool makes connections to the Google website and this was blocked by the local PC.

**Comment by dashpole** [comment]
Closed, since the issue is resolved.
