### ISSUE TITLE
cadvisor not showing sub container data with docker 1.9.1

### ISSUE THREAD

**Issue by hridyeshpant** [google/cadvisor#1115]
![docker_1 7 1](https://cloud.githubusercontent.com/assets/7502704/13039937/910ecbb0-d3f1-11e5-87bf-36dab54986ca.jpg)
![docker_1 9 1](https://cloud.githubusercontent.com/assets/7502704/13039936/910ec282-d3f1-11e5-92b7-e5449d12891f.jpg)

we recently moved docker 1.7.1 to docker 1.9.1 and seems cAdvisor not showing Subcontainers  sections with docker 1.9.1.
attaching the image for both 1.7.1 and 1.9.1.

COMMAND run :  docker run  --volume=/var/run:/var/run:rw --volume=/var/lib/docker/:/var/lib/docker:ro   --publish=8080:8080   --detach=true   --name=cadvisor   google/cadvisor:latest

log with docker 1.9.1>

I0215 04:19:44.580674       1 storagedriver.go:44] Caching stats in memory for 2m0s
I0215 04:19:44.581071       1 manager.go:131] cAdvisor running in container: "/docker/fa9ceba4782af64adb42d3ee1089f56c8cea8481fc7e5330db44b8b09554955d"
W0215 04:19:44.708814       1 fs.go:159] Could not get Docker devicemapper device: exit status 1
I0215 04:19:44.708853       1 fs.go:107] Filesystem partitions: map[/dev/mapper/docker-202:1-263179-fa9ceba4782af64adb42d3ee1089f56c8cea8481fc7e5330db44b8b09554955d:{mountpoint:/ major:253 minor:28 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-7704baba9fe1f722b6eb874b41a4f90537b04fd2c2246a25b0c0c461bc8fba2d:{mountpoint:/var/lib/docker/devicemapper/mnt/7704baba9fe1f722b6eb874b41a4f90537b04fd2c2246a25b0c0c461bc8fba2d major:253 minor:16 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-775b04fe4d43c95c673ea2c6059eac7ff16da9b4ef8ef94e483fb45ed51fca31:{mountpoint:/var/lib/docker/devicemapper/mnt/775b04fe4d43c95c673ea2c6059eac7ff16da9b4ef8ef94e483fb45ed51fca31 major:253 minor:5 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-bcca1940e3190016ce4665dbe3df7563621a25f1383e535aa0820cb13118577d:{mountpoint:/var/lib/docker/devicemapper/mnt/bcca1940e3190016ce4665dbe3df7563621a25f1383e535aa0820cb13118577d major:253 minor:8 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-11676189d23786081612c6cd3bbe6d27c4923faaaab8290a2ff752466ce96759:{mountpoint:/var/lib/docker/devicemapper/mnt/11676189d23786081612c6cd3bbe6d27c4923faaaab8290a2ff752466ce96759 major:253 minor:34 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-480a181947a7812d8d7249efe1c408734aeafef0cecc1c46c8694ee2cbc67c0e:{mountpoint:/var/lib/docker/devicemapper/mnt/480a181947a7812d8d7249efe1c408734aeafef0cecc1c46c8694ee2cbc67c0e major:253 minor:21 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-72b862e58b63ff2b5d8631f3ceb3b669153e4aa08f7d0444d6508956a4adaa38:{mountpoint:/var/lib/docker/devicemapper/mnt/72b862e58b63ff2b5d8631f3ceb3b669153e4aa08f7d0444d6508956a4adaa38 major:253 minor:6 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-eda24965c0223f7cc871b0707ea37c102d3e35724b69066014f60d107f50277e:{mountpoint:/var/lib/docker/devicemapper/mnt/eda24965c0223f7cc871b0707ea37c102d3e35724b69066014f60d107f50277e major:253 minor:24 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-847247b1652fbb34ce18e05dfe72eb3b65e1f2e780624842858f308d19fcb25b:{mountpoint:/var/lib/docker/devicemapper/mnt/847247b1652fbb34ce18e05dfe72eb3b65e1f2e780624842858f308d19fcb25b major:253 minor:17 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-f3e24c7684f52d1b3e6a18de4df3937be54c138773db425c2195268a1328b40f:{mountpoint:/var/lib/docker/devicemapper/mnt/f3e24c7684f52d1b3e6a18de4df3937be54c138773db425c2195268a1328b40f major:253 minor:22 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-176b90b691dddb1f479cad4ea73ee710fcbab48c4d72c047472d958a07d0f870:{mountpoint:/var/lib/docker/devicemapper/mnt/176b90b691dddb1f479cad4ea73ee710fcbab48c4d72c047472d958a07d0f870 major:253 minor:15 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-9949780c489ee56380b12581570a770b2afcb2f2300c0d56d4dc44d752812670:{mountpoint:/var/lib/docker/devicemapper/mnt/9949780c489ee56380b12581570a770b2afcb2f2300c0d56d4dc44d752812670 major:253 minor:9 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-75572eac115f352db4fcb302f9cdd864a74f0498fce92f4c67f5689735e8b933:{mountpoint:/var/lib/docker/devicemapper/mnt/75572eac115f352db4fcb302f9cdd864a74f0498fce92f4c67f5689735e8b933 major:253 minor:23 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-1248d2b401d7034d3db1311a3ef1dc280d1ea38083b6df72cad86a26169a2b3c:{mountpoint:/var/lib/docker/devicemapper/mnt/1248d2b401d7034d3db1311a3ef1dc280d1ea38083b6df72cad86a26169a2b3c major:253 minor:7 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-e02616764254712faf5b22eacd2d6a0790c8aceed7b3805c36a450ae42a6325e:{mountpoint:/var/lib/docker/devicemapper/mnt/e02616764254712faf5b22eacd2d6a0790c8aceed7b3805c36a450ae42a6325e major:253 minor:3 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-f037773cc126640f43114100a4c5730e061581ed08d773079eb1c273eb69fa6a:{mountpoint:/var/lib/docker/devicemapper/mnt/f037773cc126640f43114100a4c5730e061581ed08d773079eb1c273eb69fa6a major:253 minor:18 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-4db3d26d9db9947bf9787d894596b15c31a47cd416df0f7a8a333a8d71fc6c69:{mountpoint:/var/lib/docker/devicemapper/mnt/4db3d26d9db9947bf9787d894596b15c31a47cd416df0f7a8a333a8d71fc6c69 major:253 minor:19 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-9b1cd35faed02264603b4d7039752a52b96fffce2a9e7f035a4096793d4cbf42:{mountpoint:/var/lib/docker/devicemapper/mnt/9b1cd35faed02264603b4d7039752a52b96fffce2a9e7f035a4096793d4cbf42 major:253 minor:25 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-df6e86d10c4df644fd87ed46d9a8347f0f439dc28d52602cd6d458745c79a432:{mountpoint:/var/lib/docker/devicemapper/mnt/df6e86d10c4df644fd87ed46d9a8347f0f439dc28d52602cd6d458745c79a432 major:253 minor:13 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-dad6b57dcd338b61d2841355c73e7213b69e38c0c6fd61701d62e675ab936d30:{mountpoint:/var/lib/docker/devicemapper/mnt/dad6b57dcd338b61d2841355c73e7213b69e38c0c6fd61701d62e675ab936d30 major:253 minor:14 fsType: blockSize:0} /dev/xvda1:{mountpoint:/var/run major:202 minor:1 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-09310b4809384d3d731aeba4d9226c11afd6e30137e3cc05b50d649f7a2e5841:{mountpoint:/var/lib/docker/devicemapper/mnt/09310b4809384d3d731aeba4d9226c11afd6e30137e3cc05b50d649f7a2e5841 major:253 minor:11 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-b5904346f03f597304012a7fbc261d31e3ad9b9e282e2c4770cd76121aae4f1e:{mountpoint:/var/lib/docker/devicemapper/mnt/b5904346f03f597304012a7fbc261d31e3ad9b9e282e2c4770cd76121aae4f1e major:253 minor:10 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-87cedb9ea464f70b92af822593c2cd13f863b7f21f50327a8645dd9466722d44:{mountpoint:/var/lib/docker/devicemapper/mnt/87cedb9ea464f70b92af822593c2cd13f863b7f21f50327a8645dd9466722d44 major:253 minor:12 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-bb29927bb61eb21d4094b8c9d4c2b31492fe6b3bb913580b10fd3eb51eb58d36:{mountpoint:/var/lib/docker/devicemapper/mnt/bb29927bb61eb21d4094b8c9d4c2b31492fe6b3bb913580b10fd3eb51eb58d36 major:253 minor:20 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-5075228d883a883a44c7680e57638515620d55d590173f3ba3c632686dc8bd0c:{mountpoint:/var/lib/docker/devicemapper/mnt/5075228d883a883a44c7680e57638515620d55d590173f3ba3c632686dc8bd0c major:253 minor:26 fsType: blockSize:0} /dev/mapper/docker-202:1-263179-724e6737f484b655cc5a498845b620314ec2f84ac098e82c4644159883716422:{mountpoint:/var/lib/docker/devicemapper/mnt/724e6737f484b655cc5a498845b620314ec2f84ac098e82c4644159883716422 major:253 minor:27 fsType: blockSize:0}]
I0215 04:19:44.801700       1 machine.go:50] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0215 04:19:44.801742       1 manager.go:166] Machine: {NumCores:16 CpuFrequency:2900092 MemoryCapacity:31612305408 MachineID: SystemUUID:EC21D58A-9992-0A49-677A-8754A392114F BootID:26a8edd2-e5ad-4083-a54b-58b37b5915f9 Filesystems:[{Device:/dev/mapper/docker-202:1-263179-5075228d883a883a44c7680e57638515620d55d590173f3ba3c632686dc8bd0c Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-724e6737f484b655cc5a498845b620314ec2f84ac098e82c4644159883716422 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-87cedb9ea464f70b92af822593c2cd13f863b7f21f50327a8645dd9466722d44 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-bb29927bb61eb21d4094b8c9d4c2b31492fe6b3bb913580b10fd3eb51eb58d36 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-fa9ceba4782af64adb42d3ee1089f56c8cea8481fc7e5330db44b8b09554955d Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-bcca1940e3190016ce4665dbe3df7563621a25f1383e535aa0820cb13118577d Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-11676189d23786081612c6cd3bbe6d27c4923faaaab8290a2ff752466ce96759 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-7704baba9fe1f722b6eb874b41a4f90537b04fd2c2246a25b0c0c461bc8fba2d Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-775b04fe4d43c95c673ea2c6059eac7ff16da9b4ef8ef94e483fb45ed51fca31 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-eda24965c0223f7cc871b0707ea37c102d3e35724b69066014f60d107f50277e Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-480a181947a7812d8d7249efe1c408734aeafef0cecc1c46c8694ee2cbc67c0e Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-72b862e58b63ff2b5d8631f3ceb3b669153e4aa08f7d0444d6508956a4adaa38 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-f3e24c7684f52d1b3e6a18de4df3937be54c138773db425c2195268a1328b40f Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-176b90b691dddb1f479cad4ea73ee710fcbab48c4d72c047472d958a07d0f870 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-847247b1652fbb34ce18e05dfe72eb3b65e1f2e780624842858f308d19fcb25b Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-1248d2b401d7034d3db1311a3ef1dc280d1ea38083b6df72cad86a26169a2b3c Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-9949780c489ee56380b12581570a770b2afcb2f2300c0d56d4dc44d752812670 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-75572eac115f352db4fcb302f9cdd864a74f0498fce92f4c67f5689735e8b933 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-4db3d26d9db9947bf9787d894596b15c31a47cd416df0f7a8a333a8d71fc6c69 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-9b1cd35faed02264603b4d7039752a52b96fffce2a9e7f035a4096793d4cbf42 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-e02616764254712faf5b22eacd2d6a0790c8aceed7b3805c36a450ae42a6325e Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-f037773cc126640f43114100a4c5730e061581ed08d773079eb1c273eb69fa6a Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-09310b4809384d3d731aeba4d9226c11afd6e30137e3cc05b50d649f7a2e5841 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-df6e86d10c4df644fd87ed46d9a8347f0f439dc28d52602cd6d458745c79a432 Capacity:107319656448} {Device:/dev/mapper/docker-202:1-263179-dad6b57dcd338b61d2841355c73e7213b69e38c0c6fd61701d62e675ab936d30 Capacity:107319656448} {Device:/dev/xvda1 Capacity:8318783488} {Device:/dev/mapper/docker-202:1-263179-b5904346f03f597304012a7fbc261d31e3ad9b9e282e2c4770cd76121aae4f1e Capacity:107319656448}] DiskMap:map[253:1:{Name:dm-1 Major:253 Minor:1 Size:23488102400 Scheduler:none} 253:2:{Name:dm-2 Major:253 Minor:2 Size:23488102400 Scheduler:none} 253:26:{Name:dm-26 Major:253 Minor:26 Size:107374182400 Scheduler:none} 253:11:{Name:dm-11 Major:253 Minor:11 Size:107374182400 Scheduler:none} 253:14:{Name:dm-14 Major:253 Minor:14 Size:107374182400 Scheduler:none} 253:16:{Name:dm-16 Major:253 Minor:16 Size:107374182400 Scheduler:none} 253:18:{Name:dm-18 Major:253 Minor:18 Size:107374182400 Scheduler:none} 253:20:{Name:dm-20 Major:253 Minor:20 Size:107374182400 Scheduler:none} 253:23:{Name:dm-23 Major:253 Minor:23 Size:107374182400 Scheduler:none} 253:24:{Name:dm-24 Major:253 Minor:24 Size:107374182400 Scheduler:none} 253:4:{Name:dm-4 Major:253 Minor:4 Size:107374182400 Scheduler:none} 202:26368:{Name:xvdcz Major:202 Minor:26368 Size:23622320128 Scheduler:noop} 253:34:{Name:dm-34 Major:253 Minor:34 Size:107374182400 Scheduler:none} 253:0:{Name:dm-0 Major:253 Minor:0 Size:25165824 Scheduler:none} 253:13:{Name:dm-13 Major:253 Minor:13 Size:107374182400 Scheduler:none} 253:3:{Name:dm-3 Major:253 Minor:3 Size:107374182400 Scheduler:none} 253:9:{Name:dm-9 Major:253 Minor:9 Size:107374182400 Scheduler:none} 253:17:{Name:dm-17 Major:253 Minor:17 Size:107374182400 Scheduler:none} 253:27:{Name:dm-27 Major:253 Minor:27 Size:107374182400 Scheduler:none} 253:5:{Name:dm-5 Major:253 Minor:5 Size:107374182400 Scheduler:none} 202:0:{Name:xvda Major:202 Minor:0 Size:8589934592 Scheduler:noop} 253:6:{Name:dm-6 Major:253 Minor:6 Size:107374182400 Scheduler:none} 253:8:{Name:dm-8 Major:253 Minor:8 Size:107374182400 Scheduler:none} 253:10:{Name:dm-10 Major:253 Minor:10 Size:107374182400 Scheduler:none} 253:15:{Name:dm-15 Major:253 Minor:15 Size:107374182400 Scheduler:none} 253:19:{Name:dm-19 Major:253 Minor:19 Size:107374182400 Scheduler:none} 253:25:{Name:dm-25 Major:253 Minor:25 Size:107374182400 Scheduler:none} 253:7:{Name:dm-7 Major:253 Minor:7 Size:107374182400 Scheduler:none} 253:12:{Name:dm-12 Major:253 Minor:12 Size:107374182400 Scheduler:none} 253:21:{Name:dm-21 Major:253 Minor:21 Size:107374182400 Scheduler:none} 253:22:{Name:dm-22 Major:253 Minor:22 Size:107374182400 Scheduler:none} 253:28:{Name:dm-28 Major:253 Minor:28 Size:107374182400 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:02:42:ac:11:00:03 Speed:10000 Mtu:9001}] Topology:[{Id:0 Memory:31612305408 Cores:[{Id:0 Threads:[0 8] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[1 9] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:2 Threads:[2 10] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:3 Threads:[3 11] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[4 12] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:5 Threads:[5 13] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:6 Threads:[6 14] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:7 Threads:[7 15] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:26214400 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown}
I0215 04:19:44.803743       1 manager.go:172] Version: {KernelVersion:4.1.13-19.30.amzn1.x86_64 ContainerOsVersion:Alpine Linux v3.2 DockerVersion:1.9.1 CadvisorVersion:0.20.5 CadvisorRevision:9aa348f}
I0215 04:19:44.916812       1 factory.go:252] Registering Docker factory
I0215 04:19:44.919849       1 factory.go:94] Registering Raw factory
I0215 04:19:45.117911       1 manager.go:1000] Started watching for new ooms in manager
W0215 04:19:45.118675       1 manager.go:239] Could not configure a source for OOM detection, disabling OOM events: exec: "journalctl": executable file not found in $PATH
I0215 04:19:45.146574       1 manager.go:252] Starting recovery of all containers
I0215 04:19:45.146963       1 manager.go:257] Recovery completed
I0215 04:19:45.147596       1 cadvisor.go:106] Starting cAdvisor version: 0.20.5-9aa348f on port 8080

**Comment by vishh** [comment]
Are you referring to the `Docker Containers` page in the UI or
`subContainers` in the REST API?

**Comment by hridyeshpant** [comment]
yes @vishh i am referring the UI page. I tried removing "/var/lib/docker/:/var/lib/docker:ro" in my command line, but still Cadvisor Ui is not showing subContainers section . Same is working fine with docker 1.7.1. Please see the image attached, missing subContainers when running with 1.9.1 in UI.

**Comment by vishh** [comment]
Can you try the latest version v0.22.0?

**Comment by hridyeshpant** [comment]
@vishh is there docker version for  v0.22.0 . i am using google/cadvisor image

**Comment by ohmystack** [comment]
@hridyeshpant 
Your running cmd misses a few volumes.

The cmd you privided above:
> COMMAND run : docker run --volume=/var/run:/var/run:rw --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8080:8080 --detach=true --name=cadvisor google/cadvisor:latest

You need to mount:
`/:/rootfs:ro` and `/sys/fs/cgroup:/sys/fs/cgroup:ro` (OR on CentOS 6, `/cgroup:/cgroup:ro`)

cAdvisor uses libcontainer lib to read the "mount info" at `/proc/self/mountinfo`, which tells cAdvisor who the subcontainers are. If you didn't mount the root filesystem, cAdvisor cannot know the "mount info", so that there is no subcontainer.

**Comment by raykrueger** [comment]
On amazon linux I added `--volume=/cgroup:/sys/fs/cgroup:ro` to get this working again.

**Comment by dashpole** [comment]
Closing since this is resolved.
