### ISSUE TITLE
Add support for using other ports other than 8080 for cadvisor web ui

### ISSUE THREAD

**Issue by salimane** [google/cadvisor#1119]
Currently when using the docker image it's impossible to use another port for the web ui, specially if you are using ``--net=host``.
Thanks

**Comment by timstclair** [comment]
Does the `--port` flag provide what you're looking for?

**Comment by salimane** [comment]
hmm yeah but I want to be able to set it while running the docker container. Here is the cadvisor Dockerfile https://github.com/google/cadvisor/blob/master/deploy/Dockerfile . The exposed port 8080 is hardcoded.
Thanks

**Comment by timstclair** [comment]
How are you running the docker image? Does the `docker run -p <host port>:8080` option work for you? (https://docs.docker.com/engine/reference/run/#expose-incoming-ports)

**Comment by salimane** [comment]
I want to run the docker image with the following options ``docker run --net=host``, which basically means bind your ports as if you were the host. But let's say you already have an app running on port 8080, then you can't really do that.

**Comment by Vanuan** [comment]
I don't think that docker supports dynamic EXPOSE option.

**Comment by salimane** [comment]
hmm... ok i wil see what i can do
