### ISSUE TITLE
"wget: can't execute 'ssl_helper': No such file or directory" in integration test container

### ISSUE THREAD

**Issue by sjenning** [google/cadvisor#1131]
Junk in the TestDockerContainerNetworkStats test container

```
Every 1s: wget https://www.google.com/                      2016-02-27 03:35:07

Connecting to www.google.com (173.194.115.49:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
```

Apparently it tries without ssl support an fails, but that generates network traffic which makes the test ultimately pass.   Worth cleaning up though.

**Comment by kklepper** [comment]
@sjenning  no use when pulling from github...

**Comment by itoffshore** [comment]
you can also install GNU `wget` & `ca-certificates` to get support for https (in Alpine Linux containers with `busybox`)

**Comment by pklalitjha** [comment]
I got this error while downloading gradle using wget, fixed this by installing openssl package

**Comment by tvalasek** [comment]
apk update && apk add ca-certificates && update-ca-certificates && apk add openssl

**Comment by listx** [comment]
@tvalasek Can this be just `apk add --update ca-certificates openssl && update-ca-certificates` ?

**Comment by johnwesley** [comment]
`apk add --update openssl`
