### ISSUE TITLE
(Re)Enable TestDockerFilesystemStats test for RHEL integration test

### ISSUE THREAD

**Issue by sjenning** [google/cadvisor#1147]
This was disabled in #1143 to fix #1130 and allow the integration tests to pass on RHEL with devicemapper storage driver.  Need to get this working properly, though.

**Comment by vishh** [comment]
cc @ncdc.

**Comment by sjenning** [comment]
The mechanism for collecting these stats for DM was disabled do to excessive disk IOPs https://github.com/google/cadvisor/pull/1588
