### ISSUE TITLE
filesystem i/o

### ISSUE THREAD

**Issue by fahimeh2010** [google/cadvisor#1151]
Hello all
cadvisor monitor filesystem i/o for each container?
Thanks a lot

**Comment by vishh** [comment]
[Yes](https://github.com/google/cadvisor/blob/master/info/v2/container.go#L140)

**Comment by fahimeh2010** [comment]
thanks, but where in the its interface?

**Comment by vishh** [comment]
What interface are you referring to?

**Comment by fahimeh2010** [comment]
I downloaded the latest image on docker hub.(google/cadvisor:latest)

**Comment by vishh** [comment]
Sure. By `interface` are you referring to the REST APIs?
