### ISSUE TITLE
raw container GetStats not returning proper network stats in all cases

### ISSUE THREAD

**Issue by sjenning** [google/cadvisor#1156]
The raw container handler GetStats() is using the pid of the cadvisor process (or kubelet/origin) for getting the stats of every raw container.

```
func (self *rawContainerHandler) GetStats() (*info.ContainerStats, error) {
	stats, err := libcontainer.GetStats(self.cgroupManager, self.rootFs, os.Getpid(), self.ignoreMetrics)
```

The pid is currently only used for gathering network stats, but if the container is in a different network namespace, GetStats() will still return the net stats of the network namespace in which cadvisor is running.

In order to do this properly, the network stats from a pid in the ```tasks``` file of the cgroup should be used, assuming all pids in a cgroup are going to be in the same network namespace, which I don't think is a certainty, but is likely.

cc @ncdc @derekwaynecarr

**Comment by ncdc** [comment]
cc @timothysc

**Comment by ncdc** [comment]
cc @vishh

**Comment by vishh** [comment]
cc @dchen1107

**Comment by ncdc** [comment]
#1158 fixed this - we can close, right?

**Comment by derekwaynecarr** [comment]
@ncdc :+1:
