### ISSUE TITLE
Add Limit to MemoryStats

### ISSUE THREAD

**Issue by ghodss** [google/cadvisor#1157]
libcontainer recently added "Limit" (from memory.limit_in_bytes from the memory resource controller) to their MemoryStats struct in https://github.com/opencontainers/runc/pull/529. Add "Limit" to the cadvisor MemoryStats struct. This value is very helpful to generating a metric of percentage of memory used.

**Comment by vishh** [comment]
Isn't memory Limit is already exported - https://github.com/google/cadvisor/blob/master/info/v2/container.go#L48 ?

**Comment by ghodss** [comment]
Yes that's right - I was looking for it in the wrong place.

One thing that may want to be fixed is that the comment says "Default is unlimited (-1)", but the field is uint64 so "default" is actually MaxUint64 (i.e. 18446744073709551615). You may want to either make it an actual int or change the documentation.

**Comment by vishh** [comment]
Yeah. The description has to be fixed.
