### ISSUE TITLE
could shortened container id be used in API request ?

### ISSUE THREAD

**Issue by stushurik** [google/cadvisor#1164]
In the api docs examples, shortened ids are used.
But when I tried this http://localhost:8080/api/v2.0/stats/a56e78bb4b8e?type=docker  the response is 
unable to find Docker container "a56e78bb4b8e"

But when I use the full id it works as expected. 
The same is for api v.1.3.
Docker version is 1.9.1, cadvisor version is 0.22

I have copy-pasted docker command from the README.

**Comment by vishh** [comment]
It should be possible to look up using partial IDs. Feel free to post a PR
to fix this..
