### ISSUE TITLE
cadvisor do not  support the latest version of influxdb?

### ISSUE THREAD

**Issue by wangzhezhe** [google/cadvisor#1167]
It seems that the REST-API of influxdb has changed a lot in version 0.9 and 0.10 I noticed that the code in cadvisor storage part still in the old version ( < 0.8) ?

**Comment by ohmystack** [comment]
Newer version (about >= v0.20.4) cAdvisor can support for InfluxDB 0.9, but I'm not sure with 0.10.

**Comment by vishh** [comment]
Try the latest version.

**Comment by wangzhezhe** [comment]
Thanks !
