### ISSUE TITLE
Ignore mounts while calculating disk usage

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#1173]
As of now a container mounting the root filesystem will result in high disk usage. We need to avoid entering mounts or bind mounts while calculating disk usage.

**Comment by jeremyeder** [comment]
In fact we're going to be bind-mounting in lots of stuff to enable super privileged containers running software-defined-storage daemon pods scheduled by kube. I bet we are going to hit this in the next few weeks :/

/cc @ekuric

**Comment by vishh** [comment]
This is WAI. cAdvisor looks only at the writable layer.
