### ISSUE TITLE
Switch to native go vendoring instead of godeps

### ISSUE THREAD

**Issue by bluecmd** [google/cadvisor#1181]
Hi,

With Go 1.6 there is no need to use godeps. Please consider switching to the vendor structure native to 1.6.

Details: https://golang.org/cmd/go/#hdr-Vendor_Directories

Thanks

**Comment by timstclair** [comment]
xref: https://github.com/google/cadvisor/pull/1073

**Comment by vishh** [comment]
I will make some time this week to wrap up #1073.
