### ISSUE TITLE
Change port from 8080

### ISSUE THREAD

**Issue by mokshpooja** [google/cadvisor#1184]
Where could change port for cAdvisor from 8080 to something else or how to supply port as a config?

**Comment by vishh** [comment]
`--port=12345` should work.

**Comment by Farkya** [comment]
try : 
--publish=<desired-port>:8080 \

**Comment by shujamughal** [comment]
complete command if you want to run it on 8484 port is like

docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8484:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest
