### ISSUE TITLE
[docker v1.11.0-rc2] container info missing metadata

### ISSUE THREAD

**Issue by timstclair** [google/cadvisor#1185]
Comparing the output of the stats query:
```
curl -X "POST" -d '{"containerName":"/","subcontainers":true,"num_stats":1}' $(k8s-node-proxy)/stats/container
```

From a cluster running on [docker-v1.11.0-rc2](https://gist.github.com/timstclair/78eddf7c36698fcefcd5ab0d99bb2e7a) vs [docker-v1.9.1](https://gist.github.com/timstclair/7cfbb357bc151803c3dd1c991bc54ca4), the docker-v1.11.0-rc2 response is missing
- id
- aliases
- namespace
- labels

xref https://github.com/kubernetes/kubernetes/issues/23397

**Comment by timstclair** [comment]
Looks like the docker inspect API changed in https://github.com/docker/docker/commit/68fb7f4b744bf71206898d32fe203556a6261e5d, we might just need to update Godeps to the latest docker client (to include https://github.com/fsouza/go-dockerclient/pull/107)

**Comment by vishh** [comment]
Docker does not support exec driver anymore. So cAdvisor needs to stop
checking for the `native` exec driver.

**Comment by timstclair** [comment]
Fixed via https://github.com/google/cadvisor/issues/1190
