### ISSUE TITLE
cAdvisor trying to connect to non-existent rkt API on startup

### ISSUE THREAD

**Issue by timstclair** [google/cadvisor#1201]
On my local machine (not running rkt), starting cadvisor prints several error messages:
```
$ sudo ./cadvisor
2016/04/08 16:37:51 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:15441: getsockopt: connection refused"; Reconnecting to "localhost:15441"
2016/04/08 16:37:53 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:15441: getsockopt: connection refused"; Reconnecting to "localhost:15441"
2016/04/08 16:37:53 Failed to dial localhost:15441: grpc: timed out trying to connect; please retry.
E0408 16:37:55.525431   18016 manager.go:228] Registration of the rkt container factory failed: unable to get the RktPath variable couldn't GetInfo from rkt api service: rpc error: code = 2 desc = "grpc: the client connection is closing"
```
Also note that it takes ~4 seconds to fail to register the rkt runtime, 

I suggest adding a `-container_handlers` flag which takes a comma-separated list of container handlers to register. The existing flag `-docker_only` (which rkt doesn't currently respect) would be deprecated in favor of the new flag. The raw container handler would still be registered to handle the root container, but would ignore all others (same behavior as `-docker_only`).

/cc @sjpotter @vishh

**Comment by vishh** [comment]
Would it ok if we just suppress those errors? From a usability stand point, it is great if cadvisor just works on a node that is running rkt.

**Comment by sjpotter** [comment]
I guess this is just a function of grpc.  i.e. when you try to connect to the docker daemon and cant, its doing the same thing internally.

**Comment by sjpotter** [comment]
https://github.com/grpc/grpc-go/blob/master/grpclog/logger.go

does it make sense for gprc to use its own logger instead of glog?  worth filing an issue against it?

**Comment by timstclair** [comment]
> Would it ok if we just suppress those errors? From a usability stand point, it is great if cadvisor just works on a node that is running rkt.

I'm less concerned about the error messages, and more concerned with the startup latency. It blocks cAdvisor startup for about 4 seconds while grpc retries (hence the need for https://github.com/google/cadvisor/pull/1200). If we could register the handlers in separate go routines it might not be a problem, but I haven't worked through the implications of doing it concurrently.

**Comment by sjpotter** [comment]
let me try it with a 0s timeout

**Comment by sjpotter** [comment]
0, doesn't work, but 1s returns quickly.

**Comment by sjpotter** [comment]
would you be happier w/ a PR that makes it only take 1s?

**Comment by timstclair** [comment]
Happier, yes, but it would be nice to have some data around connection times rather than just picking an arbitrary numbers. Since we're dialing localhost, I imagine the success case is very fast. Is there an option to mark "connection refused" as a permanent error, or any other way to determine if rkt is running?

**Comment by sjpotter** [comment]
not sure, etcd people tell me they do something to deal with this

https://github.com/coreos/etcd/blob/master/clientv3/client.go#L131-L141

but having a hard time parsing it.

**Comment by vishh** [comment]
I think having the ability to register and re-register a handler is a
necessity. We have been punting on that for a while.

**Comment by sjpotter** [comment]
so I'm told its impossible to do a dial and drop in grpc, and the best option is to try to make a raw tcp connection to the service and if it succeeds then to have grpc dial.

**Comment by sjpotter** [comment]
fixed by https://github.com/google/cadvisor/pull/1218
