### ISSUE TITLE
cAdvisor should ignore .mount cgroups when on systemd

### ISSUE THREAD

**Issue by derekwaynecarr** [google/cadvisor#1211]
A previous fix was made in Kubernetes to ignore .mount units

https://github.com/kubernetes/kubernetes/pull/22656

I think .mount cgroups should be ignored on systemd entirely by cAdvisor.

**Comment by derekwaynecarr** [comment]
I was getting errors like the following from here:

https://github.com/kubernetes/kubernetes/blob/master/Godeps/_workspace/src/github.com/google/cadvisor/cache/memory/memory.go#L104

```
unable to find data for container /system.slice/var-lib-docker-devicemapper-mnt-6b4fa4a130bbfa32390d93562453da45350787058d449b15ee1f75c1a56a1c1f\x2dinit.mount 
```

**Comment by vishh** [comment]
Can we instead have a `systemd` plugin in cAdvisor?

**Comment by derekwaynecarr** [comment]
@vishh - that works, is there a particular interface you have in mind that we could implement?

**Comment by vishh** [comment]
Existing rkt integration will be a good place to start - https://github.com/google/cadvisor/tree/master/container/rkt

**Comment by derekwaynecarr** [comment]
I need to look into this some more, but isn't the issue that the raw container handler is what would need to be updated?

**Comment by derekwaynecarr** [comment]
So the factories are registered in-order, if I have a systemd factory registered before the raw factory, are you saying I could say that the systemd can handle .mount cgroups, but it doesn't accept them and the raw factory would just ignore them as a consequence?

**Comment by derekwaynecarr** [comment]
I guess that is what the code currently is doing... ok, I can buy that this may work.

**Comment by vishh** [comment]
Yeah. The raw drive is the fallback option. I'd like to see more systemd
specific code go into the systemd handler.

**Comment by derekwaynecarr** [comment]
Yeah, I want to add more to it as time permits
