### ISSUE TITLE
go-dockerclient update breaks Docker 1.6.2 compatibility

### ISSUE THREAD

**Issue by krallin** [google/cadvisor#1214]
Just a quick heads up that the go-dockerclient update in https://github.com/google/cadvisor/pull/1190 breaks compatibility with Docker 1.6.2 because of this issue: https://github.com/fsouza/go-dockerclient/issues/503. 

Not necessarily something that should be fixed in cAdvisor itself, but I thought you might want to know ([as far as I know, cAdvisor tries to support Docker > 1.0](https://github.com/google/cadvisor/blob/master/container/docker/handler.go#L456)).

**Comment by timstclair** [comment]
Thanks for the heads up. There's an open PR to switch to the official docker client: https://github.com/google/cadvisor/pull/1203

**Comment by Random-Liu** [comment]
@krallin @timstclair I think engine-api also has the problem, see https://github.com/docker/engine-api/blob/master/types/types.go#L224

**Comment by dashpole** [comment]
closed via #1203
