### ISSUE TITLE
Supported to compile statically?

### ISSUE THREAD

**Issue by luxas** [google/cadvisor#1227]
`kubelet` in Kubernetes depends on `cAdvisor`, and if `kubelet` is compiled statically, it complains loudly that `cAdvisor` isn't bundled and exits.

So I wonder if there are some technical difficulties to compile `cAdvisor` statically? 
I haven't tested it yet

If `cAdvisor` works fine when it's statically built, we may close this and open one on the Kubernetes side.

**Comment by djtm** [comment]
Static compile works fine, haven't gone through the tests though:
```bash
export GOPATH=~/src/go
export PATH="$PATH:$GOPATH/bin"
apt-get install golang-go # build does not work in alpine
# https://github.com/kubernetes/kubernetes/issues/19464
git clone --depth 1 https://github.com/google/cadvisor.git
go get github.com/tools/godep
go get -d github.com/google/cadvisor
# build statically for scratch image
godep go build **--ldflags '-extldflags "-static"'** github.com/google/cadvisor
```
Static scratch image at `https://hub.docker.com/r/djtm/cadvisor-386/`
You can use the same run command as usual.

**Comment by vishh** [comment]
If you can push a patch with this change, we can have the CI run all the tests.

**Comment by luxas** [comment]
It seems like it's these files that are using `cgo`: 
 - `utils/cpuload/netlink/defs.go`
 - `utils/procfs/jiffy.go`

Of course, the best way of fixing it would be to workaround/not have to depend on these C libraries, but I guess it's just fine with static CGO linking.
I'm sending a patch so we'll see if it passes.

**Comment by dashpole** [comment]
closing via #1299
