### ISSUE TITLE
CPU utilization percentage to InfluxDB

### ISSUE THREAD

**Issue by lkzcgfvf** [google/cadvisor#1232]
Hi 

 I'm using latest cAdvisor and InfluxDB. In database in "cpu_usage_*" columns I see big number values (like 406663983175815). I want to show CPU usage in percent.

How can I convert them to percentage? 
InfluxDB v0.9.6
advisor v0.22.0

P.S. I checked old answers for this topic but didn't find any "stats" table and "cpu_cumulative_usage" column.

**Comment by krallin** [comment]
@lkzcgfvf 

That's the accumulated CPU usage in nanoseconds. You should be able to convert it to core utilization with a query like:

```
SELECT DERIVATIVE(value, 1s) / 1000000000 FROM cpu_usage_total WHERE ... AND time > now() - 1h
```

Note that this won't be normalized by the number of cores, so if you have 4 cores utilized at 100%, then you'll get 4 as a result, and if you have 1 core utilized at 50%, then you'll get 0.5.

**Comment by lkzcgfvf** [comment]
@krallin 
thanks a lot. It works this way. The only concern about this - I need to know how many cores there are on each host.
if I have hosts with different number of cores in my cloud I need to hardcode this number for each host during visualization. 
Do you know is there a way to avoid it? May be to get this info from Docker daemon and store into InfluxDB? Or may be calculate percentage and store it to InfluxDB together with raw data?

**Comment by outrunthewolf** [comment]
@krallin @lkzcgfvf

Did you ever figure out how to programatically check the number of cores on a server? i have the same issue, as all my boxes have different CPU's

**Comment by RoyceShen1** [comment]
@krallin 
i just did the exact same query,but the results shows some negative figures and zeros 
SELECT derivative("value", 1s)/1000000000  FROM "cpu_usage_total" WHERE ("container_name" = 'apinfogather') AND time >= now() - 30m
![image](https://user-images.githubusercontent.com/30994778/33010371-35248e0a-ce15-11e7-8314-2ce5e718fa92.png)
i am using cadvisor v0.24 and influxdb v1.0

**Comment by Dean-Christian-Armada** [comment]
I am also encountering the negative 

```
> SELECT DERIVATIVE(value) FROM cpu_usage_total ORDER BY time DESC LIMIT 3;
name: cpu_usage_total
time                derivative
----                ----------
1513575234810842321 -13920085468.139048
1513575234646245689 940772015055.5693
1513575233854110295 -198917284788.05984
```

**Comment by tobi6112** [comment]
An aggregate function is required inside the call to `derivative` in order to return valid values. A valid query would therefore look like the follwing:

```
> SELECT derivative(mean("value"), 1s) / 1000000000 FROM "cpu_usage_total" ORDER BY time DESC LIMIT 3;
name: cpu_usage_total
time                             derivative
----                             ----------
2021-08-25T17:19:58.396+02:00    1.1072049219170705
2021-08-25T17:19:58.396+02:00    0.8893819028386799
2021-08-25T17:20:02.729+02:00    0.8953493645665052
```
