### ISSUE TITLE
cAdvisor and Docker 1.11: No container stats.

### ISSUE THREAD

**Issue by selvik** [google/cadvisor#1239]
The cAdvisor UI lists my containers but no stats are reported for any of them. I see this error message in the logs: "Docker container factory registration failed: docker found, but not using native exec driver."
I am wondering if cAdvisor can work with the new runC integration in Docker?

Thanks.

**Comment by timstclair** [comment]
Which version of cAdvisor? Dockers 1.11 support was recently added in cAdvisor 0.23

**Comment by nickvanw** [comment]
The latest version in the Docker registry does not have Docker 1.11 support. If you build from source and use the Dockerfile in `build/` you can get something that works.

**Comment by selvik** [comment]
@nickvanw @timstclair I forked cadvisor a couple of months ago and have some local changes. I'll rebase with the latest version and try again. Great to know that support is already in! Thank you very much for the responses.

**Comment by vishh** [comment]
google/cadvisor:v0.23.0 should work with docker v1.11. Once we are
confident with the release, we will switch that to be the latest.

**Comment by yuvipanda** [comment]
Did this switch happen?

**Comment by timstclair** [comment]
I believe latest currently points to v0.23.1. I'll bump that to v0.23.2 soon.

**Comment by andyxning** [comment]
the supporting version relationship between cAdvisor and Docker should be list somewhere explicitly.

**Comment by timstclair** [comment]
Closing as resolved. Please reopen if there are remaining issues.
