### ISSUE TITLE
How to just monitor docker container? 

### ISSUE THREAD

**Issue by zhangjianleaves** [google/cadvisor#1240]
I saw there are many other raw containers (they are actually not container) on cadvisor. Can we have filter on cadvisor to just monitor docker containers?

**Comment by timstclair** [comment]
The `-docker_only` flag should be what you're looking for.
```
  -docker_only
    	Only report docker containers in addition to root stats
```

**Comment by zhangjianleaves** [comment]
thanks it is working perfectly!  I didn't find this flag on document...

**Comment by timstclair** [comment]
Filed https://github.com/google/cadvisor/issues/1244
