### ISSUE TITLE
api to get docker container stats

### ISSUE THREAD

**Issue by aaskey** [google/cadvisor#1249]
According to the api document:

[cAdvisor API document](https://github.com/google/cadvisor/blob/master/docs/api.md)

I should be able to retrieve docker container using the format like: /api/v1.0/containers/docker/2c4dee605d22

There is a container in my machine:
`3ff966ba487f        gcr.io/google_containers/pause:2.0              "/pause"                 7 days ago          Up 7 days                               k8s_POD.364e00d5_delta-red-qytrw_default_50cdad1b-07fc-11e6-bdbc-00505698fae8_38627999`

But when I try to retrieve the stats of the container, it failed with "unknown container":
` $ curl http://localhost:4194/api/v1.0/containers/docker/3ff966ba487f`
`failed to get container "/docker/3ff966ba487f" with error: unknown container "/docker/3ff966ba487f"`

This cAdvisor is part of Kubelet in Kubernetes 1.2.1

What would be the right api to retrieve docker containers?

Thanks in advance.

**Comment by vishh** [comment]
You need to pass in the entire container ID. cAdvisor does not understand partial IDs. If you are running containers via Kubelet, you can also query the `/stats/summary` endpoint on the kubelet. It is exposed on port `10255` by default.

**Comment by aaskey** [comment]
Full id doesn't work either:

`$ curl http://localhost:4194/api/v1.0/containers/docker/3ff966ba487fe2bb9f775913cff2f16e09ac34934b7f6c3c23ef0a9e593da671`
`failed to get container "/docker/3ff966ba487fe2bb9f775913cff2f16e09ac34934b7f6c3c23ef0a9e593da671" with error: unknown container "/docker/3ff966ba487fe2bb9f775913cff2f16e09ac34934b7f6c3c23ef0a9e593da671"`

Kubelet /stats/summary is great. I can use it in some scenario. Is there any documents talking about Kubelet API? In addition, does Kubernetes provides similar stats in its API? If not, is there any consideration to do so?

**Comment by vishh** [comment]
@aaskey Kubernetes will expose basic `cpu` and `memory` usage metrics soon via its APIs. It will not be equivalent to that of cAdvisor or kubelet. 
As for the summary API, code is the document as of now. @timstclair is working on making it ready for prime time with better documentation.

**Comment by aaskey** [comment]
@vishh , thanks for the clarification. Hope Kubernetes metrics api can be available as soon as possible. 

Can you or someone help with the cAdvisor api question? Is API changed but document not updated?

**Comment by vishh** [comment]
@aaskey The API has not changed. We have only introduced new revisions. The UI for instance, uses the same APIs. 

One thing to note is that kubelet organizes docker containers using non-default cgroup hierarchies. To work around that you can try using `/api/v1.2/docker/3ff966ba487fe2bb9f775913cff2f16e09ac34934b7f6c3c23ef0a9e593da671`

**Comment by aaskey** [comment]
Bingo. The v1.2 API works for both docker container ID and name. Thank you so much.
