### ISSUE TITLE
Does cadvisor has a plan about collecting sum of container processes ?

### ISSUE THREAD

**Issue by allencloud** [google/cadvisor#1260]
Hi, All,
cadvisor is an awesome product to collect container metrics in container's world?

However I think, there is still some metric cadvisor can add. For instance, via cgroups procs file to collect the container process number?

WDYT?

**Comment by vishh** [comment]
There is an API for this already - `/api/v2.0/ps/<containerName>`

**Comment by timstclair** [comment]
Please reopen with more details if the existing API is insufficient.
