### ISSUE TITLE
enable_load_stats fails with netlink request failed with error errno 0

### ISSUE THREAD

**Issue by arichardet** [google/cadvisor#1287]
When I run cAdvisor on CentOS Linux release 7.2.1511 in a container with `-enable_load_stats=true`, I receive the following error:
`manager.go:264] Could not initialize cpu load reader: failed to create a netlink based cpuload reader: failed to get netlink family id for task stats: netlink request failed with error errno 0`

I am able to get load stats when running on ubuntu.
Any ideas on why this is not working?

**Comment by vishh** [comment]
cc @krallin

**Comment by krallin** [comment]
@arichardet theTask Stats netlink family (which cAdvisor uses to collect load stats) doesn't work within a network namespace. You'll need to either run your cAdvisor container in the host network (`--net=host`), or run outside of a container entirely.

**Comment by arichardet** [comment]
Thanks @krallin.

**Comment by arichardet** [comment]
@krallin I am getting zero values for load_average and some task stats for some containers.

**Comment by krallin** [comment]
@arichardet Do you have anything running in those containers? Do note that the LA reported by cAdvisor isn't fully equivalent to the LA e.g. `top` would report. In particular, cAdvisor does not include tasks waiting on IO in its LA (it only includes running / runabble tasks). This is something you could patch if you're willing to rebuild cAdvisor — e.g. https://github.com/aptible/cadvisor-factory/blob/master/patches/0006-Include-uninterruptible-and-IO-wait-tasks-in-LA.patch (I'm not sure how the cAdvisor team feels about updating this in mainline — I haven't brought it up).

There's also an issue with the load reader, where it might crash if you have a load of containers being monitored on a similar schedule (I need to update my PR in  https://github.com/google/cadvisor/pull/1188 to fix this), though IIRC this should cause the load reader to hang, not report 0.

Hope this helps! In my experience, the load reader does work reliably with the few tweaks I mentioned above :)
