### ISSUE TITLE
add filter replace all containers

### ISSUE THREAD

**Issue by upccup** [google/cadvisor#1293]
now cadvistor collect all containers info. Can add some filter to collect some Specific container?

**Comment by timstclair** [comment]
Please elaborate. Are you asking about the API, UI, or a command-line option to specify which containers cAdvisor should monitor?

**Comment by upccup** [comment]
@timstclair  thx for reply. i ask about a command-line option to specify which containers cAdvisor should monito

**Comment by timstclair** [comment]
See https://github.com/google/cadvisor/issues/1302 for filtering to a specific runtime. What is your use case for filtering to a specific container?

**Comment by upccup** [comment]
i mean the filter condition is like docker label "AAAA=bbbb",  is the possible?

**Comment by timstclair** [comment]
No, it's not currently possible. Why do you want to do that? Is it a performance issue?

**Comment by upccup** [comment]
Because now  if cadvisor get one of container monitor data failed, it did nor continue so i can not get other container info. But  the error container maybe i did not care, so i want to ignore it.

**Comment by dashpole** [comment]
closing, since this is outdated.  AFAIK, if cAdvisor is unable to collect metrics for a container, it will simply not report those, and still report metrics from other containers it successfully monitors.
