### ISSUE TITLE
How to enable TCP metrics

### ISSUE THREAD

**Issue by f0** [google/cadvisor#1298]
Hi,

the TCP Metrics are disabled per default, is there a way to enable them without patching cadvisor?
```
	// Metrics to be ignored.
	// Tcp metrics are ignored by default.
	ignoreMetrics metricSetValue = metricSetValue{container.MetricSet{container.NetworkTcpUsageMetrics: struct{}{}}}
```

**Comment by vishh** [comment]
Just run cAdvisor with `--disable-metrics=""` flag. By default that flag
has `tcp` set.

**Comment by f0** [comment]
@vishh   ok thx, thats easy, but not really obvious
