### ISSUE TITLE
Check for thin_ls in path and short-circuit if it is not installed

### ISSUE THREAD

**Issue by pmorie** [google/cadvisor#1308]
This issue is to add a check for `thin_ls` being present and avoid using it if it is not.  `NewThinPoolWatcher` should fail if the package is not installed.  

related: #1306

**Comment by godliness** [comment]
Hi pmorie, would you please tell what package should be installed to avoid this error?

**Comment by pmorie** [comment]
@godliness the package is called `devicemapper-persistent-data`

**Comment by vishh** [comment]
cc @dchen1107. @pmorie wants this fixed in v1.3

**Comment by timstclair** [comment]
I already cut the cAdvisor cherry-pick release, but since it's still in pre-release I think it would be OK to pull this fix in to it. I'm going to be OOO starting tomorrow though, so someone else will need to take responsibility for getting this in.

**Comment by ae6rt** [comment]
@pmorie Sorry, I don't see this package called devicemapper-persistent-data in a naive

```
yum provides devicemapper-persistent-data
```

Where can CentOS users get thin_ls?

**Comment by pmorie** [comment]
@ae6rt Sorry!  It's `device-mapper-persistent-data`

**Comment by ae6rt** [comment]
@pmorie Thanks.  I installed this package, but find no thin_ls anywhere:

```
$ sudo find / -name thin_ls
<no output>
```

Based on the comments in this issue, I would have expected to find thin_ls somewhere under /.  Was I wrong?

**Comment by pmorie** [comment]
@ae6rt so in my case, I'm on F23, and i installed using:

```
$ dnf install device-mapper-persistent-data --enablerepo=updates-testing --best
```

**Comment by ae6rt** [comment]
On CentOS7, I see this package info

```
$ yum info device-mapper-persistent-data 
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.tocici.com
 * extras: centos.mirror.ndchost.com
 * updates: mirrors.usc.edu
Installed Packages
Name        : device-mapper-persistent-data
Arch        : x86_64
Version     : 0.5.5
Release     : 1.el7
Size        : 1.2 M
Repo        : installed
From repo   : base
Summary     : Device-mapper Persistent Data Tools
URL         : https://github.com/jthornber/thin-provisioning-tools
License     : GPLv3+
Description : thin-provisioning-tools contains check,dump,restore,repair,rmap
            : and metadata_size tools to manage device-mapper thin provisioning
            : target metadata devices; cache check,dump,metadata_size,restore
            : and repair tools to manage device-mapper cache metadata devices
            : are included and era check, dump, restore and invalidate to manage
            : snapshot eras
```

would you mind posting your corresponding output?  

Thanks much.

**Comment by pmorie** [comment]
@ae6rt I don't think thin_ls is in the centos/RHEL package yet :-/  That's actually part of the motivation for this issue.

**Comment by ae6rt** [comment]
No problem.  I'll just build it from source.  For those of us new to thin_ls, though, what does it do for us in Kubernetes?

**Comment by pmorie** [comment]
@ae6rt thin_ls lets you gather information about filesystems backed by device mapper thin pools.

**Comment by pmorie** [comment]
@ae6rt think of it as `du` for thin pools.
