### ISSUE TITLE
Metric labels are not unique

### ISSUE THREAD

**Issue by fabxc** [google/cadvisor#1311]
We had a user report issues when scraping the Prometheus endpoint as labels could be specified more than once with different values.

Of course user defined labels should not collide with fixed labels of cAdvisor. But sometimes the user is not in control of that.
The most reasonable solution would be to resolve conflicts via prefixing on of the labels as we do in Prometheus.

**Comment by philips** [comment]
Do you have a concrete example and what the prefixing solution would look like? Maybe a prometheus bug report URL?

**Comment by jimmidyson** [comment]
Would #1315 work for you?

**Comment by fabxc** [comment]
Our prefixing is described in the comment section of the `honor_labels` option in scrap configuration: https://prometheus.io/docs/operating/configuration/#scrape_config

#1315 seems to prefix all labels with `label_` even without collisions? That seems shaky usability-wise.

**Comment by grobie** [comment]
Fixed with https://github.com/google/cadvisor/pull/1402 and can be closed.

**Comment by grobie** [comment]
@timstclair Can be closed.
