### ISSUE TITLE
Container restart count is a label

### ISSUE THREAD

**Issue by fabxc** [google/cadvisor#1312]
The number of restarts is attached as a label to all metrics for a container. This causes all time series for a container to break as it restarts as identity is defined by the full set of labels.

The restart count is a time series itself and should only be exported as such.

**Comment by vishh** [comment]
+1

**Comment by grobie** [comment]
This is a kubernetes issue and not a cAdvisor one. https://github.com/kubernetes/kubernetes/blob/b0ea89c2f6b954a27ba0f545da955db4f25009d0/pkg/kubelet/kuberuntime/labels.go#L38

**Comment by grobie** [comment]
I'm starting to understand what's going on here. Kubernetes attaches all these docker labels as a fallback to retrieve them later again. I guess the easiest would be to filter all labels which start with `io.kubernetes.`. What do you think @timstclair @vishh?

**Comment by grobie** [comment]
By the way, I believe cAdvisor shouldn't try to parse these labels and create a restart counter from it. This would be the job of Kubernetes, also as Docker containers don't have the concept of restarts.

**Comment by timstclair** [comment]
Yes, the labels should all be treated as opaque by cAdvisor.

**Comment by rikatz** [comment]
Actually, this isn't a Kubernetes Label, but a Docker Label also (when using --restart=always directive):

```
docker inspect nginx1 |grep -i restartcount
        "RestartCount": 2,
```

This is a pure Docker 17.03 running, no Kubernetes. I'm going to check what's the impact to change cAdvisor code to also set a metric containing the RestartCount of the containers.

**Comment by Magikon** [comment]
kubectl describe po nginx1 | grep "Restart Count"
      Restart Count:  0

**Comment by fgrzadkowski** [comment]
This is still not fixed for users who are using cadvisor directly. RestartCount is a label, which breaks everything and makes it pretty impossible to write alerts based on it (e.g. alert if restart happened more than X times in the last Y min)

**Comment by fgrzadkowski** [comment]
@fabxc @dashpole @vishh @timstclair

**Comment by caligo-mentis** [comment]
Any news here? It would be useful to have container_restart_count metric to setup alerting when using bare docker engine without kubernetes.

**Comment by OloBo-MSK** [comment]
Any news here?

**Comment by Go-Pomegranate** [comment]
Any news?

**Comment by dashpole** [comment]
cAdvisor is stateless, and does not track restarts of containers itself.  Some container runtimes attach a restart count label to metrics, but labels are treated as opaque by cAdvisor as pointed out above.  If the RestartCount label is causing problems, set `--store_container_labels=false` and use --whitelisted-container-labels to keep the ones you want.

**Comment by slimsag** [comment]
@dashpole I think the issue here is that folks want to use `container_label_restartcount` as a vector for alerting -- not that it is causing problems. It's just that as a label and not a vector, it is impossible to do so.

I understand Docker is what is exposing this, so maybe this is an issue to file on Docker itself? Or is there some future where cAdvisor could support remapping label values into vectors themselves?

**Comment by slimsag** [comment]
I have a very nasty hack for anyone wanting a `container_restart_count` metric that works: https://gist.github.com/slimsag/85e06781eb0d4d35beee12916aefac5f

**Comment by Aransh** [comment]
> I have a very nasty hack for anyone wanting a `container_restart_count` metric that works today: https://gist.github.com/slimsag/85e06781eb0d4d35beee12916aefac5f

A bit late to the party, but do you remember what the hack was? 😅
Link gives 404, looking to alert on restarting containers in my homelab and nothing I try works reliably... could really use a container_restart_count metric

**Comment by Aransh** [comment]
Never mind made my own little hack 🙂
If anyone stumbles into this at some point, all I did was use this command:
`docker inspect $(docker ps -aq) | jq -r '.[] | "container_restart_count{name=\"\(.Name | ltrimstr("/"))\"} \(.RestartCount)"'`

It will output all your containers with their restart count in a Prometheus metric format

You can run it in a loop on an interval however you like (I did it with crontab) and write the output to a file

Once you have that working, you can just elevate node-exporter's [textfile collector](https://www.robustperception.io/using-the-textfile-collector-from-a-shell-script/#more-4014) to scrape these metrics 😁

I then combined this with this alert rule expression:
`increase(container_restart_count[15m])`

Working perfectly 🙌🏼
