### ISSUE TITLE
Prometheus PushGateway configuration

### ISSUE THREAD

**Issue by NoumanSaleem** [google/cadvisor#1320]
Does cadvisor support pushing metrics to a pushgateway as opposed to being scraped?

I don't see any configuration options mentioned in https://github.com/google/cadvisor/blob/8ba1f6d5821876e48c8fa8bfcdb5a84262cf4ceb/docs/storage/prometheus.md

thanks

**Comment by f0** [comment]
@NoumanSaleem  hm why? Cadvisor exports prometheus metrics via /metrics

**Comment by jimmidyson** [comment]
Push gateway should only be used for ephemeral/batch jobs, not long running daemons like cadvisor. You can read more on when the push gateway is applicable at https://prometheus.io/docs/practices/pushing/

I'm going to close this issue as it's not something that cadvisor should support.

**Comment by NoumanSaleem** [comment]
@jimmidyson thanks, totally agree with you. My actual issue (which I guess wouldn't be solved by this GH issue) is that I have some containers which execute in <1 min  and I'd like to use prometheus + cadvisor to alert on `container_tasks_state{com_amazonaws_ecs_container_name="...", state="running"}[`; however It seems like cadvisor doesn't record these containers sometimes resulting in false alerts.
