### ISSUE TITLE
go get error in installing dependencies

### ISSUE THREAD

**Issue by andyxning** [google/cadvisor#1331]
I have followed the build instruction in the [doc](https://github.com/google/cadvisor/blob/master/docs/development/build.md). However, when running with `go get -d github.com/google/cadvisor`, i  got an error:

> google/cadvisor/storage/influxdb/influxdb.go:28:2: code in directory /home/vagrant/go/src/github.com/influxdb/influxdb/client expects import "github.com/influxdata/influxdb/client"

This is because [the latest influxdb](https://github.com/influxdata/influxdb/blob/master/client/influxdb.go#L1) add a import comment like this:

```
package client // import "github.com/influxdata/influxdb/client"
```

So, we should import "github.com/influxdata/influxdb/client" to reference `client`.

This is because `go get -d` will download the latest version of dependencies. 

As written in the [dockerfile in deploy](https://github.com/google/cadvisor/blob/master/deploy/canary/Dockerfile#L5-L7):

> RUN git clone https://github.com/google/cadvisor.git /go/src/github.com/google/cadvisor
> RUN go get github.com/tools/godep
> RUN cd /go/src/github.com/google/cadvisor && godep go build .

We should use `git clone` to download the source code and use `godep` to build it.

**Comment by LudicrousSpeed** [comment]
I am seeing this same issue with both go 1.6 and 1.5

**Comment by andyxning** [comment]
@LudicrousSpeed This may be related to `GO15VENDOREXPERIMENT`. As for common usage, go should use the `vendor` dir to get dependency first. And also, `vendor` contains older version of influxdb package which should work properly, going for the influxdb package in GOPATH is most properly due to `GO15VENDOREXPERIMENT`.
