### ISSUE TITLE
Export cgroup throttled data

### ISSUE THREAD

**Issue by chbatey** [google/cadvisor#1337]
As far as I can tell cadvisor doesn't currently expose when processes in a cgroup are throttled:

https://github.com/google/cadvisor/blob/master/container/libcontainer/helpers.go

Is there a reason for that? Otherwise I am happy to raise PR to add it as we'd really like this data aggregated in prometheus.

**Comment by vishh** [comment]
+1. A PR is welcome!

On Mon, Jun 20, 2016 at 1:30 AM, Christopher Batey <notifications@github.com

**Comment by grobie** [comment]
We're in high need for prometheus metrics about ceiling enforcement and I created a PR which exposes the information already collected by libcontainer.
