### ISSUE TITLE
cadvisor does not return any container stats when using devicemapper with no metadata file 

### ISSUE THREAD

**Issue by aveshagarwal** [google/cadvisor#1338]
docker-1.10 is using thin pool that is created by docker-storage-setup on rhel7, and in this case, metadata file is not populated:

```
#docker info
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 39
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: rhel-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 1.898 GB
 Data Space Total: 8.565 GB
 Data Space Available: 6.667 GB
 Metadata Space Used: 524.3 kB
 Metadata Space Total: 54.53 MB
 Metadata Space Available: 54 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 4
 Library Version: 1.02.124-RHEL7 (2016-05-04)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: bridge null host
 Authorization: rhel-push-plugin
Kernel Version: 3.10.0-426.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 7.64 GiB
Name: localhost.localdomain
ID: VFQS:UYX7:SQLV:5QOP:M3XL:7TA3:GG7I:PUDX:L2E5:A6YO:MLCY:GLN4
WARNING: bridge-nf-call-ip6tables is disabled
Registries: registry.access.redhat.com (secure), docker.io (secure)
```

Now when running a kube cluster, one could see the following error:

```
Docker container factory registration failed: couldn't determine devicemapper metadata device: Could not get the devicemapper metadata device.
```

The result is that getting stats on a local cluster fails for pods:

```
curl http://127.0.0.1:10255/stats/summary 
 ```
It only shows empty `"pods": []`, even though there is a pod and its containers.

And also getting stats for a specific container also fails:

````
curl http://127.0.0.1:10255/stats/<pod-name>/<container-name>

Internal Error: unable to find Docker container "021a9d9bc5c44d5c052b78f13079e1259c4fc76e633657386a745b9edfc5bc47"
```

**Comment by aveshagarwal** [comment]
@pmorie @sjenning @derekwaynecarr

**Comment by aveshagarwal** [comment]
Just to clarify that it happens with docker-1.9 too.

**Comment by sjenning** [comment]
cc @agoldste

This is related to the thin pool device being DM managed, in which case docker info shows the correct information, or LVM managed, in which case it doesn't.  Haven't looked into the docker DM graphdriver enough to figure out why.

In the meantime, I have a tentative fix
https://github.com/sjenning/cadvisor/commit/7702a5e9d9b558ec892917e6a850e613ad63f1b1

I'm just not sure how solid the assumption is building the dev path from the pool name.

**Comment by ncdc** [comment]
@sjenning did you ever get a yes/no from @rhvgoyal about the assumption?

**Comment by aveshagarwal** [comment]
@sjenning functionality wise your patch seem to work on rhel7, though not sure about its correctness/assumption.

**Comment by sjenning** [comment]
@ncdc He kept saying we should use cli tools to determine the metadata device, which is a mess here (cli tools not installed, capturing/parsing output, etc)

**Comment by derekwaynecarr** [comment]
The bigger issue I see is not being able to report file system usage for a
container should not cause all other stats to be inaccessible by cAdvisor
consumers for that container.

**Comment by aveshagarwal** [comment]
@sjenning A part of your patch is doing exactly what is being done in DockerThinPoolName, so you could call this I think.

**Comment by sjenning** [comment]
@aveshagarwal good call :) PR inbound...
