### ISSUE TITLE
Problem setting up cadvisor through API

### ISSUE THREAD

**Issue by nitinmulchandani** [google/cadvisor#1341]
Hi All,

I am using ubuntu server hosted on cloud and try to setup cadvisor by this command

docker run -d --name=cadvisor -p 8080:8080 --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro google/cadvisor:latest

it gets installed properly, but now i need to expose the API from browser. How do i do it

**Comment by vishh** [comment]
Are you able to access `http://localhost:8080` from your browser?

**Comment by nitinmulchandani** [comment]
Thanks for you reply.. **No.. i can't** 
i have just setup a ubuntu server (with docker and cadvisor setup) on cloud and then from my windows machine i want to access the the API's.. so how to make this possible ?

**Comment by vishh** [comment]
You need to expose the cAdvisor port, which is port `8080` based on your
description, on your VM's public IP. Then you can access cAdvisor UI from
your local machine.

On Tue, Jun 21, 2016 at 10:59 PM, nitinmulchandani <notifications@github.com

**Comment by dashpole** [comment]
closing, as the question is answered
