### ISSUE TITLE
Fs uage can't decrease after delete some files in devicemapper env

### ISSUE THREAD

**Issue by mdshuai** [google/cadvisor#1354]
On devicemapper env, when create some files in container, the fs usage in cadvisor webconsole can increase, but when delete some files, the fs usage can't decrease.
device-mapper-persistent-data-0.6.2-0.1.rc6.el7.x86_64
```
1. Create a large file in container and check fs usage
[root@ip-172-18-10-54 ~]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                NAMES
dcc47b467bb9        deshuai/hello-pod   "/hello-pod"        30 seconds ago      Up 28 seconds       8080/tcp, 8888/tcp   dreamy_thompson
[root@ip-172-18-10-54 ~]# docker inspect dcc47b467bb9 | grep DeviceId
                "DeviceId": "152",
[root@ip-172-18-10-54 ~]# docker exec -it dcc47b467bb9 /bin/bash
[root@dcc47b467bb9 /]# dd if=/dev/zero of=test.text bs=1M count=5120
5120+0 records in
5120+0 records out
5368709120 bytes (5.4 GB) copied, 39.18 s, 137 MB/s
[root@dcc47b467bb9 /]# exit
exit
[root@ip-172-18-10-54 ~]# dmsetup message /dev/mapper/docker-202:2-600992-pool 0 "reserve_metadata_snap"
[root@ip-172-18-10-54 ~]# thin_ls --no-headers -m -o DEV,EXCLUSIVE /dev/docker-vg/docker-metadata | grep 152
152 5123MiB 
[root@ip-172-18-10-54 ~]# dmsetup message /dev/mapper/docker-202:2-600992-pool 0 "release_metadata_snap"

2. Delete the large file and wait a long time then check the fs uage again
[root@ip-172-18-10-54 ~]# docker exec -it dcc47b467bb9 /bin/bash
[root@dcc47b467bb9 /]# ls
anaconda-post.log  bin	dev  etc  hello-pod  home  lib	lib64  lost+found  media  mnt  opt  proc  root	run  sbin  srv	sys  test.text	tmp  usr  var
[root@dcc47b467bb9 /]# ll test.text -h
-rw-r--r--. 1 root root 5.0G Jun 27 05:14 test.text
[root@dcc47b467bb9 /]# rm -rf test.text 
[root@dcc47b467bb9 /]# exit
exit
[root@ip-172-18-10-54 ~]# dmsetup message /dev/mapper/docker-202:2-600992-pool 0 "reserve_metadata_snap"
[root@ip-172-18-10-54 ~]# thin_ls --no-headers -m -o DEV,EXCLUSIVE /dev/docker-vg/docker-metadata | grep 152
152 5123MiB 
[root@ip-172-18-10-54 ~]# dmsetup message /dev/mapper/docker-202:2-600992-pool 0 "release_metadata_snap"

3. In cadvisor webconsole the fs usage is same value with the command result.
```

**Comment by mdshuai** [comment]
@ncdc @sjenning

**Comment by ncdc** [comment]
This is how devicemapper works. I'll get more details later but this is not
a bug.

**Comment by mdshuai** [comment]
thanks for your info

**Comment by ncdc** [comment]
@mdshuai correct, it will only ever increase. From what I understand, devicemapper allocates blocks when needed, but it doesn't know about filesystem deletes. @rhvgoyal might be able to provide more concrete details.

**Comment by rhvgoyal** [comment]
Upon file deletion, discards are not sent to thin pool (by default). That means thin pool never knows that block space consumed by file has been freed. That's why you see same space.

You have two options.

- Either enable online discards while mounting file system. That will slow down fs and is not a very good operation.
- Run fstrim on container rootfs and that should generate discards and free up space.

**Comment by vishh** [comment]
Does this mean that a device mapper fs will get filled up completely over
time?

**Comment by rhvgoyal** [comment]
File system knows about the free blocks and hopefully it exhausts free blocks first before it asks for more blocks from thin pool. So I think freed blocks will be reused. Just that these free blocks are sitting with filesystem and have not been returned to thin pool.

**Comment by vishh** [comment]
In that case, should we track the usage of filesystem in cAdvisor instead?

**Comment by ncdc** [comment]
I think it's better to track the blocks in the thin pool; otherwise, you aren't accounting for the actual space being used and it could look like you have more free space available than you actually do.

**Comment by ncdc** [comment]
i.e. I don't think this is a bug

**Comment by vishh** [comment]
Ack @ncdc
