### ISSUE TITLE
Failed to build, because of golang.org/x/exp/inotify

### ISSUE THREAD

**Issue by yogihardi** [google/cadvisor#1363]
Hi All,

I'm following the doc to build this project
`godep go build .`

but, I got error message like this:
`container/common/inotify_watcher.go:20:2: no buildable Go source files in /Users/yogi/Documents/workspaces/go/cadvisor/src/github.com/google/cadvisor/Godeps/_workspace/src/golang.org/x/exp/inotify`

it seems cann't load golang.org/x/exp/inotify libs, is there anyone got this error resolved? if so, please share with me.

Thanks.

**Comment by vishh** [comment]
What platform and OS are you building against? If you build against `amd64`
and `linux` it should work.

**Comment by yogihardi** [comment]
Using Mac.

and yes, you're right, it's running well on linux.
thanks.

**Comment by Paritosh-Anand** [comment]
Getting the same error. Is there no way to run this project on Mac ? 
```
make build
>> building binaries
>> building cadvisor
container/common/inotify_watcher.go:20:2: no buildable Go source files in /Users/paritoshanand/Documents/go-workspace/src/github.com/google/cadvisor/vendor/golang.org/x/exp/inotify
make: *** [build] Error 1
```

**Comment by timstclair** [comment]
We don't support running on a mac. If you want to build on a mac, you'll need to cross compile for linux.
