### ISSUE TITLE
Determine how to handle inodes with block level fs

### ISSUE THREAD

**Issue by derekwaynecarr** [google/cadvisor#1366]
cAdvisor returns inodes_free in `ContainerInfo` and `FsStats`

* inodes_free needs to be a pointer in `ContainerInfo`
* `FsStats` could have a `bool` that says if inode information is knowable, or we need to ensure we only set `inodes_free` or really any `inodes` related info based on `FsType`.

See: https://github.com/kubernetes/kubernetes/issues/28481#issuecomment-230799217

Related (report total inodes):
https://github.com/google/cadvisor/pull/1365

I am happy to send a PR to fix this today if we can get agreement:

@vishh @ronnielai @ncdc @pmorie

**Comment by ncdc** [comment]
I'm guessing that changing to pointers probably isn't backwards compatible, so I'm fine with `inodesReported bool` or something to that effect

**Comment by ronnielai** [comment]
@timstclair

**Comment by derekwaynecarr** [comment]
To summarize:

* inodes and inodes_free in `v2.FsInfo` will be pointers
* inodes and inodes_free will switch to use pointers in `fs.Fs`
* we will not change `v1.FsStats.InodesFree` (which means it will be wrong for devicemapper)
* we will not change `v1.FsInfo.Inodes` (which means it will be wrong for devicemapper)
* kube will use the v2 API to handle inodes related info

I will send a PR today or tomorrow.

**Comment by derekwaynecarr** [comment]
In trying to fix this:

https://github.com/google/cadvisor/blob/master/manager/manager.go#L690

Internally, cadvisor `InMemoryCache` is working against the v1 API.

An option I thought about is the following:

* inodes and inodes_free in `v2.FsInfo` will be pointers
* inodes and inodes_free will switch to use pointers in `fs.Fs`
* add `HasInodes bool` to `v1.FsStats`
* add `HasInodes bool` to `v1.FsInfo`

The above would allow us to change the code here:
https://github.com/google/cadvisor/blob/master/manager/manager.go#L690

It has advantages:
* we can convert v1 to v2 format object correctly and vice-versa while limit code churn
* we can return the proper value for devicemapper in v1 api

@vishh - please ack

**Comment by vishh** [comment]
https://github.com/google/cadvisor/issues/1366#issuecomment-230896690 SGTM
