### ISSUE TITLE
Support cAdvisor on Windows

### ISSUE THREAD

**Issue by asultan001** [google/cadvisor#1394]
As part of bringing k8s support to Windows, we will need cAdvisor to work on Windows as well. Currently Docker Stats are not supported on Windows Server 2016 and there is still no guidance from MSFT as to when that support will be ready so we need an alternative. 

Also, even with Docker Stats support, we would ideally want to use something more native to Windows and leverage the perf monitor API directly instead.

**Comment by timstclair** [comment]
I do not think we should make cAdvisor run on windows. The model is too different. Instead, we should wait for the [container runtime interface](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/container-runtime-interface-v1.md) to define a stats interface, and implement that interface through another model (not cAdvisor).

It would be good to keep windows support in mind when we're defining the stats interface, so we can choose the right level of abstraction (i.e. not cgroups).

**Comment by vishh** [comment]
What is the purpose of the integration? is it to enable windows support in
k8s or monitoring in general?

**Comment by asultan001** [comment]
Hey guys thanks for the feedback and comments. @vishh the original driver for wanting to do this was to enable windows support in k8s. Having said that, if cadvisor is the wrong abstraction layer then we'd be happy to consider something else, however without some alternative, we'll have a big gap on the Windows side of things. 

There are a few other options we can move forward with but we wanted to keep the implementation as symmetric as possible between Windows and Linux (as long as they make sense). A couple alternatives:

- Implement some rudimentary monitoring using straight Windows Perf Monitors to provide sufficient capability for k8s needs
- Leverage another monitoring solution like [snap](https://github.com/intelsdi-x/snap) since it's been proven it can [already work with k8s](https://github.com/intelsdi-x/kubesnap)
- Wait for the container runtime interface to provide a stats interface but it seems like this would take too long.

Any suggestions?

Thanks in advanced,
Abe

cc: @alexbrand

**Comment by vishh** [comment]
> Implement some rudimentary monitoring using straight Windows Perf Monitors to provide sufficient capability for k8s needs

I think this is what @timstclair is suggesting. We are introducing a Container Runtime API in kubelet, and how metrics are being collected wouldn't matter to the kubelet. 
If the plan is to make kubelet work with the existing docker integration, then the cAdvisor interfaces have to work for windows too.

> Leverage another monitoring solution like snap since it's been proven it can already work with k8s

Our plan as of now is to not use an external monitoring solution for internal core metrics. For full-fledged monitoring there are already multiple options like snap, sysdig, etc. 

> Wait for the container runtime interface to provide a stats interface but it seems like this would take too long.

I'm optimistic about this interface. There are quite a few people working towards implementing this interface. 

> @vishh the original driver for wanting to do this was to enable windows support in k8s. 

Ok. I was wondering if providing monitoring for windows containers is also a goal. For example, cAdvisor is already being used widely for monitoring docker containers on Linux, even outside of k8s.

**Comment by alexbrand** [comment]
Hey @vishh, as @asultan001 mentioned, we are working on supporting the kubelet on windows. From @timstclair's and your comments, it seems like the Container Runtime API will have a stats interface that we could then implement on the Windows side using perf counters. This sounds like a reasonable approach. On my end, I have to do a bit more research into what stats are collected by cAdvisor, and what the Kubelet is interested in.

**Comment by asultan001** [comment]
@vishh thanks for the update, a few more thoughts on this:

> Ok. I was wondering if providing monitoring for windows containers is also a goal. For example, cAdvisor is already being used widely for monitoring docker containers on Linux, even outside of k8s.

In part that is why we originally thought that supporting cAdvisor on windows would make sense as well even beyond the value for k8s. 

> I'm optimistic about this interface. There are quite a few people working towards implementing this interface.

Do you have an idea of the ETA for this? This may be the easiest route to implement if we are simply trying to unblock the requirements for k8s at this point. Also, is the goal to ship this as part of 1.4? from the conversation on #27097 and the comment on that issue by @timstclair it seems like this is not currently prioritized.

Cheers
Abe

**Comment by vishh** [comment]
> Do you have an idea of the ETA for this? This may be the easiest route to implement if we are simply trying to unblock the requirements for k8s at this point. Also, is the goal to ship this as part of 1.4? from the conversation on #27097 and the comment on that issue by @timstclair it seems like this is not currently prioritized.

I'd recommend opening an issue on k8s side to understand the timelines. AFAIK, people are already working towards making this API fully functional in the next couple of months.
