### ISSUE TITLE
cAdvisor on coreos host

### ISSUE THREAD

**Issue by LudicrousSpeed** [google/cadvisor#1396]
We are trying to get cAdvisor to run on the host of coreos and not in a container. With the mapping of the volumes something appears to be locking docker which impedes management.

Unfortunately when running the container locally I see an error which appears to be coming from this line. https://github.com/google/cadvisor/blob/master/manager/manager.go#L145

sudo ./cadvisor -docker_only -logtostderr
I0725 22:54:35.978132   29233 storagedriver.go:50] Caching stats in memory for 2m0s
I0725 22:54:35.978329   29233 manager.go:139] cAdvisor running in container: "/system.slice/system-sshd.slice"
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0xfcb5e0, 0x2a)
    /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 10 [syscall, locked to thread]:
runtime.cgocall(0xab97e0, 0xc820165bd8, 0x0)
    /usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820165b78 sp=0xc820165b48
net._C2func_getaddrinfo(0x7fec040008c0, 0x0, 0xc8201b65d0, 0xc8202f81e0, 0x0, 0x0, 0x0)
    ??:0 +0x55 fp=0xc820165bd8 sp=0xc820165b78
net.cgoLookupIPCNAME(0xeb1350, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/cgo_unix.go:111 +0x448 fp=0xc820165d50 sp=0xc820165bd8
net.cgoLookupIP(0xeb1350, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x723f6e6f69746172)
    /usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc820165da8 sp=0xc820165d50
net.lookupIP(0xeb1350, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc820165e18 sp=0xc820165da8
net.glob.func16(0x1060db8, 0xeb1350, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/hook.go:10 +0x4d fp=0xc820165e58 sp=0xc820165e18
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc820165ed8 sp=0xc820165e58
internal/singleflight.(_Group).doCall(0x162f140, 0xc8202fc0a0, 0xeb1350, 0x9, 0xc8201b43e0)
    /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc820165f88 sp=0xc820165ed8
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820165f90 sp=0xc820165f88
created by internal/singleflight.(_Group).DoChan
    /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ee

goroutine 1 [select]:
net.lookupIPDeadline(0xeb1350, 0x9, 0xecf288fae, 0xa4f7b0a, 0x16300c0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:109 +0x6a6
net.internetAddrList(0xe96aa8, 0x3, 0xeb1350, 0xf, 0xecf288fae, 0xa4f7b0a, 0x16300c0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0xe92350, 0x4, 0xe96aa8, 0x3, 0xeb1350, 0xf, 0xecf288fae, 0xc80a4f7b0a, 0x16300c0, 0x0, ...)
    /usr/local/go/src/net/dial.go:158 +0x466
net.(_Dialer).Dial(0xc82041d5b0, 0xe96aa8, 0x3, 0xeb1350, 0xf, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/dial.go:216 +0x124
net.DialTimeout(0xe96aa8, 0x3, 0xeb1350, 0xf, 0x77359400, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/dial.go:200 +0xa3
github.com/google/cadvisor/container/rkt.Client.func1()
    /go/src/github.com/google/cadvisor/container/rkt/client.go:44 +0x59
sync.(_Once).Do(0x1655538, 0x105ff30)
    /usr/local/go/src/sync/once.go:44 +0xe4
github.com/google/cadvisor/container/rkt.Client(0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/google/cadvisor/container/rkt/client.go:79 +0x47
github.com/google/cadvisor/container/rkt.RktPath(0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/google/cadvisor/container/rkt/client.go:85 +0x48
github.com/google/cadvisor/manager.New(0xc820335d40, 0x7fec153be870, 0x1655490, 0xdf8475800, 0x7fec18d5f501, 0xc82035d590, 0xc82035db60, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/google/cadvisor/manager/manager.go:145 +0x341
main.main()
    /go/src/github.com/google/cadvisor/cadvisor.go:127 +0x654

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
    /usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [chan receive]:
github.com/google/cadvisor/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1630420)
    /go/src/github.com/google/cadvisor/vendor/github.com/golang/glog/glog.go:882 +0x67
created by github.com/google/cadvisor/vendor/github.com/golang/glog.init.1
    /go/src/github.com/google/cadvisor/vendor/github.com/golang/glog/glog.go:410 +0x297

goroutine 49 [IO wait]:
net.runtime_pollWait(0x7fec153bf9b0, 0x72, 0xc8203c4000)
    /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(_pollDesc).Wait(0xc8203a01b0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0xc8203a01b0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).Read(0xc8203a0150, 0xc8203c4000, 0x1000, 0x1000, 0x0, 0x7fec18d5b050, 0xc8200101a0)
    /usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(_conn).Read(0xc82033a0b8, 0xc8203c4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7fec153bfa70, 0xc82033a0b8, 0xc820338888, 0xc8203c4000, 0x1000, 0x1000, 0x409ef3, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1690 +0x67
net/http.(_noteEOFReader).Read(0xc820387400, 0xc8203c4000, 0x1000, 0x1000, 0xc820039d1d, 0x0, 0x0)
    <autogenerated>:284 +0xd0
bufio.(_Reader).fill(0xc8200609c0)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(_Reader).Peek(0xc8200609c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(_persistConn).readLoop(0xc820338820)
    /usr/local/go/src/net/http/transport.go:1076 +0x177
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:860 +0x10a6

goroutine 50 [select]:
net/http.(_persistConn).writeLoop(0xc820338820)
    /usr/local/go/src/net/http/transport.go:1280 +0x472
created by net/http.(_Transport).dialConn
    /usr/local/go/src/net/http/transport.go:861 +0x10cb

**Comment by LudicrousSpeed** [comment]
Running from the latest release branch(v0.23) has fixed the issues.

**Comment by dashpole** [comment]
closing, since the updating to the latest release solved the issue
