### ISSUE TITLE
no fs stats per container

### ISSUE THREAD

**Issue by saiwl** [google/cadvisor#1403]
We use the v0.23 version of cadvisor. However we cannot get the fs stats per container via cadvisor api. Other stats are OK.

Here is the docker info:

``` shell
udo docker info
Containers: 70
 Running: 67
 Paused: 0
 Stopped: 3
Images: 32
Server Version: 1.12.0-rc3
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.5.0-0.bpo.2-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.69 GiB
Name: mesos20
ID: THI4:WO7E:K7YZ:WCTF:WGIJ:IIZN:DYTE:AT7E:LFVZ:LRDL:I3I2:RNFE
Docker Root Dir: /data/data/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

Thank you!

**Comment by Chentongxuedefanhua** [comment]
me toooooo
when i check the CAvisor, the "fs_**_io" is not 0,see the

picture:
![qq 20160801125057](https://cloud.githubusercontent.com/assets/18111540/17290840/13904848-5813-11e6-8972-7f1789c2cd43.png)

but，when it export to the prometheus/metrics ,it become 0:
like this 
![qq 20160801125300](https://cloud.githubusercontent.com/assets/18111540/17290850/1bdc84f8-5813-11e6-8892-b753baf89133.png)

and the prometheus Graph get 0
why?

**Comment by ZhenyangZhao** [comment]
@saiwl @Chentongxuedefanhua 
+1 
me too.
the same situation.
container fs io always 0 in metrics/

**Comment by fahimeh2010** [comment]
Same here. we use promethous and cadvisor to monitor containers . We can not view container_fs_io_current per containers.

**Comment by dashpole** [comment]
Is it just diskIO stats, or are other stats missing as well?

**Comment by ZhenyangZhao** [comment]
@dashpole just disk io

**Comment by dashpole** [comment]
this may be the same as #1450

**Comment by smarterclayton** [comment]
Looking at the prometheus exporter, we don't actually ever export `DiskIo` - so we don't have any of the block data.  We just report the `Filesystem` data.  `DiskIo` contains IO related to empty dirs, so it's definitely useful.

**Comment by smarterclayton** [comment]
@sjenning @derekwaynecarr

**Comment by dashpole** [comment]
@smarterclayton cAdvisor does not export any volume metrics, as volumes are a kubernetes construct.  This issue refers to container disk io metrics.  It would appear based on [this code](https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L364), that we do attempt to export container disk io metrics.  Based on the above, it looks like this bug is not confined to one storage driver, but rather is a problem converting to prometheus metrics.  I wont be able to debug this for a couple days, but anyone else is welcome to try and figure out what is broken.

**Comment by smarterclayton** [comment]
I'll take this and put up a provisional PR - blkio stats don't have the device name (just major and minor uids) so stats wouldn't have the same labels.  Going to:

1. in the handlers set the device name onto PerDiskStats (but not mark it as serializable so the JSON return doesn't change)
2. in the prometheus handler merge the appropriate PerDiskStats with the filesystem values

**Comment by smarterclayton** [comment]
```
container_fs_reads_total{container_name="deployment",device="",id="/system.slice/docker-491cec82b501782a8258fb1bb870fa5133f8bc538573693e7c4ef34db13c2378.scope",image="openshift/origin-deployer:v3.6.0-alpha.1",name="k8s_deployment.3512bdfd_docker-registry-1-deploy_default_f596261f-248d-11e7-9470-080027893417_8f752f68",namespace="default",pod_name="docker-registry-1-deploy"} 1311
container_fs_reads_total{container_name="registry",device="",id="/system.slice/docker-da6260076d47a04536b3a8339ccb40143a6c55c731c98c7a99fb3e32ea5b1f3f.scope",image="openshift/origin-docker-registry:v3.6.0-alpha.1",name="k8s_registry.c5fb07ea_docker-registry-1-g89b9_default_f702f49d-248d-11e7-9470-080027893417_868be8c3",namespace="default",pod_name="docker-registry-1-g89b9"} 100
```

**Comment by smarterclayton** [comment]
Opened a PR in #1642

**Comment by j-oss2023** [comment]
This problem is re-occuring again now on latest docker build
