### ISSUE TITLE
Ability to know how many inodes used per container

### ISSUE THREAD

**Issue by derekwaynecarr** [google/cadvisor#1422]
It is not possible to know how many inodes were used by the container.

It is only possible to know how many total inodes are available and free on a filesystem.

Ability to know how many inodes were used by an individual container would allow for better quality of service in Kubernetes when encountering inode exhaustion.  For example, it would allow us to know if one container has created a large number of 0 byte files, and target that container in response to inode exhaustion versus others.

**Comment by mdshuai** [comment]
Should fixed by https://github.com/google/cadvisor/pull/1489

**Comment by dashpole** [comment]
Yes, this issue is fixed by #1489.  We currently use this for inode-based eviction.  We also report inode usage for volumes.
