### ISSUE TITLE
Update metrics package to use info v2

### ISSUE THREAD

**Issue by grobie** [google/cadvisor#1434]

**Comment by timstclair** [comment]
Ref: https://github.com/google/cadvisor/issues/1367

**Comment by grobie** [comment]
@timstclair I'm happy to tackle this, but just to config: is v2 stable? Any plans when the v1 usage inside v2 will be fixed?

**Comment by timstclair** [comment]
Unfortunately our API is a mess right now. I'm actually not sure this is worth tackling in isolation. Most of cAdvisor uses the v1 API right now, so I think the best path forward would be to clone the v1 API to an "internal" API that get's used within cAdvisor, and only provide the v1/v2 APIs at the process boundaries (i.e. json API). Once we have the internal API, we're free to clean that up however we see fit. All this is to say, if we start moving individual components to the v2 API piece-meal, it's going to be more difficult to transition to that internal API state.

**Comment by grobie** [comment]
Sounds like a plan. I'll close it for now.
