### ISSUE TITLE
Display GPU Info on cAdvisor

### ISSUE THREAD

**Issue by jianzhangbjz** [google/cadvisor#1436]
Hi Guys,

I refer to the docs [cAdvisor Remote REST API](https://github.com/google/cadvisor/blob/master/docs/api.md#machine-information), and also read related code [machine.go](https://github.com/google/cadvisor/blob/master/info/v1/machine.go), but didn't find any API about GPU in `MachineInfo` struct. So, if we want to display the GPU info on cAdvisor, how can we do to implement that?

**Comment by vishh** [comment]
Extend machine.go to include GPU related information. PRs are welcome!

**Comment by andyxning** [comment]
@jianzhangbjz @vishh any progress on this? Or any material about GPU. I think we need more info.

**Comment by jianzhangbjz** [comment]
@andyxning I'm so sorry, I have been busy with other work this time. If you want to get this feature ASAP, I think you can start to do this. :)

**Comment by andyxning** [comment]
@jianzhangbjz I have no idea about GPU now. Just be willing to give a try. :)

**Comment by jianzhangbjz** [comment]
@andyxning :+1: Any problems about GPU, please feel free to contact me if you need. :)

**Comment by cmluciano** [comment]
@jianzhangbjz What specific metrics are you looking for? Is this just a count?

**Comment by pineking** [comment]
I think it is just a count,  #GPUs are used by each pods, #GPUs available/total on each nodes, do you have plan to implement this? @cmluciano

**Comment by liyubobj** [comment]
@cmluciano @pineking  No, we want to expose GPU live metrics, such as GPU core and GPU memory utility, to cAdvisor, as what they did for CPU and memory today.

**Comment by andyxning** [comment]
@liyubobj 

> GPU core and GPU memory utility

Could you please explain `GPU memory utility`. IIUC, we should only expose GPU core utility. :)

**Comment by liyubobj** [comment]
@andyxning Sorry, actually I want to say idle/used GPU memory.

**Comment by cmluciano** [comment]
Yes I can submit a PR @pineking . Would this require the use of a nvidia specific tool?

**Comment by liyubobj** [comment]
@cmluciano  Yes, you need either `libnvidia-ml.so` lib or `nvidia-smi` binary to get live metrics. Both of them are in nvidia GPU driver. But if you want to get GPU count only, a hack is to check `/dev/nvidiaX`.

**Comment by vishh** [comment]
I'd prefer avoiding additional executable dependencies to cAdvisor if
possible. Are there any nvidia libraries that we can leverage to get the
necessary metrics?

**Comment by vishh** [comment]
@therc any thoughts?

**Comment by liyubobj** [comment]
if you want to get the metric I mentioned, libnvidia-ml lib is enough. @vishh

**Comment by andyxning** [comment]
@liyubobj What if we use other GPU brands, such as AMD. It seems that we need to adapt to all major GPU brands.

**Comment by liyubobj** [comment]
In my side, I aimed at nvidia GPU only. Would you have requirement to support other GPU brands? @andyxning

**Comment by andyxning** [comment]
@liyubobj Not really. We should keep it generic enough to make cAdvisor easily query GPU metrics from all major brands if possible. :)

**Comment by cmluciano** [comment]
@andyxning I think the beta code for Kube only handles Nvidia for now, so initially I was only thinking of supporting that.

**Comment by therc** [comment]
@vishh there's the nvml library, but it's native code. The alternative is calling nvidia-smi, a nvml client, which I think is safe to assume will be installed along with the drivers. There's no need to scrape its human-readable output, because it also has an XML output mode.

Kubernetes right now only allocates whole GPU devices, but I agree that it would be nice to have some additional metrics, such as product name, driver version (because it affects which CUDA version is supported), RAM available and in use, number of processes talking to the device. Stuff like temperatures, fan speeds, performance state are less of a priority.

**Comment by pineking** [comment]
@therc @vishh @cmluciano any progress or update?

**Comment by cmluciano** [comment]
I submitted a proposal for NVML kubernetes/community#414 . I want to use things like nvidia-smi to grab metrics. I would like some more feedback over there from @vishh and @therc before I submit a PR.

**Comment by Hui-Zhi** [comment]
@therc I think so far we only need the GPU details which could be used for volume injection, I do not think share GPUs to multiple containers is a good idea now, like tensorflow always take the whole memory for its own, and once the application in an out of GPU memory situation, some times they just panic.

**Comment by seelam** [comment]
Irrespective of the GPU sharing between containers, developers need to know how much GPU memory is used by their application, total memory, gpu utilization, temperature, pcie link bandwidth etc. `Nvidia-smi` provides a rich collection of these metrics, I suggest we capture as many metrics as possible.

**Comment by vishh** [comment]
+1. I can help shepherd/review PRs that add GPU metrics.

**Comment by liyubobj** [comment]
@hangliu could you prepare the proposal for this?

**Comment by liyubobj** [comment]
I prefer to using NVML lib than `nvidia-smi` because it would be terrible if we call a binary, query all GPU metrics, parse useful GPU info from xml in every 1 second for example...

**Comment by Hui-Zhi** [comment]
NVML is the professional way to handle Nvidia GPU, nvidia-smi also uses NVML. just dynamic load and unload NVML is what we need.

**Comment by cmluciano** [comment]
cc @tianshapjq

I read through your PR on the K8s, repo and I think that you definitely have captured a few key specs.

I think that we should consider leveraging the C NVML bindings for metrics collection. This would eliminate the need for dumping/parsing XML from nvidia-smi.

**Comment by cmluciano** [comment]
cc @RenaudWasTaken @3XX0 could use your input here.

My first thought was to use the NVML bindings in nvidia-docker for gathering metrics.

**Comment by 3XX0** [comment]
This would be one way to do it, but again this shouldn't be in Kubernetes IMHO this should be pluggable (e.g. known by the GPU scheduler extender). For example, we might want to leverage DCGM instead for Tesla GPUs.

**Comment by vishh** [comment]
@3XX0 cadvisor is used not just for collecting core kubernetes metrics, but also for general purpose container monitoring. AFAIK, we do not need any core metrics for GPUs in k8s as of now. There is a need for monitoring metrics though. So, if cAdvisor needs to support multiple means for collecting metrics, that's OK. We might disable GPU monitoring metrics in the compiled-in version of cadvisor in kubelet.

**Comment by 3XX0** [comment]
Yeah sorry I realized afterwards and edited my comment :)

Also it's worth mentioning that you won't get much metrics per container with NVML.
The only thing you can get is the [memory used per PID](https://docs.nvidia.com/deploy/nvml-api/structnvmlProcessInfo__t.html#structnvmlProcessInfo__t) (be careful about the PID namespace).

`nvidia-smi pmon` uses internal functions to get more metrics, I mentioned it a while ago to the team in charge, I will try to see if they can fix it.

**Comment by WIZARD-CXY** [comment]
@Hui-Zhi @vishh any updates or pr here? thx

**Comment by WIZARD-CXY** [comment]
@vishh I plan to implement a simple version of gpu monitor using cadvisor+prometheus.I want to monitor each container's gpu sm util and mem util by using ```nvidia-smi pmon ```according to @3XX0 while I noticed many people prefer to use nvml to do the job.

**Comment by Hui-Zhi** [comment]
@WIZARD-CXY Could you write a proposal about it? I would like to give some comments about the detail.

And regarding the NVML in cadvisor, so far I am working some other projects, but this definitely in my schedule.

**Comment by andyxning** [comment]
According to [gpu impl](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go) in kubernetes, we may give NVML a try.

**Comment by cmluciano** [comment]
Yes. The NVML library from Nvidia is preferred. Wrapping the command line tool could be a performance drain. Nvidia-docker currently has nvml bindings, but we should push to get them in libnvidia-container.

**Comment by WIZARD-CXY** [comment]
@Hui-Zhi I googled about nvml today and don't  find much about how to get metrics per container with NVML as @3XX0 said while I found it really easy to use nvidia-smi pmon, so I would give it a naive try. I think I would use the same approach as other metrics like cpu usage of a container like https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L138

**Comment by cmluciano** [comment]
I believe nvidia-smi is just wrapping nvml.

https://github.com/NVIDIA/libnvidia-container
https://github.com/NVIDIA/nvidia-docker

**Comment by WIZARD-CXY** [comment]
I think we should not use nvml directly, we'd better use plugin mechanism just like cni solution, we can actually use weave, calico as different provider. We just need to define the correct interface, that's enough IMHO.

**Comment by vishh** [comment]
-1 for adding new binary dependencies.

**Comment by flx42** [comment]
@vishh I would like to know what's your opinion on how we should proceed here for adding GPU support to cAdvisor. The two main options already discussed are:
1. Call `nvidia-smi` repeatedly like suggested in https://github.com/kubernetes/kubernetes/pull/43934
`nvidia-smi` might not be installed, and probably a waste of CPU cycles (many calls to `exec` + repeated initialization of the context).
2. Use the NVML library. This will require using cgo, header `nvml.h` at build time and `dlopen/dlsym` at runtime. It will be more complex to do, but will provide better performance (a single NVML initialization).

I see a third option though:

3. Use a plugin approach for custom metrics where the NVIDIA metrics will be served by a different process over gRPC for instance. 2 years ago, it seems it was considered out of scope: https://github.com/google/cadvisor/issues/483

cc @3XX0

**Comment by vishh** [comment]
I would not recommend option `1`. We already have issues with CPU consumption.
Option `3` is complex from a deployment standpoint. cAdvisor being a single process that you can drop on any node is a great UX IMHO.

Is a native `golang` implementation possible for nvml?

**Comment by 3XX0** [comment]
Unfortunately, we can't do a native implementation because NVML is closed source.
The best we can do is to leverage cgo either in cAdvisor or in a separate gRPC service.

Either way, we will probably publish a Go package (akin to the nvidia-docker nvml package) to abstract this away.

**Comment by tianshapjq** [comment]
@3XX0 is any schedule on the release of the Go package?

**Comment by WIZARD-CXY** [comment]
I like option 3 plugin mechanism. Actually there is already a REST API  available https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin#rest-api

**Comment by cmluciano** [comment]
I've been holding off on a PR until the nvidia-container project exposes Go bindings. However, the library would still need to be available on the host as noted. 

I can start something for option 2 if we want to leverage cgo instead.

**Comment by flx42** [comment]
@vishh How do you want to proceed? Is cgo in cAdvisor an option?
If not, is cgo in an external golang package imported by cAdvisor an option? (this would just hide the cgo in the different codebase).

**Comment by cmluciano** [comment]
A quick look-through shows that several vendored libs are using cgo, but it doesn't seem to be within cadvisors pkgs.

**Comment by vishh** [comment]
Given the options, cgo seems to least intrusive.

**Comment by cmluciano** [comment]
@flx42 @renaudwastaken Are you interested in owning this?

**Comment by flx42** [comment]
Yes, but not immediately, I hope we can start working on this soon.

**Comment by yongtang** [comment]
I have a very preliminary implementation for this issue:
https://github.com/google/cadvisor/compare/master...yongtang:1436-GPU-Info

At the moment the implementation only collects model, path (`/dev/`), total memory, and used memory. The implementation dlopen' nvml (if it is available) so it relies on cgo.

If this is OK, I could create a pull request and work on further implementations like additional GPU info, etc.

**Comment by tianshapjq** [comment]
@yongtang I am working on this issue as well, but erasing "-extldflags '-static'" in build.sh still makes me confused: would it just use dynamic link for compile and then we have to mount more volumes into the container? Because there exists lots of cgo in cadvisor, is it ok to use dynamic link?

**Comment by flx42** [comment]
I don't think we can simply remove this flag like that. We can't use `RTLD_GLOBAL` like our `nvidia-docker` code does, you will need to `dlsym` each symbol manually. Tedious, but I don't believe we really have a choice.

**Comment by yongtang** [comment]
@flx42 I will update the implementation to use `dlsym`. 

Though I am not sure we could get around the dynamic issue. For example, the following snippet will generate a warning
```
root@4f51cb55a0db:/go/src/github.com/google.com/cadvisor# cat main.go 
package main

/*
#cgo linux LDFLAGS: -ldl
#include <dlfcn.h>
#include <stddef.h>

void *nvml = NULL;
*/
import "C"

import (
	"fmt"
)

func main() {
	C.nvml = C.dlopen(C.CString("libnvidia-ml.so.1"), C.RTLD_LAZY)
	if C.nvml == nil {
		fmt.Println("Couldn't load nvml library")
	}
	fmt.Println("Hello, playground")
}
root@4f51cb55a0db:/go/src/github.com/google.com/cadvisor# go build -ldflags="-extldflags '-static'"
# github.com/google.com/cadvisor
/tmp/go-link-816969679/000000.o: In function `_cgo_56e60412441f_Cfunc_dlopen':
/tmp/go-build/github.com/google.com/cadvisor/_obj/cgo-gcc-prolog:42: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

**Comment by yongtang** [comment]
@flx42 Updated and created the PR #1739 to use `dlsym` for resolving functions. Please take a look.

**Comment by flx42** [comment]
@yongtang @vishh @mindprince @3XX0 @cmluciano: before considering this PR, we should probably sync on what we want to achieve, how, and what the roadmap should be. What do you think?

**Comment by mindprince** [comment]
Agreed. Let's sync up in a meeting. This week is kubernetes code freeze deadline, so we can't meet this week. Probably sometime next week, maybe September 7?

**Comment by yongtang** [comment]
@flx42 @mindprince A sync up would be great 👍 . I am available next week but other times might work as well.

**Comment by WIZARD-CXY** [comment]
glad to see this thing move forward

**Comment by tianshapjq** [comment]
@mindprince @flx42 This issue is WIP in my work, would you please inform me if you have made the schedule of the meeting? :)

**Comment by flx42** [comment]
@mindprince September 7 works for me!

**Comment by mindprince** [comment]
Anyone who wants to join:
Meeting date: September 7, 11am to 11:50am PDT.
Meeting URL: https://talkgadget.google.com/hangouts/_/google.com/gpu-cadvisor

**Comment by tianshapjq** [comment]
@mindprince @yongtang @flx42 hi, do we have a summary after the meeting?

**Comment by mindprince** [comment]
I will try to share a doc by EOD today.

**Comment by mindprince** [comment]
Here are the meeting notes: https://docs.google.com/document/d/1cNo88Z1b5gb3svHNlOQLWCLGevF5GIOpfVbJFKDg5iY/edit

You will have to be a member of kubernetes-dev@googlegroups.com to access.

**Comment by tianshapjq** [comment]
HI, any news about this feature? still waiting for the DCGM coming up? @mindprince

**Comment by mindprince** [comment]
@tianshapjq I have a WIP PR here: https://github.com/google/cadvisor/pull/1762

**Comment by rapatel0** [comment]
Hello, 

I was just wondering what the status is? There doesn'i seem to be any documentation on how to enable gpu tracking in cadvisor.

**Comment by mindprince** [comment]
@rapatel0 https://github.com/google/cadvisor/issues/1796 tracks adding documentation about how to use this.

**Comment by guptaNswati** [comment]
@tianshapjq We have published [DCGM go bindings](https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/bindings/go/dcgm)
