### ISSUE TITLE
cadvisor non-container mode

### ISSUE THREAD

**Issue by mgdsxhy** [google/cadvisor#1441]
HI 
could cadvisor run as non-container mode? How do that?

**Comment by vishh** [comment]
What do you mean by non-container? Run outside of a container? or track
resources that are not in containers?

**Comment by mgdsxhy** [comment]
Run outside of a container, I want run the Cadvisor with nohup or systemctl.
Such as   "nohup cAdvisor &"   
              "systemctl start cAdvisor"
Can realize?

**Comment by timstclair** [comment]
Yes, you can just run `sudo cadvisor` (needs root privileges). The binary can be found on our [releases](https://github.com/google/cadvisor/releases) page, or you can build your own with `make build`.

**Comment by mgdsxhy** [comment]
Thanks, I'll try it.
