### ISSUE TITLE
Can't get any diskio data from cadvisor API if docker use overlayFS 

### ISSUE THREAD

**Issue by workhardcc** [google/cadvisor#1450]
Seems if docker use overlayFS for its storage cadvisor can not get diskio data from the API:
`"diskio": {},`
I found that there is no data in /sys/fs/cgroup/blkio/docker/$CONTAINER_ID/blkio.throttle.io_service_bytes either.

**Comment by fzu-huang** [comment]
use `dd` to make some disk IO.Then check it again.    I met this situation before..

**Comment by workhardcc** [comment]
@fzu-huang You're right. `dd if=/dev/zero of=/home/cc bs=1M count=3000` makes it work. 
I have a another question: why I `dd` some data in container's disk  but there is no change in blkio.throttle.io_service_bytes

**Comment by derekwaynecarr** [comment]
@workhardcc -- i cant tell if you resolved your own issue?

**Comment by workhardcc** [comment]
@derekwaynecarr sorry for late reply. I didn't resolve this problem, now I'm almost give up get container's diskio metrics.

**Comment by dashpole** [comment]
closing via #1642.
