### ISSUE TITLE
Docker Hub canary Image is 200+MB, All Others Are < 20MB

### ISSUE THREAD

**Issue by amcrn** [google/cadvisor#1452]
See https://hub.docker.com/r/google/cadvisor/tags/

The `canary` image is over 200MB, whereas the traditional tagged releases are < 20MB. Is it possible to update the CI so that the `canary` pushed to Docker Hub is around 20MB as well?

Thanks!

**Comment by timstclair** [comment]
The canary image builds cAdvisor from HEAD (in the container), so it has a lot more tool requirements. I'm sure it could be optimized more, but I'm not sure it's worth it (we'd still welcome a PR though). If the need is just to have a recent image built from head, it might be easier to just automate building with the same dockerfile used for the production images.

**Comment by vishh** [comment]
Currently canary images include go build env. We need to change the canary
build process to create canary images similar to how we build official
images.
