### ISSUE TITLE
Remove usage of package prometheus globals

### ISSUE THREAD

**Issue by grobie** [google/cadvisor#1459]
cAdvisor is often used as library and embedded into other programs, its usage of package globals makes isolation impossible can be even harmful. The usage of package `http` has already been removed, package `flag` globals are tracked in #1175 which leaves us with package `prometheus` globals. Using a separate registry will ensure that cAdvsior controlled metrics won't leak.

**Comment by timstclair** [comment]
+1

Is anything other than the vars [here](https://github.com/google/cadvisor/blob/d7a44cb1a2c66e1688ccdc5d09e56069eecb659a/metrics/prometheus.go#L537) (`prometheus.NewDesc(...)`) leaking?

**Comment by timstclair** [comment]
Got it. I think that's actually not too bad, since everything that method does is through exported methods and it's not done by init, but a fix would still be welcome!

**Comment by grobie** [comment]
The problem is that it makes it impossible to disable cadvisor prometheus metrics from Kubernetes, as the register method gets called even if cadvidor port == 0: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_linux.go#L133

Change is incoming, just wanted to give a heads-up and give room for a discussion first.

**Comment by grobie** [comment]
It also means that all endpoints returning prometheus metrics in a kubelet (there are two: the cadvisor /metrics endpoint as well as the api / metrics endpoint) will both return the same set of metrics.

**Comment by timstclair** [comment]
Got it. Thanks!
