### ISSUE TITLE
cAdvisor in Kube 1.4 is broken on RHEL systems when running in a container - cgroup is out of order

### ISSUE THREAD

**Issue by smarterclayton** [google/cadvisor#1461]
Kubelet start fails in cAdvisor because of an notify watch failure on what is a symlink

```
F0914 17:16:59.291599   18951 kubelet.go:1149] Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/cpuacct,cpu: no such file or directory
```

https://paste.fedoraproject.org/428168/38900021/

This is from the 1.4 cAdvisor (or just before?) - when mounted in a container cadvisor sees a different cgroup path, which causes cAdvisor to quick.  Breaks containerized kubelet using -v /sys:/sys mounts.

**Comment by smarterclayton** [comment]
@derekwaynecarr @ncdc @mrunalp correct me if I got any of that wrong.

**Comment by mrunalp** [comment]
@smarterclayton Yeah, the system order is different from what we see in the container when we bind mount /sys over /sys. IMO, cadvisor should check which path exists and set the inotify watch accordingly.

**Comment by vishh** [comment]
IIRC, this was fixed via a libcontainer update. Libcontainer was mounting
cgroups with non-identify mappings inside the container. I'm surprised this
is showing up in k8s v1.4.0

**Comment by mrunalp** [comment]
@vishh This is what libcontainer mounts inside a container (for e.g.):
```
drwxr-xr-x. 2 root root  0 Sep 14 22:18 blkio
lrwxrwxrwx. 1 root root 11 Sep 14 22:18 cpu -> cpu,cpuacct
drwxr-xr-x. 2 root root  0 Sep 14 22:18 cpu,cpuacct
lrwxrwxrwx. 1 root root 11 Sep 14 22:18 cpuacct -> cpu,cpuacct
drwxr-xr-x. 2 root root  0 Sep 14 22:18 cpuset
drwxr-xr-x. 2 root root  0 Sep 14 22:18 devices
drwxr-xr-x. 2 root root  0 Sep 14 22:18 freezer
drwxr-xr-x. 2 root root  0 Sep 14 22:18 hugetlb
drwxr-xr-x. 2 root root  0 Sep 14 22:18 memory
lrwxrwxrwx. 1 root root 16 Sep 14 22:18 net_cls -> net_cls,net_prio
drwxr-xr-x. 2 root root  0 Sep 14 22:18 net_cls,net_prio
lrwxrwxrwx. 1 root root 16 Sep 14 22:18 net_prio -> net_cls,net_prio
drwxr-xr-x. 2 root root  0 Sep 14 22:18 perf_event
drwxr-xr-x. 2 root root  0 Sep 14 22:18 pids
drwxr-xr-x. 2 root root  0 Sep 14 22:18 systemd
```

Now, when we bind mount /sys:/sys we are overwriting that with the order on the system which happens to be the opposite on RHEL and hence the issue. 
One thing that cadvisor could do is not use combined paths as symlinks are provided for each subsystem to a combined path.

Not sure how we can fix this in libcontainer.

**Comment by vishh** [comment]
cAdvisor uses libcontainer to identify the mount points. IIRC, libcontainer
used the first set of mount paths it identifies. I don't have time to dig
into it now, but in essence, libcontainer should be able to pick the right
set of mount points.

**Comment by timstclair** [comment]
Is this the same as https://github.com/google/cadvisor/issues/1444?

**Comment by mrunalp** [comment]
@vishh Yes, libcontainer looks at the first mount points that it finds. How is cadvisor expected to be launched in a container? What host paths are expected to be mounted inside? This will help identify how to fix this.

**Comment by vishh** [comment]
It expects all the cgroups mounts from the host to be mounted. It uses
libcontainer to detect the cgroup mounts.

**Comment by mrunalp** [comment]
@vishh with a -v /sys:/sys:ro ?

**Comment by mrunalp** [comment]
@vishh I went through the code and I think it will be easier if we discuss this over a call. What you really want is the later mount point from mountinfo but that isn't always the correct assumption that could be made in libcontainer especially when nesting containers (like docker-in-docker).

**Comment by vishh** [comment]
sgtm!

**Comment by mrunalp** [comment]
I propose that we enhance the libcontainer API to allow getting all the mounts in order. Then it is up to the caller to use them in whatever way they see fit. See https://github.com/opencontainers/runc/commit/5e91f1cd1b19b091c129d4fb937d5cb54a9b1db0 cadvisor could just pick the later entries and it should all work fine.

**Comment by derekwaynecarr** [comment]
I spoke w/ @mrunalp and we want to proceed as follows:

* get this merged into opencontainers/runc https://github.com/opencontainers/runc/pull/1049
* bump the cadvisor dependency to include that commit
* update the call here: https://github.com/google/cadvisor/blob/master/container/libcontainer/helpers.go#L48 to pass *true* to get all mount points.

Given the ordering of the mount points, cAdvisor when iterating them will get the proper items in its map by virtue of its iteration order in the slice as desired.

**Comment by timstclair** [comment]
Do we need this in k8s v1.4 / cAdvisor v0.24? The cAdvisor release was supposed to be cut today, but I held it back. If so, please get approval for cherrypicking into k8s v1.4 first.

**Comment by timstclair** [comment]
@pwittrock in case we need this for v1.4

**Comment by timstclair** [comment]
@eparis

**Comment by eparis** [comment]
@timstclair I think yes. Which means maybe you get the cadvisor rebase after all   :)

**Comment by derekwaynecarr** [comment]
I didn't think this needed to gate 1.4 as it only impacts running cAdvisor or Kubelet in a container... /cc @eparis @dawnchen

**Comment by dchen1107** [comment]
Agreed with @derekwaynecarr on that this shouldn't be the blocker for 1.4 release.

**Comment by philips** [comment]
@mrunalp What do you mean by "Now, when we bind mount /sys:/sys we are overwriting that with the order on the system which happens to be the opposite on RHEL and hence the issue?"

**Comment by derekwaynecarr** [comment]
this is fixed now, take a look at the PR and should be clear.  If your host
had cpu,cpuacct but inside the container it was always looking for
cpuacct,cpu independent of what the host had since it didn't look at all
mountpoints.  So if your OS had sys/fs/cgroup/ setup in the opposite order,
you would hit this.

**Comment by qband** [comment]
Here is the solution that works https://github.com/kubernetes/kubernetes/issues/32728#issuecomment-252469277

**Comment by nnordrum** [comment]
Assuming you're running in docker, you can do this too:
```
sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpuacct,cpu:rw \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest
```

I just took the example from the front page and added this:
```
  --volume=/sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpuacct,cpu:rw \
```
Works like a champ!
