### ISSUE TITLE
cAdvisor container names not captured when running cAdvisor in mesos

### ISSUE THREAD

**Issue by mohamedhaleem** [google/cadvisor#1468]
hi

We are running cAdvisor in mesos on each of our mesos agents and it appears that the containers names are not showing up. Is there anything that we need to do differently to get the container names to show up versus cgroup names

docker ps output
```
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                      NAMES
b25903cd149c        google/cadvisor:latest       "/w/w /usr/bin/cadvis"   7 days ago          Up 7 days           0.0.0.0:31920->8080/tcp    mesos-f3b1b03c-c900-43ac-b07c-697c555dc65e-S17.8f295e5e-3463-418f-91de-2e765335f3b2
75d8f7811d25        titpetric/netdata            "/w/w /bin/sh -c '/us"   7 days ago          Up 7 days           0.0.0.0:31875->19999/tcp   mesos-f3b1b03c-c900-43ac-b07c-697c555dc65e-S17.009682eb-48a1-4ff2-b24c-7c5a0d9698fc
15d1d1192228        weaveworks/plugin:1.6.1      "/home/weave/plugin"     7 days ago          Up 7 days                                      weaveplugin
7eac0e6a9e00        weaveworks/weaveexec:1.6.1   "/home/weave/weavepro"   7 days ago          Up 7 days                                      weaveproxy
76aaa9665c89        weaveworks/weave:1.6.1       "/home/weave/weaver -"   7 days ago          Up 7 days                                      weave
```

Marathon JSON file for deployment

```
{
"id": "cadvisor",
"apps": [
    {
    "constraints": [
        [
            "hostname",
            "UNIQUE"
        ]
    ],
    "container": {
        "docker": {
            "image": "google/cadvisor:latest",
            "labels": { "tags": "cadvisor" },
            "forcePullImage": true,
            "network": "BRIDGE",
            "portMappings": [ { "containerPort": 8080, "hostPort": 0, "servicePort": 0, "protocol": "tcp" } ]
        },
        "parameters": [ { "key": "restart", "value": "always" } ],
        "type": "DOCKER",
        "volumes": [
            { "containerPath": "/rootfs", "hostPath": "/", "mode": "RO" },
            { "containerPath": "/var/run", "hostPath": "/var/run", "mode": "RW" },
            { "containerPath": "/sys", "hostPath": "/sys", "mode": "RO" },
            { "containerPath": "/var/lib/docker", "hostPath": "/var/lib/docker", "mode": "RO" }           
        ]
    },
    "cpus": 0.5,
    "id": "cadvisor",
    "instances": 5,
    "healthChecks": [{
         "gracePeriodSeconds": 300,
         "intervalSeconds": 20,
         "maxConsecutiveFailures": 3,
         "path": "/containers/",
         "portIndex": 0,
         "protocol": "HTTP"
         }],
    "mem": 256
    }
       ]
}
```

thank you for any pointers/help - have looked at #1127, am not yet at a point to integrate with influxdb just yet, but will be adding that.

regards

**Comment by timstclair** [comment]
Can you add the cAdvisor output for one of those containers?

**Comment by mohamedhaleem** [comment]
@timstclair - how can i get the cAdvisor output? are you looking for the UI?

**Comment by timstclair** [comment]
`<cAdvisor_addr>:8080/api/v2.1/stats/<full_container_id>`
Specifically, I'm interested in the aliases field.

**Comment by mohamedhaleem** [comment]
"aliases": [
                    "mesos-f3b1b03c-c900-43ac-b07c-697c555dc65e-S12.fc74c1b1-23c1-4c3c-a26f-4b74e2da6ded",
                    "41606b8d7a54235d9886057c398a9b4ccba3e9360d41816b89595e88b2bc392f"
                ],

**Comment by timstclair** [comment]
Hmm, which version of docker & which version of cAdvisor are you running?

**Comment by mohamedhaleem** [comment]
`
docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

# docker exec -i 59830455d9ad /usr/bin/cadvisor -version
cAdvisor version 0.23.8 (5c5b2b8)
`

**Comment by mohamedhaleem** [comment]
@timstclair any more ideas?

**Comment by timstclair** [comment]
Actually, that looks like it's working as intended. The name of that container is `mesos-f3b1b03c-c900-43ac-b07c-697c555dc65e-S12.fc74c1b1-23c1-4c3c-a26f-4b74e2da6ded`. cAdvisor uses the first alias as the container name. In the UI it will use that name if you click the "docker containers" link. Where is the confusion?

**Comment by mohamedhaleem** [comment]
thank you for looking into it @timothysc -those names are correct, we wanted a way to specify human readable name that we can then group the applications together.

**Comment by franklsm1** [comment]
@mohamedhaleem Did you figure out a work around to get a human readable name as the alias for mesos containers? I am hitting the same thing and it would be really nice to use the image name or something like that.

**Comment by mimmus** [comment]
I am hitting the same thing and it would be really nice to use the image name or something like that.

**Comment by mohamedhaleem** [comment]
Well - we are no longer using cadvisor and instead defer to using https://github.com/bobrik/collectd-docker

- Mohamed

**Comment by franklsm1** [comment]
@mimmus I ended up adding a label field to the docker parameter section of marathon like so:
```
"parameters": [
      {
        "key": "label",
        "value": "application=cadvisor"
      }
    ]
```
that allowed me to query based on the label. The label will be the same for multiple instances which can be bad if you wanted each one separate (would be nice if there was a way to append an instance identifier), but that allowed me to at lease be able to tell which container I was looking at.

**Comment by giuseppecossu** [comment]
Thank you @franklsm1 it works!
