### ISSUE TITLE
Cannot start container in centos

### ISSUE THREAD

**Issue by JamesKyburz** [google/cadvisor#1480]
Running `Linux dpd2 3.10.0-229.1.2.el7.centos.onapp.x86_64 #1 SMP Tue Apr 7 13:04:56 EEST 2015 x86_64 x86_64 x86_64 GNU/Linux`

I am getting issue #1476.

Am running version v0.24.0 from dockerhub. Any change you could publish a new version with this fix?

**Comment by timstclair** [comment]
We will publish a `v0.24.1` with the fix, probably in the next 1-2 weeks.

/cc @derekwaynecarr

**Comment by JamesKyburz** [comment]
@derekwaynecarr @timstclair  Great thanks!

**Comment by dashpole** [comment]
closing this, since v0.24.1 has been released
