### ISSUE TITLE
cadvisor redundantly gathering docker stats on ubuntu 16.04

### ISSUE THREAD

**Issue by rhuddleston** [google/cadvisor#1495]
See attached file. Basically cadvisor is gathering stats about the same container twice:

container_cpu_system_seconds_total{id="/docker/dfae05cccdaa4c7b38c0f19cbe8b13674474f81bc2454956dfa08b04464a2115",image="google/cadvisor:v0.24.0",name="cadvisor"} 243.51
container_cpu_system_seconds_total{id="/system.slice/var-lib-docker-containers-dfae05cccdaa4c7b38c0f19cbe8b13674474f81bc2454956dfa08b04464a2115-shm.mount",image="google/cadvisor:v0.24.0",name="cadvisor"} 0

The /system.slice/var-lib-docker-containers-<container_id>-shm.mount version either is always 0 or exactly the same as the other version of the same stat with id "/docker/<container_id>"

The examples where it's exactly the same:

container_fs_usage_bytes
container_last_seen
container_network_*
container_spec_cpu_*
container_start_time_seconds

These ones always return 0 for the shm.mount version:
container_cpu_*
container_memory_*

Can we either automatically ignore the redundant shm.mount version and add some way to filter these out so I'm not storing unneeded timeseries data in prometheus.
[cadvisor.txt](https://github.com/google/cadvisor/files/520118/cadvisor.txt)

**Comment by dashpole** [comment]
The fix for #1572, which is #1573 is in v0.25.0.  Can you confirm that your issue is solved with the new version?

**Comment by dashpole** [comment]
closing until we see if this is reproducible on the newest version
