### ISSUE TITLE
cadvisor push a lot of null (0) values in influxdb

### ISSUE THREAD

**Issue by LeJav** [google/cadvisor#1499]
I am using cadvisor v0.24.0 with influxdb and notice that a lot of values in influxdb are 0 as they would not.
For instance:

> select \* from memory_usage 
> 1476378957143152358 squash      az-cadvisor-int 0
> 1476378962131111872 squash      az-cadvisor-int 17707008
> 1476378979871953620 squash      az-cadvisor-int 0
> 1476378982526166681 squash      az-cadvisor-int 17707008
> 1476379018907039946 squash      az-cadvisor-int 17600512
> 1476379020922015431 squash      az-cadvisor-int 0
> 1476379055024139939 squash      az-cadvisor-int 17600512
> 1476379093094305989 squash      az-cadvisor-int 17604608
> 1476379124982305969 squash      az-cadvisor-int 0
> 1476379128596337094 squash      az-cadvisor-int 17686528
> 1476379153414064044 squash      az-cadvisor-int 17682432

As you can see, there is no reason to have 0 for memory_usage.
It is the same for CPU measurements.

I avoid these values with a "where value != 0" in sql query but it not optimal.
With 0 values means are incorrect and my graphs are not good.

I tried to play with a lot of parameters but no way to get rid of these 0 values.
Please, could somebody help me to understand what is wrong with my configuration?

**Comment by dashpole** [comment]
Apologies for the slow response.  What OS/runtime are you using?

**Comment by LeJav** [comment]
OS is CentOS 7.2
cadvisor runs in docker container
Honestly, I have given up with cadvisor due to this problem.

**Comment by dashpole** [comment]
What are the columns from your output?  We recently fixed bugs related to cadvisor metrics dissapearing with on systemd systems.  
Sorry to hear that.  If you arent interested in debugging this, feel free to close the issue.

**Comment by LeJav** [comment]
I thank you for your feedback.
But as this ticket is now old and I do not use anymore cadvisor, I close now this issue.
Anyway, thanks for your good work and your support.
