### ISSUE TITLE
Execute shell command based on conditions

### ISSUE THREAD

**Issue by michaelalhilly** [google/cadvisor#1525]
There is at least 1 common use case for the need to run a script in response to Docker container states. In cases where container addresses have to be added and removed from Nginx/HAProxy configuration files when containers are starter, stopped, or removed this would be very useful. While there are some solutions out there they do not work across the board.

It seems executing a shell command based on a set of conditions would be very useful.

**Comment by dashpole** [comment]
To me, this seems out of the scope of cAdvisor, which is primarily concerned with collecting and publishing stats for containers.  How does this feature relate to container monitoring?

**Comment by michaelalhilly** [comment]
I don't disagree with you.

In cluster environments it is a common task to run a script in response to a change in a container state. In my mind it would be added to cadvisor as an event that we can hook into. It seems reasonable since the container state is already being tracked. However if it would add too much overhead or whatever then it's not worth it.
