### ISSUE TITLE
container_fs_io_current per containers

### ISSUE THREAD

**Issue by fahimeh2010** [google/cadvisor#1532]
Hello All
First thank you for your open source project.
I use promethous and cAdvisor to monitor containers. In cAdvisor:8080/metrics I do not get container_fs_io_current per containers. actually it is per physical partitions. How can I get container_fs_io_current for each containers?

Docker info:
Server Version: 1.12.2
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local local-persist
 Network: host null bridge overlay weavemesh
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-040400-generic

cAdvisor metrics:
.
.
.
`# HELP container_fs_io_current Number of I/Os currently in progress`
`# TYPE container_fs_io_current gauge`
container_fs_io_current{device="/dev/sda2",id="/"} 0
container_fs_io_current{device="/dev/sda3",id="/"} 51
container_fs_io_current{device="overlay",id="/"} 0
`# HELP container_fs_io_time_seconds_total Cumulative count of seconds spent doing I/Os`
`# TYPE container_fs_io_time_seconds_total counter`
container_fs_io_time_seconds_total{device="/dev/sda2",id="/"} 0.000348888
container_fs_io_time_seconds_total{device="/dev/sda3",id="/"} 0.000555204
container_fs_io_time_seconds_total{device="overlay",id="/"} 0
.
.
.

Thank you

**Comment by dashpole** [comment]
similar issues: #1403, #1450.  I will look to resolve these soon...

**Comment by dashpole** [comment]
closing via #1642
