### ISSUE TITLE
[Question] Extract cpu usage using v1 client

### ISSUE THREAD

**Issue by nlamirault** [google/cadvisor#1541]
hi,
I would like to know how to extract the percentage of CPU from the CpuUsage [1] data ?

[1] : https://godoc.org/github.com/google/cadvisor/info/v1#CpuUsage

**Comment by timstclair** [comment]
For a node or container? If a container, a percentage of what? You can find available CPU numbers in the [MachineInfo](https://godoc.org/github.com/google/cadvisor/info/v1#MachineInfo) and [CpuSpec](https://godoc.org/github.com/google/cadvisor/info/v1#CpuSpec) (under the [ContainerSpec](https://godoc.org/github.com/google/cadvisor/info/v1#ContainerSpec))

**Comment by dashpole** [comment]
closing since the question was answered.
