### ISSUE TITLE
cadvisor do gather but not copy tcpstat of container.

### ISSUE THREAD

**Issue by fzu-huang** [google/cadvisor#1546]
When I try to get number of container's tcp CloseWait. I found that cadvisor did not put that into stat data:
`/info/v2/conversion.go`:
```
//func MachineStatsFromV1
if cont.Spec.HasNetwork {
			stat.Network = &NetworkStats{
				// FIXME: Use reflection instead.
				Tcp:        TcpStat(val.Network.Tcp),
				Tcp6:       TcpStat(val.Network.Tcp6),
				Interfaces: val.Network.Interfaces,
			}
		}

//func ContainerStatsFromV1
if spec.HasNetwork {
			// TODO: Handle TcpStats
			stat.Network = &NetworkStats{
				Interfaces: val.Network.Interfaces,
			}
		}
```
I am sure cadvisor will gather tcp stat (only if we set `--disable_metrics=""` ) Why don't cadvisor just copy the data into `v2.ContainerStats.Network.Tcp`  ?  If I set `--disable_metrics=""` , I still can't get any tcpstat when I using cadvisor API:`/api/v2.1/stats/{CID}`

**Comment by timstclair** [comment]
Looks like an oversight. We'd welcome a PR :)
