### ISSUE TITLE
How do you get cpu usage using the REST API?

### ISSUE THREAD

**Issue by tadivenkat** [google/cadvisor#1557]

**Comment by ebuildy** [comment]
Use docker API!

**Comment by tadivenkat** [comment]
I have a java client which is reports the monitoring metrics. Hence I am constrained in using REST API.
There seems to be a formula which I need to find out in calculating cpu usage at a given instant of time.

**Comment by timstclair** [comment]
The rest API includes `CpuInstStats` for cpu usage of containers & node: https://github.com/google/cadvisor/blob/master/info/v2/container.go#L280

**Comment by tadivenkat** [comment]
I am making this request http://16.103.209.61:8081/api/v2.0/summary/
I see the following response:
{"/":{"timestamp":"2016-12-12T18:42:57.459650443Z","latest_usage":{"cpu":100,"memory":1779097600},"minute_usage":{"percent_complete":100,"cpu":{"present":true,"mean":144,"max":677,"fifty":124,"ninety":240,"ninetyfive":254},"memory":{"present":true,"mean":1767151665,"max":1779077120,"fifty":1764810752,"ninety":1778312806,"ninetyfive":1778353766}},"hour_usage":{"percent_complete":1,"cpu":{"present":true,"mean":144,"max":677,"fifty":240,"ninety":240,"ninetyfive":240},"memory":{"present":true,"mean":1767151665,"max":1779077120,"fifty":1778312806,"ninety":1778312806,"ninetyfive":1778312806}},"day_usage":{"percent_complete":0,"cpu":{"present":true,"mean":144,"max":677,"fifty":240,"ninety":240,"ninetyfive":240},"memory":{"present":true,"mean":1767151665,"max":1779077120,"fifty":1778312806,"ninety":1778312806,"ninetyfive":1778312806}}}}

I don't see CpuInstStats in the response.

My question is still not answered.

**Comment by timstclair** [comment]
Try `http://16.103.209.61:8081/api/v2.1/stats/<container_name>`, or `http://16.103.209.61:8081/api/v2.1/stats/?recursive=true` to get all containers.
