### ISSUE TITLE
Release cAdvisor v0.25

### ISSUE THREAD

**Issue by timstclair** [google/cadvisor#1566]
We did not cut a cAdvisor release with the last Kubernetes release, so there are now a couple features (e.g. https://github.com/google/cadvisor/issues/1560, @micahhausler ) that have been unrealesed since September.

Should we cut v0.25 now, or wait for k8s 1.6? What other features are we missing?

**Comment by edannenberg** [comment]
Is Go 1.7 support in yet? I remember it was planned for v0.24. Distributions like Gentoo don't have Go 1.6 in there package repository anymore.

**Comment by timstclair** [comment]
Yes, our test infrastructure is running with go1.7.1 now.

**Comment by dashpole** [comment]
closing via #1609
