### ISSUE TITLE
Does cAdvisor supports disk io about docker mapped volumes

### ISSUE THREAD

**Issue by andyxning** [google/cadvisor#1569]
Currerntly, i am working on adding disk io metrics to [Heapster](https://github.com/kubernetes/heapster/issues/690). 

There is one question that i can not be sure. Does cAdvisor's [`DiskIoStats`](https://github.com/google/cadvisor/blob/master/info/v1/container.go#L315-L324) contains disk io data for mapped volumes added with` docker run -v`.

**Comment by timstclair** [comment]
@dashpole do you know the answer?

**Comment by EdSchouten** [comment]
I think it's not just disk I/O that's not present, but also file system space/inode statistics, right? We would be very interested in having such information exported as well, as it allows us to keep an eye on usage of EBS volumes.

**Comment by dashpole** [comment]
I dont believe cAdvisor has any concept of volumes at the moment.  Kubernetes has separate libraries (not cAdvisor) for monitoring volumes, as they are largely tied to pods in k8s.  Ill put this on my todo list for the upcoming cAdvisor work.

**Comment by andyxning** [comment]
@dashpole IIUC, Kubernetes has separate libraries for getting disk io statistics. Any reference?

**Comment by dashpole** [comment]
There are a number of files in kubernetes/kubernetes/pkg/volume that deal with metrics collection for volumes.  My current question is this:  are kubernetes volumes the same thing as docker volumes?  If yes, then it would make sense to unify those pieces of code, and publish volume metrics.  If not, then I will likely only have the bandwidth to work on the kubernetes volume-related code.

**Comment by dashpole** [comment]
Sorry for the slow response.  It appears that kubernetes doesnt use docker volumes, so I dont think it would make sense to move kubernetes volume information into cAdvisor.  If you are looking for the library cadvisor uses to collect disk IO stats, take a look at [how we use libcontianer](https://github.com/google/cadvisor/blob/master/container/libcontainer/helpers.go#L436).  Im closing this for now.

**Comment by EdSchouten** [comment]
Would it make sense to open up a ticket elsewhere?

**Comment by dashpole** [comment]
This issue is about whether or not cAdvisor exports metrics for docker volumes.  From your earlier comment, it sounded like you were asking for usage metrics for remote block storage?  I am not familiar with EBS... If you want to propose adding any metrics, feel free to open an issue with your proposal.  If you need kubernetes volume metrics, those are available via the node summary API: /stats/summary
