### ISSUE TITLE
cadvisor does not work on ZFS

### ISSUE THREAD

**Issue by netvl** [google/cadvisor#1579]
My system is running ZFS, and Docker uses the ZFS driver for images. cadvisor apparently cannot work with ZFS. If I run the command exactly as it is specified in the readme file:

```
docker run \
  -v /:/rootfs:ro \
  -v /var/run:/var/run:rw \
  -v /sys:/sys:ro \
  -v /var/lib/docker:/var/lib/docker:ro \
  -p 8080:8080 \
  --rm \
  google/cadvisor:latest
```

Then I get the following errors in its log:
```
I0126 09:23:44.673182       1 fs.go:116] Filesystem partitions: map[zroot/DATA/home:{mountpoint:/rootfs/home major:0 minor:41 fsType:zfs blockSize:0} zroot/ROOT/swapkey:{mountpoint:/rootfs/swapkey major:0 minor:42 fsType:zfs blockSize:0} zroot/ROOT/docker:{mountpoint:/var/lib/docker/zfs major:0 minor:43 fsType:zfs blockSize:0} zroot/ROOT/docker/e5f652a5e6f8fb2210debc978e82286d5aa70c0959b9951d8147f93a4c93ae45:{mountpoint:/ major:0 minor:45 fsType:zfs blockSize:0} zroot/ROOT/default:{mountpoint:/rootfs major:0 minor:19 fsType:zfs blockSize:0}]
E0126 09:23:54.700609       1 fs.go:332] Stat fs failed. Error: exit status 1: "/usr/sbin/zfs zfs get -Hp all zroot/ROOT/docker" => The /dev/zfs device is missing and must be created.
Try running 'udevadm trigger' as root to create it.
```

If I mount the `/dev/zfs` device into the container:

```
docker run \
  -v /:/rootfs:ro \
  -v /var/run:/var/run:rw \
  -v /sys:/sys:ro \
  -v /var/lib/docker:/var/lib/docker:ro \
  -v /dev/zfs:/dev/zfs:ro \
  -p 8080:8080 \
  --rm \
  google/cadvisor:latest
```

I get the following errors in the log:
```
I0126 09:26:36.033175       1 fs.go:116] Filesystem partitions: map[zroot/ROOT/docker/7551cb59d6a78e8154fc2acd1b771cdfc0779ffbbf9e169b2e47935f2894f9dd:{mountpoint:/ major:0 minor:45 fsType:zfs blockSize:0} zroot/ROOT/default:{mountpoint:/rootfs major:0 minor:19 fsType:zfs blockSize:0} zroot/DATA/home:{mountpoint:/rootfs/home major:0 minor:41 fsType:zfs blockSize:0} zroot/ROOT/swapkey:{mountpoint:/rootfs/swapkey major:0 minor:42 fsType:zfs blockSize:0} zroot/ROOT/docker:{mountpoint:/var/lib/docker/zfs major:0 minor:43 fsType:zfs blockSize:0}]
E0126 09:26:36.054627       1 fs.go:332] Stat fs failed. Error: exit status 1: "/usr/sbin/zfs zfs get -Hp all zroot/ROOT/docker" => Failed to initialize the libzfs library.
E0126 09:26:36.057612       1 fs.go:332] Stat fs failed. Error: exit status 1: "/usr/sbin/zfs zfs get -Hp all zroot/ROOT/docker/7551cb59d6a78e8154fc2acd1b771cdfc0779ffbbf9e169b2e47935f2894f9dd" => Failed to initialize the libzfs library.
E0126 09:26:36.060710       1 fs.go:332] Stat fs failed. Error: exit status 1: "/usr/sbin/zfs zfs get -Hp all zroot/ROOT/default" => Failed to initialize the libzfs library.
E0126 09:26:36.063692       1 fs.go:332] Stat fs failed. Error: exit status 1: "/usr/sbin/zfs zfs get -Hp all zroot/DATA/home" => Failed to initialize the libzfs library.
E0126 09:26:36.067007       1 fs.go:332] Stat fs failed. Error: exit status 1: "/usr/sbin/zfs zfs get -Hp all zroot/ROOT/swapkey" => Failed to initialize the libzfs library.
```

**Comment by nlopez** [comment]
I had success using the `--device` docker run param:

```
docker run \
  -v /:/rootfs:ro \
  -v /var/run:/var/run:rw \
  -v /sys:/sys:ro \
  -v /var/lib/docker:/var/lib/docker:ro \
  --device /dev/zfs:/dev/zfs \
  -p 8080:8080 \
  --rm \
  google/cadvisor:latest
```

**Comment by l8nite** [comment]
Thanks @nlopez - just tried it out and worked for me too :D

**Comment by aaronjwood** [comment]
My boot drive is running btrfs but my other drives are setup for RAIDZ2. Docker reports that it's using the btrfs storage driver which sounds right but I do have some of my containers mapping things back into a ZFS dataset. I can confirm that `--device /dev/zfs:/dev/zfs` is necessary in this scenario as well.

**Comment by dashpole** [comment]
This appears to be resolved.  Feel free to reopen if there are anymore issues.

**Comment by from-nibly** [comment]
Are there any other solutions to this? I would like to run this as a daemonset in kubernetes but kubernetes does not have a passthrough for the --device flag.

**Comment by dashpole** [comment]
ZFS support has been added in recent versions, so it should just work now.

**Comment by dashpole** [comment]
based on the [--device docs](https://docs.docker.com/engine/reference/run/#additional-groups) also linked above, it looks like that includes both mounting, and granting privileges to the container.
`--device=[]: Allows you to run devices inside the container without the --privileged flag.`
So you should be able to configure the cAdvisor daemonset to have those privileges as well.  Check out the [security context docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).

**Comment by from-nibly** [comment]
Ahh ok. So I set `privileged: true` in the containers `securityContext` and everything is working fine. thanks!

**Comment by kusmierz** [comment]
Unfortunately it doesn't work on a swarm (`Note: This option is ignored when deploying a stack in swarm mode with a (version 3) Compose file.` https://docs.docker.com/compose/compose-file/#devices). `privileged` flag is unsupported as well...
