### ISSUE TITLE
Build and release using Go 1.8

### ISSUE THREAD

**Issue by aaronjwood** [google/cadvisor#1602]
I'm using the `latest` tag with the Docker container for cAdvisor and noticed that it was built with 1.6.3. Can cAdvisor be built and shipped with the latest version of Go? I figured it would be beneficial to do this to take advantage of the new SSA back end as well as all of the GC improvements.

**Comment by andyxning** [comment]
@aaronjwood Does current go1.6.3 version cadvisor can not uses too much resource for you? Just curious. :)

**Comment by aaronjwood** [comment]
@andyxning it's not really that bad but yeah, it's a little too much for me to stick on my server full time. I see it using between 5-18% CPU and it spikes around wildly. I tried tuning it a bit using settings similar to what people were talking about here https://github.com/google/cadvisor/issues/1498 which made it idle better. It still spikes pretty high (0.5-9% CPU) though.

**Comment by andyxning** [comment]
@aaronjwood I am afraid that updating golang version to 1.8 may not solve your problem. IIUC, what you concern is decreasing CPU usage, however, cadvisor has not so much memory that will utiling more CPU for GC. Updating golang version to 1.8 will improve build speed and make cadvisor binary more smaller.  :)

**Comment by aaronjwood** [comment]
@andyxning sure, I totally expect that. I didn't think it would be a silver bullet for my case. I was just suggesting that cAdvisor take advantage of the big optimizations from newer versions of the language. My problem is (somewhat) orthogonal to what I'm asking.

**Comment by andyxning** [comment]
@aaronjwood Seems reasonable to me. I agree that we should at least use golang 1.7.5 since golang 1.8 has released a few days before. :)

@timstclair WDYT. It seems that the `google/cadvisor` image is built by you. :)

**Comment by dashpole** [comment]
I believe we currently use the latest 1.7.x release. see #1603.  I am not 100% sure what our policy for switching go versions is, but ill probably wait a couple patch releases before bumping to 1.8
