### ISSUE TITLE
[Question] Can we use HTTPS to expose containers stats  ?

### ISSUE THREAD

**Issue by JeromeVi** [google/cadvisor#1608]
Hi,
I'm just looking if it's possible to expose the data with HTTPS because on the repo it says : 

> cAdvisor exposes container statistics as Prometheus metrics out of the box. By default, these metrics are served under the /metrics **HTTP** endpoint. This endpoint may be customized by setting the **-prometheus_endpoint** command-line flag.

But I can't find the doc for the `-prometheus_endpoint`

Thank you for your help

**Comment by dashpole** [comment]
I am afraid that flag is simply to change the name of the endpoint.  According to #1621, the best setup for authentication is using a proxy.
