### ISSUE TITLE
unable to launch cadvisor always in mesos waiting status 

### ISSUE THREAD

**Issue by shamimgeek** [google/cadvisor#1624]
I am new to this. Please tell me if am doing wrong

{
  "id": "cadvisor",
  "cpus": 0.1,
  "mem": 512,
  "disk": 0,
  "instances": 11,                
  "constraints": [["hostname", "UNIQUE"]],
  "container": {
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/rootfs",
        "hostPath": "/",
        "mode": "RO"
      },
      {
        "containerPath": "/var/run/",
        "hostPath": "/var/run",
        "mode": "RW"
      },
      {
        "containerPath": "/sys",
        "hostPath": "/sys",
        "mode": "RO"
      },
      {
        "containerPath": "/var/lib/docker",
        "hostPath": "/var/lib/docker",
        "mode": "RO"
      }
    ],
    "docker": {
      "image": "google/cadvisor:latest",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 8080,
          "hostPort": 3002,
          "protocol": "tcp"
        }
      ],
      "forcePullImage": true
    }
  }
}

**Comment by JinsYin** [comment]
@shamimgeek 
{
	"id": "/cadvisor",
	"args": [],
	"mem": 128.0,
	"cpus": 0.2,
	"instances": 1,
	"constraints": [["hostname", "UNIQUE"]],
	"labels": {
		"VERSION": "0.24.1",
		"WEB_PORT": "8080"
	},
	"container": {
		"type": "DOCKER",
		"docker": {
			"image": "google/cadvisor:v0.24.1",
			"forcePullImage": true,
			"network": "HOST",
			"privileged": true
		},
		"volumes": [
			{
				"containerPath": "/rootfs",
				"hostPath": "/",
				"mode": "RO"
			},
			{
				"containerPath": "/var/run",
				"hostPath": "/var/run",
				"mode": "RW"
			},
			{
				"containerPath": "/sys",
				"hostPath": "/sys",
				"mode": "RO"
			},
			{
				"containerPath": "/var/lib/docker/",
				"hostPath": "/var/lib/docker",
				"mode": "RO"
			}
		]
	},
	"healthChecks": [
		{ "protocol": "HTTP", "port": 8080, "path": "/" }
	]
}

**Comment by JinsYin** [comment]
@shamimgeek "hostPort" must be 0.
{
	"id": "/cadvisor",
	"args": [],
	"mem": 128.0,
	"cpus": 0.2,
	"instances": 1,
	"constraints": [["hostname", "UNIQUE"]],
	"labels": {
		"VERSION": "0.24.1",
		"WEB_PORT": "8080"
	},
	"container": {
		"type": "DOCKER",
		"docker": {
			"image": "google/cadvisor:v0.24.1",
			"forcePullImage": true,
			"network": "BRIDGE",
			"privileged": true,
			"portMappings": [
				{ "containerPort": 8080, "hostPort": 0, "servicePort": 18080, "protocol": "tcp" }
			]
		},
		"volumes": [
			{
				"containerPath": "/rootfs",
				"hostPath": "/",
				"mode": "RO"
			},
			{
				"containerPath": "/var/run",
				"hostPath": "/var/run",
				"mode": "RW"
			},
			{
				"containerPath": "/sys",
				"hostPath": "/sys",
				"mode": "RO"
			},
			{
				"containerPath": "/var/lib/docker/",
				"hostPath": "/var/lib/docker",
				"mode": "RO"
			}
		]
	},
	"healthChecks": [
		{ "protocol": "HTTP", "portIndex": 0, "path": "/" }
	]
}

**Comment by shamimgeek** [comment]
@JinsYin : Thanks alot for correct json :+1:

**Comment by dashpole** [comment]
Thanks a bunch @JinsYin
