### ISSUE TITLE
Support GPU stats collecting via GPU CRI

### ISSUE THREAD

**Issue by tianshapjq** [google/cadvisor#1632]
As discussed in the [kubernetes414](https://github.com/kubernetes/community/pull/414), the kubernetes is going to enhance the GPU capability. Also in #1436, we discussed about supporting gpu stats collecting in cadvisor.
I've made some achievements via GPU CRI, and I commited to kubernetes, the PR is located at [kubernetes/43934](https://github.com/kubernetes/kubernetes/pull/43934). I wonder if this is necessary in present and I will commit to cadvisor if so.
Thanks.

**Comment by tianshapjq** [comment]
@derekwaynecarr @vishh I'm not sure who can handle about this, any suggestions for me? thx.

**Comment by cmluciano** [comment]
Is this technically a duplicate of #1436 ?

**Comment by dashpole** [comment]
Yeah, lets move this to #1436.  @tianshapjq, I am happy to answer questions about cAdvisor, but I am not familiar with any tools for collecting metrics on GPUs.  I think that is being discussed in the other issue.  Closing as duplicate.v
