### ISSUE TITLE
Should anything in this output log be concerning?

### ISSUE THREAD

**Issue by knepperjm** [google/cadvisor#1645]
We have a beefy r3 memory node in AWS EC2 that is running some memory intensive applications.  We noticed that randomly some of the applications on these memory nodes with these memory-specific applications installed go down from time to time and almost at random.  There are some errors, but we also notice cAdvisor has this sort of continuous / redundant logging inside the output:

`4/22/2017 5:44:18 PMI0423 00:44:18.364097       1 storagedriver.go:48] Using backend storage type "influxdb"
4/22/2017 5:44:18 PMI0423 00:44:18.364163       1 storagedriver.go:50] Caching stats in memory for 2m0s
4/22/2017 5:44:18 PMI0423 00:44:18.364230       1 manager.go:143] cAdvisor running in container: "/docker/d274033425700b26bc64e49c2ef63546c9a2e6f42dc4124d32bade44a4ebb946"
4/22/2017 5:44:18 PMW0423 00:44:18.396822       1 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
4/22/2017 5:44:18 PMI0423 00:44:18.431930       1 fs.go:117] Filesystem partitions: map[/dev/xvda1:{mountpoint:/var/lib/docker major:202 minor:1 fsType:ext4 blockSize:0}]
4/22/2017 5:44:18 PMI0423 00:44:18.442348       1 manager.go:198] Machine: {NumCores:64 CpuFrequency:3000000 MemoryCapacity:270480486400 
4/22/2017 5:44:18 PMI0423 00:44:18.443294       1 manager.go:204] Version: {KernelVersion:4.4.0-63-generic ContainerOsVersion:Alpine Linux v3.4 DockerVersion:1.12.6 CadvisorVersion:v0.25.0 CadvisorRevision:17543be}
4/22/2017 5:44:18 PMI0423 00:44:18.457450       1 factory.go:309] Registering Docker factory
4/22/2017 5:44:18 PMW0423 00:44:18.457465       1 manager.go:247] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
4/22/2017 5:44:18 PMI0423 00:44:18.457470       1 factory.go:54] Registering systemd factory
4/22/2017 5:44:18 PMI0423 00:44:18.459369       1 factory.go:86] Registering Raw factory
4/22/2017 5:44:18 PMI0423 00:44:18.461823       1 manager.go:1106] Started watching for new ooms in manager
4/22/2017 5:44:18 PMW0423 00:44:18.462024       1 manager.go:275] Could not configure a source for OOM detection, disabling OOM events: unable to find any kernel log file available from our set: [/var/log/kern.log /var/log/messages /var/log/syslog]
4/22/2017 5:44:18 PMI0423 00:44:18.462970       1 manager.go:288] Starting recovery of all containers
4/22/2017 5:44:18 PMI0423 00:44:18.638689       1 manager.go:293] Recovery completed
4/22/2017 5:44:18 PMI0423 00:44:18.721087       1 cadvisor.go:157] Starting cAdvisor version: v0.25.0-17543be on port 8080
4/22/2017 7:15:57 PMI0423 02:15:57.134075       1 manager.go:1096] Exiting thread watching subcontainers
4/22/2017 7:15:57 PMI0423 02:15:57.134110       1 manager.go:354] Exiting global housekeeping thread
4/22/2017 7:15:57 PMI0423 02:15:57.134117       1 cadvisor.go:191] Exiting given signal: terminated
4/22/2017 11:28:29 PMI0423 06:28:29.871653       1 storagedriver.go:48] Using backend storage type "influxdb"
4/22/2017 11:28:29 PMI0423 06:28:29.872274       1 storagedriver.go:50] Caching stats in memory for 2m0s
4/22/2017 11:28:29 PMI0423 06:28:29.872356       1 manager.go:143] cAdvisor running in container: "/docker/d274033425700b26bc64e49c2ef63546c9a2e6f42dc4124d32bade44a4ebb946"
4/22/2017 11:28:29 PMW0423 06:28:29.896702       1 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
4/22/2017 11:28:29 PMI0423 06:28:29.925214    `

What is most concerning is:

`1 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
4/22/2017 5:44:18 PMI0423 00:44:18.431930 `

, And the continuous attempts at some form of recovery:

`0       1 manager.go:288] Starting recovery of all containers
4/22/2017 5:44:18 PMI0423 00:44:18.638689       1 manager.go:293] Recovery completed
4/22/2017 5:44:18 PMI0423 00:44:18.721087       1 cadvisor.go:157] Starting cAdvisor version: v0.25.0-17543be on port 8080
4/22/2017 7:15:57 PMI0423 02:15:57.134075       1 manager.go:1096] Exiting thread watching subcontainers
4/22/2017 7:15:57 PMI0423 02:15:57.134110       1 manager.go:354] Exiting global housekeeping thread
4/22/2017 7:15:57 PMI0423 02:15:57.134117       1 cadvisor.go:191] Exiting given signal: terminated
4/22/2017 11:28:29 PMI0423 06:28:29.871653       1 storagedriver.go:48] Using backend storage `

Should any of this be concerning?  Also, we get the following errors in docker:

`time="2017-04-23T02:16:02Z" level=error msg="Error processing event &events.Message{Status:\"die\", ID:\"1234123412341234\", From:\"google/cadvisor:latest\", Type:\"container\", Action:\"die\", Actor:events.Actor{ID:\"2143123412341234\", Attributes:map[string]string{\"io.rancher.cni.network\":\"ipsec\", \"io.rancher.cni.wait\":\"true\", \"io.rancher.project.name\":\"cadvisor\", \"io.rancher.service.launch.config\":\"io.rancher.service.primary.launch.config\", \"name\":\"r-cadvisor-cadvisor-31-ace588ed\", \"com.demandbase.environment\":\"production\", \"io.rancher.container.mac_address\":\"02:9b:c3:2d:bf:1f\", \"io.rancher.container.pull_image\":\"always\", \"io.rancher.scheduler.global\":\"true\", \"io.rancher.service.deployment.unit\":\"909090909\", \"io.rancher.stack_service.name\":\"cadvisor/cadvisor\", \"io.rancher.container.ip\":\"10.42.231.35/16\", \"io.rancher.container.name\":\"cadvisor-cadvisor-31\", \"io.rancher.container.start_once\":\"true\", \"io.rancher.container.uuid\":\"123412341234\", \"io.rancher.project_service.name\":\"cadvisor/cadvisor\", \"exitCode\":\"0\", \"image\":\"google/cadvisor:latest\", \"io.rancher.service.hash\":\"123412341234\", \"io.rancher.service.requested.host.id\":\"561\", \"io.rancher.stack.name\":\"cadvisor\"}}, Time:1492913762, TimeNano:1492913762611404360}. Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" `

We are running Rancher (v1.5.4) Container management system and our hosts have swap enabled, and our cAdvisor version is v0.25.0, and docker version is v1.12.6.  Any help or advice as to what could cause cAdvisor or potentially other applications (logstash, druid) to go down on this host as well?  I am wondering if there is some sort of competing resources.  OS limits seem to be okay.

**Comment by dashpole** [comment]
The unable to connect to rkt error isnt important.  It is expected if you are not running rkt.

**Comment by dashpole** [comment]
From the cAdvisor logs, the only thing out of the ordinary is `cadvisor.go:191] Exiting given signal: terminated 4/22/2017 11:28:29 PMI0423 06:28:29.871653 `
"Recovery" just refers to the process of discovering what containers already exist on the host, and is part of the startup process.
I suspect cAdvisor isnt correctly configured?  This: `Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"` makes me think you didnt mount /var/run inside the cadvisor container...

**Comment by knepperjm** [comment]
Hi, @dashpole Thanks for the prompt feedback.  

`1 version: '2'
  2 services:
  3   cadvisor:
  4     image: "google/cadvisor:latest"
  5     ports:
  6      - "20027:8080"
  7     labels:
  8       io.rancher.scheduler.global: "true"
  9       io.rancher.container.pull_image: always
 10       io.rancher.container.start_once: 'true'
 11       io.rancher.stack.name: "google/cadvisor:latest"
 12       com.demandbase.environment: "$ENVIRONMENT"
 13     volumes:
 14       - "/:/rootfs:ro"
 15       - "/var/run:/var/run:rw"
 16       - "/sys:/sys:ro"
 17       - "/var/lib/docker/:/var/lib/docker:ro"
 18     environment:
 19       - ENV=${ENV}
 20       - INFLUX_USER=${INFLUX_USER}
 21       - INFLUX_PASSWD=${INFLUX_PASSWD}"
 22     stdin_open: true
 23     command:  ["-storage_driver=influxdb", "-storage_driver_host=influxdb${ENV}.demandbase.com:8086", "-storage_driver_user=${INFLUX_USER}", "-storage_driver_password=${INFLUX_PASSWD}"]
`

**Comment by dashpole** [comment]
That looks correct... Based on the logs, it looks like cAdvisor is also randomly terminated.  Are you getting system OOMs or something?

**Comment by knepperjm** [comment]
It's hard to say - any recommendations to detecting that in retrospect?

**Comment by dashpole** [comment]
If you are using systemd, then use journalctl -k.  If not, then look in var/log/kern.log or var/log/messages.log, or var/log/dmesg.log

**Comment by knepperjm** [comment]
Ah, great advice! I will check it out after lunch.  I am very appreciative of your help, @dashpole

**Comment by dashpole** [comment]
I am going to close this for now.  Feel free to reopen if you have follow-up questions.
