### ISSUE TITLE
[code problem] how to quickly get container name and its pid mapping

### ISSUE THREAD

**Issue by WIZARD-CXY** [google/cadvisor#1650]
Hi, I want to know which container of a given pid is belong to, for example: pid 3456 -> containerName abcded. I assume there may be a map in the cadvisor worked as a cache, but I don't find it in the code, maybe somebody could give me some insight? 
Thanks in advance!

**Comment by dashpole** [comment]
Assuming you are looking at docker containers, they are both part of the handler struct:
[dockerContainerHandler](https://github.com/google/cadvisor/blob/master/container/docker/handler.go#L51)

**Comment by WIZARD-CXY** [comment]
thx @dashpole so i need to loop through all the handlers and there is no cache exist？

**Comment by dashpole** [comment]
I would recommend against looping through.  The dockerContainerHandler has a number of methods, including GetStats(), GetSpec(), Start(), etc.  Most metric collection can be implemented by modifying these methods.

**Comment by WIZARD-CXY** [comment]
oh my need is that I have some pids, and I want to find their relevant containers, So dockerContainerHandler may not be enough
