### ISSUE TITLE
Is cadvisor storage driver support Elasticsearch5.x ?

### ISSUE THREAD

**Issue by happyboy310** [google/cadvisor#1654]
I use lower verison Elasticsearch is success, but Elasticsearch5.x failed.
F0516 08:46:17.420717       1 cadvisor.go:117] Failed to initialize storage driver: failed to create the elasticsearch client - no Elasticsearch node available 
How to deal with this error?

**Comment by dashpole** [comment]
#1597 is currently pending.  It isnt clear when we will be able to add 5.x support.
