### ISSUE TITLE
Microsoft/go-winio/*.go tests fail on Linux

### ISSUE THREAD

**Issue by seth-priya** [google/cadvisor#1656]
Hi,

It seems that these tests are Windows specific, so expected to fail on Linux. I just wanted to understand if there is a graceful way of bypassing/disabling them for other platforms?

Thanks!

Regards,
Priya

**Comment by dashpole** [comment]
what command are you running?  `make test` doesn't run unit tests from my vendor directory..

**Comment by seth-priya** [comment]
@dashpole thanks for you response. I was using the **go test** command

**Comment by dashpole** [comment]
I am closing this for now
