### ISSUE TITLE
cadvisor consul

### ISSUE THREAD

**Issue by mnuic** [google/cadvisor#1663]
Hi,

We are using offical docker cadvisor image and sending metrics to statsd container and from there to graphite. We set env variable in docker with statsd ip address for every host.

Is there a way we can configure cadvisor so that it ask consul for statsd ip address/location so that we don't have to do it manually for every host? Could you put a consul-template inside offical cadvisor image, so we could ask consul for services?

Example for statsd (or any other service):
```
consul-template \
    -consul $node_ip:8500 \
    -template "/templates/cadvisor.cfg:/etc/cadvisor/cadvisor.cfg" \
    -once
```

so that start cmd on Dockerfile could be:
```
/go/src/github.com/google/cadvisor/cadvisor -storage_driver=statsd -storage_driver_host={STATSD_SERVICE} -storage_driver_db=hostXYZ
```
where STATSD_SERVICE is IP address that cadvisor would get from consul. 

Thanks

**Comment by Christopher-Bui** [comment]
I don't think coupling consul and cadvisor is appropriate. Is there a reason you can't just link cadvisor to your consul container?

**Comment by mnuic** [comment]
Hi @Christopher-Bui,

We are using consul image in our production as a service discovery tool, alongside cadvisor and statad images. The problem is that we manually have to define statsd ip address for every cadvisor container on every host in our environment and we have a lot of hosts.

If cadvisor image would have a consul-template running when starting the container we wouldn't have to define statsd ip manually. It would automaticaly pick up (discover) the closest statsd service from consul and get the ip address. The example for it is above.

**Comment by colinrymer** [comment]
You can use consul-template or envconsul outside of the cadvisor container, e.g. having consul-template running on the host manage the cadvisor lifecycle and providing a file for the `--env-file` flag.

**Comment by mnuic** [comment]
We have tried that, and it works when you have few (static) hosts... but with a production system with 100+ hosts when hosts are automatically scaled up or down (start and destroyed) it is not very convenient to edit all the hosts manually. That's why I am asking if cadvisor could have consul-template inside container, so that starting a container on a host could automatic discover a service from consul, in my case statsd service.

Thanks

**Comment by colinrymer** [comment]
I'm not sure you're following what I'm saying. Instead of putting consul-template in the container, invert the dependency so that consul-template sits outside the container and manages it. Nothing in that scenario would require manually editing any hosts.

**Comment by mnuic** [comment]
I'll try this way, thanks @colinrymer

**Comment by dashpole** [comment]
Issue appears resolved.
