### ISSUE TITLE
Support `docker exec` to collect custom metrics

### ISSUE THREAD

**Issue by Colstuwjx** [google/cadvisor#1670]
Hi team,

As the cadvisor is missing some metrics inner container, such as `tcp connections`, `process stats` etc.
It would be better if cadvisor support custom metrics via `docker exec` each container.

Thanks.

**Comment by dashpole** [comment]
tcp metrics are disabled by default.  You can configure this using the `--disable-metrics` flag documented [here](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#metrics).  We also have already support for [custom application metrics](https://github.com/google/cadvisor/blob/master/docs/application_metrics.md)

**Comment by Colstuwjx** [comment]
Although cadvisor support custom application metrics, app need to expose an endpoint which contain these metrics, but e.g. tcp connections, cpu load, process stats, these are basic system level metrics, and should have a pretty way to achieve, rather than binding into application's code logical.

**Comment by dashpole** [comment]
tcp connections are already supported, cpu load is already supported.  You can see the [api that we expose for containers](https://github.com/google/cadvisor/blob/master/info/v1/container.go#L519).   The current design of cAdvisor is to monitor containers, not processes.

**Comment by Colstuwjx** [comment]
As #1674 merged, I'd like to close this, due to each metrics is included in prom `/metrics` endpoint.
