### ISSUE TITLE
Filter the cadvisor metrics

### ISSUE THREAD

**Issue by wdp-007** [google/cadvisor#1697]
Is there any way to add some filter to collect some Specific container?

cAdvisor returns metrics for a lot of the running processes on the system its running on. This results in a lot of extra metrics that cAdvisor exposes, and for the most these are metrics we do not care about. 
Is there any API or configuration to filter the cadvisor metrics?

**Comment by jianzi123** [comment]
i thought cadvisor has some... and k8s has one...

**Comment by wdp-007** [comment]
I just want to whether cadvisor has some methods or API or labels to filter metrics. And I don't use this in k8s.

**Comment by wdp-007** [comment]
Can someone give some idea or advice?

**Comment by dashpole** [comment]
We dont support filtering metrics in cadvisor.  It should be fairly simple to filter the output of any api call.
