### ISSUE TITLE
cadvisor not exposing metrics

### ISSUE THREAD

**Issue by jinsr65** [google/cadvisor#1701]
cadvisor is runing ""/usr/bin/cadvisor"      19 seconds ago      Up 18 seconds       8080/tcp, 0.0.0.0:8080->9010/tcp                                   cadvisor" .

However when u try to get the metrics on 9010 from the local host, connection is getting refused. i see a process using 9010 .

**Comment by zeisss** [comment]
you need to connect to port 8080, since you are running a docker container wird a port forwarding for 8080 to container port 9010.

**Comment by dashpole** [comment]
looks like the question is answered
