### ISSUE TITLE
Unable to see container's metrics about external volumes attached (k8s persistent volumes)

### ISSUE THREAD

**Issue by eedugon** [google/cadvisor#1702]
Hello, 

We are having a discussion at "prometheus-operator" project, and based on @brancz suggestion, we are raising the topic here, as our problem seems related with cadvisor in some way.
(this is the original thread, just in case: #https://github.com/coreos/prometheus-operator/issues/485)

In a kubernetes + prometheus-operator environment we are not able to get any kind of metric about persistent volumes that are attached to containers in pods, and we don't really understand why.

Keeping out of the topic that Kubernetes should probably provide information about them, because PVs are actually K8s resources, we are wondering how we can't find any information at cadvisor/kubelet level metrics.

For example, a container might show the following disks (by df -h directly in a bash of the container):

```
# df -h
overlay 154G 12G 136G 9% /
/dev/xvdbg       20G   46M   19G   1% /var/lib/zookeeper (THIS IS THE PERSISTENT VOLUME)
/dev/xvda1 154G 7.2G 140G 5% /etc/hosts
...
...
```
In that output, the "154G" device is the main disk of the container owner (k8s node), and we have no problem finding metrics about that disk at all levels.
But the other device (/dev/xvdbg) is actually the persistent volume that is mounted in the container, and there's no track of it at all in the metrics.

container_fs_usage_bytes information about that pod/container has only:
container_fs_usage_bytes{container_name="kafka",device="/dev/xvda1",.....}
Which represents actually the physical disk of the k8s node, owning the container.
But there's noting else about /dev/xvdbg, and that's what we are looking for...

Do you have any suggestion, idea or explanation for this behavior? Are we missing something at configuration level to make kubelet reporting this?

Note1: At node level, lsblk shows the disk of the PV:
```
admin@node$ lsblk 
NAME    MAJ:MIN   RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0      0  164G  0 disk 
`-xvda1 202:1      0  164G  0 part /
xvdbg   202:14848  0   20G  0 disk /var/lib/kubelet/pods/ae6c1d55-6d7a-11e7-bc61-068b6da15381/volumes/kubernetes.io~aws-ebs

# and it's also mounted
/dev/xvdbg       20G   46M   19G   1% /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/eu-west-2a/vol-0bafa0be2b20de87a
```

In the node we have cadvisor/kubelet metrics and also node_exporter.... none of them are reporting what we are looking for. I suspect we are missing some kind of mapping or configuration somewhere, because the disk is there...

Thanks very much in advance, any help will be appreciated,
Eduardo
(+ @hartmut-pq)

**Comment by dashpole** [comment]
The current scope of cAdvisor is restricted to monitoring containers.  It provides the kubelet with container metrics only, and has no concept of volumes, pods, or any other higher-level Kubernetes API objects.  The kubelet has a built-in cadvisor, which monitors containers in kubernetes.  The kubelet currently takes the container metrics provided by cAdvisor, and combines them with volume metrics, and kubernetes-specific metadata (e.g. container->pod mappings) to produce the [summary API](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/stats/v1alpha1/types.go), which is exposed by the kubelet at 10255/stats/summary.

The underlying issue you are raising here is that the kubelet does not expose this via prometheus.

**Comment by hartmut-pq** [comment]
Hi @dashpole so you're saying all relevant information is available / provided by cAdvisor already but not mapped/interpreted by the kubelet->summary implementation yet?

**Comment by dashpole** [comment]
No, cAdvisor does not provide volume metrics, and has no concept of volumes or pods, which is why there are no volume metrics exposed via prometheus.
The kubelet itself collects and exposes volume metrics via the summary API, but doesnt expose it in any other way (e.g. prometheus)

**Comment by brancz** [comment]
Interesting, thanks for the insight @dashpole. Seems like we should maybe work towards exposing the stats API as Prometheus metrics by the kubelet.

**Comment by dashpole** [comment]
Would just adding volume metrics to the kubelet's prometheus endpoint be sufficient?

**Comment by eedugon** [comment]
Hi @dashpole ,

Yes, the information we are looking for is available in :10255/stats/summary, and as you said, that's not translated to any kind of metric (that was actually the issue to me).

I don't want to ask for anything out of the scope for any component, that's the reason my question is more or less.... "who do you think should be responsible of translating that into a prometheus metric"?

Your proposal "just adding volume metrics to the kubelet's prometheus endpoint" is exactly what I was looking for, but i don't know if by kubelet or whom (controller-manager?).

I also fully agree that cadvisor should know nothing about k8s concepts like persistent volumes, but from container perspective, if a docker has a filesystem mounted, I expect prometheus metrics to be exported about that filesystem, which is actually very important to track.

Let me know your view and thanks in advance!
Edu

**Comment by hartmut-pq** [comment]
@brancz so would this be escalated with kubernetes/kubernetes then? 
May this be closely related to the works/proposal for 1.8? (https://github.com/coreos/prometheus-operator/issues/485#issuecomment-317410371)
Who's going to push it to the next round then? :-)

**Comment by brancz** [comment]
@gnufied told me there is something already in the works, maybe he can comment on where we should go next.

**Comment by gnufied** [comment]
@brancz yes I was talking about this proposal - https://github.com/kubernetes/community/pull/855 cc @jingxu97

**Comment by brancz** [comment]
@gnufied I don't want to hijack that PR so I'll ask here. Do you think it's reasonable to also add all of those metrics as metrics exposed in the `/metrics` endpoint of the kubelet?

**Comment by dashpole** [comment]
I think it is reasonable.  We should also have a discussion on the relationship between kubernetes and prometheus.  Seems odd to have some metrics on the cadvisor port, and others on the kubelet port.  I think ideally, the prometheus endpoint should mirror the information provided by the kubelet's http endpoints (e.g summary API).

**Comment by dashpole** [comment]
I guess my biggest concern/question is that I don't know how prometheus deals with metrics changing.  What about a metric (name, format, labels) can change across a release without causing disruption.  Prometheus doesnt look like it has versioning.

**Comment by hartmut-pq** [comment]
anyone pls correct my if I'm wrong - but @dashpole prometheus merely reads what's there - and it's entirely up to the prometheus consumers do deal with changed labels/data... The major usage basically are prometheus alert rules and grafana to visualise based on the metrics.

**Comment by hartmut-pq** [comment]
@dashpole the proposal you mentioned will simply expose the storage metrics - and seem to aim to map/provide `PVCReference`. 
Most benefit in terms of monitoring - if you have a quick look at the original comment/issue here https://github.com/coreos/prometheus-operator/issues/485#issue-244086169 would be to be allowed to alert if PVs are running out of storage...

**Comment by gnufied** [comment]
@brancz I think that is doable. but @jingxu97 will have more information. BTW - which metric endpoint, there seems to be 2 of them with kubelet. :-)

**Comment by hartmut-pq** [comment]
or e.g. mirror existing metrics like
`node_filesystem_avail`
`node_filesystem_files`
`node_filesystem_files_free`
`node_filesystem_free`
`node_filesystem_readonly`
`node_filesystem_size`

**Comment by eedugon** [comment]
@gnufied : I think it should be :10255/metrics, what other endpoint do you see?

@dashpole : When you mention cadvisor port, what port do you mean? I thought in terms of metrics, cadvisor/kubelet where going to expose only one set of metrics. If there are 2 endpoints let me know which is the other one and I will check if the info we are looking for is already available there.

And as you mention, the "summary API" has the correct and complete set of information. So, I don't know who, but someone needs to put that information into a "metrics" format.

But when you talk about "prometheus" and "kubelet" relationship I don't completely get you. 

> the prometheus endpoint should mirror the information provided by the kubelet's http endpoints (e.g summary API)
There are no prometheus endpoints, as prometheus does not generate metrics. If with that you mean cadvisor or kubelet "metrics" endpoint, then I agree, but prometheus won't be able to mirror anything, as prometheus is only a metrics consumer.

Regarding metrics names and changes I agree with @hartmut-pq , there won't be any important disruption in prometheus if that happens, just that all components that read data from prometheus should be updated to start digging for the new names.

The information we are looking for from containers point of view is the same information you are already providing for other filesystems of the container (size, usage bytes, free bytes, ...). (container_fs_*)... 

This is info from a container is taken from stats/summary endpoint:
```
    "volume": [
     {
      "time": "2017-07-28T07:32:22Z",
      "availableBytes": 97228500992,
      "capacityBytes": 105555197952,
      "usedBytes": 2941210624,
      "inodesFree": 6551983,
      "inodes": 6553600,
      "inodesUsed": 1617,
      "name": "datadir"
     }
```

And that volume (container_fs) is completely missing in the kubelet metrics endpoint (that I also thought it was cadvisor endpoint).

**Comment by jingxu97** [comment]
@eedugon Thanks for your comment and feedback. I am currentlto y working on a feature to expose storage metrics to users which will address your issue.
My understanding is that when we say "prometheus endpoint" because kubelet registers metrics to prometheus which allows to expose the registered metrics via HTTP. Based on your feedback and others, I think we plan to register the volume metrics to prometheus so that user can use /metric endpoint to check the information. One problem is that it seems some users might want to use PVC as index and some want to use PV name

**Comment by brancz** [comment]
@jingxu97 that sounds great!

Regarding:

> One problem is that it seems some users might want to use PVC as index and some want to use PV name

I think this is something we can discuss further in the proposal. Feel free to tag us once you have something ready. :slightly_smiling_face:

**Comment by eedugon** [comment]
@jingxu97 : just for curiosity... any progress about this issue? Thanks in advance!

**Comment by jingxu97** [comment]
@eedugon sorry that I missed your message. Currently you can use the following ways to get PVC metrcis

1. Run "kubectl proxy" first. Then " curl localhost:8001/api/v1/proxy/nodes/<nodename>:10250/metrics"
2. Ssh to the node, Run "curl -k http://localhost:10255/metrics"

Please let me know if you have problems or questions. Thanks~!

**Comment by tiloso** [comment]
@eedugon Kubernetes 1.8 exposes following volume related metrics for Prometheus which can be used to monitor PVC disk usage:
```
kubelet_volume_stats_available_bytes
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
kubelet_volume_stats_inodes_used
kubelet_volume_stats_used_bytes
```

**Comment by eedugon** [comment]
Thanks a lot, @tiloso  and @jingxu97 !

**Comment by brancz** [comment]
Would love to see a dashboard and or alerting rules with these! :slightly_smiling_face:

**Comment by f0** [comment]
@tiloso  i run k8s 1.8.3 with vsphere volumes, i do not have these metrics....

**Comment by f0** [comment]
@tiloso i see, but i do not have metrics with the name kubelet_volume* (not in prometheus, not when curling the kubelet) but i do have pvc's.
Does your kubelet run in a Container?

**Comment by brancz** [comment]
@tiloso awesome! I can definitely see very nice `predict_linear` queries to do early alerts on volumes filling up! :slightly_smiling_face:

**Comment by piwi91** [comment]
I don't see these metrics too... @f0 did you found a solution?

**Comment by f0** [comment]
@piwi91 no, but haven't looked at this to deep

**Comment by giancarlocosta** [comment]
@piwi91 Did you find a solution? I'm using 1.8.3 as well and I don't see these metrics

**Comment by piwi91** [comment]
@giancarlocosta Unfortunately not... I'm going to monitor it with Zabbix (with auto-discovery) when I have setup connectivity to the monitoring network. If someone has a better solution, I'm all ears.

**Comment by cyrus-mc** [comment]
I am seeing these metrics, however it shows metrics for volumes that are no longer attached/present. 

If I stop and restart kubelet that clears them from the metrics reported.

**Comment by chhetripradeep** [comment]
Quick question - are these metrics only available for k8s version >= 1.8.0 ?

**Comment by chhetripradeep** [comment]
Hi, this is really important for me since i need to monitor disk space usage for all PV. Can someone suggest me if it is available in any of k8s 1.7 minor versions

**Comment by dashpole** [comment]
yes, these metrics were added in https://github.com/kubernetes/kubernetes/pull/51553, which first became available in 1.8.0.

**Comment by gnufied** [comment]
@cyrus-mc  that was fixed recently and we have backported it to 1.9 https://github.com/kubernetes/kubernetes/pull/60013 

If you are still on 1.9 - you should upgrade to next version with the fix.

**Comment by juliohm1978** [comment]
Apologies for joining late on this thread... but I am confused by @dashpole's [comment](https://github.com/google/cadvisor/issues/1702#issuecomment-317452058).

Regardless of how the kubelet colllects and agregates cAdvisor metrics, your explanation does not make it clear to me why the device in question (`/dev/xvdbg`) does not appear in cAdvisor metrics to begin with.

I'm running into a similar issue on our k8s clusters, where we need to gather metrics on volumes mounted by each container. Independently of how k8s concepts, I expected cAdvisor to spit metrics on every device it finds inside the container. I'm not sure the answer provides an explanation.

I'm glad to use kublet's `kubelet_volume_stats_*` metrics, but I'm running the latest k8s v1.10.2 and these metrics are still missing.

Anyone else still having issues on this? I can't find a way to get `kubelet_volume_stats_*` do show up.

**Comment by dashpole** [comment]
@juliohm1978  You need to query the kubelet's `/metrics` endpoint, rather than cadvisor's `/metrics` endpoint.

**Comment by juliohm1978** [comment]
I could be wrong. Isn't this the kubelet endpoint?

```
root@infra03-lab:~# curl -s http://infra03-lab:10255/metrics | grep kubelet_volume | wc -l
0
```

`infra03-lab` being the node hosting a container with a mounted nfs volume.

**Comment by gnufied** [comment]
@juliohm1978 you are not seeing those metrics for nfs volumes because nfs volume plugin does not implement necessary metric interface.  If you are up to it - see https://github.com/kubernetes/kubernetes/issues/62644 github issue about how to fix it. 

The reason some of the volume types don't implement metric interface is because - we haven't had a pressing need until now. We welcome any patches for fixing it though.

**Comment by juliohm1978** [comment]
Excellent. Thank you!

**Comment by chhetripradeep** [comment]
Strange, that i am seeing stale metrics for the volumes which are no longer attached to the host. I am running 1.8.11. Anyone has seen this issue ? Is upgrading to 1.9.latest the only way to solve this.

**Comment by aghassabian** [comment]
@tiloso Actually I can fetch the kubelet_volume_* metrics, but I get multiple values for a single persistent volume on different nodes. I have a cluster on GKE and claim a PV for a pod in namespace X.  when I query for kubelet_volume_stats_used_bytes, I get multiple records for same persistent volume in the same namespace with different values on different cluster nodes. Do you have any idea or have you ever faced this issue?

**Comment by andrezaycev** [comment]
Have the same situation. pv+pvc under nfs-deployment+gce disk
container_fs and kubelet_volume have not needed nfsstorage stats
Maybe anyone have new solution since Jun2018?

**Comment by szediktam** [comment]
> @juliohm1978 you are not seeing those metrics for nfs volumes because nfs volume plugin does not implement necessary metric interface. If you are up to it - see [kubernetes/kubernetes#62644](https://github.com/kubernetes/kubernetes/issues/62644) github issue about how to fix it.
> 
> The reason some of the volume types don't implement metric interface is because - we haven't had a pressing need until now. We welcome any patches for fixing it though.

host-path and nfs volume does not implement metric interface for now? @gnufied

**Comment by agolomoodysaada** [comment]
Is it possible to extend `container_fs_io_time_seconds_total` and similar metrics for PVCs?
I can only access them via `node_disk_io_time_seconds_total` from node-exporter but there's no way to automatically map those to the container mounting the disk without some seriously manual process. I'm happy to contribute a fix for this with some guidance.

**Comment by ctyjrsy** [comment]
I am running a k8s cluster on digital ocean, are do-block-storage volume type supported in prometheus monitoring via publish of kubelet_volume* metrics. I can not access these metrics via grafana (Prometheus Operator setup)

Running K8S 1.13+

**Comment by shinebayar-g** [comment]
@ctyjrsy I've deployed prometheus-operator via helm [chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator) yesterday. kubelet_volume* metrics weren't exposed. But it was exposed in normal prometheus helm [chart](https://github.com/helm/charts/tree/master/stable/prometheus). I'm on GKE 1.13.x

**Comment by marzottifabio** [comment]
I don't see these metrics too... with last k8s version.....

**Comment by dashpole** [comment]
I'm closing this issue, as it is out of the scope of cAdvisor.  If there is a specific kubernetes volume type that doesn't have metrics or bug with the existing kubelet volume metrics, that would probably be best tracked with an issue in k/k.

**Comment by SmilingNavern** [comment]
For anyone struggling to find answer like i did. If you use some cis plugin for persistent volume and this plugin doesn't expose metrics you won't find them. For example: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/223

**Comment by aasourav** [comment]
> @eedugon Kubernetes 1.8 exposes following volume related metrics for Prometheus which can be used to monitor PVC disk usage:
> 
> ```
> kubelet_volume_stats_available_bytes
> kubelet_volume_stats_capacity_bytes
> kubelet_volume_stats_inodes
> kubelet_volume_stats_inodes_free
> kubelet_volume_stats_inodes_used
> kubelet_volume_stats_used_bytes
> ```

`kubelet_volume_stats_available_bytes` This metric provides an invalid value.
