### ISSUE TITLE
Summary stats are zero before a minute has passed

### ISSUE THREAD

**Issue by carlwitt** [google/cadvisor#1715]
I noticed that when polling the summary stats of a container using

```
http://localhost:8080/api/v2.0/summary/container?type=docker
```

the minute_usage, hour_usage, and day_usage contain all zero fields until a minute/hour/day has passed by.
```
{"/docker/62e4d1[...]":{"minute_usage":{"memory":{"max":0,"mean":0,"fifty":0,"ninety"[...]
{"/docker/62e4d1[...]":{"minute_usage":{"memory":{"max":0,"mean":0,"fifty":0,"ninety"[...]
{"/docker/62e4d1[...]":{"minute_usage":{"memory":{"max":0,"mean":0,"fifty":0,"ninety"[...]
{"/docker/62e4d1[...]":{"minute_usage":{"memory":{"max":0,"mean":0,"fifty":0,"ninety"[...]
{"/docker/62e4d1[...]":{"minute_usage":{"memory":{"max":1606574080,"mean":898818048,"[...]
```
For me, it would be more useful to have these fields report quantiles right from the beginning. However, I'm not sure if other user would expect it to be this way.

**Comment by dashpole** [comment]
It seems reasonable that minute/hour/day usage doesnt show up until that quantity of time has passed.  I am not sure I want to change the behavior at this point, since I would rather not break anyone who may rely on the current behavior.
