### ISSUE TITLE
CPU Shares are named "Limit"

### ISSUE THREAD

**Issue by f0** [google/cadvisor#1717]
Hi,

in https://github.com/google/cadvisor/blob/master/info/v2/container.go#L32, the cpu shares are named limit
Is this intentional? 
AFAIK the shares are not a limit.

regards f0

**Comment by dashpole** [comment]
Yeah, I am not quite sure why the name was chosen initially.  It also appears that MaxLimit isn't ever set either.  I would recommend using Quota as the container limit.

**Comment by f0** [comment]
@dashpole ok, so this should be fixed?

**Comment by f0** [comment]
makes sense, thx
