### ISSUE TITLE
CAdvisor leaks journalctl (and thus inotify instances)

### ISSUE THREAD

**Issue by mtaufen** [google/cadvisor#1725]
When the Kubernetes kubelet exits, the journalctl started here: https://github.com/google/cadvisor/blob/a1e1ede0b2c0e91b294d85e1e1f3b618799a19a2/utils/oomparser/oomparser.go#L169 is left running. Each of these journalctl orphans consumes four inotify instances. Since the Kubelet needs to restart for our dynamic config feature, an arbitrary number of config changes can put the Kubelet into a crash loop (the Kubelet crashes if it cannot start CAdvisor, which happens if we hit the inotify instance cap). The cap is typically low, e.g. 128, so this can happen pretty easily.

I think we can try setting [cmd.SysProcAttr.Pdeathsig](https://golang.org/pkg/syscall/#SysProcAttr) to SIGKILL to fix this.

**Comment by dashpole** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/34965

**Comment by dashpole** [comment]
closed via #1729
