### ISSUE TITLE
Whitelist labels

### ISSUE THREAD

**Issue by cirocosta** [google/cadvisor#1730]
Hey,

I'm new to using `cadvisor` together with `InfluxDB`  but from what I understood we can't specify a set of labels to be retrieved from containers and sent to influx - all of them are sent. 

In my use case that's a problem as we don't control the full set of labels that a user can attach to his/her container (whilst we only need one or two labels that our platform defines). 

I noticed that for Prometheus there's a way of programmatically specifying the set of labels to be retrieved (https://github.com/google/cadvisor/pull/1429) but I think something more like `-docker_env_metadata_whitelist string` could be useful for not only `InfluxDB` users but also those using other storage drivers which are sending possibly more labels than the desired. 

I couldn't find another issue about this so I think it's not a duplicate (please let me know if this is incorrect!)

I'd be willing to implement this if desired 👍  

Wdyt?

Thx!

**Comment by dashpole** [comment]
That seems like a reasonable use case.  Feel free to post a PR.  My main request is that it defaults to the current behavior.

**Comment by dashpole** [comment]
fixed by #1984
