### ISSUE TITLE
Should we allow merge commits

### ISSUE THREAD

**Issue by dashpole** [google/cadvisor#1776]
forked from: https://github.com/google/cadvisor/pull/1769#issuecomment-338312210

"Does this repository have the "Allow merge commits" setting off? Is there any reason? The commit history does look nice and linear as a result, but this rebase was 100% unnecessary. There's no conflicts, no reason it would conflict, and it's a total waste of developer time.

If the worry is that it isn't being tested identically to how it's merged, well, that's what the submit queue solves for k8s proper, and what homu solves for other repositories (like rust)... and those solutions don't require your contributors to do utterly pointless busy work."

cc @tallclair @vishh

**Comment by euank** [comment]
It looks like github added an additional setting under the "Branch protection" header named "Require branches to be up to date before merging".

I don't think that's the right tradeoff for developers.

-----


![41404376-55bd-4671-8ab9-ded34c4bb6a8](https://user-images.githubusercontent.com/2147649/31971607-5bfa8150-b8d1-11e7-95f2-f0f835080ffb.png)

**Comment by dashpole** [comment]
Looks like we enable "Allow merge commits".  Maybe we just arent using it correctly.  Let me test it out.

**Comment by dashpole** [comment]
I see.  We did have the "Require branches to be up to date before merging".  I think we can disable this.  We just need to be careful, but we can always revert if builds go red.

**Comment by dashpole** [comment]
I have made the change, but would like to get a second opinion
cc @ixdy @krzyzacy
cAdvisor doesnt have the "rebase required" label infrastructure.  But we only get ~5 commits per week at most.
Would you recommend we keep the "Require branches to be up to date before merging" enabled?  Or can we disable it to make rebasing less frustrating for contributors?

**Comment by krzyzacy** [comment]
from our side, bootstrap will abort presubmit runs if your branch has merge conflicts with HEAD. I think it doesn't have to be up-to-date, as long as it does not have merge conflicts, it's fine.

**Comment by ixdy** [comment]
I believe our test infra merges the PR into the branch at HEAD when running tests, so even if the PR is out of date, it'll test as if it were to merge at that point. (This is different from Travis, I believe, which just tests the PR as-is.)

If a PR was created, tests were run, and then it was merged many days later (without explicitly running tests again), it's possible that the old test results would be stale and invalid. This is why we periodically re-run tests on LG'd PRs in k/k and always re-run before merging, though I also don't think the "require branches to be up-to-date" option existed when we first implemented the SQ, either.
