### ISSUE TITLE
 manager.go:161] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused

### ISSUE THREAD

**Issue by xiamujun** [google/cadvisor#1802]
docker run --volume=/:/rootfs:ro \
--volume=/var/run:/var/run:rw \
--volume=/sys:/sys:ro \
--volume=/var/lib/docker/:/var/lib/docker:ro \
--volume=/cgroup:/cgroup:ro \
--privileged=true \
--publish=8080:8080 \
--detach=true \
--link influxsrv:influxsrv \
--name=cadvisor \
google/cadvisor:v0.28.0 \
-storage_driver_db=influxdb \
-storage_driver_host=influxsrv:8086 \
-storage_driver_db=cadvisor

docker logs cadvisor
I1113 06:34:17.159807       1 storagedriver.go:50] Caching stats in memory for 2m0s
I1113 06:34:17.160070       1 manager.go:149] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct"
W1113 06:34:17.173969       1 manager.go:161] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
W1113 06:34:17.174078       1 manager.go:172] unable to connect to CRI-O api service: Get http://%2Fvar%2Frun%2Fcrio.sock/info: dial unix /var/run/crio.sock: connect: no such file or directory
I1113 06:34:17.189041       1 fs.go:139] Filesystem UUIDs: map[]
I1113 06:34:17.189059       1 fs.go:140] Filesystem partitions: map[/dev/vdb1:{mountpoint:/rootfs/data-aliyun major:253 minor:17 fsType:ext4 blockSize:0} shm:{mountpoint:/rootfs/var/lib/docker/containers/c3d1b599b30b363516f5f06609bf47cb35a85d96406ca733330a6702bc6c4e22/shm major:0 minor:42 fsType:tmpfs blockSize:0} tmpfs:{mountpoint:/dev major:0 minor:116 fsType:tmpfs blockSize:0} /dev/vda1:{mountpoint:/var/lib/docker/overlay major:253 minor:1 fsType:ext4 blockSize:0}]
I1113 06:34:17.190197       1 manager.go:223] Machine: {NumCores:2 CpuFrequency:2494222 MemoryCapacity:4141957120 HugePages:[{PageSize:1048576 NumPages:0} {PageSize:2048 NumPages:0}] MachineID:f0f31005fb5a436d88e3c6cbf54e25aa SystemUUID:35DE9982-7E86-4561-80D5-0212908A2411 BootID:a0059eb1-2089-4c9d-9103-2bd160bb0a25 Filesystems:[{Device:tmpfs DeviceMajor:0 DeviceMinor:116 Capacity:67108864 Type:vfs Inodes:505610 HasInodes:true} {Device:/dev/vda1 DeviceMajor:253 DeviceMinor:1 Capacity:42139451392 Type:vfs Inodes:2621440 HasInodes:true} {Device:/dev/vdb1 DeviceMajor:253 DeviceMinor:17 Capacity:105553780736 Type:vfs Inodes:6553600 HasInodes:true} {Device:shm DeviceMajor:0 DeviceMinor:42 Capacity:67108864 Type:vfs Inodes:505610 HasInodes:true} {Device:overlay DeviceMajor:0 DeviceMinor:112 Capacity:42139451392 Type:vfs Inodes:2621440 HasInodes:true}] DiskMap:map[253:0:{Name:vda Major:253 Minor:0 Size:42949672960 Scheduler:none} 253:16:{Name:vdb Major:253 Minor:16 Size:107374182400 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:00:16:3e:0a:d3:58 Speed:-1 Mtu:1500}] Topology:[{Id:0 Memory:4141957120 Cores:[{Id:0 Threads:[0] Caches:[]} {Id:1 Threads:[1] Caches:[]}] Caches:[{Size:41943040 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I1113 06:34:17.190909       1 manager.go:229] Version: {KernelVersion:4.13.12-1.el7.elrepo.x86_64 

ContainerOsVersion:Alpine Linux v3.4 DockerVersion:17.11.0-ce-rc3 DockerAPIVersion:1.34 CadvisorVersion:v0.28.0 CadvisorRevision:3d2e7fc}
I1113 06:34:17.203104       1 factory.go:355] Registering Docker factory
W1113 06:34:17.203132       1 manager.go:273] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
W1113 06:34:17.203214       1 manager.go:284] Registration of the crio container factory failed: Get http://%2Fvar%2Frun%2Fcrio.sock/info: dial unix /var/run/crio.sock: connect: no such file or directory
I1113 06:34:17.203231       1 factory.go:54] Registering systemd factory
I1113 06:34:17.204126       1 factory.go:86] Registering Raw factory
I1113 06:34:17.204991       1 manager.go:1161] Started watching for new ooms in manager
I1113 06:34:17.205542       1 nvidia.go:47] No NVIDIA devices found.
I1113 06:34:17.206412       1 manager.go:322] Starting recovery of all containers
I1113 06:34:17.305398       1 manager.go:327] Recovery completed
I1113 06:34:17.420127       1 cadvisor.go:159] Starting cAdvisor version: v0.28.0-3d2e7fc on port 8080

#####################
docker info
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.11.0-ce-rc3
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.13.12-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.857GiB
Name: prod_shipyard
ID: S7IY:SOI5:Q7CN:ZFTS:CDJZ:3KBT:LVSB:AYX5:ZTGI:WM7I:SMK3:OP7N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://vfjfj35s.mirror.aliyuncs.com/
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

 centos7.4 kernel4.13.12

**Comment by xiamujun** [comment]
docker run --volume=/:/rootfs:ro \
--volume=/var/run:/var/run:rw \
--volume=/sys:/sys:ro \
--volume=/var/lib/docker/:/var/lib/docker:ro \
--volume=/cgroup:/cgroup:ro \
--volume=/dev/disk/:/dev/disk:ro \
--privileged=true \
--publish=8080:8080 \
--detach=true \
--link influxsrv:influxsrv \
--name=cadvisor \
google/cadvisor:v0.28.0 \
-storage_driver_db=influxdb \
-storage_driver_host=influxsrv:8086 \
-storage_driver_db=cadvisor

**Comment by dashpole** [comment]
The error message in the title occurs because you are not running rkt.  cAdvisor attempts to connect to all container runtimes it knows about.  Since you are running docker, but not rkt, it is expected that it will fail to connect to rkt.

**Comment by dashpole** [comment]
Are you experiencing any other issues?

**Comment by xiamujun** [comment]
I obviously run docker, why cadvisor this version will even rkt? I refer to the following link configuration, I remember at that time is operating normally on ubuntu14.04.

https://www.brianchristner.io/how-to-setup-docker-monitoring/?spm=5176.100239.blogcont5065.15.H88S2l

**Comment by mister2d** [comment]
@dashpole Is there a flag to tell cadvisor to not attempt to connect to Rkt or CRI-O runtimes?

**Comment by dashpole** [comment]
No, there is no flag.  The way cAdvisor works is by monitoring all containers (and cgroups) on the machine it lands on, including docker, rkt, cri-o, and containerd soon.  If you are not running rkt, for example, then it will not monitor rkt containers and will produce that log message.  However, docker container monitoring should work regardless of whether or not you are also running other container runtimes.  So this error message should be benign.

Are you experiencing any other issues?

**Comment by mister2d** [comment]
No other issues. I just was confused as to what the `-docker_only` argument does.

**Comment by xiamujun** [comment]
thanks

**Comment by Asher-Shoshan** [comment]
Can not connect to Docker in my machine, when starting cadvisor in docker.   --privileged=true is not accepted

**Comment by dashpole** [comment]
I dont think that is related to this issue @Asher-Shoshan.  Based on [the documentation](https://github.com/google/cadvisor/blob/master/docs/running.md#centos-fedora-and-rhel) that may be the only option for some OS distributions.

**Comment by Asher-Shoshan** [comment]
Sorry for not being clear.   The cadvisor container saying it's unable to connect to docker daemon...
(This I see when running it interactively -  run -i -t ...)

**Comment by dashpole** [comment]
You can probably still use cAdvisor in that case.  You just wont get docker metadata.

**Comment by Asher-Shoshan** [comment]
But I need it for monitoring the containers in Kubernetes and use the metrics for Autoscaling...
What good is it without?
Is that a bug? Has anyone else faced it?

**Comment by Asher-Shoshan** [comment]
It's a separate one...   I don't know how to check the embedded one in 'kubelet' or how to install/deploy it.

**Comment by dashpole** [comment]
Have you checked out the [autoscaling docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/)?

The kubelet's cadvisor port is 4194, although we plan to deprecate this in the future. Try `curl localhost:4194/metrics` from a node.
The kubelet also exposes the [summary API](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/stats/v1alpha1/types.go), which is exposed on port 10255.  Try `curl localhost:10255/stats/summary` from a node.

Heapster is an open-source aggregator, which collects metrics from the summary API, and can be used for autoscaling (see the docs above).
