### ISSUE TITLE
There is a Race between Setup and GetCollector in nvidia.go

### ISSUE THREAD

**Issue by choury** [google/cadvisor#1810]
`GetCollector` will failed when  `nm.nvmlInitialized` are `true` but `initializeNVML` hasn't finished.
I can open a PR to fix it if you think this is a bug.

**Comment by dashpole** [comment]
cc @mindprince

**Comment by mindprince** [comment]
@choury You are right. I sent a quick PR to fix this: https://github.com/google/cadvisor/pull/1814

Thanks for finding this out.

@dashpole Do you think this fix can make the vendoring cut for 1.9?
