### ISSUE TITLE
Provide documentation how to expose cadvisor application metrics via prometheus metrics endpoint.

### ISSUE THREAD

**Issue by jmatusewicz-bringmeister** [google/cadvisor#1823]
Our cadvisor instance scraps successful the configured application endpoints of our docker containers. The application metrics are also available via http://cadvisor/api/v2.0/appmetrics/{nameOfDockerContainer} as JSON, but aren't available via http://cadvisor/metrics as Prometheus format.

What is the intended way of getting application metrics to a prometheus server?

Our prometheus server is setup to scrap http://cadvisor/metrics.

**Comment by dashpole** [comment]
You would need to add custom metrics to the prometheus exporter here: https://github.com/google/cadvisor/blob/master/metrics/prometheus.go

**Comment by dashpole** [comment]
Closing as duplicate of https://github.com/google/cadvisor/issues/1616.  Feel free to discuss this there.
