### ISSUE TITLE
unable to get the image name in container_last_seen metric

### ISSUE THREAD

**Issue by sundeepk1** [google/cadvisor#1828]
Hi Team,

I am trying to get the number of containers that are running currently based on the image name, however I am unable to find the info . can you please add this feature .

It would be good if you could recommend a workaround to resolve this

# container_last_seen
Element | Value
-- | --
container_last_seen{id="/",instance="cadvisor:8080",job="cadvisor"} | 1511862090
container_last_seen{id="/docker",instance="cadvisor:8080",job="cadvisor"} | 1511862090
container_last_seen{id="/init.scope",instance="cadvisor:8080",job="cadvisor"} | 1511862090
container_last_seen{id="/system.slice",instance="cadvisor:8080",job="cadvisor"} | 1511862090
container_last_seen{id="/system.slice/accounts-daemon.service",instance="cadvisor:8080",job="cadvisor"} | 1511862090
container_last_seen{id="/system.slice/acpid.service",instance="cadvisor:8080",job="cadvisor"} | 1511862090
container_last_seen{id="/system.slice/apparmor.service",instance="cadvisor:8080",job="cadvisor"} | 1511862090
container_last_seen{id="/system.slice/apport.service",instance="cadvisor:8080",job="cadvisor"} | 1511862090
container_last_seen{id="/system.slice/atd.service",instance="cadvisor:8080",job="cadvisor"} | 1511862090
container_last_seen{id="/system.slice/cgroupfs-mount.service",instance="cadvisor:8080",job="cadvisor"} | 1511862090
container_last_seen{id="/system.slice/cloud-config.service",instance="cadvisor:8080",job="cadvisor"} | 1511862090

**Comment by dashpole** [comment]
It looks like this is available in the v2 API: https://github.com/google/cadvisor/blob/master/info/v2/container.go#L99, as well as exported by prometheus:
https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L793.

What version of cadvisor are you using?

**Comment by sundeepk1** [comment]
@dashpole 

I am using  google/cadvisor:v0.27.2 image

**Comment by dashpole** [comment]
This may be related to https://github.com/google/cadvisor/issues/1704.  I still need to release a version with the fix.

**Comment by sundeepk1** [comment]
@dashpole thanks for the update .. i reverted to google/cadvisor:v0.25.0 where i am able to get the required details

**Comment by dashpole** [comment]
The fix should be in v0.27.3 and v0.28.3
