### ISSUE TITLE
Emit docker hostname when using a storage driver

### ISSUE THREAD

**Issue by cboggs** [google/cadvisor#183]
We noticed that we can differentiate same-named containers by their container ID when querying InfluxDB for cadvisor stats, but can't find out what host a container is running on. 

I'm sure there are some external tools being built that we could query with a container ID to figure out what host it's on, but if the hostname was included in the stored stats it would save a step. It would also make life easier for building situational dashboards & monitoring to highlight & alert on problematic docker hosts.

**Comment by ntquyen** [comment]
@vishh I know this issue is old and it must have been fixed. But I still don't know how to replace the cadvisor container id in the `machine` column with the hostname. Can you give me a hint?

**Comment by ntquyen** [comment]
Never mind, I have figured out to change the container hostname using `--hostname` flag in `docker run`
