### ISSUE TITLE
Comment on versioning on docker hub

### ISSUE THREAD

**Issue by davidkarlsen** [google/cadvisor#1836]
https://hub.docker.com/r/google/cadvisor/

states
"latest: Latest stable build, this is the latest officially supported releases.
canary: Images built from HEAD periodically. Potentially unstable!"

what about the other versions? latest is 9 months old which is quite a lot, while the other versions are younger - are these seen as stable?

**Comment by dashpole** [comment]
I dont think updating latest is part of our release process right now.  That would explain why it is so far behind.

**Comment by davidkarlsen** [comment]
@dashpole If that is the case maybe the docs on dockerhub should be updated as they are misleading. What is thew recommended stable version to run?

**Comment by dashpole** [comment]
I would recommend 0.27.3, unless you use prometheus, in which case you would want to use v0.25.0 or v0.28.3.

**Comment by dashpole** [comment]
I updated latest to v0.28.3
