### ISSUE TITLE
Getting docker container oom event.

### ISSUE THREAD

**Issue by TambetP** [google/cadvisor#1837]
Hello. 

Is there a way to get container oom event as a prometheus metric?
I am using cAdvisor to monitor docker containers with Prometheus and Grafana. I can see that there is a **oom_kill_event** in the API, but cannot find something similar in prometheus metrics.

**Comment by dashpole** [comment]
You would have to add it to the [prometheus endpoint](https://github.com/google/cadvisor/blob/master/metrics/prometheus.go).

**Comment by TambetP** [comment]
Has someone already done that or maybe working on it, or planning to add it?

**Comment by dashpole** [comment]
No one is working on it as far as I am aware

**Comment by Klohto** [comment]
How likely is the revisit of this topic? Currently, one needs to create its own collector or use a "third-party" like https://github.com/draganm/missing-container-metrics
