### ISSUE TITLE
any metrics to alert if one container stopped?

### ISSUE THREAD

**Issue by hiscal2015** [google/cadvisor#1838]
Hi, all

I'm trying to find out if there're any metrics for container stop event, but seems no luck.
I looked into container_last_seen, but even if one container stopped, the value of container_last_seen is still the current unix timestamp.
Please help, thanks a lot.

**Comment by dashpole** [comment]
cAdvisor doesnt try and maintain container state.  It can tell when a container exists by examining the cgroup tree, but cant tell what is running in it, or anything else.  Monitoring docker directly for this information is probably the best solution

**Comment by hiscal2015** [comment]
@dashpole Thanks for the answer, but what does "Monitoring docker directly for this information is probably the best solution" mean?

**Comment by dashpole** [comment]
You could write a lightweight exporter to query docker, and export metrics in prometheus format, or use one of the prometheus exporters that scrape the docker api.

**Comment by dashpole** [comment]
You could also look for when there are memory or CPU metrics from cadvisor.  Stopped containers do not have any processes, and thus should have 0 for both of these metrics.

**Comment by hiscal2015** [comment]
@dashpole Thanks for the advise. For stopped containers, there will be no metrics by cpu or memory rather than returning 0, and seems "absent" can not handle multiple container stop events, so maybe a customized exporter would be a better choice.

**Comment by jftavira** [comment]
Use "container_last_seen" when a container stops after a while this metric dissaperars.
I use count(container_last_seen{image="xxxx"}) to know if a kind of container is down.
J
