### ISSUE TITLE
GPU metrics without running cadvsior in container 

### ISSUE THREAD

**Issue by guptaNswati** [google/cadvisor#1853]
I am trying to get Gpu metrics in cadvisor and running cadvisor in a container works fine by passing <nvml path> and Gpu access but how do I get the metrics without running cadvisor in container. I tried with <./cadvisor -docker_env_metadata_whitelist="-e path to nvml, --device, other flags"> but it dint work.

**Comment by dashpole** [comment]
Thats strange... usually it is easier to run things outside of a container than inside.  Are you getting any errors related to GPU initialization in cadvisor?
cc @mindprince

**Comment by guptaNswati** [comment]
No errors and I don't think nvml is getting initialized either. I am passing all these,
sudo ./cadvisor -docker_env_metadata_whitelist=“--volume=/usr/lib/nvidia-384:/usr/lib/nvidia-384, LD_LIBRARY_PATH=/usr/lib/nvidia-384, --privileged, --device-cgroup-rule=‘c 195:* mrw’, --device=/dev/nvidiactl:/dev/nvidiactl, --device=/dev/nvidia0:/dev/nvidia0, --device=/dev/nvidia1:/dev/nvidia1, --publish=8080:8080”

**Comment by mindprince** [comment]
Not sure what `docker_env_metadata_whitelist` does or why is it needed.

Did you check https://github.com/google/cadvisor/blob/master/docs/running.md#hardware-accelerator-monitoring

**Comment by guptaNswati** [comment]
I am using this flag to pass access to nvidia devices. I did follow the instructions from above link but it only documents for containers. How do I pass nvml-path and device access to the binary?

**Comment by mindprince** [comment]
If you are running cadvisor outside the container as root, you don't need to give it explicit device access. root already has that. To make sure it has access to NVML libraries, you either update your ldconfig or do something like:
```
export LD_LIBRARY_PATH=<path-to-nvml>
sudo ./cadvisor
```

**Comment by guptaNswati** [comment]
I had my LD_LIBRARY_PATH set but since sudo wont have the usr env, this does not work. It should be `sudo LD_LIBRARY_PATH="nvml-path" ./cadvisor - logtostderr`
I see nvml initialized but still no Gpu metrics on /metrics endpoint.

**Comment by mindprince** [comment]
Are there any containers running that are using GPUs? You will only see metrics for containers using GPUs. There are no machine level GPU metrics.

**Comment by mindprince** [comment]
Also, as the documentation mentions the containers should be explicitly using GPU devices.

**Comment by guptaNswati** [comment]
Oh right! missed that. Let me try running a Gpu container.

Thanks

**Comment by guptaNswati** [comment]
Ran a Gpu container, getting this error, 
`NVML initialized. Number of nvidia devices: 1
I0105 22:22:13.010226   17819 manager.go:329] Starting recovery of all containers
W0105 22:22:13.085032   17819 container.go:507] Failed to update stats for container "%s": %s/docker/ad33e310628098e54ec8af4feec25afb59b38299e1eacec069ff7206b8e292baerror while getting gpu utilization: nvml: Not Found`

**Comment by mindprince** [comment]
Is this still an issue? Can this be closed?

**Comment by guptaNswati** [comment]
Yes, got it working. Closing, thanks.
