### ISSUE TITLE
How does cAdvisor collects metrics from containers?

### ISSUE THREAD

**Issue by jpslopes** [google/cadvisor#1854]
I have a doubt about how cAdvisor gathers the containers metrics. Is it through using Docker API, cgroups (control groups) or namespaces? I already have read the description and I did not found anything about this issue...

**Comment by dashpole** [comment]
It gets some container metrics, such as cpu and memory, through cgroups.  It gets disk metrics by using statfs on the filesystems, or du to get container writable layer usage.  Runtime-specific metrics or info are retrieved directly from the runtime.

**Comment by jpslopes** [comment]
Thank you very much for the answer. I have another 2 questions: 
- How much instrusive is cAdvisor with the containers that it is collecting metrics from?
- What is the best way to gather metrics from containers: running cAdvisor as a container or as "standalone"?

**Comment by dashpole** [comment]
I am not quite sure what you mean by intrusive.  I would say it isnt intrusive at all--containers monitored by cAdvisor are entirely unaware of its existence.  For most metrics, cAdvisor simply observes the cgroup tree, and reports the metrics it exposes.

I think it depends on how you deploy your software.  Running cAdvisor as a container could allow you, for example, to set container CPU or memory limits if you want to ensure it doesn't consume too many resources.  You can use systemd configurations or containers to automatically start cAdvisor, and restart it if it were to crash for some reason.  I dont think either is better or worse.

**Comment by jpslopes** [comment]
Thank you for answering.

**Comment by dashpole** [comment]
no problem
