### ISSUE TITLE
Timestamp inconsistency

### ISSUE THREAD

**Issue by jpslopes** [google/cadvisor#1857]
Hello, when I go to http://localhost:8080/api/v2.0/stats/docker/<container>?count=60 in my web browser, I verified that the timestamp associated to each stat does not follow the time between collected metrics. I'm using the default housekeeping interval (1 second) and many of the timestamps present breaks between 2 and 3 seconds. Why is this happening? Should not the timestamps have an interval of 1 second in this case?
I already tried lowering the housekeeping interval to 100ms, but it still does not work as it presents breaks too...

In the following screenshot, there is a break of 1 second between the stats 2 and 3.

![screenshot 1](https://user-images.githubusercontent.com/15234158/34729332-4e73b032-f554-11e7-991f-9924f291b899.jpg)

**Comment by dashpole** [comment]
This is probably because of dynamic housekeeping, which adds jitter to the time between stats collection to try and prevent spikes of usage.
See https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#housekeeping for more info.
