### ISSUE TITLE
Adding /proc/<pid>/schedstat

### ISSUE THREAD

**Issue by nielsole** [google/cadvisor#1865]
I was looking into measuring whether a container is running into CPU performance issues on its host.
While the `cpu.stats.throttled_time`/`container_cpu_cfs_throttled_seconds_total` is helpful, it does only reflect when the scheduler has explicitly throttled the process. What I was looking for was a metric that shows, whether a process was waiting for CPU time or not (kind of blocked by CPU). 

The kernel measures this metric, but cAdvisor does not collect it. It apparently was already included back in 2014 https://github.com/google/cadvisor/commit/324874411d0d4ad6f0b76fa46af8e53696fed866 

Is there a reason this is not included in cAdvisor?

From the kernel docs: https://www.kernel.org/doc/Documentation/scheduler/sched-stats.txt

    /proc/<pid>/schedstat
    ----------------
    schedstats also adds a new /proc/<pid>/schedstat file to include some of
    the same information on a per-process level.  There are three fields in
    this file correlating for that process to:
     1) time spent on the cpu
     2) time spent waiting on a runqueue
     3) # of timeslices run on this cpu

    A program could be easily written to make use of these extra fields to
    report on how well a particular process or set of processes is faring
    under the scheduler's policies.  A simple version of such a program is
    available at
    http://eaglet.rain.com/rick/linux/schedstat/v12/latency.c

**Comment by hanikesn** [comment]
Doing some further investigation it looks like https://github.com/google/cadvisor/blob/master/info/v1/container.go#L256 could give us cpu saturation information, though it won't be as accurate as blocked time is not accumulated like with `time spent waiting on a runqueue`.

**Comment by dashpole** [comment]
Yeah, it looks like it was exposed once upon a time: https://github.com/google/cadvisor/pull/142, but then removed as https://github.com/google/cadvisor/issues/1865#issuecomment-357943893 points out.  According to https://github.com/google/cadvisor/pull/431, it looks like some of the metrics were not accurate.

**Comment by nielsole** [comment]
I read #431 that `sched_debug` (not `schedstat`) is not suitable for measuring load. It doesn't mention `schedstat` but just removes it. I could well imagine that `schedstat` is not suitable for measuring load on a system, but that is not what we are attempting to do.

**Comment by dashpole** [comment]
I would be willing to review a PR which adds those metrics.  I request that they be disabled by default (we have an `ignoreMetrics` mechanism you can use).  They should also be metrics associated with containers, rather than processes in the API.

**Comment by cirocosta** [comment]
Looks like this can be closed (https://github.com/google/cadvisor/pull/1872) 😁
