### ISSUE TITLE
Can't run on port other than 8080

### ISSUE THREAD

**Issue by NaitikShah** [google/cadvisor#1889]
Hi,
I am trying to run cadvisor using docker-compose file which looks like
`
version: '2'

services:

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    ports:
      - 9080:9080
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
`
But this forcefully runs on port 8080.

I just want to know if this is hard coded from within cadvisor or not ... as i have another app running on 8080 i need to change cadvisor running port.

@dashpole if you can please help me out?

**Comment by dashpole** [comment]
It isnt hard-coded.  You can either map port 8080 to a different port, or [use the `--port` flag](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#http)

**Comment by dashpole** [comment]
feel free to reopen if you have follow-up questions

**Comment by NaitikShah** [comment]
Hi @dashpole as you must have seen in the above docker-compose file, I have been specifying ports as:
`ports:` 
`    - 9080:9080`
But still, it doesn't work on the specified port and as said I have another app running on 8080.

**Comment by NaitikShah** [comment]
I guess I found the issue, 
It's mainly because I was using
`network_mode: host`

**Comment by patrickjeried** [comment]
Hi im encountering this issue right now as other application is allocating port 8080.

what was your work around on this?

**Comment by katarzyna-z** [comment]
I've built and run cAdvisor from current master and I am able to run cAdvisor on different port using this command: 
```
sudo ./cadvisor --port 8001
```
