### ISSUE TITLE
InfluxDB as backend storage, to add memory_rss measurement.

### ISSUE THREAD

**Issue by alicek106** [google/cadvisor#1899]
When InfluxDB is set as backend storage, memory related data is collected in two measurements.

(1) memory_usage
(2) memory_working_set

According to #638 , 
memory_usage = rss + cache
memory_working_set = memory_usage - inactive (inactive file + inactive anon)

But in many cases, memory except cache (only rss) will necessary because memory rss is consistent with docker stats API, so I propose to add a feature to push memory_rss measurement into influxdb backend storage.

Actually, I already forked cadvisor and using my modified version well. :D It was very easy.

https://github.com/alicek106/cadvisor/commit/ed3d9c40ae83ac377891061a7dc22f92ccd53f8c

I hope to update this feature the latest version of cadvisor. thank you.

**Comment by dashpole** [comment]
sounds good to me! Feel free to post a PR.

**Comment by alicek106** [comment]
Close because https://github.com/google/cadvisor/pull/1908 has been merged.
