### ISSUE TITLE
Unable to find cpuset on AWS ECS

### ISSUE THREAD

**Issue by akomic** [google/cadvisor#1900]
AWS ECS instances have /sys/fs/cgroup empty so you need to mount /cgroup:/sys/fs/cgroup on cadvisor, but the problem is not solved.
In /cgroup/cpuset/docker/ are only containers manually started on ECS machines, the rest of container is in e.g.:

/cgroup/cpuset/ecs/407f6abe-0744-4a5e-b6e1-397b1032febc/<container_id>
Where "ecs/407f6abe-0744-4a5e-b6e1-397b1032febc" can be found in docker inspect output as "CgroupParent".

**Comment by dashpole** [comment]
That is quite odd.  Do you know if they are actually using docker to run the "rest of [the] containers? Or are they running them with something else?

**Comment by akomic** [comment]
They are using docker for all containers. Beside this there is no difference visible difference between containers. Would it make sense to have Cadvisor use "CgroupParent" attribute for each container?


```bash
docker run --help | grep cgroup-parent
      --cgroup-parent string           Optional parent cgroup for the container
```

**Comment by akomic** [comment]
Fixed.
Instead of 
```
sInfo, err := c.SubcontainersInfo("/docker", &request)
```
Use
```
sInfo, err := c.SubcontainersInfo("/", &request)
```
