### ISSUE TITLE
Status about cpu load metrics

### ISSUE THREAD

**Issue by andyxning** [google/cadvisor#1914]
According to the docs, it is said that cpu load metrics are experimental. Is it ok to use it in production or in another words any problems about not make it as stable? 

BTW, i want to add the support for collecting cpu load metrics to heapster.

/cc @dashpole

**Comment by dashpole** [comment]
I'm not sure how much use they have gotten since they were added.  I don't see an issue with adding them to heapster if there is demand for them.  I guess we will find out if it works well or not once people start using them.  Do you have users who are asking for these metrics?

**Comment by andyxning** [comment]
> Do you have users who are asking for these metrics?

Actually i have added `cpu/load` metrics to heapster in https://github.com/kubernetes/heapster/pull/1989. I have some demands about container/cgroup loads to meet the user habits when they are in bare metal/vm.

**Comment by andyxning** [comment]
Close this as it seems that there are not so many people currently using cpu load metrics. Will see this later.
