### ISSUE TITLE
Definition of Virtual Size

### ISSUE THREAD

**Issue by spirrello** [google/cadvisor#1922]
Hi,

We had an issue where a group of pods for a deployment started consuming the majority of the disk space on one of our hosts.  To investigate which pod was at fault we tried using the cadvisor UI and came across the virtual size.  

Can someone advise what this metric is measuring?  Can we use this for measuring disk space utilization by a pod?

<img width="1309" alt="cadvisor" src="https://user-images.githubusercontent.com/7174260/38432829-c0950d4c-3996-11e8-83c7-a940f1ee7acf.png">

**Comment by dashpole** [comment]
This metric is measuring virtual memory size.  "It includes all memory that the process can access, including memory that is swapped out, memory that is allocated, but not used, and memory that is from shared libraries."
from https://stackoverflow.com/questions/7880784/what-is-rss-and-vsz-in-linux-memory-management

**Comment by dashpole** [comment]
Looks like you are in the process page.  You should be able to see disk usage in the container page.

**Comment by spirrello** [comment]
We're browsing directly to our K8s node like this and I don't see anything stating disk utilization.  Do I need to run cAdvisor as a daemonset to get a newer version perhaps to see the disk utilization?

Also, we're using K8s 1.5.4 - is this an issue?

http://nodeip/4194/containers/docker/cfa34ca5d3f2731564fa3b855e48b903c896c440b789e236a50f2dc1f64f243c

**Comment by dashpole** [comment]
Disk utilization should be one of the metrics collected in that version IIRC, but that was ages ago.  You could try running a newer version of cAdvisor as a daemonset to see if it was added since that version.

**Comment by spirrello** [comment]
Okay I'll try that.  Thanks.

**Comment by spirrello** [comment]
Got it working thanks.
