### ISSUE TITLE
cadvisor may take too many time when it try to get usage of disk

### ISSUE THREAD

**Issue by knightXun** [google/cadvisor#1941]
see kubernetes issue [#61793](https://github.com/kubernetes/kubernetes/issues/61793).So can we replace linux command `du` with go program?

**Comment by dashpole** [comment]
I 'm not sure why a `go` program would perform better than a `c` program.  We have tried this in the past, and it ended up being slightly slower when written in go.

**Comment by knightXun** [comment]
maybe we can use some cache
