### ISSUE TITLE
Metrics missing, such as container_cpu_usage_seconds_total

### ISSUE THREAD

**Issue by ArvinDevel** [google/cadvisor#1958]
I used [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) to monitor the k8s, but I found that the container level metrics is restricted to those pods in `kube-system`,`monitoring` and `kubeflow-seldon` namespace, the pods info in other namespace is not displayed, such as `default` namespace. I'm curious about the reason. 
Some one else happened to has [the same problem](https://github.com/kubernetes/kube-state-metrics/issues/329), and the kube-state-metrics members thought the reason may be lay in cadvisor. 
The [official doc](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/) said that the cadvisor is integrated in k8s, so I wanna use `log` command to investigate it but found that the k8s has no daemonset named cadvisor. Can you give me some suggestions to debug the cadvisor in k8s.

**Comment by ArvinDevel** [comment]
Up to now, I found the problem is that the metrics generated by cadvisor(except those can be displayed by prometheus) has lots of null labels, shown on the picture. The output metrics is output of one node/kubelet from `http://localhost:8001/api/v1/nodes/MYNODE/proxy/metrics/cadvisor` after apply `kubectl proxy`.
Output of 
```shell
kubectl version
```
is
```shell
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
I think this is related to #1704. Is my k8s cluster's version too small to suffer such problem?

**Comment by ArvinDevel** [comment]
![cadvisor-metrics](https://user-images.githubusercontent.com/16100052/41200941-883856fc-6ce0-11e8-8392-5ad0e1bd744a.png)

**Comment by dashpole** [comment]
cAdvisor logs are found in the kubelet logs.
I don't see any null labels, it looks like they are all filled in with empty strings if they are not found.  #1704 results in a different set of metrics each time.  Sometimes it shows only containers, sometimes only cgroups.  Your issue sounds different.

**Comment by ArvinDevel** [comment]
@dashpole thanks. 
yeah, not null labels, just empty strings.
What does the `id` field of metric labels mean? is there any docs to explain this?

**Comment by ArvinDevel** [comment]
I solved my question using [this method](http://centosquestions.com/prometheus-kubelet-metrics-server-returned-http-status-403-forbidden/), I forgot to clarify that some of my kubelet don't grant the `kube-state` to access it. And now the metrics what I want has emerged, but these still exists lots of metrics with empty labels. I think these too much metrics maybe is related to system.

**Comment by dashpole** [comment]
cAdvisor produces metrics for each cgroup.  It just happens to attack extra information to cgroups that it identifies as containers.

**Comment by ArvinDevel** [comment]
since the problem has been solved, close it now. thanks for you @dashpole .
