### ISSUE TITLE
AllDockerContainers failed as cache not synced

### ISSUE THREAD

**Issue by lichuqiang** [google/cadvisor#1970]
Our upper components call cadvisor to get all container information regularly.
And upon container deletion, we found it has a chance to fail with a status code of 500.

Looking into the code, in `AllDockerContainers`:
```
func (self *manager) AllDockerContainers(query *info.ContainerInfoRequest) (map[string]info.ContainerInfo, error) {
	containers := self.getAllDockerContainers()

	output := make(map[string]info.ContainerInfo, len(containers))
	for name, cont := range containers {
		inf, err := self.containerDataToContainerInfo(cont, query)
		if err != nil {
			return nil, err
		}
		output[name] = *inf
	}
	return output, nil
}
```

we get the  containers from manager.containers, and in `containerDataToContainerInfo`, we query stats from its memoryCache. there is a chance we get the containers list before a container deleted, and when querying `containerDataToContainerInfo`, a container has already been removed from the memoryCache. as a result, we got error.

**What expected to happen**:
Avoid the cache not synced issue.
Or at least avoid returning with a status code 500 roughly, maybe log the error, and return the data of available containers.

**Comment by dashpole** [comment]
What is the entry-point of your upper components?  Do they call `AllDockerContainers` directly, or are they making an API call?

**Comment by lichuqiang** [comment]
> What is the entry-point of your upper components? Do they call AllDockerContainers directly, or are they making an API call?

api call: http://127.0.0.1:4194/api/v1.2/docker
i.e: https://github.com/google/cadvisor/blob/master/api/versions.go#L198

**Comment by dashpole** [comment]
Sounds like it would be better to log a warning, and return a best-effort response.  Feel free to send me a PR, and ill review it.
