### ISSUE TITLE
Plan to add disk usage per container?

### ISSUE THREAD

**Issue by tifayuki** [google/cadvisor#198]
Hi,
I wonder if there is a plan to add disk usage metrics for each container to cAdvisor. And also may include the volume size of each container?

BTW, thanks for this awesome cAdvisor project.

**Comment by vishh** [comment]
Disk usage metrics are already supported. cAdvisor could possibly expose usage of volumes if they happen to be separate filesystems. Shared volumes will be tricky to handle though.
I'm closing this issue for now.

**Comment by discordianfish** [comment]
@vishh Are they? At least they aren't available on GKE's k8s. I have container_fs_usage_bytes but without a total or free space metric this isn't useful.

**Comment by ivan046** [comment]
> Disk usage metrics are already supported. cAdvisor could possibly expose usage of volumes if they happen to be separate filesystems. Shared volumes will be tricky to handle though.
> I'm closing this issue for now.

I curl the cadvisor of GKE node and get the following:
# HELP container_fs_usage_bytes Number of bytes that are consumed by the container on this filesystem.
# TYPE container_fs_usage_bytes gauge
container_fs_usage_bytes{container="",container_name="",device="/dev/sda1",id="/",image="",name="",namespace="",pod="",pod_name=""} 9.616154624e+09 1592321393409


As you can see, container_name is empty so I can't get space used per container. why?

**Comment by DavidPerezIngeniero** [comment]
I don't know how to measure the needs of ephemereal space of containers in a k8s cluster.
It would be very useful to have stats by container instead of by node.

**Comment by Hemanthbhk** [comment]
> I don't know how to measure the needs of ephemereal space of containers in a k8s cluster. It would be very useful to have stats by container instead of by node. I wonder if after eight years, any progress has been made.

Have you gone through this [doc](https://docs.openshift.com/container-platform/4.8/storage/understanding-ephemeral-storage.html#storage-ephemeral-storage-monitoring_understanding-ephemeral-storage) /bin/df as a tool to monitor ephemeral storage usage on the volume where ephemeral container data is located .
