### ISSUE TITLE
Container labels sometimes not passed through

### ISSUE THREAD

**Issue by BertHartm** [google/cadvisor#1986]
I'm seeing some situations where metrics are being reported for the prometheus exporter without their container labels. A restart of cadvisor fixes it.

I'm running cadvisor as just the binary, not as a container, so it's possible that it's coming up before docker does, I'm not sure if that would make a difference. It is picking up the docker containers correctly.

I'm specifically seeing this on a node where jobs get scheduled, so containers come and go, and there may not be much workload when the machine comes up.

**Comment by dashpole** [comment]
Yeah, check the beginning of the logs for a failure to connect to docker.  If that fails, you won't get labels or anything from docker.

**Comment by BertHartm** [comment]
Sorry for leaving this open so long. It appears that starting cadvisor before docker was the issue
