### ISSUE TITLE
Builds failing on RHEL

### ISSUE THREAD

**Issue by dashpole** [google/cadvisor#1988]
The failure was on RHEL here: https://148.100.110.186/jenkins/job/cAdvisor_RHEL7_s390x_GHPRB/255/console
```
+ godep go build .
# github.com/google/cadvisor/container/mesos
container/mesos/mesos_agent.go:33: syntax error: unexpected = in type declaration
godep: go exit status 2
```

Type alias is introduced in go.1.9(https://github.com/golang/proposal/blob/master/design/18130-type-alias.md), so we need to update the go version in those builds.

This superceeds #1987

**Comment by Nayana-ibm** [comment]
@dashpole build is successful after upgrading golang to v1.9.4 
https://148.100.110.186/jenkins/job/cAdvisor_RHEL7_s390x_GHPRB/257/

**Comment by dashpole** [comment]
Thanks!
