### ISSUE TITLE
Collect and report the processes belonging to a cgroup for each container

### ISSUE THREAD

**Issue by sashankreddya** [google/cadvisor#1995]
1) The cgroups.procs under "cpu" cgroup of each container has a list of process id's.
2) Report the total number of processes for each container as "container_procs_total"

**Comment by dashpole** [comment]
I think number of processes is a reasonable metric to expose.  IIRC, we expose this in the v2 Json API, so we just need to figure out how to expose this in prometheus format.

**Comment by pnagral** [comment]
I have prometheus container that's collecting data from cadvisor. In a given container that cadvisor is monitoring, I have several processes running. What query I can use to display memory used by each process inside a given container?

**Comment by dashpole** [comment]
looks like this was fixed in #2069.

@pnagral, [ProcessInfo](https://github.com/google/cadvisor/blob/master/info/v2/container.go#L244) should be available at `/api/v2.0/ps`

**Comment by pnagral** [comment]
Thanks @dashpole

**Comment by dashpole** [comment]
I think #1616 is about custom application metrics, not per-process metrics.

**Comment by pnagral** [comment]
Hello @dashpole 

https://github.com/google/cadvisor/issues/1616 talks about appending application metrics to /metrics so that prometheus can read. If this is already supported, I'll just need documentation on how to achieve that.

**Comment by dashpole** [comment]
It isn't supported right now, as no one ever implemented it.
