### ISSUE TITLE
getting container labels using cAdvisor

### ISSUE THREAD

**Issue by shikhasriva** [google/cadvisor#1996]
I am looking at reading container labels via cAdvisor apis. Are there such apis planned  or does it exists and i am missing it...Thanks 
@carrolp

**Comment by dashpole** [comment]
Labels are available in the container spec in the Json API: https://github.com/google/cadvisor/blob/master/info/v1/container.go#L49
Labels are attached to prometheus metrics as prometheus labels.

**Comment by shikhasriva** [comment]
It is, but not exposed via cAdvisor. I am looking fior a way to read labels for all container running in my K8 cluster

**Comment by dashpole** [comment]
Ah, I see.  Prometheus performs poorly with very large numbers of labels, which we often get with adding container labels.  I would recommend running [cAdvisor as a daemonset](https://github.com/google/cadvisor/tree/master/deploy/kubernetes) if you need this functionality.  The cAdvisor port is disabled in 1.11 anyways and will be removed entirely in 1.12.

I believe its also possible to get this information using [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) from [here](https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/collectors/pod.go#L65).

**Comment by shikhasriva** [comment]
Thanks @dashpole
