### ISSUE TITLE
Cadvisor behind reverse proxy does not work due to initial redirection to "/containers/"

### ISSUE THREAD

**Issue by sbakir** [google/cadvisor#2018]
I checked issue history and it seems that when reverse proxying via Host:Port/CadvisorAppName/ initial redirection replace "CadvisorAppName" with "/containers/" because it is given as absolute path . Is there any information regarding this topic?

**Comment by sbakir** [comment]
Thanks @tghosgor  for the fix.

**Comment by davidnewhall** [comment]
I'm leaving a comment here since this is the first hit when googling "cadvisor reverse proxy." See this Issue: https://github.com/google/cadvisor/issues/1587
