### ISSUE TITLE
Remote Docker Host Monitoring using API

### ISSUE THREAD

**Issue by aviratna** [google/cadvisor#2065]
Hi,

I wanted to check if cAdvisor supports monitoring of remote docker host using API.
I am running cAdvisor in container in another host and I am trying to monitor the docker host which is remote using API. cAdvisor is not running on docker host.

Command to start the cAdvisor:
 cadvisor -docker="https://Remote Docker Host:2376" -log_dir="/home" -logtostderr -v=5 -docker_only=true -enable_load_reader=true -docker-tls=true -docker-tls-cert="/cert.pem" -docker-tls-key="/key.pem" -docker-tls-ca="/ca.pem"

cAdvisor is running and I am able to see the UI with dashboard.
It will shows the list of docker images running on remote docker host
Number of Images
Number of containers
Docker Host version and other details.

However it doesn't display the list of containers running on remote docker host and 

http://cadvisor IP:8080/api/v2.0/ps
Error:
500 Internal Server Error
process listing failed: failed to execute "ps" command: exit status 1

I verified the response of curl https://Docker remote host:2376/v1.24/containers/json?all
It returns the list of containers in Json format.

Also verified
docker -H tcp://docker remote host:2375 ps
It returns the list of containers.

Can you please confirm if cAdvisor supports remote monitoring or its bug.

**Comment by dashpole** [comment]
cAdvisor needs access to the host's filesystem (at minimum /sys/fs/cgroup/) in order to provide container metrics.  I don't know of a way to do that remotely.

**Comment by aviratna** [comment]
@dashpole Hi David, Thanks for your response. I just wanted to check if there is any plan to get the container details and related metrics using API instead of dependency on host filesystem in future which will be more scalable. The reason I am asking is there are container solution which doesn't run directly on Host. e.g. VMWare Integrated Containers.

**Comment by dashpole** [comment]
There isn't a plan to do so.  The general plan within the kubernetes community is to encourage container runtimes themselves to produce container metrics to make the metrics pipeline simpler and more direct.
