### ISSUE TITLE
can cadvisor collect some kernel events?

### ISSUE THREAD

**Issue by knightXun** [google/cadvisor#2067]
We found cadvisor may be blind for some bad kernel events.for example, if a filesystem is down, cadvisor will not detect it. kubelet which is cadvisor's upstream, may just down without any warnning events.I think cadvisor can find a solutions for this.

**Comment by dashpole** [comment]
If you are using kubernetes, I would highly recommend running the Node Problem Detector, which is purpose-built for collecting kernel events: https://github.com/kubernetes/node-problem-detector#node-problem-detector
