### ISSUE TITLE
The file system data returned using cadvisor's `/api/v1.2/docker` interface is inconsistent with executing `docker ps -s` command

### ISSUE THREAD

**Issue by Lynzabo** [google/cadvisor#2068]
Execute the `docker ps -s` command to get the container information as follows:
```shell
lynzabo@ubuntu:~$ docker ps -s
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                    NAMES               SIZE
0a8859982d26        nginx                    "nginx -g 'daemon of…"   10 minutes ago      Up 10 minutes       80/tcp                   test-df             2B (virtual 109MB)
12d9cddd8571        google/cadvisor:latest   "/usr/bin/cadvisor -…"   4 days ago          Up 22 minutes       0.0.0.0:8080->8080/tcp   cadvisor            0B (virtual 62.2MB)
lynzabo@ubuntu:~$
```

Execute the `/api/v1.2/docker` interface of the cadvisor, where the obtained container occupies the disk size and the `docker ps -s` command does not correspond.

```json
{
  "/docker/0a8859982d261d379cd6e8b40087c2870d17876de7b141a0e2a53485f9963cca": {
    "id": "0a8859982d261d379cd6e8b40087c2870d17876de7b141a0e2a53485f9963cca",
    ...
    "stats": [
      {
        ...
        "filesystem": [
          {
            "device": "/dev/sda1",
            "type": "vfs",
            "capacity": 103441399808,
            "usage": 81920,
            "base_usage": 45056,
            "available": 0,
            "has_inodes": false,
            "inodes": 11,
            "inodes_free": 0,
            "reads_completed": 0,
            "reads_merged": 0,
            "sectors_read": 0,
            "read_time": 0,
            "writes_completed": 0,
            "writes_merged": 0,
            "sectors_written": 0,
            "write_time": 0,
            "io_in_progress": 0,
            "io_time": 0,
            "weighted_io_time": 0
          }
        ]
      },
      ...
    ]
  }
  ...
}
```
What is the reason for this?

**Comment by dashpole** [comment]
what version of cAdvisor is this?

**Comment by dashpole** [comment]
Can you run a quick experiment for me?  Run a container (busybox or some basic image) with the command, and show me the same stuff as the original post:
`i=0; while [ $i -lt 100 ]; do dd if=/dev/urandom of=file${i} bs=1048576 count=1 2>/dev/null; i=$(($i+1)); done; while true; do sleep 5; done`

That should write almost exactly 100 MiB to the container's writable layer.  The biggest problem for me is that I'm not really sure what docker's definition of disk space used includes...  But I can at least check and make sure cAdvisor is returning the correct value.

**Comment by Lynzabo** [comment]
@dashpole The disk data returned by the cadvisor interface looks more like the container writable layer size. In fact, I need to get the sum of the data of all layers. Because some basic images will be very large.

**Comment by dashpole** [comment]
The reason we didn't decide to include that in our metric is because images can be shared.  I.E. you wouldn't be able to sum over container's disk space to get aggregate usage.  We do have basic image information from this API: https://github.com/google/cadvisor/blob/master/info/v1/docker.go#L32.  I havent been able to figure out where we serve it outside of the UI yet though.

**Comment by Lynzabo** [comment]
@dashpole Thank you very much!
