### ISSUE TITLE
Application Metrics to Graphite

### ISSUE THREAD

**Issue by mtt-g** [google/cadvisor#2087]
Hi,

I've configured cAdvisor to gather application metrics from an endpoint using the details here:

https://github.com/google/cadvisor/blob/master/docs/application_metrics.md

I can see the metrics are being gathered by querying the cAdvisor App Metrics endpoint - so far so good. I have cAdvisor configured to pass metrics to the Graphite using the statsd driver but I'm not seeing any of the application metrics in Graphite.

This is the configuration I am using to test with:
```
docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:ro \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/dev/disk/:/dev/disk:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest \
  -storage_driver=statsd \
  -storage_driver_host=graphite.example.net:8125 \
  -storage_driver_db=docker_node_001
```

I wondered if someone would be able to confirm that custom application metrics should be being passed via the statsd driver and onwards to Graphite in the same way as the container level metrics are? Should this happen automatically or do I have to explicitly ask cAdvisor to forward on these metrics?

Any assistance would be appreciated.

Matt.

**Comment by dashpole** [comment]
It probably just isn't implemented.  Custom metrics are not very widely used, and the combination of custom + graphite may not have been tried yet.  Feel free to add it here: https://github.com/google/cadvisor/blob/master/storage/statsd/statsd.go
