### ISSUE TITLE
import cadvisor metrics from external VM to prometheus running on k8

### ISSUE THREAD

**Issue by akramwaseem** [google/cadvisor#2088]
Hi, 
This is a question not an issue.
We can use node_exporter to run on external machines and allow prometheus to scrape the metrics running on kubernetes.
Can we do the same using cadvisor ??
Since node exporter only scrapes machines metrics but not the container.
It would be great if I can find some info on how to do it.
I tried the same as node_exporter by running it on a VM as docker container and defining endpoints and service on the kubernetes side, Which works well for node_exporter but not for the cadvisor.

Let me know how  it can be done.

**Comment by dashpole** [comment]
I'm not sure I understand... What do you mean by "external machines" or "metrics running on kubernetes"?  You could run cAdvisor as a daemonset, if that is what you are trying to do: https://github.com/google/cadvisor/tree/master/deploy/kubernetes#cadvisor-kubernetes-daemonset

**Comment by akramwaseem** [comment]
@dashpole  -- This is for standalone VMs which are not under Kubernetes.
Sorry for the late rply.

**Comment by dashpole** [comment]
cAdvisor can be run on non-kubernetes VMs.  See the [standalone](https://github.com/google/cadvisor/blob/master/docs/running.md#standalone) running docs.

**Comment by akramwaseem** [comment]
@dashpole -- Thanks, will try it.
