### ISSUE TITLE
cadvisor complie error

### ISSUE THREAD

**Issue by WanLinghao** [google/cadvisor#2100]
I try complie cadvisor directed by https://github.com/google/cadvisor/blob/master/docs/development/build.md
And error happens like:
```
$ make build
>> building assets
>> building binaries
>> building cadvisor
# github.com/google/cadvisor
/home/wlh/mywork/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-build911679512/b001/exe/a.out: final close failed: Invalid operation
collect2: error: ld returned 1 exit status

Makefile:42: recipe for target 'build' failed
make: *** [build] Error 2
```

go version:
`go version go1.11.2 linux/amd64`

--------------------------------------------------------
gcc version:
```
gcc (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413
Copyright (C) 2015 Free Software Foundation, Inc.
```
--------------------------------------------------------
OS version:
`ubuntu 16.04`

**Comment by dashpole** [comment]
my best guess is that you need to install gcc.

**Comment by WanLinghao** [comment]
@dashpole upgrade gcc solve my problem! Now the gcc version is:
`gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609`
Thanks!
