### ISSUE TITLE
Does cadvisor work with unified cgroup?

### ISSUE THREAD

**Issue by keepclean** [google/cadvisor#2105]
Hello!

When I tried launch cadvisor on machine with kernel version 4.14.59 and kernel options 
` ... cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1 ...` 

I found on cadvisor's logs messages like:

`Nov 23 08:11:45 <redacted> cadvisor[124466]: I1123 08:11:45.689071  124466 storagedriver.go:50] Caching stats in memory for 2m0s
Nov 23 08:11:45 <redacted> cadvisor[124466]: F1123 08:11:45.689216  124466 cadvisor.go:137] Failed to create a Container Manager: mountpoint for cpu not found`

**Comment by bobrik** [comment]
Looks like there's some progress: #2309.

**Comment by AkihiroSuda** [comment]
`setMemoryStats()` still needs to be updated to support v2.
https://github.com/google/cadvisor/blob/d16bbe88c62c5e111dc476d8bf5fa84a4350532c/container/libcontainer/handler.go#L706

cc @giuseppe

**Comment by giuseppe** [comment]
I've opened another PR to take care of some other issues on cgroup v2: https://github.com/google/cadvisor/pull/2469

@AkihiroSuda are there new stats for cgroup v2 that weren't present when I've first added it?

**Comment by AkihiroSuda** [comment]
The stats file is just incompatible across v1 and v2. e.g. `"total_inactive_file"` doesn't exist on v2.

**Comment by giuseppe** [comment]
> The stats file is just incompatible across v1 and v2. e.g. `"total_inactive_file"` doesn't exist on v2.

but on cgroup v2 the `total_inactive_file` will not be found in the `s.MemoryStats.Stats` map and it will be ignored.

I think leaving them not set is fine.  Do you think we need a different handling for the stats that don't exist on cgroup v2?

**Comment by AkihiroSuda** [comment]
On v2 we should subtract `inactive_file` (rather than `total_inactive_file`) from workingset
https://github.com/google/cadvisor/blob/d16bbe88c62c5e111dc476d8bf5fa84a4350532c/container/libcontainer/handler.go#L732-L738

**Comment by giuseppe** [comment]
> On v2 we should subtract `inactive_file` (rather than `total_inactive_file`) from workingset

thanks, does https://github.com/google/cadvisor/pull/2469/commits/3074667d91b53af25915c921bef892474db34b10 look good to you?

**Comment by AkihiroSuda** [comment]
thanks, looks good

**Comment by eero-t** [comment]
Are there still remaining issues or can this be closed?

**Comment by yriveiro** [comment]
I'm still having "mountpoint for cpu not found" error using version `0.47.2` on Ubuntu 23.04

**Comment by iwankgb** [comment]
I can't replicate your problem, @yriveiro:
```
iwan@ubuntu:~$ cat /etc/debian_version 
bookworm/sid
iwan@ubuntu:~$ uname -a
Linux ubuntu 6.2.0-27-generic #28-Ubuntu SMP PREEMPT_DYNAMIC Wed Jul 12 22:39:51 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
iwan@ubuntu:~$ sudo docker run -ti -v /:/rootfs:ro -v /sys:/sys:ro -v /var/run:/var/run:rw -p28080:8080 gcr.io/cadvisor/cadvisor:v0.47.2
W0820 16:01:14.827527       1 machine_libipmctl.go:64] There are no NVM devices!
W0820 16:01:14.833439       1 manager.go:286] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory
```

**Comment by iwankgb** [comment]
Verified on Ubuntu 23.04 running with a little help from Qemu. No error is reported and statistics are displayed as expected.

**Comment by yriveiro** [comment]
Hi @iwankgb you are running the command with docker, I don't have docker, I'm using rootless nerdctl, basically you ran:

`sudo docker run -ti -v /:/rootfs:ro -v /sys:/sys:ro -v /var/run:/var/run:rw -p28080:8080 gcr.io/cadvisor/cadvisor:v0.47.2`

In my case would be

`nerdctl run -ti -v /:/rootfs:ro -v /sys:/sys:ro -v /var/run:/var/run:rw -p28080:8080 gcr.io/cadvisor/cadvisor:v0.47.2`

**Comment by iwankgb** [comment]
If docker works while nerdctl/containerd don't then I think that problem might not be related to cAdvisor at all.

**Comment by iwankgb** [comment]
Works for me:
```
iwan@ubuntu:~/nerdctl$ ./_output/nerdctl run -ti -v /:/rootfs:ro -v /sys:/sys:ro -v /var/run:/var/run:rw -p28080:8080 gcr.io/cadvisor/cadvisor:v0.47.2
W0821 14:58:32.210803       1 machine_libipmctl.go:64] There are no NVM devices!
E0821 14:58:32.212867       1 info.go:119] Failed to get system UUID: open /etc/machine-id: no such file or directory
W0821 14:58:32.215619       1 manager.go:286] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory
^CI0821 14:58:42.711114       1 manager.go:1176] Exiting thread watching subcontainers
I0821 14:58:42.711188       1 manager.go:401] Exiting global housekeeping thread
I0821 14:58:42.711464       1 cadvisor.go:210] Exiting given signal: interrupt
iwan@ubuntu:~/nerdctl$ ./_output/nerdctl --version
nerdctl version 1.5.0-50-g76e0211
```

**Comment by yriveiro** [comment]
Well, that is prof the problem is on my side, what version of `nerdctl` are you using? Did you install it on `.local/bin` as the documentation says and run the rootless script?
