### ISSUE TITLE
Timestamp gap between cadvisor and prometheus

### ISSUE THREAD

**Issue by Betula-L** [google/cadvisor#2123]
For `type Counter` metrics, exact timestamp is essential for calculating rate of those metrics.

Now, **CAdvisor do not expose `Prometheus Counter metrics` properly.** 

**CAdvisor should expose `Prometheus Counter metrics` with timestamp as [documentation](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example)**

**Expected /metrics:**
`container_cpu_system_seconds_total{container_name="",id="/kubepods",image="",name="",namespace="",pod_name=""} 6.21201942e+06 1395066363000`
**Current  /metrics:**
`container_cpu_system_seconds_total{container_name="",id="/kubepods",image="",name="",namespace="",pod_name=""} 6.21201942e+06`
is equal to
`container_cpu_system_seconds_total{container_name="",id="/kubepods",image="",name="",namespace="",pod_name=""} 6.21201942e+06 time.Now()`
**Why?**
By default, the timestamp of metrics in Prometheus is when "Prometheus send Get request to /metrics".

For cadvisor, a metric for Prometheus is produced by three step:
1. scrape metrics by system call - Time A
2. store to cache - Time B
3. get metrics from cache if func `Collector` triggered - Time C

Cadvisor should provide metrics with Time A, but now it provide metrics with Time C.

Eventually, Prometheus users evaluate an error rate if using metrics with this error timestamp. 

**Comparison for timestamp**
- Exact scraped time of cadvisor: `1395066363000 2014/3/17 22:26:3`
- CAdvisor RESTful API exposed timestamp: : `1395066363000 2014/3/17 22:26:3`
- **Prometheus timestamp with current branch:** `1395066395000 2014/3/17 22:26:35` 
- Prometheus expected timestamp: `1395066363000 2014/3/17 22:26:3`

 **Related Issues:**
This is the root cause of https://github.com/google/cadvisor/pull/2028 https://github.com/google/cadvisor/pull/2059

**Version:** release-v0.32 
**Commit:** 8949c822ea91fa6b4996614a5ad6ade840be24ee

**Comment by dashpole** [comment]
great work @Betula-L
