### ISSUE TITLE
cadvisor hung at startup

### ISSUE THREAD

**Issue by GaelPerret** [google/cadvisor#2128]
Today we restarted our monitoring stack in our swarm, and the cadvisor containers cannot complete their startup. The containers are running, but they don't open their /metrics endpoint. Consequently prometheus fails to scrape their metrics
This is very strange as it worked perfectly during months. 

>Docker version: 18.06.1 swarm
Operating System and version: Debian 8.11

This how it is configured:
>  cadvisor:
    image: ${DOCKER_REGISTRY}/prom/cadvisor:v0.27.1
    networks:
      - monitor-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

We also tried different version up to version 0.32.0 but still no luck.

This is the log we get when starting cadvisor:

[logs.txt](https://github.com/google/cadvisor/files/2681070/logs.txt)

It seems it did not reach the following lines that we used to get:
`I1020 00:25:57.207300 00001 manager.go:252] Recovery completed
I1020 00:25:57.233508 00001 cadvisor.go:94] Starting cAdvisor version:
"0.18.0" on port 8080`

Any ideas on how to troubleshoot this issue, or a suggestion of what to try?
Rebboting the nodes or the docker daemon are not really good options here, but if necessary we will do that.

Thanks

**Comment by dashpole** [comment]
> cadvisor.go:94] Starting cAdvisor version: "0.18.0" on port 8080

It looks like you were using a really old version of cAdvisor before.

I don't see anything unusual in the logs...  Is the docker daemon on the node responsive?

**Comment by GaelPerret** [comment]
Right, this is a very old log, but we don't use this version any longer, actually this is the trace that I the cadvisor containers are not reaching, they hang before.

Yes the daemon is responsive. 

I attached more logs with the verbose level = 10 (strangely it seems more verbose than with level = 42)
[logs2.txt](https://github.com/google/cadvisor/files/2690149/logs2.txt)

I got similar logs on all nodes, the last line is "Start housekeeping for container..."

Also, when I remove the lines:
> /sys:/sys:ro

then the cadvisor containers complete their initialization (but no metrics are present).

**Comment by dashpole** [comment]
Based on the log, cAdvisor is hung at the beginning of [createContainer](https://github.com/google/cadvisor/blob/master/manager/manager.go#L948), as the last log was from the previous createContainer call starting container housekeeping in a seperate goroutine.  My best guess is that you are either hanging on connecting to docker, or have deadlock.

**Comment by GaelPerret** [comment]
Thank you, I will restart the daemon in the coming days, let's hope this fix the problem. Do you see anything else that could help to investigate the issue? This is our production environment, so I am sure that docker is working well.

**Comment by GaelPerret** [comment]
Hello, the problem disappears after I restarted the daemon.
I don't know where is the problem, docker or cadisor, and I don't have any releavent logs, so let's close it.
