### ISSUE TITLE
exclude system.slice metrics from being exposed as prometheus metrics

### ISSUE THREAD

**Issue by viberan** [google/cadvisor#2129]
we are using cAdvisor to collect docker container metrics with Prometheus. There are tons of cgroup related metrics being exposed that are not relevant and we want cAdvisor to filter them out
--docker_only flag does not change anything for some reason, we continue to see all /system.slice/* stuff being exposed. After some googling, I came across rawPrefixWhiteList = "/system.slice/kubelet.service, /system.slice/docker.service.." setting #2048 #1926 
But I can not figure out how to use that setting and how it relates to docker_only flag? Could anyone explain it in more details how to use rawPrefixWhiteList? Seems it's not documented anywhere.

**Comment by dashpole** [comment]
`docker_only` makes cAdvisor only collect docker container metrics, and machine level metrics.  We don't actually expose rawPrefisWhiteList as a flag.  We may want to consider consuming this in the kubelet to get that behavior.

**Comment by viberan** [comment]
thanks for your quick response. 
does it mean we should NOT see  /system.slice/* metrics when using docker_only flag? What do you refer to as machine level metrics?

I'm just looking for a way to tell cAdvisor not to collect/expose /system.slice/* metrics as there is noticeable performance impact. We don't use kubernetes

**Comment by dashpole** [comment]
with `docker_only`, you only get cgroup metrics for cgroups that belong to docker containers, e.g. `/kubepods/pod<pod_uid>/<container_id>` will be collected, but `/kubepods/pod<pod_uid>` will not.

Machine metrics are metrics from the `/` cgroup, as well as, for example, disk metrics from filesystems on the node.  We collect these metrics when `--docker_only` is specified even though it isn't a docker container cgroup.

**Comment by viberan** [comment]
so, is there a way not to collect system.slice metrics?

**Comment by lixianyang** [comment]
We don't use kubernetes too, but want to use cadvisor to collect docker container metrics. It collect all cgroup metrics in / , prometheus curl these metrics take a long time.

**Comment by viberan** [comment]
I wanted to elaborate more on our use case for cAdvisor and Prometheus.
We're running fleets of spot instances that come and go many times a day with peak number of 1500-2000 instances at a moment. Each spot instance hosts a dozen of docker containers which are not static either. All in all it is pretty dynamic environment which in turn produces millions of different time series and leads to extremely high cardinality metrics. 
Basically we need just a handful of metrics to monitor CPU and memory usage of every docker container at resolution of every few seconds.
cAdvisor exposes over 2700 time series on every spot instance at any given time. While trying to ingest all of those from every spot into Prometheus, I observed over 400 millions(!) of head time series before it crashed the biggest Prometheus server I could try.
Yes, I can drop the unnecessary metrics at Prometheus side and it does help to get cardinality under control. Still the 2700 time series is over one megabyte of data which Prometheus has difficult time to scrape at high pace. Given there are some 2000 endpoints to scrape, it's a lot of traffic too. It seems there is cpu overhead for collecting un-needed metrics as well.

For the above reasons, it would be helpful to have the option to collect and expose docker related metrics only.

**Comment by viberan** [comment]
@dashpole thanks for taking care of this. Is the pull request #72787 above going to solve the issue when cAdvisor is used outside of kubernetes?

**Comment by dashpole** [comment]
no, but you should be able to use the --docker_only flag if you just want metrics for docker containers.

**Comment by viberan** [comment]
@dashpole at the moment cadvisor with the --docker_only flag collects metrics from the `/system.slice` cgroup which is exactly what we are trying to avoid. Is this behavior going to change?

**Comment by dashpole** [comment]
@viberan that sounds like a bug.  The --docker_only flag should mean you only get docker containers + the `/` (root) container.

**Comment by dashpole** [comment]
can you paste your configuration (flags + cadvisor version) and the prometheus metrics you are getting here?

**Comment by viberan** [comment]
```
  cadvisor:
    image: google/cadvisor:v0.32.0
    network_mode: bridge
    container_name: cadvisor
    ports:
      - 9600:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    command: ["--docker_only=false"]

**Comment by viberan** [comment]
@dashpole not sure whether it's a bug or a feature, what I could understand from the source below, `accept` will always be `true` for default `[]string{"/"}` value of `rawPrefixWhiteList` 

https://github.com/google/cadvisor/blob/150629c099b66e13223ec0601fdf9d49a3282c68/container/raw/factory.go#L70-L75

This would allow all raw cgroups to be always collected, hence there is all that /system.slice/* stuff reported by cAdvisor regardless of -docker_only flag being set.

**Comment by viberan** [comment]
@dashpole  thank you for the #2161

Would you mind to add the ability to white list certain cgroup prefixes via a command line flag - #2164

**Comment by lededje** [comment]
Anyone reading this in current year, the `--docker-only` flag has been removed. Instead use the `raw_cgroup_prefix_whitelist`.

`--raw_cgroup_prefix_whitelist=/docker/` should filter out everything save for docker processes.

**Comment by trallnag** [comment]
@lededje, are you sure? I did not check it myself, but the flag still shows up in the source code https://github.com/google/cadvisor/blob/f17af505243c9f637b49a279f64de70a98edf3a3/container/raw/factory.go#L32
