### ISSUE TITLE
"latest" tag is a year old

### ISSUE THREAD

**Issue by bitglue** [google/cadvisor#2143]
`google/cadvisor:latest`, which the top-level README instructs people to use, hasn't been updated in a year.

**Comment by dashpole** [comment]
I pushed an updated image to dockerhub.  gcr.io/google_containers/cadvisor:latest is in the process of being updated.

**Comment by itsx** [comment]
Currently, `latest` tag is again out of sync with the newest release `v0.33.0`. 

**Dockerhub**:
![cadvisor-tags-dockerhub](https://user-images.githubusercontent.com/15692136/63421025-27eaea00-c408-11e9-86e9-42d81d77f9fa.png)

**Google cloud platform**:
![cadvisor-tags-gcp](https://user-images.githubusercontent.com/15692136/63421043-2caf9e00-c408-11e9-8172-d3c9d2d0c346.png)

**Comment by dashpole** [comment]
We usually only update latest after some soak time to see if any issues arise with the new version.  This was fixed earlier this year.
