### ISSUE TITLE
Cannot make application metrics work

### ISSUE THREAD

**Issue by njouve** [google/cadvisor#2145]
I cannot make application metrics work.
I have a spring app with a prometheus endoint running in docker container that I want to monitor.
My config file is added in the docker image like this in the docker file:

```
ADD cadvisor_caplab_config.json /var/cadvisor/cadvisor_caplab_config.json
LABEL io.cadvisor.metric.prometheus-caplab="/var/cadvisor/cadvisor_caplab_config.json"

```

The file itself contains
```
{
  "endpoint" : "http://localhost:8091/actuator/prometheus"
}
```
When I log into the docker container and run
`curl http://localhost:8091/actuator/prometheus`
I get an output (extract only here)
```
# TYPE jvm_memory_used_bytes gauge
jvm_memory_used_bytes{area="nonheap",id="CodeHeap 'non-nmethods'",instance="1@dfc4e4826aea",} 1274752.0
jvm_memory_used_bytes{area="nonheap",id="Metaspace",instance="1@dfc4e4826aea",} 1.06447624E8
tance="1@dfc4e4826aea",} 7731200.0

```
But cadvisor fails to retrieve app metrics from the container:

`W0115 08:11:34.527426 1 container.go:523] Failed to update stats for container "/docker/dfc4e4826aeaaac332287f44466b3789a2370b8fe79dd6b75ad259a411b72c24": Error 0: Get http://localhost:8091/actuator/prometheus: dial tcp 127.0.0.1:8091: connect: connection refused, continuing to push custom stats`

Why ? I thought that the cadvisor would login to the container and call the endpoint from **within** the container ?

Here is the command line I use to launch cadvisor  (the machine it self runs RHEL 7.5):

`docker run   --volume=/:/rootfs:ro   --volume=/var/run:/var/run:ro   --volume=/sys:/sys:ro   --volume=/var/lib/docker/:/var/lib/docker:ro   --volume=/dev/disk/:/dev/disk:ro   --publish=8083:8080   --detach=true   --name=cadvisor --volume=/cgroup:/cgroup:ro --privileged=true  google/cadvisor:latest`

**Comment by njouve** [comment]
Oh really ? IMHO that makes it very unpractical to use for application metrics, if you have to handle port mappings for all the containers you want to monitor....

**Comment by dashpole** [comment]
Yeah, the feature never left alpha after being introduced a few years ago.

**Comment by njouve** [comment]
Ultimately my goal was to monitor these containerized application metrics with Prometheus. Can you think to any alternative solution for this ?

**Comment by dashpole** [comment]
I generally recommend having the prometheus server scrape your application.  It removes the dependency on cAdvisor, and is generally how prometheus is designed to be used

**Comment by njouve** [comment]
You are right for "pure application metrics" who not depend on the container. But for JVM metrics that are container specific, you have to implement some kind of container discovery. Currently we still use docker swarm (we may switch to Kubernetes in a near future), and container discovery for docker swarm is not available AFAIK...

**Comment by dashpole** [comment]
Maybe try using push instead of pull?  That way only the prometheus server needs to be discoverable...
https://prometheus.io/docs/instrumenting/pushing/

**Comment by njouve** [comment]
Yeah, this was my last resort option. But I will dig this. Thank you for your precious insights and advices. Have a good day. I close the issue

**Comment by sanek9** [comment]
https://github.com/google/cadvisor/issues/1212#issuecomment-287304500
It works for me:
```
{
  "endpoint" : {
    "protocol": "http",
    "port": 9200,
    "path": "/metrics"
  }
}
```
