### ISSUE TITLE
dch-photon cAdvisor Docker driver setup: [Unsupported]

### ISSUE THREAD

**Issue by fontanacalifornia** [google/cadvisor#2173]
I am running cAdvisor on VMware's dch-photon OS and it is not populating container names or images.

DISTRIB_ID="VMware Photon"
DISTRIB_RELEASE="1.0"
DISTRIB_CODENAME=Photon
DISTRIB_DESCRIPTION="VMware Photon 1.0"
NAME="VMware Photon"
VERSION="1.0"
ID=photon
VERSION_ID=1.0
PRETTY_NAME="VMware Photon/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
VMware Photon Linux 1.0
PHOTON_BUILD_NUMBER=62c543d

/validate shows me:

Docker driver setup: [Unsupported]
	Docker setup is invalid: failed to detect Docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

I have tried modifying /usr/lib/systemd/system/docker.service but not sure I have tried it correctly.

[Unit]
Description=Docker Daemon
Documentation=http://docs.docker.com
Wants=network-online.target
After=network-online.target docker-containerd.service
Requires=docker-containerd.service

[Service]
Type=notify
EnvironmentFile=-/etc/default/docker
ExecStart=/usr/bin/docker daemon $DOCKER_OPTS \
          -H unix:///var/run/docker.sock --containerd /run/containerd.sock
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-abnormal
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target

I cannot seem to get past this.

Has anyone else tried this configuration?

**Comment by dashpole** [comment]
You have confirmed docker is running, right?  I.E. `docker ps` works.  I have run into some trouble in the past with docker being run as sudo, but cAdvisor not or vice-versa.  Does `sudo docker ps` also work?

**Comment by fontanacalifornia** [comment]
Thanks for the quick reply.

When running the docker info command from the host directly. I have to specify the following to get it to respond:

"docker -H tcp://[host IP]:2376 --tlsverify --tlscacert=/path/to/ca.pem --tlscert=/path/to/cert.pem --tlskey=/path/to/key.pem info"

It is only listening to 2376 and not 2375 and also when trying the command with the -H I get the following:

"certificate is valid for [network name].localhost., not localhost"

I am guessing I need to tweak cAdvisor to call the docker daemon specifically for these needs but do not know how to do so.

**Comment by dashpole** [comment]
See if any of the docker auth options we have can fix your problem: https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#docker.  Otherwise, you would need to add a new option to cAdvisor to be passed through.

**Comment by fontanacalifornia** [comment]
Is there a way to set the docker= option to a network interface instead of a socket?

If so what would be the format? The same as what we call with "-H tcp://xxx.xxx.xxx.xxx:2376"

I have tried many combinations but can't seem to get it right.

The default socket does not exist on this server. but /var/run/docker/libcontainerd/docker-containerd.sock does exist. I tried using that with no other options, and I get the "Are you trying to connect to a TLS-enabled daemon without TLS?" error.

So I tried that with all the tls options to no success.

Is the tls cert options local to where I am running the Docker command from? Which is my windows workstation.

Please advise.

**Comment by dashpole** [comment]
The tls cert option is local to cAdvisor.  What orchestrator are you using to run the cAdvisor container?  I'm only familiar with kubernetes, which has the concept of a `Secret` to pass that kind of information along with the container.

**Comment by fontanacalifornia** [comment]
Just Docker for now.

So you are saying that I need to include the certificate file in the container itself. I can work with that and let you know how it goes.

Thanks for the update.

**Comment by fontanacalifornia** [comment]
One more question. Do the tls-cert commands take a absolute or relative path, or just a file name and assume a specific location?

**Comment by dashpole** [comment]
I think it should be relative to the cadvisor binary.  Normally, the orchestration layer handles secrets: https://docs.docker.com/engine/swarm/secrets/.  I'm not sure what the best practices are for doing this with just docker.

**Comment by fontanacalifornia** [comment]
These should be the certificates used to access the docker host correct?

Just for testing purposes, I am copying the the certificates into the container using a dockerfile/custom image. I just put them in /home and used an absolute path in the tls commands. The weird thing is that the container will launch but not run no matter what I used for the TLS commands.

**Comment by dashpole** [comment]
What do you mean by not run?  Do you still get the tls error?

**Comment by fontanacalifornia** [comment]
The container will not stay running, so I cannot check the validate page for more info.

**Comment by dashpole** [comment]
do you have logs?

**Comment by fontanacalifornia** [comment]
I am sorry to say that I figured it out : )

I ended up just needed to pull the latest vmware/dch-photon image and it now allows for both the network interface and /var/run/docker sockets to run simultaneously. 

Thanks for all your guidance. I learned quite a bit along the way.
