### ISSUE TITLE
set alerts for breaching cpu usage

### ISSUE THREAD

**Issue by amitlodhiIT** [google/cadvisor#2178]
How to set the alerts for summary data ie. aggregated by minutes, hours and days  If breaching.

**Comment by dashpole** [comment]
alerting is done upstream from cAdvisor.  cAdvisor just provides the metrics.  For example, if you are using cAdvisor's prometheus endpoint, you can configure the prometheus alertmanager to alert on metrics provided by cAdvisor

**Comment by amitlodhiIT** [comment]
Thank you for your answer. I am now clear about this. :+1:
