### ISSUE TITLE
get subcontainer name using api

### ISSUE THREAD

**Issue by amitlodhiIT** [google/cadvisor#2179]
Hi, I am using this api "http://127.0.0.1:8080/api/v2.1/summary?type=docker&recursive=true" to get the summary data but in this response I am not able to get the subcontainer  name, instead of this I am getting subcontainer id( /docker/7e0f395487c38f4642b366e27105a5d816bf8ce2e26bb531e46cfff9b789114f). How to get the name of subconatiner.

**Comment by dashpole** [comment]
It doesn't look like you can get the name of the container with that query, as it only returns a single "name" identifier for the container using that API: https://github.com/google/cadvisor/blob/master/manager/manager.go#L486.  Other APIs which return [containerInfo](https://github.com/google/cadvisor/blob/master/info/v2/container.go#L59) will have multiple identifiers, including the container name.

**Comment by amitlodhiIT** [comment]
I understand but is there any api which directly give the name of container/subcontainer?

**Comment by dashpole** [comment]
Try `/api/v1.3/subcontainers`, which has pretty much everything.

**Comment by amitlodhiIT** [comment]
It worked for me. Thanks @dashpole
