### ISSUE TITLE
Panic in v0.33.0

### ISSUE THREAD

**Issue by blakebarnett** [google/cadvisor#2181]
Kubernetes 1.11.5 (GKE)

Startup options

```
       '--housekeeping_interval=10s',
       '--max_housekeeping_interval=15s',
       '--event_storage_event_limit=default=0',
       '--event_storage_age_limit=default=0',
       '--disable_metrics=tcp,udp',
       '--docker_only=true',
       '--raw_cgroup_prefix_whitelist=kubepods',
```

panics immediately:
```
cadvisor-mf2vd cadvisor panic: duplicate label names
cadvisor-mf2vd cadvisor
cadvisor-mf2vd cadvisor goroutine 171 [running]:
cadvisor-mf2vd cadvisor github.com/google/cadvisor/vendor/github.com/prometheus/client_golang/prometheus.MustNewConstMetric(0xc0003bb420, 0x2, 0x41d7176cf6000000, 0xc0001e4c00, 0x40, 0x40, 0x40, 0x0)
cadvisor-mf2vd cadvisor 	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/vendor/github.com/prometheus/client_golang/prometheus/value.go:102 +0xb0
cadvisor-mf2vd cadvisor github.com/google/cadvisor/metrics.(*PrometheusCollector).collectContainersInfo(0xc00018c370, 0xc000a1c060)
cadvisor-mf2vd cadvisor 	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/metrics/prometheus.go:1165 +0x581
cadvisor-mf2vd cadvisor github.com/google/cadvisor/metrics.(*PrometheusCollector).Collect(0xc00018c370, 0xc000a1c060)
cadvisor-mf2vd cadvisor 	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/metrics/prometheus.go:1078 +0x89
cadvisor-mf2vd cadvisor github.com/google/cadvisor/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
cadvisor-mf2vd cadvisor 	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/vendor/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x193
cadvisor-mf2vd cadvisor created by github.com/google/cadvisor/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
cadvisor-mf2vd cadvisor 	/usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/vendor/github.com/prometheus/client_golang/prometheus/registry.go:5
```

**Comment by blakebarnett** [comment]
Possibly related to this? https://github.com/google/cadvisor/pull/2124

**Comment by dashpole** [comment]
Just to confirm, this doesn't happen on v0.33.0?

**Comment by blakebarnett** [comment]
Correct, that's what we were running before (minus the cgroups whitelist)

**Comment by Betula-L** [comment]
@blakebarnett Excuse me, i did not reproduce this panic in Kubernetes 1.11.5. Would you specify more details about it?

**Comment by dashpole** [comment]
I think he is running cAdvisor as a pod in kubernetes, not using the cAdvisor built-in to the kubelet.

**Comment by blakebarnett** [comment]
Just to verify it had nothing to do with cluster version I tested it on both `1.10.9-gke.5` and `1.11.7-gke.6`.  Here's the entire DaemonSet yaml that I'm trying this with: https://gist.github.com/blakebarnett/68e3b35754a683173e43cc3e4975aeda

Initially I thought this was happening on all replicas, but I've just verified it only happens on 1 node. I'll debug further and find the culprit.

@dashpole is correct, this is running as a separate DaemonSet in kubernetes, because we need some of the additional metrics that are not available in the kubelet version.

**Comment by blakebarnett** [comment]
I moved a few pods off the node, and the problem went away. There was nothing special about any of them, and now I can't reproduce it by running similar pods on that same node again.  I'll close this until I can track down more specifics.

**Comment by blakebarnett** [comment]
I was able to track this down to the annotations on kubernetes pods. We had a these two annotations on 2 different pods:

`"annotation.config-checksum"` and `"annotation.config_checksum"`

After sanitizeLabelName() https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L1243 runs they conflict. I imagine this case is fairly easy to bump into given how arbitrary annotations can be. 

Should I submit a PR to prevent the clash after sanitization?

**Comment by blakebarnett** [comment]
Our work-around for now is to use `--store_container_labels=false` with `--whitelisted_container_labels=` of the few we know we need, maybe this should just be recommended as a default when running in kubernetes.

**Comment by dashpole** [comment]
I would happily review a PR to fix it.  Yeah, this is something we should add to the kubernetes yaml...
