### ISSUE TITLE
Requesting Clarification about CPU Usage

### ISSUE THREAD

**Issue by DevinCampbell** [google/cadvisor#2182]
I am attempting to set up a graph in Grafana showing total CPU usage by container over time. I currently have InfluxDB, cAdvisor, and Grafana all running in Docker containers. When I look in cAdvisor's web GUI the y-axis shows "Cores" but when I go into Grafana and choose the metric "cpu_usage_total" it is showing significantly larger numbers, so there must be something I'm not understanding here about how CPU usage is measured by cAdvisor. I have attempted to look in the documentation in google/cadvisor/docs but I'm not seeing an explanation for this.

**Comment by dashpole** [comment]
In the [influxdb storage plugin](https://github.com/google/cadvisor/blob/master/storage/influxdb/influxdb.go#L179), it sends "cpu_usage_total" as the value of stats.CPU.Usage.Total, which is in nanoseconds according to [the v1 api](https://github.com/google/cadvisor/blob/master/info/v1/container.go#L265)

**Comment by DevinCampbell** [comment]
Ok, so stats.CPU.Usage.Total measures CPU usage by the amount of time in nanoseconds each container utilizes the CPU?

**Comment by dashpole** [comment]
yeah, it is a cumulative metric, so it is the total number of nanosecond-cores a container has utilized since its creation.
