### ISSUE TITLE
kubelet cadvisor (default cadvisor running in k8s cluster) not giving "container_cpu_load_average"

### ISSUE THREAD

**Issue by vivekj11** [google/cadvisor#2185]
I have configured Prometheus monitoring for my k8s cluster where Prometheus was able to detect cadvisor on the basis of service discovery.
 I have noticed that it is not giving any value ( Zero ) for container_cpu_load_average_10s.

After some google search, I found that we need to enable load_reader in cadvisor to get this details. However, I am not sure how  can I do so in current scenario. 
Which file should I edit or how can I apply this flag to my cadvisor which is already running in my k8s cluster.

**Comment by dashpole** [comment]
The kubelet [re-registers the `--enable_load_reader flag`](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/globalflags_linux.go#L63) as part if it's flagset

**Comment by dashpole** [comment]
So to answer your question, it depends on how you or your provider has set up your cluster.  For GKE, for example, the options are set at `/etc/default/kubelet`, but that might change if you used something like KOPS or something else

**Comment by vivekj11** [comment]
I missed to inform here, the above solution worked.
I updated my kubelet config file with  "--enable-load-reader=true" and then restarted the service.
