### ISSUE TITLE
How to get hostname inside a docker container on a vm ?

### ISSUE THREAD

**Issue by jinxiao** [google/cadvisor#2187]
i am running cadvisor on a vm by this script 
```
docker run \
  --hostname=dev \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:ro \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/dev/disk/:/dev/disk:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:v0.33.0
```
but when i get info from "/metrics" there is no hostname defined , data looks like this 

```
# HELP cadvisor_version_info A metric with a constant '1' value labeled by kernel version, OS version, docker version, cadvisor version & cadvisor revision.
# TYPE cadvisor_version_info gauge
cadvisor_version_info{cadvisorRevision="511ec9ef",cadvisorVersion="v0.33.0",dockerVersion="17.03.0-ce",kernelVersion="4.4.0-139-generic",osVersion="Alpine Linux v3.8"} 1
# HELP container_cpu_load_average_10s Value of container cpu load average over the last 10 seconds.
# TYPE container_cpu_load_average_10s gauge
container_cpu_load_average_10s{container_label_aliyun_log_logtail="",container_label_build_time="",container_label_com_docker_compose_config_hash="",container_label_com_docker_compose_container_number="",container_label_com_docker_compose_oneoff="",container_label_com_docker_compose_project="",container_label_com_docker_compose_service="",container_label_com_docker_compose_version="",container_label_maintainer="",container_label_org_label_schema_build_date="",container_label_org_label_schema_license="",container_label_org_label_schema_name="",container_label_org_label_schema_schema_version="",container_label_org_label_schema_vendor="",container_label_proj="",container_label_version="",id="/",image="",name=""} 0 1551865860627
```
so , how can i get machine column or hostname ?

**Comment by dashpole** [comment]
What is querying cAdvisor?  Usually the aggregator (e.g. prometheus server) adds information about the thing being queried, such as host ip.  cAdvisor does have a machine api `/api/v1.3/machine` that provides some information, such as cloud provider and instance id.

**Comment by jinxiao** [comment]
> What is querying cAdvisor? Usually the aggregator (e.g. prometheus server) adds information about the thing being queried, such as host ip. cAdvisor does have a machine api `/api/v1.3/machine` that provides some information, such as cloud provider and instance id.

yes , i'm using prometheus ,but i only got a instance column which showed the ip:port of cadvisor , but no machine column

**Comment by jinxiao** [comment]
> What is querying cAdvisor? Usually the aggregator (e.g. prometheus server) adds information about the thing being queried, such as host ip. cAdvisor does have a machine api `/api/v1.3/machine` that provides some information, such as cloud provider and instance id.

i tried this api path , but no hostname , only machine-id showed

**Comment by jinxiao** [comment]
i think this is the limitation of cadvisor. if i am using static configs , nothing about hostname would be shown. i will choose dns_sd_configs instead, dns-name which is hostname fqdn will be showed , then i can relabel instance with this dns-name , thank u all
