### ISSUE TITLE
Grafana CPU Graph showing over 200,000% 

### ISSUE THREAD

**Issue by daviddavis83** [google/cadvisor#2192]
I am having a strange issue where my cpu graph that get's the cpu percentage for all cores spikes from normal to percentages above 200,000. I believe the issue revolves around missing values from Influxdb since I am using a non_negative_derivative function to convert from jiffies to cpu%. The strange part is a I have single core graphs over the same time period that don't repeat this behavior so it only happens when trying to aggregate all the cores.

**Comment by daviddavis83** [comment]
Grafana Query to influxdb 
`SELECT non_negative_derivative(mean("value"), 1s) FROM "autogen"."cpu_value" WHERE "host" =~ /^$host$/ AND "type_instance" = 'system' AND $timeFilter GROUP BY time(10s) fill(null)`

**Comment by daviddavis83** [comment]
Update: I found that there is missing data in the database. since the data is null the non negative derivative function is making the cpu value spike exponentially. I have the function fill(null) in the query but it doesn't seem to fix the issue.

**Comment by dashpole** [comment]
I'm not very familiar with influxdb at all.  I'll mark this as help wanted, but I would recommend looking for influxdb expertise elsewhere.  I'm happy to answer questions about cAdvisor if any come up.

**Comment by gtoews** [comment]
I believe I'm experiencing the same issue.

This query:

`"SELECT non_negative_derivative(mean("value"), 10s) FROM "cpu_value" WHERE ("host" =~ /^bch-test-db-vm0$/ AND "type_instance" = 'user') AND time >= 1593467658360ms and time <= 1593468120481ms GROUP BY time(10s), "host""`

Results in: 
<img width="1308" alt="Screen Shot 2020-06-29 at 3 23 25 PM" src="https://user-images.githubusercontent.com/28987267/86061995-a1863800-ba1c-11ea-86be-831dcc0bbc6a.png">

Although inspecting the raw data with this query:

`select value from /cpu/ where "host" =~ /bch-test-db-vm0/ and "type_instance" = 'user' and time >= 1593467658360ms and time <= 1593468120481ms`

shows all samples in range (for example):  

`1593468105569709000	1.5571186e+07
1593468105569714000	1.5318664e+07
1593468105569716000	2.1717646e+07
1593468105569717000		1.6184352e+07
1593468105569718000	1.5396037e+07
1593468105569719000	1.5095332e+07
1593468105569720000	2.2041922e+07
1593468105569722000	1.5995204e+07
1593468105569724000	1.546887e+07
1593468105569727000	1.4741964e+07
`

Is this some kind of aliasing issue where the sample rates don't match?

Is there anyway to discard outliers?
