### ISSUE TITLE
How to create and configure the cAdvisor for metric data

### ISSUE THREAD

**Issue by amitlodhiIT** [google/cadvisor#2195]
I am new in cAdvisor. I don't know how to configure for metrics data( url: [metrics_url](http://127.0.0.1:8080/metrics)).  Do cAdvisor collects and showing in cAdvisors UI just like promotheus by taking some queries.? or cAdvisors need some monitoring system like promotheus? If no, then can anyone provide some docs . 

url : [metrics_url](http://127.0.0.1:8080/metrics)
Sample data: 
```
# HELP cadvisor_version_info A metric with a constant '1' value labeled by kernel version, OS version, docker version, cadvisor version & cadvisor revision.
# TYPE cadvisor_version_info gauge
cadvisor_version_info{cadvisorRevision="8949c822",cadvisorVersion="v0.32.0",dockerVersion="18.09.1",kernelVersion="4.4.0-142-generic",osVersion="Alpine Linux v3.7"} 1
# HELP container_cpu_load_average_10s Value of container cpu load average over the last 10 seconds.
# TYPE container_cpu_load_average_10s gauge
container_cpu_load_average_10s{id="/",image="",name=""} 0
container_cpu_load_average_10s{id="/docker",image="",name=""} 0
container_cpu_load_average_10s{id="/docker/036eaab4566a149432c46bd5db6649601226825a345dcc4a70e00fdca9ec2cde",image="jenkins",name="jenkins"} 0
container_cpu_load_average_10s{id="/docker/220dba0ef0087b2c10a6782d6ea67419c2a8f29264662ebfcfb2af5bdc4434e6",image="selenium/hub:2.53.0",name="selenium-hub"} 0
container_cpu_load_average_10s{id="/docker/57d8faa0a4cbf92eede9bed6a280f935daf5cbb41a0091982d28b504f1a6dd3c",image="google/cadvisor:latest",name="cadvisor"} 0
container_cpu_load_average_10s{id="/init.scope",image="",name=""} 0
container_cpu_load_average_10s{id="/system.slice",image="",name=""} 0
container_cpu_load_average_10s{id="/system.slice/ModemManager.service",image="",name=""} 0
container_cpu_load_average_10s{id="/system.slice/NetworkManager-wait-online.service",image="",name=""} 0
```

**Comment by dashpole** [comment]
The cAdvisor UI uses the json endpoint (/api/v1.3/subcontainers, for example) to supply data for the dashboards.  cAdvisor itself supports many ways of exporting metrics, including json, prometheus, influxdb, elasticsearch, etc.  Check out the [exporting stats](https://github.com/google/cadvisor#exporting-stats) section of the README.  If you are using the `/metrics` prometheus endpoint, you can use prometheus server + grafana to collect, store, and graph data from cAdvisor.

**Comment by amitlodhiIT** [comment]
Then how to get which services is running in dockers/docker_containers?

**Comment by dashpole** [comment]
It is definitely possible.  I recommend looking at what /api/v1.3/subcontainers returns for the full set of information.  You would have to parse it yourself if you don't use a metrics backend.

**Comment by dummyMaxy** [comment]
Hi, kubelet also use the data that cadivsor provided , what kind of format data that cadvisor expose 
 to kubelet?  
BTW, is there cadivsor written in java ?

**Comment by dashpole** [comment]
cAdvisor is only written in golang, i'm afraid.  The kubelet uses cadvisor's [v2 container api](https://github.com/google/cadvisor/blob/master/info/v2/container.go#L59).

The original question has been answered, so I'll close this for now.  Feel free to open new bugs with new questions.
