### ISSUE TITLE
don't assign to port

### ISSUE THREAD

**Issue by masikmos** [google/cadvisor#2197]
Its OMFG!!!

I run in docker and on host

cadvisor don't assign to ports!

only on one server

`cat /etc/issue
Ubuntu 16.04.2 LTS \n \l`

`sudo ./cadvisor --logtostderr --v=999 --port 8080 --listen_ip 127.0.0.1
I0314 19:43:40.479980   19140 storagedriver.go:50] Caching stats in memory for 2m0s
I0314 19:43:40.480442   19140 manager.go:156] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct/user.slice"
I0314 19:43:40.533337   19140 manager.go:167] Rkt not connected: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: connect: connection refused
I0314 19:43:40.533529   19140 manager.go:178] CRI-O not connected: Get http://%2Fvar%2Frun%2Fcrio%2Fcrio.sock/info: dial unix /var/run/crio/crio.sock: connect: no such file or directory
I0314 19:43:40.580872   19140 fs.go:144] Filesystem UUIDs: map[31e2b854-803d-4f7d-bd71-1df4814ff90b:/dev/md1 549af840-9860-4c94-ba12-dbed77a0ab8a:/dev/md2 737b28c9-0120-4951-9df9-15e77eb3e4fe:/dev/md0]
I0314 19:43:40.580951   19140 fs.go:145] Filesystem partitions: map[shm:{mountpoint:/var/lib/docker/containers/719dfc5309306d28e0093da141c50701fde1cf532d60c4fb4c6796f36ef69405/mounts/shm major:0 minor:42 fsType:tmpfs blockSize:0} tmpfs:{mountpoint:/run major:0 minor:19 fsType:tmpfs blockSize:0} /dev/md2:{mountpoint:/ major:9 minor:2 fsType:ext4 blockSize:0} /dev/md0:{mountpoint:/boot major:9 minor:0 fsType:ext2 blockSize:0}]
I0314 19:43:40.584386   19140 manager.go:231] Machine: {NumCores:8 CpuFrequency:2133000 MemoryCapacity:33726484480 HugePages:[{PageSize:1048576 NumPages:0} {PageSize:2048 NumPages:0}] MachineID:c938304d9255aed5a47124d3595ac10f SystemUUID:B85755E6-211B-12CB-B3D9-0025906589FC BootID:5459d7d0-25ab-4d49-9fe9-cff757ef2618 Filesystems:[{Device:tmpfs DeviceMajor:0 DeviceMinor:19 Capacity:3372650496 Type:vfs Inodes:4117002 HasInodes:true} {Device:/dev/md2 DeviceMajor:9 DeviceMinor:2 Capacity:1936195461120 Type:vfs Inodes:120070144 HasInodes:true} {Device:/dev/md0 DeviceMajor:9 DeviceMinor:0 Capacity:289053696 Type:vfs Inodes:73152 HasInodes:true} {Device:shm DeviceMajor:0 DeviceMinor:42 Capacity:67108864 Type:vfs Inodes:4117002 HasInodes:true}] DiskMap:map[8:32:{Name:sdc Major:8 Minor:32 Size:2000398934016 Scheduler:deadline} 8:48:{Name:sdd Major:8 Minor:48 Size:2000398934016 Scheduler:deadline} 9:0:{Name:md0 Major:9 Minor:0 Size:298516480 Scheduler:none} 9:1:{Name:md1 Major:9 Minor:1 Size:32751222784 Scheduler:none} 9:2:{Name:md2 Major:9 Minor:2 Size:1967196733440 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:2000398934016 Scheduler:deadline} 8:16:{Name:sdb Major:8 Minor:16 Size:2000398934016 Scheduler:deadline}] NetworkDevices:[{Name:enp3s0 MacAddress:00:25:90:65:89:fc Speed:1000 Mtu:1500} {Name:enp4s0 MacAddress:00:25:90:65:89:fd Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:16817246208 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:9 Threads:[2] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:10 Threads:[3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:8388608 Type:Unified Level:3}]} {Id:1 Memory:16909238272 Cores:[{Id:0 Threads:[4] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[5] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:9 Threads:[6] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:10 Threads:[7] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:8388608 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I0314 19:43:40.585818   19140 manager.go:237] Version: {KernelVersion:4.4.0-62-generic ContainerOsVersion:Ubuntu 16.04.2 LTS DockerVersion:18.09.0 DockerAPIVersion:1.39 CadvisorVersion:v0.33.0 CadvisorRevision:511ec9ef}
I0314 19:43:40.635010   19140 factory.go:356] Registering Docker factory
I0314 19:43:40.635067   19140 manager.go:310] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: connect: connection refused
I0314 19:43:40.636624   19140 factory.go:136] Registering containerd factory
I0314 19:43:40.636820   19140 manager.go:326] Registration of the crio container factory failed: Get http://%2Fvar%2Frun%2Fcrio%2Fcrio.sock/info: dial unix /var/run/crio/crio.sock: connect: no such file or directory
I0314 19:43:40.637632   19140 manager.go:331] Registration of the mesos container factory failed: unable to create mesos agent client: failed to get version
I0314 19:43:40.637664   19140 factory.go:54] Registering systemd factory
I0314 19:43:40.638212   19140 factory.go:100] Registering Raw factory
I0314 19:43:40.638753   19140 manager.go:1256] Started watching for new ooms in manager
I0314 19:43:40.651802   19140 nvidia.go:53] No NVIDIA devices found.
I0314 19:43:40.651956   19140 factory.go:120] Factory "docker" was unable to handle container "/"
I0314 19:43:40.652000   19140 factory.go:120] Factory "containerd" was unable to handle container "/"
I0314 19:43:40.652110   19140 factory.go:109] Error trying to work out if we can handle /: / not handled by systemd handler
I0314 19:43:40.652128   19140 factory.go:120] Factory "systemd" was unable to handle container "/"
I0314 19:43:40.652156   19140 factory.go:116] Using factory "raw" for container "/"
I0314 19:43:40.653356   19140 manager.go:1045] Added container: "/" (aliases: [], namespace: "")
I0314 19:43:40.654373   19140 handler.go:325] Added event &{/ 2019-03-04 15:56:49.481022994 +0300 MSK containerCreation {<nil>}}
I0314 19:43:40.654451   19140 manager.go:369] Starting recovery of all containers
I0314 19:43:40.654531   19140 container.go:464] Start housekeeping for container "/"
I0314 19:43:40.686100   19140 factory.go:120] Factory "docker" was unable to handle container "/system.slice/chef-client.service"
I0314 19:43:40.686157   19140 factory.go:120] Factory "containerd" was unable to handle container "/system.slice/chef-client.service"
I0314 19:43:40.686173   19140 factory.go:109] Error trying to work out if we can handle /system.slice/chef-client.service: /system.slice/chef-client.service not handled by systemd handler
I0314 19:43:40.686187   19140 factory.go:120] Factory "systemd" was unable to handle container "/system.slice/chef-client.service"
I0314 19:43:40.686201   19140 factory.go:116] Using factory "raw" for container "/system.slice/chef-client.service"
I0314 19:43:40.686464   19140 manager.go:1045] Added container: "/system.slice/chef-client.service" (aliases: [], namespace: "")
I0314 19:43:40.686646   19140 handler.go:325] Added event &{/system.slice/chef-client.service 2019-03-04 15:56:49.593022996 +0300 MSK containerCreation {<nil>}}
I0314 19:43:40.686808   19140 container.go:464] Start housekeeping for container "/system.slice/chef-client.service"
I0314 19:43:40.697997   19140 factory.go:120] Factory "docker" was unable to handle container "/system.slice/networking.service"
I0314 19:43:40.698107   19140 factory.go:120] Factory "containerd" was unable to handle container "/system.slice/networking.service"
I0314 19:43:40.698125   19140 factory.go:109] Error trying to work out if we can handle /system.slice/networking.service: /system.slice/networking.service not handled by systemd handler
I0314 19:43:40.698138   19140 factory.go:120] Factory "systemd" was unable to handle container "/system.slice/networking.service"
I0314 19:43:40.698152   19140 factory.go:116] Using factory "raw" for container "/system.slice/networking.service"
I0314 19:43:40.698535   19140 manager.go:1045] Added container: "/system.slice/networking.service" (aliases: [], namespace: "")
I0314 19:43:40.698755   19140 handler.go:325] Added event &{/system.slice/networking.service 2019-03-04 15:56:49.521022995 +0300 MSK containerCreation {<nil>}}
I0314 19:43:40.699015   19140 factory.go:120] Factory "docker" was unable to handle container "/system.slice/console-setup.service"
I0314 19:43:40.699040   19140 factory.go:120] Factory "containerd" was unable to handle container "/system.slice/console-setup.service"
I0314 19:43:40.699054   19140 factory.go:109] Error trying to work out if we can handle /system.slice/console-setup.service: /system.slice/console-setup.service not handled by systemd handler
I0314 19:43:40.699064   19140 factory.go:120] Factory "systemd" was unable to handle container "/system.slice/console-setup.service"
I0314 19:43:40.699076   19140 factory.go:116] Using factory "raw" for container "/system.slice/console-setup.service"
I0314 19:43:40.699681   19140 container.go:464] Start housekeeping for container "/system.slice/networking.service"
I0314 19:43:40.699792   19140 manager.go:1045] Added container: "/system.slice/console-setup.service" (aliases: [], namespace: "")
I0314 19:43:40.700091   19140 handler.go:325] Added event &{/system.slice/console-setup.service 2019-03-04 15:56:49.565022996 +0300 MSK containerCreation {<nil>}}
I0314 19:43:40.700151   19140 factory.go:120] Factory "docker" was unable to handle container "/system.slice/var-lib-docker-containers-4027da0b4e2a99d41a45dcd6374076c9c5ca4e0968cddec8f682560c0dd4f1f8-mounts-shm.mount"
I0314 19:43:40.700180   19140 factory.go:120] Factory "containerd" was unable to handle container "/system.slice/var-lib-docker-containers-4027da0b4e2a99d41a45dcd6374076c9c5ca4e0968cddec8f682560c0dd4f1f8-mounts-shm.mount"
I0314 19:43:40.700200   19140 factory.go:113] Factory "systemd" can handle container "/system.slice/var-lib-docker-containers-4027da0b4e2a99d41a45dcd6374076c9c5ca4e0968cddec8f682560c0dd4f1f8-mounts-shm.mount", but ignoring.
I0314 19:43:40.700223   19140 manager.go:1005] ignoring container "/system.slice/var-lib-docker-containers-4027da0b4e2a99d41a45dcd6374076c9c5ca4e0968cddec8f682560c0dd4f1f8-mounts-shm.mount"
I0314 19:43:40.700254   19140 factory.go:120] Factory "docker" was unable to handle container "/system.slice/system-systemd\\x2dfsck.slice"
I0314 19:43:40.700277   19140 factory.go:120] Factory "containerd" was unable to handle container "/system.slice/system-systemd\\x2dfsck.slice"
I0314 19:43:40.700297   19140 factory.go:109] Error trying to work out if we can handle /system.slice/system-systemd\x2dfsck.slice: /system.slice/system-systemd\x2dfsck.slice not handled by systemd handler
I0314 19:43:40.700312   19140 factory.go:120] Factory "systemd" was unable to handle container "/system.slice/system-systemd\\x2dfsck.slice"
I0314 19:43:40.700328   19140 factory.go:116] Using factory "raw" for container "/system.slice/system-systemd\\x2dfsck.slice"
I0314 19:43:40.700625   19140 manager.go:1045] Added container: "/system.slice/system-systemd\\x2dfsck.slice" (aliases: [], namespace: "")
I0314 19:43:40.700872   19140 handler.go:325] Added event &{/system.slice/system-systemd\x2dfsck.slice 2019-03-04 15:56:49.609022996 +0300 MSK containerCreation {<nil>}}
I0314 19:43:40.700925   19140 factory.go:120] Factory "docker" was unable to handle container "/system.slice/var-lib-docker-containers-55ba4ccda0918ecf67ea79b752d0919bd117f6aa45fef02a3158dc051e65ead1-mounts-shm.mount"
I0314 19:43:40.700969   19140 container.go:464] Start housekeeping for container "/system.slice/system-systemd\\x2dfsck.slice"
I0314 19:43:40.701125   19140 container.go:464] Start housekeeping for container "/system.slice/console-setup.service"
I0314 19:43:40.700955   19140 factory.go:120] Factory "containerd" was unable to handle container "/system.slice/var-lib-docker-containers-55ba4ccda0918ecf67ea79b752d0919bd117f6aa45fef02a3158dc051e65ead1-mounts-shm.mount"
I0314 19:43:40.701464   19140 factory.go:113] Factory "systemd" can handle container "/system.slice/var-lib-docker-containers-55ba4ccda0918ecf67ea79b752d0919bd117f6aa45fef02a3158dc051e65ead1-mounts-shm.mount", but ignoring.
I0314 19:43:40.701494   19140 manager.go:1005] ignoring container "/system.slice/var-lib-docker-containers-55ba4ccda0918ecf67ea79b752d0919bd117f6aa45fef02a3158dc051e65ead1-mounts-shm.mount"
I0314 19:43:40.701523   19140 factory.go:120] Factory "docker" was unable to handle container "/system.slice/run-docker-netns-74734d30e737.mount"
I0314 19:43:40.701548   19140 factory.go:120] Factory "containerd" was unable to handle container "/system.slice/run-docker-netns-74734d30e737.mount"
I0314 19:43:40.701571   19140 factory.go:113] Factory "systemd" can handle container "/system.slice/run-docker-netns-74734d30e737.mount", but ignoring.
I0314 19:43:40.702404   19140 manager.go:1005] ignoring container "/system.slice/run-docker-netns-74734d30e737.mount"
I0314 19:43:40.702445   19140 factory.go:120] Factory "docker" was unable to handle container "/system.slice/atd.service"
I0314 19:43:40.702476   19140 factory.go:120] Factory "containerd" was unable to handle container "/system.slice/atd.service"
I0314 19:43:40.702505   19140 factory.go:109] Error trying to work out if we can handle /system.slice/atd.service: /system.slice/atd.service not handled by systemd handler
I0314 19:43:40.702527   19140 factory.go:120] Factory "systemd" was unable to handle container "/system.slice/atd.service"
I0314 19:43:40.702552   19140 factory.go:116] Using factory "raw" for container "/system.slice/atd.service"
I0314 19:43:40.703164   19140 manager.go:1045] Added container: "/system.slice/atd.service" (aliases: [], namespace: "")
I0314 19:43:40.703488   19140 handler.go:325] Added event &{/system.slice/atd.service 2019-03-04 15:56:49.569022996 +0300 MSK containerCreation {<nil>}}
I0314 19:43:40.703570   19140 factory.go:120] Factory "docker" was unable to handle container "/system.slice/var-lib-docker-containers-f6af91f7e616ffb8681e48780d294b8c0002149db0468546fa6c61e351101ed5-mounts-shm.mount"
I0314 19:43:40.703629   19140 container.go:464] Start housekeeping for container "/system.slice/atd.service"
I0314 19:43:40.703606   19140 factory.go:120] Factory "containerd" was unable to handle container "/system.slice/var-lib-docker-containers-f6af91f7e616ffb8681e48780d294b8c0002149db0468546fa6c61e351101ed5-mounts-shm.mount"
I0314 19:43:40.704156   19140 factory.go:113] Factory "systemd" can handle container "/system.slice/var-lib-docker-containers-f6af91f7e616ffb8681e48780d294b8c0002149db0468546fa6c61e351101ed5-mounts-shm.mount", but ignoring.
I0314 19:43:40.704187   19140 manager.go:1005] ignoring container "/system.slice/var-lib-docker-containers-f6af91f7e616ffb8681e48780d294b8c0002149db0468546fa6c61e351101ed5-mounts-shm.mount"
I0314 19:43:40.704224   19140 factory.go:120] Factory "docker" was unable to handle container "/system.slice/kmod-static-nodes.service"
I0314 19:43:40.704256   19140 factory.go:120] Factory "containerd" was unable to handle container "/system.slice/kmod-static-nodes.service"
I0314 19:43:40.704283   19140 factory.go:109] Error trying to work out if we can handle /system.slice/kmod-static-nodes.service: /system.slice/kmod-static-nodes.service not handled by systemd handler
I0314 19:43:40.704306   19140 factory.go:120] Factory "systemd" was unable to handle container "/system.slice/kmod-static-nodes.service"
I0314 19:43:40.704330   19140 factory.go:116] Using factory "raw" for container "/system.slice/kmod-static-nodes.service"
I0314 19:43:40.704641   19140 manager.go:1045] Added container: "/system.slice/kmod-static-nodes.service" (aliases: [], namespace: "")
I0314 19:43:40.704908   19140 handler.go:325] Added event &{/system.slice/kmod-static-nodes.service 2019-03-04 15:56:49.541022995 +0300 MSK containerCreation {<nil>}}
I0314 19:43:40.705067   19140 container.go:464] Start housekeeping for container "/system.slice/kmod-static-nodes.service"`

HELP PLEASE??!?!

**Comment by dashpole** [comment]
How have you determined that cAdvisor isn't listening on port 8080?  What happens if you run `curl localhost:8080/metrics`?

**Comment by masikmos** [comment]
`curl localhost:8080/metrics
curl: (7) Failed to connect to localhost port 8080: Connection refused`

`netstat -plunt | grep 8080` empty

**Comment by masikmos** [comment]
if i say
`sudo ./cadvisor -port 999999 --logtostderr -listen_ip 999.999.999.999 -v=999`
he just started!!!

**Comment by masikmos** [comment]
strace don't see any of attempts to listen ports or IPs!

**Comment by masikmos** [comment]
only after reboot of all server, this problem resolved
