### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jomach** [google/cadvisor#2205]
when running cadvisor on a node with mesos it breaks. 

`./cadvisor`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xde9054]

goroutine 1 [running]:
github.com/google/cadvisor/container/mesos.(*state).fetchLabelsFromTask(0xc00086b3a0, 0xc0000ea6e0, 0x4c, 0xc000925110, 0xc000233058, 0x0)
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/container/mesos/mesos_agent.go:116 +0xf4
github.com/google/cadvisor/container/mesos.(*state).FetchLabels(0xc00086b3a0, 0xc00075c780, 0x11, 0xc0000ea6e0, 0x4c, 0x4, 0x4, 0xc00086b3b0)
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/container/mesos/mesos_agent.go:141 +0x3dd
github.com/google/cadvisor/container/mesos.(*client).getLabels(0xc0001863b8, 0xc0000c0340, 0x24, 0xc0000c0340, 0x0)
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/container/mesos/client.go:181 +0x175
github.com/google/cadvisor/container/mesos.(*client).ContainerInfo(0xc0001863b8, 0xc000440d57, 0x24, 0x24, 0x40c538, 0x10)
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/container/mesos/client.go:89 +0x73
github.com/google/cadvisor/container/mesos.(*mesosFactory).CanHandleAndAccept(0xc00025daa0, 0xc000440d50, 0x2b, 0xc00086b558, 0x2, 0x2)
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/container/mesos/factory.go:110 +0x8a
github.com/google/cadvisor/container.NewContainerHandler(0xc000440d50, 0x2b, 0x0, 0x1e45c01, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/container/factory.go:107 +0x124
github.com/google/cadvisor/manager.(*manager).createContainerLocked(0xc0004503c0, 0xc000440d50, 0x2b, 0x0, 0x0, 0x0)
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/manager/manager.go:965 +0xd6
github.com/google/cadvisor/manager.(*manager).createContainer(0xc0004503c0, 0xc000440d50, 0x2b, 0x0, 0x0, 0x0)
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/manager/manager.go:952 +0x94
github.com/google/cadvisor/manager.(*manager).detectSubcontainers(0xc0004503c0, 0x11abe05, 0x1, 0x0, 0x0)
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/manager/manager.go:1145 +0x199
github.com/google/cadvisor/manager.(*manager).Start(0xc0004503c0, 0xc000525e60, 0x13312c0)
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/manager/manager.go:366 +0x50e
main.main()
        /usr/local/google/home/dashpole/go/src/github.com/google/cadvisor/cadvisor.go:171 +0x492`

cAdvisor version v0.32.0 (8949c822)

On version 0.33 works but on 0.33 integration with prometheus seems broken as  now metrics have a timestamp at the end.

**Comment by dashpole** [comment]
> On version 0.33 works but on 0.33 integration with prometheus seems broken as now metrics have a timestamp at the end.

**Comment by jomach** [comment]
I don't know yet still investigation why, fact is I was pushing these metrics to the push server from prometheus and now it does not work anymore.

**Comment by dashpole** [comment]
Ah, yeah.  You can't use the push gateway with timestamps.  I had heard that from someone else as well.  If you don't mind sharing, why are you using the push gateway?

**Comment by jomach** [comment]
Just for testing because of FW issues. I just tested this all in one machine and it works fine. But this should go into the notes that now it is not possible to use the push gateway from version 0.32 on
