### ISSUE TITLE
Cadvisor convert nanosecond CPU time in CPU nanocores

### ISSUE THREAD

**Issue by manpreetsingh001** [google/cadvisor#2206]
I was reading source code of cadvisor and it seems like cadvisor does support converting nanosecond cpu to nanocores/second.

Cadvisor exposes CPU [Inststats ](https://github.com/google/cadvisor/blob/master/info/v2/container.go#L138)nanocores/second. It is part of [v2](https://github.com/google/cadvisor/blob/master/info/v2/container.go) cadvisor schema.

Cadvisor storage schema exposes interface method [Addstats](https://github.com/google/cadvisor/blob/master/storage/storage.go#L25) which takes cadvisor schema ["V1"](https://github.com/google/cadvisor/blob/master/info/v1/container.go) and I am using "statsd" as a storage driver and want to send "CpuInstUsage.Total".

Two ways I think of getting CpuInstUsage.Total
1. Use conversion method available for V2 schema to convert V1 schema to V2.I tried this method but does not seems to working for me.
2. Switch cadvisor to V2 schema? But seems like storage interface signature is tied to V1 schema.how can i switch cadvisor to V2 schema?

**Comment by manpreetsingh001** [comment]
@dashpole  any suggestion?

**Comment by dashpole** [comment]
Just to confirm, you want to add instantaneous CPU usage to the statsd storage driver, right?

I don't see an easy way to accomplish that, as the V1 api only has instantaneous metrics.  Does statsd have the ability to take rates?  It is generally preferable to do that in the aggregator, rather than in the collector.

**Comment by manpreetsingh001** [comment]
@dashpole Correct,I want to send Instantaneous CPU usage to the storage driver. 
We want to convert CPU usage Time to Nanocores(Instantaneous usage) because accumulative  usage suffers from integer overflow when we try to do sum(aggregation) in statsd.
Instantaneous CPU usage is exposed only in V2 schema but Cadvisor  storage driver Interface is tied to V1 schema.I was basically making changes in [AddStats](https://github.com/google/cadvisor/blob/master/storage/statsd/statsd.go#L129) method in storage driver to convert V1 to V2 schema  using  [conversion](https://github.com/google/cadvisor/blob/master/info/v2/conversion.go#L99) method but unfortunately  it is not converting  the schema.

I see at other part of the cadvisor [code](https://github.com/google/cadvisor/blob/master/api/versions.go#L519) conversion is being done from V1 to V2 schema and I am trying to do he same but it is not working for me.

**Comment by dashpole** [comment]
If you are using [ContainerStatsFromV1](https://github.com/google/cadvisor/blob/master/info/v2/conversion.go#L99), you need to supply multiple container stats so it can calculate the rate

**Comment by manpreetsingh001** [comment]
@dashpole  yeah i just realized that.I am trying to get my head around why /api/v2.1/stats/docker/<id>(which returns multiple container stats) follows different path code then AddStats method.Any pointer would be helpful.
Since Cadvisor has v2.1 client library I am thinking to use it to call  /api/v2.1/stats/docker/<id> endpoint to get nanocores and embed that into "AddStats"method but not sure what would be the performance impact on cadvisor.

**Comment by manpreetsingh001** [comment]
any comments?

**Comment by dashpole** [comment]
I'm not sure I understand exactly what you are proposing... Are you saying you plan to use the cadvisor API instead of the statsd exporter?  All of cAdvisor's APIs return cached metrics, so serving additional responses shouldn't have too much overhead.

**Comment by manpreetsingh001** [comment]
@dashpole Apoligies If i wasn't clear enough. Yes I plan to use the cadvisor API instead of the statsd exporter.Thanks for confirming it.This issue can be mark resolved
