### ISSUE TITLE
Disabling cadvisor GPU accelerator when running inside kubelet

### ISSUE THREAD

**Issue by visheshtanksale** [google/cadvisor#2210]
I have a host with Nvidia GPUs and Nvidia driver installed. When I deploy kubelet on the host, the kubelet process accesses these GPUs as can be seen by the output of lsof
```
[root@10 ~]# lsof /dev/nvidia*
COMMAND     PID USER   FD   TYPE  DEVICE SIZE/OFF   NODE NAME
kubelet   36960 root    6u   CHR   195,0      0t0  94021 /dev/nvidia0
kubelet   36960 root   10u   CHR 195,255      0t0  94020 /dev/nvidiactl
kubelet   36960 root   21u   CHR   195,1      0t0 105147 /dev/nvidia1
kubelet   36960 root   27u   CHR   195,2      0t0 126594 /dev/nvidia2
kubelet   36960 root   28u   CHR   195,3      0t0 133514 /dev/nvidia3
kubelet   36960 root   29u   CHR   195,0      0t0  94021 /dev/nvidia0
kubelet   36960 root   30u   CHR   195,4      0t0 113448 /dev/nvidia4
kubelet   36960 root   31u   CHR   195,5      0t0 144595 /dev/nvidia5
kubelet   36960 root   32u   CHR   195,6      0t0 134552 /dev/nvidia6
kubelet   36960 root   33u   CHR   195,7      0t0 128477 /dev/nvidia7
kubelet   36960 root   34u   CHR   195,1      0t0 105147 /dev/nvidia1
kubelet   36960 root   35u   CHR   195,0      0t0  94021 /dev/nvidia0
kubelet   36960 root   36u   CHR   195,1      0t0 105147 /dev/nvidia1
kubelet   36960 root   37u   CHR   195,0      0t0  94021 /dev/nvidia0
kubelet   36960 root   38u   CHR   195,2      0t0 126594 /dev/nvidia2
kubelet   36960 root   39u   CHR   195,1      0t0 105147 /dev/nvidia1
kubelet   36960 root   40u   CHR   195,3      0t0 133514 /dev/nvidia3
kubelet   36960 root   41u   CHR   195,2      0t0 126594 /dev/nvidia2
kubelet   36960 root   42u   CHR   195,2      0t0 126594 /dev/nvidia2
kubelet   36960 root   43u   CHR   195,3      0t0 133514 /dev/nvidia3
kubelet   36960 root   44u   CHR   195,4      0t0 113448 /dev/nvidia4
kubelet   36960 root   45u   CHR   195,3      0t0 133514 /dev/nvidia3
kubelet   36960 root   46u   CHR   195,5      0t0 144595 /dev/nvidia5
kubelet   36960 root   47u   CHR   195,4      0t0 113448 /dev/nvidia4
kubelet   36960 root   48u   CHR   195,4      0t0 113448 /dev/nvidia4
kubelet   36960 root   49u   CHR   195,5      0t0 144595 /dev/nvidia5
kubelet   36960 root   50u   CHR   195,5      0t0 144595 /dev/nvidia5
kubelet   36960 root   51u   CHR   195,6      0t0 134552 /dev/nvidia6
kubelet   36960 root   52u   CHR   195,6      0t0 134552 /dev/nvidia6
kubelet   36960 root   53u   CHR   195,6      0t0 134552 /dev/nvidia6
kubelet   36960 root   54u   CHR   195,7      0t0 128477 /dev/nvidia7
kubelet   36960 root   55u   CHR   195,7      0t0 128477 /dev/nvidia7
kubelet   36960 root   56u   CHR   195,7      0t0 128477 /dev/nvidia7
```
I want to override the Nvidia driver with VFIO-PCI driver so that I can pass-through GPUs to VMs. But since kubelet is accessing these GPU, it has a lock preventing the switch of drivers. If I kill the kubelet process it is possible to switch the drivers. I have not set LD_LIBRARY_PATH env variable but cAdvisor GPU accelerator is still talking to NVML and accessing GPUs.
I see the following in kubelet logs
```
I0328 15:25:52.222151   72765 manager.go:155] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct/user.slice" 
```

Is there any work around for this? Is it possible to not allow cAdvisor to know about those GPUs?

**Comment by dashpole** [comment]
We could add accellerator stats to the [ignore whitelist](https://github.com/google/cadvisor/blob/master/cadvisor.go#L81), but the kubelet sets the ignore metrics anyways...

What if you set the LD_LIBRARY_PATH to an explicitly incorrect path?

**Comment by visheshtanksale** [comment]
Yeah setting LD_LIBRARY_PATH was my first instinct. But it does not work. 
I think Kubelet is creating and running cadvisor in a container [here](https://github.com/kubernetes/kubernetes/blob/18789bfb601b5fccaa3ffadf4423110bdbcc9efd/cmd/kubelet/app/server.go#L654) 

Also, I just see this message in Kubelet logs
```
I0328 15:25:52.222151   72765 manager.go:155] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct/user.slice" 
```
I am not able to see this message in the kubelet logs
```
NVML initialized. Number of nvidia devices
```
Any idea what is it doing in that container? How is it able to access Nvidia NVML Library?

**Comment by dashpole** [comment]
Can you up the verbosity of the kubelet to 4?  `--v=4`

**Comment by visheshtanksale** [comment]
Ok. No luck with it.

This is my `10-kubeadm.conf`
```
# Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
Environment="KUBELET_EXTRA_ARGS=--v=4"
# This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably, the user should use
# the .NodeRegistration.KubeletExtraArgs object in the configuration files instead. KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/sysconfig/kubelet
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
```
This is the search output
```
[root@10 /]# sudo journalctl -u kubelet --no-pager | grep -i NVML
[root@10 /]#
```

**Comment by visheshtanksale** [comment]
I am able to see the log message in which NVML is initialized. 
```
[root@10 /]# sudo journalctl -u kubelet --no-pager | grep -i NVML
Apr 01 13:00:43 10.0.1.7 kubelet[68401]: I0401 13:00:43.165000   68401 nvidia.go:100] NVML initialized. Number of nvidia devices: 8
```
But I am still not able to understand how is it able to access the NVML library, because I have not set  LD_LIBRARY_PATH. Any clues how is it reading NVML library.

**Comment by visheshtanksale** [comment]
@dashpole  Does [this](https://github.com/vikaschoudhary16/community/blob/060a25c441269be476ade624ea0347ebc113e659/keps/sig-node/compute-device-assignment.md) proposal warrant for removal of GPU based accelerators that is embedded inside kubelet by cAdvisor?

**Comment by dashpole** [comment]
I suppose it is related.  I have plans to remove cAdvisor from the kubelet that are more fully documented here: https://github.com/kubernetes/kubernetes/issues/68522.  But i'm afraid this won't happen quickly...

**Comment by eero-t** [comment]
Maybe Nvidia runc, or some setting for it, is adding the NVML library path information to all the containers: https://github.com/NVIDIA/nvidia-container-runtime ?

**Comment by pacoxu** [comment]
[DisableAcceleratorUsageMetrics](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) is GAed in Kubernetes v1.25 with PR https://github.com/kubernetes/kubernetes/pull/110940.

> The kubelet no longer supports collecting accelerator metrics through cAdvisor. The feature gate `DisableAcceleratorUsageMetrics` is now GA and cannot be disabled.
