### ISSUE TITLE
v0.33.0 does not show labels

### ISSUE THREAD

**Issue by atcjunior** [google/cadvisor#2214]
After have upgraded from 0.32.0 to 0.33.0 labels like container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_docker_type and a lot of others seems to have disappeared.

Is there any option I need to enable to get them back again?

**Comment by dashpole** [comment]
I don't think that was an intended change.  Are you setting `--store_container_labels` or `--whitelisted_container_labels` flags?

**Comment by atcjunior** [comment]
Actually none of them, only "--logtostderr" . I've started application with this command:
cadvisor --logtostderr

**Comment by dashpole** [comment]
ok, that is a bug.  I'll see if I can reproduce it.

**Comment by atcjunior** [comment]
I've realised what was my mistake, I was starting container with a non root user.
After rebuild my docker image to start with root user, everything worked as before.

Thank you very much for you help!
