### ISSUE TITLE
First time running cadvisor

### ISSUE THREAD

**Issue by ARafik** [google/cadvisor#2224]
Hi,

After a fresh install of cadvisor
`docker run google/cadvisor`
and the response is 
```
Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory
Failed to start container manager: inotify_add_watch /sys/fs/cgroup/cpuset: no space left on device
```

and the files

/etc/machine-id
/var/lib/dbus/machine-id

are on the host, and contain the same number.

what I am doing wrong ?

Thank's

**Comment by dashpole** [comment]
See the [quick start guide](https://github.com/google/cadvisor#quick-start-running-cadvisor-in-a-docker-container) in the readme.  You need to specify mounts for cAdvisor to have access to files it needs.

Optimistically closing this.  Reopen if you have further questions
