### ISSUE TITLE
does cadvisor collect mesos network metrics now?

### ISSUE THREAD

**Issue by tongbinxiang** [google/cadvisor#2231]

**Comment by tongbinxiang** [comment]
I see source code: https://github.com/google/cadvisor/blob/master/utils/sysinfo/sysinfo.go#L162 . Does cadvisor only collect **InterfaceStats** info at present? Does cadvisor collect the other **NetworkStats** info like **Tcp/Tcp6**?

**Comment by dashpole** [comment]
The libcontainer handler (https://github.com/google/cadvisor/blob/master/container/libcontainer/handler.go) is a common cgroup stats collector that is used by all collectors, including mesos.  That handles the collection of TCP and UDP metrics
