### ISSUE TITLE
container_processes metric doesn't get populated correctly

### ISSUE THREAD

**Issue by rahanar** [google/cadvisor#2251]
Hello, 

I am trying to expose **container_processes** metric by running a standalone version of cAdvisor on a Kubernetes cluster. However, the metric never gets populated and is always set to 0.

I followed [instructions](https://github.com/google/cadvisor/tree/master/deploy/kubernetes) provided in the repo to deploy cAdvisor as a daemonset and set the following arguments:

```
      containers:
      - args:
        - --housekeeping_interval=10s
        - --max_housekeeping_interval=15s
        - --event_storage_event_limit=default=0
        - --event_storage_age_limit=default=0
        - --disable_metrics=diskIO,disk,network,tcp,udp,percpu,sched
        - --docker_only
```

I was not sure whether I was doing something wrong or if there is a bug, so I run cAdvisor through delve and noticed the following code path was never reaching:

https://github.com/google/cadvisor/blob/master/container/libcontainer/handler.go#L128

Hence, container_processes metric for all containers is set to 0. I am still trying to figure out why that code path never gets hit (it is not obvious, PC jumps to the end of the else statement right before that function call). I verified that cgroup.procs for a target container has correct values, the metric should be populated correctly.

I would appreciate a feedback whether I am missing something or doing something wrong. If you have any suggestion what else I can do to debug this, please share.

Thank you,
Anar

**Comment by rahanar** [comment]
I am not sure why the code was jumping over that function in my previous sessions, but after recompiling the code and running through the debugger again, it seems like the following doesn't work as expected:

https://github.com/google/cadvisor/blob/master/container/libcontainer/handler.go#L146

```	
out, err := ioutil.ReadFile(filePath)
	if err != nil {
		return info.ProcessStats{}, fmt.Errorf("couldn't open cpu cgroup procs file %v : %v", filePath, err)
	}
```

```
=> 160:		for _, pid := range pids {
   161:			dirPath := path.Join(rootFs, "/proc", pid, "fd")
   162:			fds, err := ioutil.ReadDir(dirPath)
   163:			if err != nil {
   164:				klog.V(4).Infof("error while listing directory %q to measure fd count: %v", dirPath, err)
   165:				continue
(dlv) p pids
[]string len: 0, cap: 1, []
(dlv) p pids
[]string len: 0, cap: 1, []
(dlv) p filePath
"/sys/fs/cgroup/cpu,cpuacct/docker/60c8446e92f6c2b402fb0764f1279a0a4c94fe4711dd612c79989cc90b2fa2ae/cgroup.procs"
```

```
cat /sys/fs/cgroup/cpu,cpuacct/docker/60c8446e92f6c2b402fb0764f1279a0a4c94fe4711dd612c79989cc90b2fa2ae/cgroup.procs
1310
25485
```

Hence the values are always 0.

**Comment by rahanar** [comment]
```
(dlv) p r
io.Reader(*os.File) *{
	file: *os.file {
		pfd: (*"internal/poll.FD")(0xc000187aa0),
		name: "/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pode211bd97-887b-11e9-b7d9-760e611aebd4/74bc840169c12599d8e7fed347847e5d471c5b5bac7b57af51cd69a140c60015/cgroup.procs",
		dirinfo: *os.dirInfo nil,
		nonblock: true,
		stdoutOrErr: false,},}
(dlv) s
> io/ioutil.readAll() /usr/local/go/src/io/ioutil/ioutil.go:34 (PC: 0x5faac0)
    29:			} else {
    30:				panic(e)
    31:			}
    32:		}()
    33:		_, err = buf.ReadFrom(r)
=>  34:		return buf.Bytes(), err
    35:	}
    36:
    37:	// ReadAll reads from r until an error or EOF and returns the data it read.
    38:	// A successful call returns err == nil, not err == EOF. Because ReadAll is
    39:	// defined to read from src until EOF, it does not treat an EOF from Read
(dlv) p buf
bytes.Buffer {
	buf: []uint8 len: 0, cap: 0, nil,
	off: 0,
	lastRead: opInvalid (0),}
```

I am not sure why it is not about able to read the file. I assume if it was a permission error, I would get an error back.

**Comment by rahanar** [comment]
Tested by running cadvisor directly on the host and I am able to get the required metrics. Seems like the reads on that file silently fail (?) inside container.

**Comment by rahanar** [comment]
The files that cadvisor is expected to read are, for some reason, empty inside the container. If I check cgroup.procs on the host, it has correct values.

I gave cadvisor privileged access and still the same issue

```
  privileged: true
  allowPrivilegeEscalation: true```

**Comment by qingwave** [comment]
I am troubled with the same problem, mount the `cgroup.procs` will be empty in container, if cp the `cgroup` --> `tmp-cgroup`, mount the` tmp-cgoup` and `cgroup.procs` has value. Maybe mounting cgroup dir in an unsusal way. See  [mount_namespaces](http://man7.org/linux/man-pages/man7/mount_namespaces.7.html)

**Comment by qingwave** [comment]
Set docker flag`--pid=host`(k8s `hostPID: true`), you can get the true value

**Comment by rahanar** [comment]
You are right. I thought I tried this before, but seems like I messed up. Thank you for the help

**Comment by BegoniaGit** [comment]
> Set docker flag`--pid=host`(k8s `hostPID: true`), you can get the real value

非常感谢，这个配置完全可行。
