### ISSUE TITLE
Feature request: Expose number of cgroups as metric

### ISSUE THREAD

**Issue by mariusgrigoriu** [google/cadvisor#2267]
We recently ran a container runtime that was leaking cgroups, causing some hard to track stability issues. Having visibility into the number of cgroups might have helped us figure it out sooner. Is there interest in exporting stats about cgroups? (Apologies if it already does this.)

**Comment by dashpole** [comment]
Have you tried counting the number of a particular metric?  cAdvisor collects metrics for all cgroups on the node, and most monitoring solutions support grouping by COUNT.

**Comment by mariusgrigoriu** [comment]
I'm only seeing container_* metrics (using built-in cAdvisor in 1.14.3 kubelet w/ Prometheus metrics). Is it required to run cAdvisor separately to get more cgroup metrics?

**Comment by dashpole** [comment]
The name is misleading.  We treat every cgroup as a "container".  So you should, for example, see metrics for systemd services showing up in container_* metrics.

**Comment by mariusgrigoriu** [comment]
Good call. Counting cAdvisor metrics does the job. No need for this feature.
