### ISSUE TITLE
container names not exposed

### ISSUE THREAD

**Issue by terpdog** [google/cadvisor#2270]
I've looked quite a few places and I can't see where cAdvisor has the individual container names.  I will see something like 

/docker/f6e7a131f8a8ed9a1c8dd7101944b6fab5c1a2a49f81eb4ca570cb66b5e53668

but if  would like to see Ansible which is what we named it.

I've looked through the API's and I don't see "name".  If I do a docker inspect or a docker stats I do see that.

We have cAdvisor gathering the metrics and then utilizing prometheus to keep the data.

I saw that there were some questions about this years ago but I didn't see a solution.  Is there a configuration that I'm missing?

**Comment by dashpole** [comment]
There should be a "name" label with the name according to docker.  It is possible that cAdvisor isn't able to connect to docker.  Can you look in your logs for errors related to connecting to docker, or share your cAdvisor logs here?

**Comment by terpdog** [comment]
I'm able to connect to cAdvisor, I can connect to all the cAdvisor API's and I can see all the information.   But all the containers show /docker/<id>.. I don't see name anywhere.

When I do a docker stats I do see the name

I'm pretty sure that it's connecting to docker because we are getting metrics about CPU/Memory/etc.. for each container, we just aren't getting the name.

**Comment by dashpole** [comment]
cadvisor gets those metrics from cgroups on the node.  It gets metadata, such as the container name, from the container runtime.

**Comment by terpdog** [comment]
Ok, i figured that  when you did something like starting a container with docker-compose like 

version: "3"
services:
  ansible:
    command:
      - /bin/bash
    container_name: ansible
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DISTTAG=f29container
      - FGC=f29
      - FBR=f29
    hostname: abjansible
    image: fc29/ansible:latest
    ipc: shareable
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/hosts:/etc/hosts
      - /root/files:/root/files
      - /root/scripts:/root/scripts

and see the following in docker stats that you would get the name and not just the container id.


CONTAINER ID                                                       NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
cdc3651335a3c5b9ad542afd19a24d2256c1e29b9f4460716f407c6583f6cbca   prometheus          2.98%               5.464GiB / 62.43GiB   8.75%               76.1GB / 842MB      169MB / 12.3kB      112
56fe9b0ccb866b0bb86b0e6f2057204d29096641192c3d7d44e7c756690b7b52   cadvisor            2.89%               170MiB / 62.43GiB     0.27%               19.2MB / 1.39GB     62MB / 270kB        95
f6e7a131f8a8ed9a1c8dd7101944b6fab5c1a2a49f81eb4ca570cb66b5e53668   ansible          180.77%             658.2MiB / 62.43GiB   1.03%               9.17GB / 86.1GB     784MB / 22.5MB      76


I'll have to learn more about cgroups... thanks for pointing me in the correct direction.
