### ISSUE TITLE
why cadvisor cannot give me more infomation when monitoring gpu?

### ISSUE THREAD

**Issue by code1wind** [google/cadvisor#2271]
&nbsp;&nbsp;Hi, I have tested gpu monitor with cadvisor.  however, I found that there was only 3 metrics about gpu(container_accelerator_duty_cycle, container_accelerator_memory_totoal_bytes, container_accelerator_memory_used_bytes).

&nbsp;&nbsp;Can I get more metrics about gpu with cadvisor? such as temperature, power and other parameters about gpu? Thanks!

**Comment by code1wind** [comment]
![Selection_252](https://user-images.githubusercontent.com/22953895/61536396-23c55880-aa67-11e9-8ddd-77de60eddd9d.png)
![Selection_253](https://user-images.githubusercontent.com/22953895/61536491-5c653200-aa67-11e9-91b4-53378e0dd6a1.png)

**Comment by code1wind** [comment]
I have read the source code of cadvisor. It seems that cadvisor only support metrics include gpu id, total memory, used memory, gpu utilization. 
![Selection_254](https://user-images.githubusercontent.com/22953895/61538219-802a7700-aa6b-11e9-84cc-11c41773fa18.png)

I found that cadvisor use package gonvml to get gpu info, which can get more info such as temperature, power, fan speed and so on. So why not make cadvisor more powerful about gpu?
![Selection_255](https://user-images.githubusercontent.com/22953895/61538398-ec0cdf80-aa6b-11e9-9bbf-fe5db08b65a3.png)

**Comment by dashpole** [comment]
We only added the metrics we wanted for our environment (which happens to be virtualized).  Hence, temperature, power usage, and fan speed were not a requirement.  Feel free to open a PR to add additional metrics.

**Comment by code1wind** [comment]
> We only added the metrics we wanted for our environment (which happens to be virtualized). Hence, temperature, power usage, and fan speed were not a requirement. Feel free to open a PR to add additional metrics.

ok, thanks for your reply!

**Comment by RajezMariner** [comment]
@dashpole , @code1wind  By any chance, is there any other additional features are enabled for GPU monitoring other than container max and full memory?

**Comment by code1wind** [comment]
> @dashpole , @code1wind By any chance, is there any other additional features are enabled for GPU monitoring other than container max and full memory?

Cadvisor now only support 3 metrics about accelerator mentioned above. If you want more metrics, just modify the code with the abilities 'gonvml' provide, by which you can get more information about GPU like temperaure, fans and so on. In fact, it is not complex.

By the way, you can monitor NVDIA GPU with cadvisor and 'dcgmi'

**Comment by dashpole** [comment]
> @dashpole , @code1wind By any chance, is there any other additional features are enabled for GPU monitoring other than container max and full memory?

If you are running on kubernetes, I would encourage you to use nvidia's dcgm kubernetes daemonset: https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/k8s/node-exporter/pod-gpu-node-exporter-daemonset.yaml.  It has many more GPU metrics than cAdvisor.

**Comment by RajezMariner** [comment]
> > @dashpole , @code1wind By any chance, is there any other additional features are enabled for GPU monitoring other than container max and full memory?
> 
> If you are running on kubernetes, I would encourage you to use nvidia's dcgm kubernetes daemonset: https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/k8s/node-exporter/pod-gpu-node-exporter-daemonset.yaml. It has many more GPU metrics than cAdvisor.

@dashpole , @code1wind yes...I have used basic pynvml python module to get the GPU and Memory utilization of a machine and published in our monitoring tool. Just wondered why this simple technique has not been introduced in cAdvisor.
