### ISSUE TITLE
run cadvisor image error,can't start

### ISSUE THREAD

**Issue by juhuahaoteng** [google/cadvisor#2273]
env:centos 7.3.1611/docker version 17.03.2 can't run cadvisor images
"
docker run --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8080:8080 --detach=true --name=cadvisor --privileged=true --volume=/cgroup:/cgroup:ro google/cadvisor:latest
"
docker logs:
E0722 01:49:22.463472       1 factory.go:340] devicemapper filesystem stats will not be reported: usage of thin_ls is disabled to preserve iops
F0722 01:49:22.543274       1 cadvisor.go:172] Failed to start container manager: inotify_add_watch /sys/fs/cgroup/cpuacct,cpu: no such file or directory

**Comment by dashpole** [comment]
Can you try https://github.com/google/cadvisor/issues/1890#issuecomment-371529131 to see if it helps?

**Comment by juhuahaoteng** [comment]
it works!!! thank you.
mount -o remount,rw '/sys/fs/cgroup'
ln -s /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/cpuacct,cpu
