### ISSUE TITLE
Is there a way to collect the process info in a container like the pic blow

### ISSUE THREAD

**Issue by nevenchen** [google/cadvisor#2274]
![image](https://user-images.githubusercontent.com/3069043/61792965-8dbb7480-ae50-11e9-91b5-821ea21c3445.png)

**Comment by dashpole** [comment]
process stats are available at cAdvisor's `/ps` endpoint:
https://github.com/google/cadvisor/blob/master/info/v2/container.go#L252

**Comment by nevenchen** [comment]
Thanks, I got it
