### ISSUE TITLE
Failed to get container "/" with error: unable to find data in memory cache

### ISSUE THREAD

**Issue by farawaaay** [google/cadvisor#2275]
Hi,

According to the readme file in this repository, I started the cadvisor with the following command:

```bash
sudo docker run \
--privileged=true \
--volume=/:/rootfs:ro \
--volume=/var/run:/var/run:rw \
--volume=/sys:/sys:ro \
--volume=/var/lib/docker/:/var/lib/docker:ro \
--volume=/cgroup:/cgroup:ro \
--publish=8080:8080 \
--detach=true \
--name=cadvisor \
google/cadvisor:latest
```

But I got an error saying `failed to get container "/" with error: unable to find data in memory cache` when I open web UI in browser.

The system I was using is a RHEL (version 7) like private Linux distribution and the kernel version is **3.10.0-327**.

Any help would be greatly appreciated.

**Comment by dashpole** [comment]
Are there any other errors you see?  That one in particular amounts to "we don't have any data".  Feel free to paste your full log here.

**Comment by dmwyatt** [comment]
I was getting this when I first installed a 10 minutes ago, but after a few minutes it went away.

**Comment by farawaaay** [comment]
This is issue from `runc/libcontainer`, so I am going to close this issue here.

**Comment by olivierHa** [comment]
Hello @dashpole 
I've got the same error when I've enabled "disable_root_cgroup_stats" option. I've also the same error in #2341 
"/metrics" seems OK, but Webui isn't displaying. 

Any ideas ?

**Comment by wangxf1987** [comment]
steps:
1. systemctl daemon-reexec
2. systemctl restart docker
3. systemctl restart kubelet

**Comment by wangxf1987** [comment]
it's may be the containerd-shim not exit, you can run 
```shell
ps aux | grep docker
```

**Comment by finkr** [comment]
I had this issue because old cadvisor version don't support "recent" cgroups v2 version.
more on  https://stackoverflow.com/q/72754039/1260896
