### ISSUE TITLE
Unable to find package k8s.io/utils/inoticfy  error

### ISSUE THREAD

**Issue by mrturkmen06** [google/cadvisor#2295]
Hi, 
I have tried to get all dependencies as described on [build page](https://github.com/google/cadvisor/blob/master/docs/development/build.md) however there is a complain about  getting this package : k8s.io/utils/inoticfy

<img width="669" alt="Screenshot 2019-08-22 at 15 53 48" src="https://user-images.githubusercontent.com/13614433/63520665-61e5ea00-c4f5-11e9-8df8-1a66de1c2e8a.png">

Any suggestion or comment would be useful :)

**Comment by Colstuwjx** [comment]
Are you build cadvisor on mac or windows? inoticfy package only contains inoticfy_linux.go which only can be found on linux environment.

You can try build it on linux, it works fine.

**Comment by mrturkmen06** [comment]
Yeah, exactly I have used Mac.Then minor edition to build page could be useful  regarding to inoticfy_linux. :) Thank you very much ! I am closing the issue.
