### ISSUE TITLE
invalid metric output

### ISSUE THREAD

**Issue by Colstuwjx** [google/cadvisor#2299]
Hi,

I'm using cadvisor v0.33.0 ( k8s.gcr.io/cadvisor:v0.33.0 ), and fount that the /metrics output is not valid prometheus metric format:

```
container_cpu_cfs_periods_total{container_label_io_kubernetes_pod_name="cadvisor-w7xgw",container_label_io_kubernetes_pod_namespace="cadvisor",container_label_name="",id="/kubepods/burstable/pod6cf45207-c873-11e9-a94f-fa163e497eee/f6ebd64358210825f8b65f0007bba7f4c7594dc3a3e81dfa5ffa7386b91e021d",image="sha256:752d61707eac173cfe56a23aa9de051597444286163667d60f8e6d4c63306472",name="k8s_cadvisor_cadvisor-w7xgw_cadvisor_6cf45207-c873-11e9-a94f-fa163e497eee_0"} 477 1566873441209
...
```

It seems that all metrics are added unix time value?

**Comment by Colstuwjx** [comment]
Sorry, as [open metric format](https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information) said, timestamp is optional field, and is valid format.

**Comment by muzammil360** [comment]
@Colstuwjx, perhaps you are using pushgateway. Were you able to find a fix for that?
