### ISSUE TITLE
Upload v0.33.1 and v0.34.0 to the registry

### ISSUE THREAD

**Issue by zerkms** [google/cadvisor#2301]
At the moment `k8s.gcr.io/cadvisor:v0.33.1` and `k8s.gcr.io/cadvisor:v0.34.0` are not found in the k8s.gcr.io.

Can you please upload it.

And then modify https://github.com/google/cadvisor/blob/master/deploy/kubernetes/base/daemonset.yaml correspondingly.

**Comment by dgonzalezruiz** [comment]
Can anyone please have a look at this?

**Comment by vitovitolo** [comment]
@zerkms did you workaround this somehow? I'm out of ideas other than build docker image and push to a private registry myself. thanks!

**Comment by zerkms** [comment]
@vitovitolo nope, I'm on the latest available version `v0.33.0` I think

**Comment by wsilva** [comment]
Is there any update?

The release `v0.34.0` says that it has an image (https://github.com/google/cadvisor/releases/tag/v0.34.0) but we can't pull it from the registry yet.

**Comment by vitovitolo** [comment]
the image is now available on `gcr.io/google_containers/cadvisor:v0.34.0` :+1: thanks!

**Comment by dashpole** [comment]
I don't have plans to add the v0.33.1 image, and the 0.34.0 image is available now.

**Comment by nightah** [comment]
@dashpole are the containers only going to be provided at the `gcr.io` repository?

Are there no plans to upload this to DockerHub? As the `v0.34.0` container is still missing.

**Comment by dashpole** [comment]
I don't have access to our dockerhub anymore to push the images.  I'm asking around to see if I can figure out who to talk to.  For now, it is probably best to assume that they will only be provided at gcr.io.

**Comment by jeroenj** [comment]
For what it's worth `v0.35.0` is also missing from [GCP](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/cadvisor?gcrImageListsize=30). 😕
