### ISSUE TITLE
cadvisor doesn't have statistics on network connections？

### ISSUE THREAD

**Issue by niuxsh** [google/cadvisor#2303]
Why does cadvisor not have statistics on network connections, including established, close_wait, etc.
Thanks.

**Comment by dashpole** [comment]
You are probably looking for our TCP metrics, which are disabled by default.  They are exported [here](https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L828).

Set the [--disable_metrics](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#metrics) flag to enable these.
