### ISSUE TITLE
Metrics leftovers lead to high CPU and memory usage

### ISSUE THREAD

**Issue by kabakaev** [google/cadvisor#2313]
Label metric names from one container are written to metrics of all other containers. Those garbage labels always have empty values. See an example below.

It looks like some container labels hash map is not properly reset/recreated, thus leaking metrics label names between containers.
This leads to thousands of wrong and useless metric labels in each and every container metric.

Hence `/metrics` HTTP endpoint has to prepare a huge response, allocate memory, burn CPU, torture network etc.

We see sometimes cadvisor consuming gigabytes of RAM and 50 to 70% CPU. 
Running `cadvisor -store_container_labels=false` immediately brings CPU and memory usage to some sane low values.

### Environment
- cadvisor container v0.33.0
- kubernetes v1.14.6
- docker 18.06.3-ce
- CoreOS 2135.6.0

### Example

Let's fetch all metrics from a cadvisor container that runs on local kubernetes node
and get the first contaier metric about itself:
```bash
curl 10.1.17.15:8080/metrics > cadvisor-2pd9r.metrics
grep cadvisor-2pd9r cadvisor-2pd9r.metrics | head -n1
```

Here is what we get:

<details>
  <summary>Container metrics example. Click to expand.</summary>
  container_cpu_cfs_periods_total{container_label_Description="",
    container_label_Vendor="",
    container_label_Version="",
    container_label_alertmanager_access="",
    container_label_annotation_checksum_config="",
    container_label_annotation_checksum_secret="",
    container_label_annotation_io_kubernetes_container_hash="4c81184f",
    container_label_annotation_io_kubernetes_container_ports="[{\"name\":\"http\",
    \"containerPort\":8080,
    \"protocol\":\"TCP\"}]",
    container_label_annotation_io_kubernetes_container_preStopHandler="",
    container_label_annotation_io_kubernetes_container_restartCount="0",
    container_label_annotation_io_kubernetes_container_terminationMessagePath="/dev/termination-log",
    container_label_annotation_io_kubernetes_container_terminationMessagePolicy="File",
    container_label_annotation_io_kubernetes_pod_terminationGracePeriod="0",
    container_label_annotation_kubernetes_io_config_seen="",
    container_label_annotation_kubernetes_io_config_source="",
    container_label_annotation_kubernetes_io_psp="",
    container_label_annotation_prometheus_io_path="",
    container_label_annotation_prometheus_io_port="",
    container_label_annotation_prometheus_io_scrape="",
    container_label_app="",
    container_label_app_type="",
    container_label_caas_tenant_operator_access="",
    container_label_chart="",
    container_label_controller_revision_hash="",
    container_label_description="",
    container_label_enabled="",
    container_label_goss_access="",
    container_label_heritage="",
    container_label_io_kubernetes_container_logpath="/var/log/pods/kube-system_cadvisor-2pd9r_6d91e1dd-d002-11e9-82e8-fa163e33a25d/cadvisor/0.log",
    container_label_io_kubernetes_container_name="cadvisor",
    container_label_io_kubernetes_docker_type="container",
    container_label_io_kubernetes_pod_name="cadvisor-2pd9r",
    container_label_io_kubernetes_pod_namespace="kube-system",
    container_label_io_kubernetes_pod_uid="6d91e1dd-d002-11e9-82e8-fa163e33a25d",
    container_label_io_kubernetes_sandbox_id="b46a2b9633464a10c480a96d2fa0995cd21a9b9298023afa1c2ef1d766a098c0",
    container_label_k8s_app="",
    container_label_maintainer="",
    container_label_maintainers="",
    container_label_minio_client="",
    container_label_name="",
    container_label_org_label_schema_description="",
    container_label_org_label_schema_docker_schema_version="",
    container_label_org_label_schema_name="",
    container_label_org_label_schema_url="",
    container_label_org_label_schema_vendor="",
    container_label_org_label_schema_version="",
    container_label_org_opencontainers_image_authors="",
    container_label_org_opencontainers_image_created="",
    container_label_org_opencontainers_image_description="",
    container_label_org_opencontainers_image_documentation="",
    container_label_org_opencontainers_image_revision="",
    container_label_org_opencontainers_image_source="",
    container_label_org_opencontainers_image_title="",
    container_label_org_opencontainers_image_url="",
    container_label_org_opencontainers_image_vendor="",
    container_label_org_opencontainers_image_version="",
    container_label_pdb="",
    container_label_pod_template_generation="",
    container_label_pod_template_hash="",
    container_label_pushgateway_access="",
    container_label_release="",
    container_label_revision="",
    container_label_statefulset_kubernetes_io_pod_name="",
    container_label_thanos_peer="",
    container_label_version="",
    container_label_zone="",
    id="/kubepods/pod6d91e1dd-d002-11e9-82e8-fa163e33a25d/45771f36ba7f04e57097ef0e5175ce649432dd2d2c9966840f0d12ee724e1eba",
    image="sha256:752d61707eac173cfe56a23aa9de051597444286163667d60f8e6d4c63306472",
    name="k8s_cadvisor_cadvisor-2pd9r_kube-system_6d91e1dd-d002-11e9-82e8-fa163e33a25d_0"} 1.609408e+06 1568364193870
</details>

That looks strange: the cadvisor-2pd9r never had the `alertmanager-access` label:
```bash
# docker inspect `docker ps | grep cadvisor-2pd9r |grep -v pause | cut -d' ' -f1 `
...snip...
"Labels": {
    "annotation.io.kubernetes.container.hash": "4c81184f",
    "annotation.io.kubernetes.container.ports": "[{\"name\":\"http\",\"containerPort\":8080,\"protocol\":\"TCP\"}]",
    "annotation.io.kubernetes.container.restartCount": "0",
    "annotation.io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
    "annotation.io.kubernetes.container.terminationMessagePolicy": "File",
    "annotation.io.kubernetes.pod.terminationGracePeriod": "0",
    "io.kubernetes.container.logpath": "/var/log/pods/kube-system_cadvisor-2pd9r_6d91e1dd-d002-11e9-82e8-fa163e33a25d/cadvisor/0.log",
    "io.kubernetes.container.name": "cadvisor",
    "io.kubernetes.docker.type": "container",
    "io.kubernetes.pod.name": "cadvisor-2pd9r",
    "io.kubernetes.pod.namespace": "kube-system",
    "io.kubernetes.pod.uid": "6d91e1dd-d002-11e9-82e8-fa163e33a25d",
    "io.kubernetes.sandbox.id": "b46a2b9633464a10c480a96d2fa0995cd21a9b9298023afa1c2ef1d766a098c0"
}
...snip...
```

How come we see the `container_label_alertmanager_access` prometheus label above?

It turns out the `alertmanager-access` label is set in another container running on the local node:
```json
# docker inspect SomeAnotherContainerId
"Labels": {
    "alertmanager-access": "true",
    "app": "prometheus",
    "chart": "prometheus-0.1.0",
    "controller-revision-hash": "prometheus-559cdb9cd7",
    "io.kubernetes.container.name": "POD",
    "io.kubernetes.docker.type": "podsandbox",
    "io.kubernetes.pod.name": "prometheus-1",
    "io.kubernetes.pod.namespace": "monitoring",
    "statefulset.kubernetes.io/pod-name": "prometheus-1",
    "thanos-peer": "true"
}
```

**Comment by dashpole** [comment]
Yeah... prometheus enforces that all metrics with the same name have the same label set, so a label on one metric means all other metrics must have the label set as well.

Many users have hit this, so we added `--store_container_labels` and `--whitelisted_container_labels` flags.  Setting `--store_container_labels=false` means container labels are not automatically added to prometheus metrics.  Additionally setting `--whitelisted_container_labels='key1,key2` will add labels with key1 and key2 back in.

**Comment by sbueringer** [comment]
@dashpole Thx for the hint. Makes sense to me. I think we'll use the container label whitelist to solve our problem. @kabakaev I think think you can close this issue?

**Comment by kabakaev** [comment]
@sbueringer, sure. I just wanted to put our version of `whitelisted_container_labels` into the close comment. But the comment can be updated later.

**Comment by py-wy** [comment]
thanks cadvisor was eating 100% cpu until I have set '--store_container_labels=false' now I can move forward and add whitelisted labels
