### ISSUE TITLE
cAdvisor cannot obtain container Pid from cri-o

### ISSUE THREAD

**Issue by rkojedzinszky** [google/cadvisor#2314]
It seems, that on slower machines, cri-o is not starting up containers enough, that a call to /containers/ will return info with pid == 0. This later makes network usage metrics (and perhaps others) to be retrieved.

The relevant code is in container/crio/client.go, ContainerInfo(). I dont know if a following patch would make any sense:
```
diff --git a/container/crio/client.go b/container/crio/client.go
index e9951362..5a29142a 100644
--- a/container/crio/client.go
+++ b/container/crio/client.go
@@ -133,5 +133,9 @@ func (c *crioClientImpl) ContainerInfo(id string) (*ContainerInfo, error) {
        if err := json.NewDecoder(resp.Body).Decode(&cInfo); err != nil {
                return nil, err
        }
+       // Container might not have started up
+       if cInfo.Pid == 0 {
+               return nil, fmt.Errorf("Error finding pid for container %s", id)
+       }
        return &cInfo, nil
 }
```

It would make code retry the failing containers later, I think.

The same as https://github.com/kubernetes/kubernetes/issues/82709

**Comment by dashpole** [comment]
Have you tried with the latest version?  I think https://github.com/google/cadvisor/pull/2284 was meant to fix this.

**Comment by rkojedzinszky** [comment]
@dashpole I've not tried, but it seems to aim that too. Then, I will close my pull req. Thanks for pointing me that.
