### ISSUE TITLE
cadvisor reports 0 for CPU load average

### ISSUE THREAD

**Issue by dgkanatsios** [google/cadvisor#2321]
I'm running cadvisor on a Linux VM with the following command:

```bash
sudo docker run \
  --privileged \
  --net=host \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:ro \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/dev/disk/:/dev/disk:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  docker.io/google/cadvisor:v0.33.0 \
  -storage_driver=statsd -storage_driver_host=localhost:8125 \
  -stderrthreshold=0 -v=4
```

Any hints on why it's reporting 0 as load average to my statsd server? I'm generating some dummy jobs and I can see that /proc/loadavg reports numbers > 0.

Thanks!

FWIW, other metrics are reported just fine

**Comment by dashpole** [comment]
make sure you set `--enable_load_reader=true`

**Comment by dgkanatsios** [comment]
and that did the trick, thanks @dashpole!
