### ISSUE TITLE
Filter exported metrics

### ISSUE THREAD

**Issue by dgkanatsios** [google/cadvisor#2322]
I'm using cadvisor with a statsd server to get metrics. Is there any option/configuration in cadvisor that would allow me to export only a subset of these metrics e.g. only the system wide CPU/memory/network?

Thanks!

**Comment by dashpole** [comment]
You can enable/disable sets of metrics using the --disable_metrics flag, and that should cause them to no longer be exported.  These are the metrics that can be disabled: https://github.com/google/cadvisor/blob/master/container/factory.go#L45.  Any metrics you don't specify are assumed to be enabled.

**Comment by dgkanatsios** [comment]
thanks @dashpole! is there (or have you considering adding) an option where you get metrics only for a set of processes and not from everything running on the system?

**Comment by dashpole** [comment]
You can try out `--raw_cgroup_prefix_whitelist`, which defines the tree that cAdvisor collects metrics within.  For example, setting `--raw_cgroup_prefix_whitelist=/kubepods` in kubernetes should return only metrics for pods and contianers, rather than, for example, systemd processes.

**Comment by dgkanatsios** [comment]
great, thanks @dashpole, I'll try that :) 
Closing the issue for now
