### ISSUE TITLE
How to get some metic of diskio rate of read/write from one container?

### ISSUE THREAD

**Issue by lwx294821** [google/cadvisor#2334]
There is a container inside one application is  reading and writing files, is there any way to get the rate of reading and writing IO of the internal disk of the container?
1.The application wad developed by Java. 
2.When read or write file, Inevitably use the cache ，so PromQL "rate(container_fs_writes_bytes_total{...}[5m])" cann't get the metric.

**Comment by dashpole** [comment]
If it doesn't show up in container_fs_writes_bytes_total, I don't know if there is a way to monitor it with cAdvisor.  If you can find a linux cgroup metric that gives you what you are looking for, we can consider adding it to cAdvisor.

**Comment by lwx294821** [comment]
I don't  know if there is a way to calculate  the  IO rate of read/write when one processor is working.  Sometimes I  got some useful information by using  "cat /proc/$PID/io" .   I need to get read and write rate at a processor or task level, similar to use  'iotop -p $PID' to see IO rate.Can you provide some help?
