### ISSUE TITLE
missing container name if user remapping is enabled

### ISSUE THREAD

**Issue by tavolodobela** [google/cadvisor#2336]
I use docker 19.03.4 with latest cadvisor image (v0.32.0). I also scrape the metrics with prometheus. The problem is that I have enabled the user remapping feature, and it seems to break the metrics output that it won't provide name="" nor image="" labels:

container_memory_rss{id="/docker/19359d07154100a38425d64afd088b66d3b48a594e4ffe66948d634f1b3b72b9"} 8.6892544e+07

Without the user remapping enabled I can see both the name and image labels, eg.

container_memory_rss{id="/docker/a91de9b2a98cc5aca6a0e6f9af27b8e9f154ba44dcdee18c1b4c34b2492a1289",image="google/cadvisor:latest",name="cadvisor"} 1.6166912e+07

How can I see the name label with user remapping enabled?

**Comment by dashpole** [comment]
Is there anything in the cAdvisor logs?  Missing container information is usually due to cAdvisor not being able to connect to the docker daemon

**Comment by tavolodobela** [comment]
$ docker logs cadvisor 
E1107 11:08:00.410998       1 info.go:140] Failed to get system UUID: open /etc/machine-id: no such file or directory
W1107 11:08:00.411137       1 info.go:53] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
W1107 11:08:00.412888       1 manager.go:349] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory

Btw. I tried to pass -v /etc/machine-id:/etc/machine-id:ro as well, so only the /dev/kmsg line remained, but the result is the same: no container name in the cadvisor metrics.

How can I debug that cadvisor is able to connect to the docker daemon?

**Comment by dashpole** [comment]
Can you try running cAdvisor with higher verbosity?  `--v 4` should do the trick

**Comment by tavolodobela** [comment]
Please find the -v logs attached.

[verbose-log.txt](https://github.com/google/cadvisor/files/3835380/verbose-log.txt)

**Comment by dashpole** [comment]
>  I1112 08:15:17.466836       1 factory.go:54] Registering systemd factory
I1112 08:15:17.470797       1 factory.go:97] Registering Raw factory

It doesn't look like the docker factory registered at all.  But I don't see an error message either...

**Comment by dashpole** [comment]
Ah, appologies.  The registration errors for factories are V(5): https://github.com/google/cadvisor/blob/8949c822ea91fa6b4996614a5ad6ade840be24ee/manager/manager.go#L301

You will have to re-run with --v 5 to get the docker connection error.

**Comment by tavolodobela** [comment]
I think I've nailed it. Since the cadvisor container also runs under user remapping, though it runs as root (inside the container), it's not really root. So by passing --userns=host to the docker run arguments finally made it work properly. I can see the name and image labels. Perhaps this info is worth to a FAQ or similar :-)

Anyway, if you still need the -v 5 logs, I can attach it.

**Comment by dashpole** [comment]
That makes sense.  I don't need the logs.  Actually, it looks like it is already in our docs: https://github.com/google/cadvisor/blob/master/docs/running.md#running-cadvisor
