### ISSUE TITLE
CRI-O containers support (Without docker installed)

### ISSUE THREAD

**Issue by YanzheL** [google/cadvisor#2344]
Does cadvisor support "pure" CRI-O containers? I mean, there is no `docker.sock` or 'containerd.sock' .on the host, just crio.

From the runtime options, I can only see `-docker unix:///var/run/docker.sock` and `-containerd unix:///var/run/containerd.sock`, so it seems like there is no support for `unix:///var/run/crio/crio.sock`

I tried to mount `/var/run/crio/crio.sock:/var/run/crio/crio.sock` inside cadvisor container, but it cannot auto-detect it.

#### Environment
crio: 1.15.2
cadvisor: 0.33.0
OS: CentOS-7.7

**Comment by dashpole** [comment]
Yes, we do have support.  It should work as long as the socket is at /var/run/crio/crio.sock ...

https://github.com/google/cadvisor/blob/master/container/crio/client.go#L27

**Comment by dashpole** [comment]
It looks like the socket is hard-coded, which explains why there isn't a flag.

**Comment by YanzheL** [comment]
Are CRI-O containers listed in the "Subcontainers" section?

In "Subcontainers", I cannot recognize any containers of my app, because it shows me totally different outputs than what I see in `crictl ps -a`.

![image](https://user-images.githubusercontent.com/25402886/69724818-a10c8280-1157-11ea-8e1f-2787085b6954.png)

![image](https://user-images.githubusercontent.com/25402886/69725196-84bd1580-1158-11ea-9fb2-5a96684ffa84.png)

If I click "Docker Containers", it shows me `failed to get docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

Is it normal?

**Comment by dashpole** [comment]
Ah, it sounds like the UI doesn't work with non-docker container runtimes... You should be able to get prometheus metrics by querying cAdvisor's `/metrics` endpoint and search for metrics for your application.
