### ISSUE TITLE
v0.35.0 image doesn't exist

### ISSUE THREAD

**Issue by lubo** [google/cadvisor#2346]
Two days after releasing v0.35.0, `gcr.io/google_containers/cadvisor:v0.35.0` image still doesn't exist.

**Comment by dashpole** [comment]
Yes, there is a qualification process for cAdvisor images that it is still going through.  It will be pushed once it is approved by that process.

**Comment by lubo** [comment]
Is that process open? Where can I learn more about it?

**Comment by dashpole** [comment]
It doesn't appear to be, and i'm not personally familiar with the internals.  I would expect it to be up in the next week.
