### ISSUE TITLE
Docker Host info in cadvisor_version_info

### ISSUE THREAD

**Issue by bmkrkolli** [google/cadvisor#2353]
It is better to have Docker Host Info like hostname, fqdn, os etc to be included in cadvisor_version_info metric.
It will help to identify on which docker host the metric is coming from.

**Comment by bmkrkolli** [comment]
My bad
{{ printf \"cadvisor_version_info\" | query | first }}
Adding above line in alert summary is sending the Docker Host Info

**Comment by shayanshabaniii** [comment]
> My bad {{ printf "cadvisor_version_info" | query | first }} Adding above line in alert summary is sending the Docker Host Info

Hi
I need to get info from Docker's host
but in cadvisor_version_info  metric I have this:
`cadvisor_version_info{cadvisorRevision="7dfeea7d",cadvisorVersion="v0.47.1",dockerVersion="",kernelVersion="4.12.14-lp151.28.36-default",osVersion="Alpine Linux v3.16"} 1`

how I can add docker info to this result?
