### ISSUE TITLE
Feature Request: allow configuration of http/api path

### ISSUE THREAD

**Issue by karl-tpio** [google/cadvisor#2377]
I am sorry i can't just open a PR... i am not a very seasoned goLang dev.

I did look through the `.go` files that appear to handle the `/api/*` requests, and the change did look pretty reasonable. But then i did a search for `/containers` and found that the path appears to be hard-coded in multiple places... which might make this a bit harder to implement. If that's the case, i completely get it.

In any event, I am requesting a `--http_base_path=/containers` or similar command line option which will change the base path that all web resources are loaded from.

**The Reason** for the ask: I use `cadvisor` and some other monitoring software - call it `netmon` for the purposes of this post - on each of my individual hosts. Both `cadvisor` and `netmon` sit behind a reverse proxy that performs authentication and enforces some TLS/Cipher requirements.

*unfortunately* both `cadvisor` and `netmon` both use a hard-coded `/api` path. Neither supports changing this, and this makes it impossible to tell the reverse proxy to route (authenticated) requests to `/api/*` to the correct host/port.

Thanks for your time. Happy to provide more detail if needed and or work on documentation.

**Comment by dashpole** [comment]
Can does `url_base_prefix` meet your needs?  See https://github.com/google/cadvisor/pull/2117

**Comment by karl-tpio** [comment]
@dashpole  Yes it does!

I'm ashamed to admit that i didn't fully go through the `--help` text, only consulted the doc here:
https://github.com/google/cadvisor/blob/master/docs/runtime_options.md

Shall i close this issue and open a PR against that document to include the `url_base_prefix` option?

**Comment by dashpole** [comment]
Please do, thanks.

**Comment by karl-tpio** [comment]
Done!

https://github.com/google/cadvisor/pull/2379
