### ISSUE TITLE
container_fs_writes_bytes_total does not behave as expected

### ISSUE THREAD

**Issue by DrmagicE** [google/cadvisor#2378]
I run a centos container to test the metrics:`docker run -itd centos /bin/bash`  and  generate a  test  file in container with the following `dd` command：`dd if=/dev/zero of=test bs=100M count=5 && sync`. I expect `container_fs_writes_bytes_total` should increase about 500MB. 

I search in prometheus with  `container_fs_writes_bytes_total{image="centos"}`  and find that the metric does not change or just increase a few MB. 

But if i search with `sum(container_fs_writes_bytes_total{})`, the result is increased about 500MB.  Why? Is this expected. If so, how can i get correct `container_fs_writes_bytes_total` of a specific container?

I run cadvisor with latest docker images：
```
docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:ro \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/dev/disk/:/dev/disk:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  gcr.io/google-containers/cadvisor:latest
```

**Comment by dashpole** [comment]
Where are the writes being reported under?  I.E. if it isn't that container, which container is it reporting under?

**Comment by DrmagicE** [comment]
I look into cgroup stats file:
```
/sys/fs/cgroup/blkio/docker/$container_id
cat blkio.throttle.io_service_bytes
253:0 Read 432619520
253:0 Write 27766784  <---  the same as cadvisor reported
253:0 Sync 27406336
253:0 Async 432979968
253:0 Total 460386304
Total 460386304
```
Maybe this is a cgroup issue?

**Comment by dashpole** [comment]
cAdvisor basically just reads cgroup files, so it is almost definitely a cgroup issue.  But i'm not sure if its WAI or not.  Often it is just a misunderstanding of what the value means on our side...

**Comment by DrmagicE** [comment]
if I add `oflag=direct` to dd: `dd if=/dev/zero of=test bs=100M count=5 oflag=direct`, or just reduce `bs`, e.g: `dd if=/dev/zero of=test bs=10M count=5`, the cgroup file shows expected value. Seems there are some differences between `dd xxx & sync` and `dd xxx oflag=direct`.

**Comment by josefwilfinger** [comment]
why closed? it still does not work. in version 19.03.6
