### ISSUE TITLE
Support for IPv6?

### ISSUE THREAD

**Issue by stevebail** [google/cadvisor#2423]
Does cAdvisor (the deamonSet) support IPv6?
If so, any configuration needed (e.g. arguments to pass)?

**Comment by dashpole** [comment]
I believe it does.  We have some network metrics which have "6" at the end of them: https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L898.  There shouldn't be any arguments to pass other than enabling the relevant metric using `--ignore-metrics`, and not specifying `tcp` for example.
