### ISSUE TITLE
Add 'bot' user to cAdvisor CI s390x

### ISSUE THREAD

**Issue by Nayana-ibm** [google/cadvisor#2436]
Hello,
This is with reference to https://github.com/google/cadvisor/pull/886
We had setup cadviosr CI for s390x using GHPRB plugin as disscued [here](https://github.com/google/cadvisor/pull/886#issuecomment-163346648)

Earlier we were using GitHub 'bot' user (zSys-bot) with collaborator access and Push & Pull rights provided by cAdvisor community. However zSys-bot user is not working now so we have to create a new bot user (zarch-bot) . Could you please add this user as collaborator and also make necessary settings (like webhooks et.) so that we can get triggers for build on s390x CI job.

Please let me know if you need more info.

**Comment by dashpole** [comment]
zarch-bot now has access.  Can I remove the zSys-bot?

**Comment by Nayana-ibm** [comment]
@dashpole thank you.  yes, remove the zSys-bot user.  
Now I am checking if we are getting build triggers on PR

**Comment by dashpole** [comment]
removed

**Comment by Nayana-ibm** [comment]
@dashpole We had setup cadviosr CI for s390x using GHPRB plugin as disscued [here](https://github.com/google/cadvisor/pull/886#issuecomment-163346648) and added zarch-bot user. 

The build should get trigger whenever PR gets comment as ok-to-test ( we have configured job for this). However build is not getting triggered. 
Any suggestions?

**Comment by dashpole** [comment]
the ok-to-test command is only triggered for people who are not members of the cAdvisor repo, so not all PRs will have that comment placed.

**Comment by Nayana-ibm** [comment]
@dashpole Yes..I was checking PRs those have ok-to-test command and still builds are not getting triggered. 
Here are the configurations made at our end. Could you please take a look

**On Jenkins -> Configure system**
![j1](https://user-images.githubusercontent.com/20816038/79563238-0393fa00-80ca-11ea-8da3-5feebf237337.PNG)
![j2](https://user-images.githubusercontent.com/20816038/79563256-0b539e80-80ca-11ea-883c-200d3d2d8729.PNG)

**On slave node for RHEL:**
![image](https://user-images.githubusercontent.com/20816038/79563381-540b5780-80ca-11ea-922b-799ee09cfd06.png)

![slave_2](https://user-images.githubusercontent.com/20816038/79563278-1dcdd800-80ca-11ea-8040-07a4ec027ae3.PNG)
![slave_3](https://user-images.githubusercontent.com/20816038/79563267-127aac80-80ca-11ea-9ef0-4eb16a704662.PNG)

Am I missing anything here? Please let me know.

**Comment by dashpole** [comment]
Sorry, i've never used jenkins before... I tried closing and reopening the referenced PR, but I don't think that helped

**Comment by Nayana-ibm** [comment]
@dashpole I noticed that cadvisor now uses prow CI. As we are facing issues with Jenkins, thought to check with prow. Is it possible to extend existing cadvisor Prow CI setup for s390x? Can we add slave nodes to Prow CI? Please let us know

**Comment by dashpole** [comment]
I believe this is the configuration we use to specify the images we run on: https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/image-config.yaml.  It is the same configuration that is used by kubernetes sig-node to run their tests.

**Comment by Nayana-ibm** [comment]
@dashpole Thank you for info. We will look into configuration

**Comment by Nayana-ibm** [comment]
@dashpole We are trying to setup prow CI. Just keeping this issue open in case we need any info

**Comment by Nayana-ibm** [comment]
closing the issue. 
Will create other one in case of any issue with Prow CI
