### ISSUE TITLE
go.mod/go.sum/vendor directory are out of date for 0.36.0.

### ISSUE THREAD

**Issue by williamh** [google/cadvisor#2453]
Hello.

I was working on building cadvisor for Gentoo and I noticed by running go mod tidy on v0.36.0 that the go.mod/sum files are out of date.
Can we have a 0.36.1 that just updates the go.mod, go.sum and vendor directories for 0.36?
I need to use the information from there to create a build script for Gentoo, so this would be very helpful.

Thanks,

William

**Comment by dashpole** [comment]
Our release cadence is aligned with kubernetes.  Are you unable to vendor by commit hash for some reason?

**Comment by williamh** [comment]
Since there is a vendor directory in your repository, we assume that the contents of that directory is up to date. If It isn't, it is easy to ignore this vendor directory and pull down the dependencies based on go.mod/go.sum contents.

Where does your build system pass the "-mod=vendor" flag to go? If I know that I can disable it in my package manager's build script for this release.

**Comment by dashpole** [comment]
We recently removed the vendor directory for that very reason.

**Comment by williamh** [comment]
As you see in the previous comment, I  was able to fix this on the Gentoo side by removing the vendor directory from the build and using the contents of go.sum to determine the dependencies.

Thanks a lot for pointing out that you removed your vendor directory. That will actually make our downstream builds easier.
