### ISSUE TITLE
Why cadvisor consumes so much CPU resource?

### ISSUE THREAD

**Issue by DanielYWoo** [google/cadvisor#2459]
I am running many containers on ubuntu 18.04, it seems that cadvisor consumes much more resources than other containers. Are there any way to make cadvisor consume less CPU resource? My server is optimized for low power consumption.

![Screen Shot 2020-04-02 at 3 34 24 PM](https://user-images.githubusercontent.com/514417/78222330-a60f8300-74f7-11ea-8826-cd06e70f7cdf.png)

**Comment by dashpole** [comment]
There are a few things you can do to reduce CPU usage.  It basically boils down to "collect fewer metrics".

I would recommend playing around with --disable_metrics.  A good place to start is `--disable_metrics=percpu,hugetlb,sched,tcp,udp,advtcp` from https://github.com/google/cadvisor/blob/master/deploy/kubernetes/overlays/examples/cadvisor-args.yaml#L19.

The most expensive metric is disk, as we walk file trees of container writable layers.  If you don't need it, consider adding `disk` to disable_metrics above.

You can also consider setting the --docker_only flag if you only want metrics from containers.

**Comment by DanielYWoo** [comment]
Thanks for your help. I already have --docker_only days ago, that won't work. I will try disable_metrics soon.

**Comment by DanielYWoo** [comment]
I disabled everything except process metrics, set --docker_only, set prometheus scrape interval to 30 seconds, it still consumes most of CPU resource. Anything else I can do?

**Comment by dashpole** [comment]
If you are going to scrape less frequent, you can also lengthen the housekeeping interval (which actually controls collection) with `--housekeeping_interval`.  Also, how large is your machine?  Just curious what the CPU usage is in cores, rather than %

**Comment by DanielYWoo** [comment]
Ar ha, currently I run docker contains on my ubuntu NAS (AMD 2200g, 24G RAM, 17T disks). It's my toy, not a working machine. I am trying to minimize the power consumption, stop the disks whenever possible, lower the CPU frequency etc. Next, I will run cadvisor and prometheus on my Raspberry PI to monitor my NAS, test server, router, AP with a dozen of docker containers, and detect temperatures at multiple positions in my 15u rack with DHT11 cheap sensors, and maybe record PM2.5 indicators in my rooms via some cheap Arduino devices. Then send alerts to my phone.

Alright, it's for fun ;-)  I have a LCD meter on my PDU to monitor power consumption. I just want to see  how less power consumption it could be since I need to run them 7x24 and I want to keep the world green. ;-)

I will try housekeeping_interval for another 12 hours to see if it works, thanks!

**Comment by DanielYWoo** [comment]
After 2 hours test, it seems to be working if I change housekeeping_interval longer. Thanks a lot!
