### ISSUE TITLE
Update ContainerInfo struct for crio client

### ISSUE THREAD

**Issue by tedyu** [google/cadvisor#2462]
Here are the new fields in ContainerInfo struct from cri-o master branch:
```
        ImageRef        string            `json:"image_ref"`
        CrioAnnotations map[string]string `json:"crio_annotations"`
        Sandbox         string            `json:"sandbox"`
```
This field from cri-o corresponds to the IP field in the cadvisor counterpart:
```
        IPs             []string          `json:"ip_addresses"`
```

**Comment by dashpole** [comment]
Are you suggesting we need to update our crio client?  Is there a bug that needs to be fixed?

**Comment by tedyu** [comment]
crio client doesn't have compile time dependency on cri-o.
If the json response has fields which are not defined in ContainerInfo struct of cadvisor, they would be ignored.

The fields mentioned above are supported by latest cri-o release. Hence I propose adding them to ContainerInfo struct of cadvisor.

**Comment by dashpole** [comment]
What is the reason you want to add them?  Would they be new fields in container info, or filling in fields that are left empty today?

**Comment by tedyu** [comment]
This is in regards to new fields.
Can wait till the use case is more mature.
