### ISSUE TITLE
cadvisor doesn't distinguish sockets and NUMA nodes in MachineInfo.Topology

### ISSUE THREAD

**Issue by AlexeyPerevalov** [google/cadvisor#2470]
On x86 server with NUMA topology, when number of NUMA nodes is not equal to number of sockets
MachineInfo.Topology contains sockets instead of NUMA nodes.
On aarch64 architecture MachineInfo.Topology consists of correct NUMA nodes.

Code in https://github.com/google/cadvisor/blob/16ebc4c053a49948dbb1dc75c64efcef86638b50/machine/machine.go#L214 goes through /proc/cpuinfo, but it's better to follow approach which was implemented in https://github.com/kubernetes/kubernetes/blob/c1f1b1bceb8e6dfbc0083617a25f17dd8d57340b/pkg/kubelet/cm/cpumanager/topology/topology.go#L290
by traversing on /sys/devices/system/node/online, looks like this approach:

1. has lesser code/runtime complexity
2. works for most architectures (no need to add isAArch64 conditions)

**Comment by katarzyna-z** [comment]
@AlexeyPerevalov Which version of cAdvisor do you use? #2427 introduced reading of information about NUMA node only from "/sys/devices/system/node/"

**Comment by AlexeyPerevalov** [comment]
Oh, thank you, my HEAD was on  9251e327b9eff094bf1503c362c0568185ca3601 (about one month ago), and before submitting I was looking for an issue.
