### ISSUE TITLE
container_cpu_load_average_10s is always coming zero

### ISSUE THREAD

**Issue by manoj-k-kumar** [google/cadvisor#2529]
Hi Experts,
I am using release-v0.34 of cAdvisor, and deploying it in a docker container. I do set enable_load_reader. But I am still getting load as zero for all the containers in the docker host. Am I missing some configuration? Here are some relevant config from docker inspect:
           "Entrypoint": [
                "/usr/bin/cadvisor",
                "--disable_metrics=udp,sched,tcp",
                "--enable_load_reader=true"
            ],
...
       "HostConfig": {
            "Binds": [
                "/dev/disk:/dev/disk:ro",
                "/var/lib/docker:/var/lib/docker:ro",
                "/:/rootfs:ro",
                "/var/run:/var/run:ro",
                "/sys:/sys:ro",
                "/cgroup:/cgroup:ro"
            ],
....
           "PidMode": "host",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,

**Comment by dashpole** [comment]
You need to run on the host network for the load reader to work.

**Comment by manoj-k-kumar** [comment]
Please explain how to do that. Is it just the flag "hostNetwork: true"? 
or a network configuration like ..
    networks:
      - <some-network>

**Comment by dashpole** [comment]
https://github.com/google/cadvisor/issues/2051#issuecomment-424432574

**Comment by manoj-k-kumar** [comment]
Thanks so much @dashpole for the hint! I am not deploying in kuberenetes cluster, but just in a docker container. So adding this config helped!
**network_mode: host**
I hope this is the right one as I started getting load from other containers in the same docker host. 

There is still a minor glitch though. Occasionally loads from some containers come as zero. Is there any other fine tuning?

**Comment by dashpole** [comment]
CPU Load is an interesting metric...  It is the 10s average of the number of threads running (https://github.com/google/cadvisor/blob/master/utils/cpuload/netlink/reader.go#L63).  But IIRC, housekeeping is 10-15s, so it is really a single sample (not an average of multiple samples).  You don't get consistent values for cpu load average since it is an instantaneous metric.

**Comment by manoj-k-kumar** [comment]
Thanks again @dashpole!
