### ISSUE TITLE
http: superfluous response.WriteHeader

### ISSUE THREAD

**Issue by katarzyna-z** [google/cadvisor#2537]
Sometimes /metrics endpoint does not respond and in logs there is following information:
```
2020/05/08 09:09:20 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:344)
2020/05/08 09:10:39 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:344)
2020/05/08 09:10:46 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:344)
2020/05/08 09:11:26 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:344)
2020/05/08 09:11:32 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:344
```
There is an issue in client-golang which could be related: https://github.com/prometheus/client_golang/issues/672

**Comment by nightah** [comment]
Also seeing similar issues with my instance of cadvisor:
```
2020/05/08 15:58:35 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:306)
2020/05/08 15:58:40 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:306)
2020/05/08 15:58:45 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:306)
2020/05/08 15:58:50 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:306)
2020/05/08 15:58:55 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:306)
2020/05/08 15:59:00 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:306)
```

A restart seems to restore the service, however, this intermittently will pop up again.

**Comment by katarzyna-z** [comment]
> A restart seems to restore the service, however, this intermittently will pop up again.
I have the same observations.

**Comment by romulolibralon** [comment]
In my case this is happening because a have a lot of information from my metrics. Im also trying to find the solution.

**Comment by nightah** [comment]
@dashpole https://github.com/prometheus/client_golang/releases/tag/v1.5.1 seems to suggest that the bug was fixed upstream.

Just looking at node_exporter to see if there's any correlation in client_golang and while I know I have not experienced this issue in node_exporter they are running: `github.com/prometheus/client_golang v1.6.0`.

I'll perform some testing locally first to see if this does indeed resolve the issue. Assuming it does I'll submit a PR accordingly.
