### ISSUE TITLE
Repeated logs: Not collecting filesystem statistics because file "/proc/diskstats" was not found

### ISSUE THREAD

**Issue by RKVoddapelly** [google/cadvisor#2544]
Running cadvisor on centos 7 and it shows in logs that for every 1 or 2 seconds it raises a message "Not collecting filesystem statistics because file "/proc/diskstats" was not found"
I am running centos on top of virtuozzo container which does't provide /proc/diskstats. In such case how to run cAdvisor.

**Comment by RKVoddapelly** [comment]
I am running centos on top of virtuozzo container which does't provide /proc/diskstats. In such case how to run cAdvisor.

**Comment by dashpole** [comment]
try making sure you have --disable_metrics set, and that it includes disk and diskIO.  Then container collection shouldn't require parsing /proc/diskstats

**Comment by RKVoddapelly** [comment]
Even after setting --disable_metrics with disk and diskIO it continuosly logs the following (like every 1 second, and my log is being filled by this): 
1 fs.go:434] Not collecting filesystem statistics because file "/proc/diskstats" was not found

**Comment by dashpole** [comment]
Ah, my bad... It looks like we need proc/diskstats to collect metrics for the root cgroup even when those metrics are disabled for other containers: https://github.com/google/cadvisor/blob/050551287c93c67d318131f7c593ce61cae7de85/container/raw/handler.go#L197
