### ISSUE TITLE
Adding podIp to 'DefaultContainerLabels' , is that meaningful?

### ISSUE THREAD

**Issue by w0nwig** [google/cadvisor#2591]
I'm a developer from china. For the company i work for, we use an application monitoring system called CAT which records application's monitoring data by podIp. When we come across a problem, it's not convenient that CAT provides the monitoring data based on ip while prometheus provides the data based on podName. It's a question that confusing me for a long time. So, Adding podIp to 'DefaultContainerLabels' , is that meaningful?

**Comment by dashpole** [comment]
What orchestrator are you using?  We probably don't want to add it to defaultcontainerlabels, but could consider adding a container_spec metric for the IP that you could join with

**Comment by w0nwig** [comment]
We are using docker in kubernetes. Could you tell me why cadvisor doesn't collect container's ip information? Adding a container_spec metric for the IP, that would be awesome!

**Comment by dashpole** [comment]
It does collect it, it just doesn't expose a prometheus metric for it.

**Comment by w0nwig** [comment]
It's true. If i fork the repository and want to implement the feature, which branch should i create branch from, release-v0.36 or master?

**Comment by dashpole** [comment]
master

**Comment by w0nwig** [comment]
Adding ip to the **metrics' labels**, that would be convenient. 
Like you say, **expose a prometheus metric for container's ip**, that may not solve my problem. I can't query the metrics by the ip of the container.

**Comment by dashpole** [comment]
You would have to join the ip metric with the metric you care about to add the label

**Comment by w0nwig** [comment]
For example, a timeseries like container_cpu_usage_seconds_total{container_label_app="abc"}, i can't query the timeseries by the container's ip , so i want to add ip label to the timeseries, which would seem like  container_cpu_usage_seconds_total{container_label_app="abc", container_ip="1.2.3.4"}. 
 
From your words above, **join the ip metric with the metric** , i can't figure out what that means. 
Hope my confusion doesn't bother you.

**Comment by dashpole** [comment]
You would use the `On` and `group_left` keywords in promql.  See https://prometheus.io/docs/prometheus/latest/querying/operators/#many-to-one-and-one-to-many-vector-matches.  Googling "prometheus join" or "prometheus group_left" will probably provide better explanations than I can here.

**Comment by w0nwig** [comment]
Understood. Thanks a lot.

**Comment by w0nwig** [comment]
We’re running docker along with kubernetes on a cloud vendor called aliyun from china. The truth is ipAddress is ‘’ when i execute command ‘docker inspect ${container_id}’ on the host, so is the pause container. What is the reason for that?

**kubernetes version: 1.12
cni plugin: Flannel v0.8
Docker: 18.09.2
related cadvisor’s code**

related cadvisor’s code
`
	ipAddress := ctnr.NetworkSettings.IPAddress
	networkMode := string(ctnr.HostConfig.NetworkMode)
	if ipAddress == "" && strings.HasPrefix(networkMode, "container:") {
		containerID := strings.TrimPrefix(networkMode, "container:")
		c, err := client.ContainerInspect(context.Background(), containerID)
		if err != nil {
			return nil, fmt.Errorf("failed to inspect container %q: %v", id, err)
		}
		ipAddress = c.NetworkSettings.IPAddress
	}
`

**Comment by dashpole** [comment]
What is the network mode for the container?

**Comment by w0nwig** [comment]
Container. The output is like this:
```
"NetworkMode": "container:d01ee105ef005c432d47a5bfee53ffc6b728846c3560678ebf0854d639ffcc38"
```
Obviously, d01ee105ef005c432d47a5bfee53ffc6b728846c3560678ebf0854d639ffcc38 is the id of the pause container.

According to cadvisor's code , i execute 'docker inspect d01ee105ef005c432d47a5bfee53ffc6b728846c3560678ebf0854d639ffcc38' to see ipAddress  of it's pause. It's '' too.

**Comment by dashpole** [comment]
You are right.  At least in kubernetes, that doesn't seem to work.  I wonder if it was added for docker (only) users...  It looks like you have to inspect the network interfaces associated with the container, which is a bit more challenging

**Comment by w0nwig** [comment]
When i execute 'docker exec -t b07cee1aa30f ifconfig' on the host, i can get the ip of the container:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.104.26.233  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 0a:58:0a:68:1a:e9  txqueuelen 0  (Ethernet)
        RX packets 3624152  bytes 681964342 (650.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2802256  bytes 568624196 (542.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 10  bytes 770 (770.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10  bytes 770 (770.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Or i can use the restful api of the api-server, which looks like '/api/v1/namespaces/{namespace}/pods/{name}' to get the pod's ip, which actually is also the container's ip. 

I wonder which way is more suitable  and practical.

**Comment by dashpole** [comment]
cAdvisor should not call out to the api-server.

However, it looks like kube-state-metrics already does this: https://github.com/kubernetes/kube-state-metrics/blob/master/internal/store/pod.go#L42.  You should be able to join that metric with cAdvisor metrics to add the pod IP as a label.  You would have to run KSM in your cluster with pod metrics enabled, and collect metrics from it.

**Comment by w0nwig** [comment]
All right. I will try KSM. Really appreciate your help.
