### ISSUE TITLE
cadvisor is showing status as unhealthy

### ISSUE THREAD

**Issue by isabelnoronha61** [google/cadvisor#2592]
version: '3.7'
services:
  cadvisor:
    #image: google/cadvisor
    image: gcr.io/google_containers/cadvisor:v0.36.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      #- /cgroup/cpu:/cgroup/cpu
      #- /cgroup/cpuacct:/cgroup/cpuacct
      #- /cgroup/cpuset:/cgroup/cpuset
      #- /cgroup/memory:/cgroup/memory
      #- /cgroup/blkio:/cgroup/blkio
      #- /cgroup:/sys/fs/cgroup:ro
      - /cgroup:/cgroup:ro
    ports:
      - 8080:8080
    privileged: true
    command:
      - --allow_dynamic_housekeeping=true
      - --housekeeping_interval=5m
      - --global_housekeeping_interval=2m
      - --disable_metrics=percpu,sched,tcp,udp,disk,network
      #advtcp
      - --docker_only=true
      - --log_cadvisor_usage=true
      - --profiling=true
      #- --log_cadvisor_usage=true
      #- --log_dir="../logs/out.logs"
      #- --store_container_labels=false
    restart: always
    deploy:
      mode: global

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global

It used to work fine until today.
How should I solve this?

**Comment by dashpole** [comment]
Can you share the cAdvisor logs?

**Comment by isabelnoronha61** [comment]
I'm sorry but I couldn't see any logs either.
docker logs cadvisor showed nothing

**Comment by isabelnoronha61** [comment]
But I got this from docker journactl
time="2020-06-23T17:03:16.163768617+05:30" level=error msg="fatal task error                                       " error="starting container failed: OCI runtime create failed: container_linux.go:348: starting container process c                                       aused \"process_linux.go:402: container init caused \\\"process_linux.go:385: running prestart hook 0 caused \\\\\\                                       \"error running hook: exit status 2, stdout: , stderr: runtime/cgo: pthread_create failed: Resource temporarily una                                       vailable\\\\\\\\nSIGABRT: abort

level=error msg="fatal task error                                       " error="starting container failed: OCI runtime create failed: container_linux.go:348: starting container process c                                       aused \"process_linux.go:402: container init caused \\\"process_linux.go:385: running prestart hook 0 caused \\\\\\                                       \"fork/exec /proc/33012/exe: resource temporarily unavailable\\\\\\\"\\\"\": unknown" module=node/agent/taskmanager

**Comment by isabelnoronha61** [comment]
It's working fine now.
I don't  know the root cause though.

**Comment by dashpole** [comment]
Looks like you ran out of threads on your host, and cAdvisor couldn't start.

**Comment by Mahdigolbaz** [comment]
> It's working fine now.
> I don't know the root cause though.
sorry
i have the same problem how to solv this?
