### ISSUE TITLE
Is there a way to know if a container has stopped working inside a docker swarm service?or if container restarts?

### ISSUE THREAD

**Issue by isabelnoronha61** [google/cadvisor#2595]

**Comment by dashpole** [comment]
You can try using container_last_seen: https://github.com/google/cadvisor/issues/2305 to see if a container has died.  There is container_start_time_seconds as well, but I don't think docker re-creates cgroups, so it may not show restarts

**Comment by isabelnoronha61** [comment]
> You can try using container_last_seen: #2305 to see if a container has died. There is container_start_time_seconds as well, but I don't think docker re-creates cgroups, so it may not show restarts

I'm already using container_last_seen but it is not helping much.
time() - container_last_seen{name=my-container} > 60
However, I get way too many alerts for the containers that have not sent metrics and this isn't helping me really.

Is there a query that monitors the exit status of containers?
A way to know that a particular container has exited with an exit status code?

I believe to use  "absent" all the jobs should be defined. It cannot take dynamic values for labels.

**Comment by dashpole** [comment]
There isn't anything that includes the exit status of containers, as that information isn't obtainable from cgroups AFAICT.

**Comment by isabelnoronha61** [comment]
Thank you!

**Comment by isabelnoronha61** [comment]
Sorry to bother,but is there any query which cadvisor or any exporter that can be used which makes use of docker events?
So I can get metrics in prometheus format?

**Comment by dashpole** [comment]
No worries.  I'm not aware of anything that exports metrics for docker events, but I also haven't ever looked.

**Comment by isabelnoronha61** [comment]
> No worries. I'm not aware of anything that exports metrics for docker events, but I also haven't ever looked.

Thank you , but if anyone is looking to use docker events to monitor containers this is a great project.
https://bitbucket.org/quaideman/dem/src/master/
