### ISSUE TITLE
List of metrics that can be disabled is inaccurate

### ISSUE THREAD

**Issue by sevagh** [google/cadvisor#2602]
cadvisor on Linux amd64, using v0.36.0

Here's a full list of metrics that I should be able to ignore: https://github.com/google/cadvisor/blame/196b510b5270421351122e0ae3e0ea4c0bc2da55/cmd/cadvisor.go#L95 

I noticed that in reality I can only disable the following metrics:

```
CAN DISABLE:
	sched
	process
	disk
	diskIO
	percpu

CANNOT:
	cpu
	memory
	cpuLoad
	accelerator
	app
	hugetlb
	perf_event
	referenced_memory
	cpu_topology
	resctrl
```

My discovery process was simply trying to launch `cadvisor --disable_metrics=$x`, for every value of x in
```
$ cat script.sh
#!/usr/bin/env bash

IFS=','; for b in `echo "sched,process,disk,diskIO,cpu,percpu,memory,cpuLoad,accelerator,app,hugetlb,perf_event,referenced_memory,cpu_topology,resctrl"`;
do
        echo "trying to disable metric $b..."
        sudo /opt/cadvisor/cadvisor --disable_metrics=$b 2>&1 | head -n5
done
```
Script outputs:
```
invalid value "cpu" for flag -disable_metrics: unsupported metric "cpu" specified in disable_metrics
invalid value "memory" for flag -disable_metrics: unsupported metric "memory" specified in disable_metrics
invalid value "cpuLoad" for flag -disable_metrics: unsupported metric "cpuLoad" specified in disable_metrics
invalid value "accelerator" for flag -disable_metrics: unsupported metric "accelerator" specified in disable_metrics
invalid value "app" for flag -disable_metrics: unsupported metric "app" specified in disable_metrics
invalid value "hugetlb" for flag -disable_metrics: unsupported metric "hugetlb" specified in disable_metrics
invalid value "perf_event" for flag -disable_metrics: unsupported metric "perf_event" specified in disable_metrics
invalid value "referenced_memory" for flag -disable_metrics: unsupported metric "referenced_memory" specified in disable_metrics
invalid value "cpu_topology" for flag -disable_metrics: unsupported metric "cpu_topology" specified in disable_metrics
invalid value "resctrl" for flag -disable_metrics: unsupported metric "resctrl" specified in disable_metrics
```

**Comment by dashpole** [comment]
We have added a bunch of categories since the last release.    resctrl, cpu_topology, referenced_memory, perf_event, hugetlb, accelerator were all added since the last release.

I don't think cpu, memory, cpuLoad, or app can be disabled.  Is that documented as possible to disable somewhere?

**Comment by sevagh** [comment]
>I don't think cpu, memory, cpuLoad, or app can be disabled. Is that documented as possible to disable somewhere?

No, those parts of my scripts' output do agree with the expectation - I could've made that clearer.

>We have added a bunch of categories since the last release. resctrl, cpu_topology, referenced_memory, perf_event, hugetlb, accelerator were all added since the last release.

I'll try a build from master to see if I can disable these ones, thanks. I didn't notice there have been 278 commits since v0.36.0.

**Comment by sevagh** [comment]
After building from master, the only one I can't disable is `perf_event`, which is expected according to the help text. Thanks!
