### ISSUE TITLE
When can we expect new tagged release?

### ISSUE THREAD

**Issue by sridhav** [google/cadvisor#2614]
Its been a while a new release has been posted on cAdvisor. When can we expect the new release to be happening? There is a change #2585 we are very much interested in be tagged to a release.

**Comment by dashpole** [comment]
v0.37.0 was released yesterday.

**Comment by sridhav** [comment]
@dashpole The release says its a pre-release, is this expected?

**Comment by dashpole** [comment]
The most recent release is always marked pre-release.  It is moved to latest after the next release.

**Comment by sridhav** [comment]
Thanks for the info @dashpole
