### ISSUE TITLE
Does support for structured application metrics really exist?

### ISSUE THREAD

**Issue by Womagrid** [google/cadvisor#2620]
As far as I can tell, parsing of application metrics configuration fails when it is discovered that metrics_config has 0 length.  This happens if you only specify an endpoint (as shown in one of the documentation examples).  Am I missing something?

**Comment by dashpole** [comment]
Application metrics are not widely used, so it very well may be a bug.

**Comment by Womagrid** [comment]
Thanks.  Just to be clear, that test is only the first obstacle.  I don't think the code to discover the structure of metrics actually exists.

**Comment by Womagrid** [comment]
This was caused by omitting the "prometheus" prefix in the name of the label providing the location of the configuration file.
