### ISSUE TITLE
Release notes of 0.37 report wrong docker image repo

### ISSUE THREAD

**Issue by GiovanniPaoloGibilisco** [google/cadvisor#2624]
Looking ad [this release page ](https://github.com/google/cadvisor/releases/tag/v0.37.0) the image should be available under  `gcr.io/google_containers/cadvisor:v0.37.0` but actually, as said in the release notes images have been migrated to `gcr.io/cadvisor/cadvisor:v0.37.0`

**Comment by dashpole** [comment]
Thanks!  I fixed it.
