### ISSUE TITLE
different number of data points for container_cpu_usage_seconds_total

### ISSUE THREAD

**Issue by pradykaushik** [google/cadvisor#2625]
I'm using prometheus to scrape cAdvisor metrics every 1s.
I'm using this setup to monitor cpu usage of docker containers running in my cluster of 8 servers.

The prometheus query being run is `container_cpu_usage_seconds_total{container_label_task_id!="", container_label_task_hostname!=""}[2s]`.
task_id and task_hostname are container labels that I assign to containers.

When I run this query, I get data that looks like shown below.

| Element                                                                                          | Value                                                        |
|--------------------------------------------------------------------------------------------------|--------------------------------------------------------------|
| container\_cpu\_usage\_seconds\_total\{container\_label\_task\_id="task1", cpu="cpu00", \.\.\.\} | 0\.082544866 @1595273282\.136                                |
| container\_cpu\_usage\_seconds\_total\{container\_label\_task\_id="task1", cpu="cpu01", \.\.\.\} | 0\.082544866 @1595273282\.136 <br> 0\.082869964 @1595273283\.135 |
| container\_cpu\_usage\_seconds\_total\{container\_label\_task\_id="task2", cpu="cpu00", \.\.\.\} | 0\.082544866 @1595273282\.136 <br> 0\.082869964 @1595273283\.135 |
| container\_cpu\_usage\_seconds\_total\{container\_label\_task\_id="task2", cpu="cpu01", \.\.\.\} | 0\.082544866 @1595273282\.136 <br> 0\.082869964 @1595273283\.135 |

As you can see, for task1 and cpu00, there is only a single data point.
Here's my understanding. The CPU scheduler can assign a ready process to any of the available cpus (unless the tasks are pinned). So, it is possible that a task ran for less than 2s on a cpu before being preempted and reassigned to another cpu later on. In such a scenario, looking at the data received, I presume that we need not get 2 data points for cpu usage seconds on all cpus for task. My question is how do we compute CPU utilization in a situation like this?

My current calculation expects two data points and calculates cpu utilization as shown below.

```
n = number of data points.
if n >= 2 {
    cpu utilization on a single cpu = 100 * ((cpu_usage_seconds[n-1] - cpu_usage_seconds[0]) / (n-1) * 
        prometheus_scrape_interval_seconds)
}
```

I also want to add that I'm using just `cpu-shares` resource limiting and not `cpu-quota`.

**Comment by dashpole** [comment]
The two datapoints appear to be at different timestamps.  The per-cpu metrics should report the cumulative usage on _that_ CPU.  So summing across all CPUs should provide the total CPU usage.

**Comment by pradykaushik** [comment]
I'm performing a range query on prometheus for the past 2s. Therefore, I get data points, one for now and one for the previous second.
I just wrote a sample piece of data to show here as otherwise it would get cluttered :)

Okay so what you're saying is that I should sum up the latest cpu usage seconds values for all cpus to get the total CPU usage in seconds? In that case, I don't need 2 data points do I? I could possibly just fetch the cpu usage seconds now and then 1s from now and compute delta in the sums. Am I right?

**Comment by dashpole** [comment]
Yes

**Comment by pradykaushik** [comment]
Awesome!! Thanks for a super quick response as always :)
