### ISSUE TITLE
where is the definition of the window used by cAdvisor for calculating CPU usage rate?

### ISSUE THREAD

**Issue by snowplayfire** [google/cadvisor#2636]
I am fresh in `cadvisor` and want some helps about code. 

```
func getCadvisorContainerInfo(ca cadvisor.Interface) (map[string]cadvisorapiv2.ContainerInfo, error) {
	infos, err := ca.ContainerInfoV2("/", cadvisorapiv2.RequestOptions{
		IdType:    cadvisorapiv2.TypeName,
		Count:     2, // 2 samples are needed to compute "instantaneous" CPU
		Recursive: true,
	})
	if err != nil {
		if _, ok := infos["/"]; ok {
			// If the failure is partial, log it and return a best-effort
			// response.
			klog.Errorf("Partial failure issuing cadvisor.ContainerInfoV2: %v", err)
		} else {
			return nil, fmt.Errorf("failed to get root cgroup stats: %v", err)
		}
	}
	return infos, nil
}
```
There is a comment:`2 samples are needed to compute "instantaneous" CPU`, but I can not find any code to calculate using the 2 samples, and I also don't know what is the window between the 2 samples.  Can anyone help me?  Thanks!

**Comment by dashpole** [comment]
I think one example of calculating it is here: https://github.com/google/cadvisor/blob/master/manager/container.go#L524

**Comment by snowplayfire** [comment]
@dashpole  Thanks!

Refer this #2496 [cAdvisor collects and caches metrics in the background and then serves them from its cache. I think the metric collected here is not instantaneous, it is an average in a window.  Do you know what is the window value?

**Comment by dashpole** [comment]
yes, that is determined by --housekeeping-interval
