### ISSUE TITLE
README.md may need to be updated (kubernetes-users mailing list is moved)

### ISSUE THREAD

**Issue by jihoon-seo** [google/cadvisor#2649]
In [Community section of `README.md`](https://github.com/google/cadvisor/blob/master/README.md#community),
there exists a link to the [kubernetes-users Google Groups mailing list](https://groups.google.com/forum/#!forum/kubernetes-users).
But this mailing list went READ-ONLY, and moved to https://discuss.kubernetes.io .

**Comment by dashpole** [comment]
opened a PR to update it.  PTAL
