### ISSUE TITLE
FS IO metrics all zero on prometheus endpoint (apparently old problem)

### ISSUE THREAD

**Issue by Fryuni** [google/cadvisor#2656]
All metrics regarding io are zeroed out on the metrics endpoint. This should have been solved on #1642 back in 2018, but seems like it wasn't.

I'm running from a fresh GKE cluster version v1.15.12-gke.9

I have run essentially the same command used as example on the PR, changing the `sed` command to show the name of the metrics. One line per metric per container as it should, but all with zero and the timestamp. I truncated it to 5 lines per metric, because it was _huuuge_, here it is:
```
> curl -s http://localhost:8001/api/v1/nodes/gke-app-mem-4-76184aebf9-59c8e46b-0bex/proxy/metrics/cadvisor | egrep '^cadvisor_version_info|^container_fs_io'|sed -E 's/(container\w+)\{.*\}/\1/'
cadvisor_version_info{cadvisorRevision="",cadvisorVersion="",dockerVersion="19.03.1",kernelVersion="4.19.112+",osVersion="Container-Optimized OS from Google"} 1
container_fs_io_current 0 1599005385618
container_fs_io_current 0 1599005370623
container_fs_io_current 0 1599005387132
container_fs_io_current 0 1599005377758
container_fs_io_current 0 1599005375191
container_fs_io_time_seconds_total 0 1599005385618
container_fs_io_time_seconds_total 0 1599005370623
container_fs_io_time_seconds_total 0 1599005387132
container_fs_io_time_seconds_total 0 1599005377758
container_fs_io_time_seconds_total 0 1599005375191
container_fs_io_time_weighted_seconds_total 0 1599005385618
container_fs_io_time_weighted_seconds_total 0 1599005370623
container_fs_io_time_weighted_seconds_total 0 1599005387132
container_fs_io_time_weighted_seconds_total 0 1599005377758
container_fs_io_time_weighted_seconds_total 0 1599005375191
```

And this is the info from inside the same node:
```
# > docker info
Client:
 Debug Mode: false

Server:
 Containers: 43
  Running: 41
  Paused: 0
  Stopped: 2
 Images: 60
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a4bc1d432a2c33aa2eed37f338dceabb93641310
 runc version: 
 init version: fec3683b971d9c3ef73f284f176672c44b448662
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.112+
 Operating System: Container-Optimized OS from Google
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 25.51GiB
 Name: gke-app-mem-4-76184aebf9-59c8e46b-0bex
 ID: AWBJ:A6NL:R6IF:GUXN:YB6E:GQM2:BSQY:QWN3:Y55X:M2KG:C4ZE:YIWD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  10.0.0.0/8
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.gcr.io/
 Live Restore Enabled: true

**Comment by dashpole** [comment]
Can you test using the same pod as https://github.com/google/cadvisor/issues/2641#issue-680050591, and add `oflag=direct`, as that person did in https://github.com/google/cadvisor/issues/2641#issuecomment-679113488?  Disk IO cgroups only measure "direct" writes, which doesn't actually catch IOs from many applications.

**Comment by Fryuni** [comment]
That indeed works, but that being the case doesn't help at all. I can't change how every application does IO internally, even in our applications is not that low-level. I'll just drop those metrics since they are totally meaningless and see if I can get IO wait time metrics somewhere else.  
Kinda disappointing for the builtin metrics of kubelet to expose something that just does not work for _any_ application that we use/made

**Comment by ringerc** [comment]
Note that when this thread mentions `oflag=direct` they're talking about telling `dd` to do direct I/O, instead of the default buffered I/O. In other words, these metrics are not capturing and measuring buffered I/O in the cgroup container I/O stats.

You may find that with some I/O schedulers, direct I/O isn't counted either.

If possible, switch to cgroups v2 for much better container I/O stats. See https://github.com/google/cadvisor/issues/1946#issuecomment-2865008050
