### ISSUE TITLE
Improve storage drivers

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#266]
cAdvisor does not export the container spec and the machine usage to the supported db's. We need to do the following:
1. Move filesystem data to a separate tables - 'Filesystem Spec' and 'Filesystem Stats'
2. Add a 'Container Spec' table and export container spec whenever we encounter new containers or existing containers get updated. 
We can use container name '/' to refer to the machine in both Filesystem and Container Spec tables. If that might be confusing to users, we can have a export a 'Machine' table. We do not expect this table to be updated often. Users can refer to the information in the latest row.

**Comment by iwankgb** [comment]
Closing very old issue.
