### ISSUE TITLE
GetCpuLoad err in kernal 5.4 and cgroupv2

### ISSUE THREAD

**Issue by luodw** [google/cadvisor#2664]
I use cadvisor to collect metrics and our env is debian kernal 5.4 and cgroupv2.  We encounter a problem when we use GetCpuLoad to get container's cpu load metrics, it raise a err,
![image](https://user-images.githubusercontent.com/14847074/92405191-aaeff700-f167-11ea-9b3a-6bf6529be9d9.png)

Does anyone encounter this?  
code is here: https://github.com/google/cadvisor/blob/master/utils/cpuload/netlink/reader.go#L63

**Comment by cwdsuzhou** [comment]
What is the final solution. 

+1 for this
