### ISSUE TITLE
Custom container labels are intermittently set to blank

### ISSUE THREAD

**Issue by Fizpaket** [google/cadvisor#2670]
### Brief problem description
We are running Cadvisor in the following configuration and encounter a problem with metric custom labels:
1. There are 2 identical servers, each running identical Cadvisor instances and identical test containers with some custom labels
2. The Cadvisor instances are scraped for metrics by a singular Prometheus instance
3. One of the servers provides metrics consistently, while the second one intermittently presents some or all of the custom label values as blank. This results in Prometheus reporting a singular metric for the first server and multiple for the second, as it lists all the permutations of labels - all filled, all blank and everything in between.

### Detailed problem description
The test containers are run via docker-compose file:
```
version: "3"

services:
  application:
    image: "crccheck/hello-world"
    labels:
      - "service_feature=hello-world"
      - "service_product=experiments"
      - "a=a"
      - "b_b=b"
    network_mode: host
    restart: always
```

When scraping the /metrics handle on cadvisor the first server presents a consistent metric like:
```container_fs_inodes_total{container_label_a="a",container_label_b_b="b", ...  ,container_label_service_feature="hello-world", container_label_service_product="experiments"} 1 1600055017468```

While the second server may present the metric inconsistently as follows:
```container_fs_inodes_total{container_label_a="a",container_label_b_b="b", ...  ,container_label_service_feature="hello-world", container_label_service_product="experiments"} 1 1600055017468```
OR
```container_fs_inodes_total{container_label_a="a",container_label_b_b="b", ...  ,container_label_service_feature="hello-world", container_label_service_product=""} 1 1600055017468```
OR
```container_fs_inodes_total{container_label_a="a",container_label_b_b="b", ...  ,container_label_service_feature="", container_label_service_product="experiments"} 1 1600055017468```
OR
```container_fs_inodes_total{container_label_a="a",container_label_b_b="b", ...  ,container_label_service_feature="", container_label_service_product=""} 1 1600055017468```

The example above causes the Prometheus to report 4 metrics instead of the expected 1.

The problem is complicated by the fact that labels "a" and "b_b" are present consistently, while "service_feature" and "service_product" are sometimes set to blank. We have found some other possible label names that demonstrate the same problem, but we don't understand the cause for some labels to behave in that way - or why the same label names don't cause any problems on the first server.

### System
Cadvisor is run on both servers as proposed by documentation, tried with versions v0.35.0, v0.36.0 and v0.37.0:
```
VERSION=v0.35.0 # use the latest release version from https://github.com/google/cadvisor/releases
docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=18080:8080 \
  --name=cadvisor \
  gcr.io/cadvisor/cadvisor:$VERSION
```

System info for the server with no label problems:
```cadvisor_version_info{cadvisorRevision="4fe450a2",cadvisorVersion="v0.35.0",dockerVersion="19.03.12",kernelVersion="5.4.0-42-generic",osVersion="Alpine Linux v3.10"} ```

System info for the server with intermittently blank custom labels:
```cadvisor_version_info{cadvisorRevision="49033161",cadvisorVersion="v0.35.0",dockerVersion="19.03.12",kernelVersion="5.3.0-62-generic",osVersion="Alpine Linux v3.10"}```

**Comment by dashpole** [comment]
Prometheus requires the labels present on each scrape to be the same across all metrics with a given name.  cAdvisor finds all of the metric labels and fills in streams that don't have that label with "".  This produces the behavior you describe when a pod with a new label is added.  https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L1827

I would recommend running with `--store_container_labels=false` and `--whitelisted_container_labels=a,b`.  This will limit your container labels to a specific set.  See https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L1797

**Comment by Fizpaket** [comment]
Thank you very much for your reply, the combination of ```--store_container_labels=false``` and ```--whitelisted_container_labels=a,b``` does provide a consistent set of labels regardless of the server.
