### ISSUE TITLE
dashpole is moving on

### ISSUE THREAD

**Issue by dashpole** [google/cadvisor#2684]
cc  @katarzyna-z @odinuge @Creatone @iwankgb 

I'm still trying to figure out some details, but i'm stepping away from cAdvisor for now.  We are still working out some details.

**Comment by iwankgb** [comment]
I wish you all the best wherever you will end up! It was pleasure to work with you, let me know if I can support the transition somehow.

**Comment by katarzyna-z** [comment]
Thank you for great collaboration! I wish the best in a new place.

**Comment by dims** [comment]
thanks for the heads up @dashpole It was great working with you! Best wishes on new stuff.

**Comment by nightah** [comment]
All the best @dashpole, thanks for your efforts!

**Comment by Creatone** [comment]
Thanks, @dashpole for your work! It was a joy working with you. 
I wish you all the best on your new path 💪💪💪!

**Comment by bobbypage** [comment]
Hi all, 👋! I will be the new maintainer of cadvisor from Google side moving forward. 
 
@dashpole has been helping me to onboard to the project. Please ping me if you need something from my side. I'm also @bobbypage on the k8s slack. 

Thanks again to @dashpole on all the work on this project and helping to bring me onboard here!

**Comment by Creatone** [comment]
Welcome on board! :)
