### ISSUE TITLE
CoreOS  cAdvisor 0.4.1 Influxdb Storage not working 

### ISSUE THREAD

**Issue by udomsak** [google/cadvisor#271]
I found issue cAdvisor 0.4.1 on CoreOS  when using with Storage backend like  Influxdb  it can't send the data to Influxdb  

Influxdb is working fine   

My running environment  

* Coreos 
* cAdvisor 0.4.1 , cAdvisor 0.4.0 running from  **google Docker images** 
* InfluxDB 0.8.3  

The  error log said 

``` JSON
E1015 10:46:18.415676 00001 memory.go:109] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/cadvisor/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused

E1015 10:47:18.448986 00001 memory.go:109] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/cadvisor/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused

```

**Comment by vmarmol** [comment]
This issue seems over and taken over by other things :) closing. Feel free to open other issues if you run into anything.
