### ISSUE TITLE
Data race between `OnDemandHousekeeping` and `housekeepingTick`

### ISSUE THREAD

**Issue by pkagrawal** [google/cadvisor#2754]
`statsLastUpdatedTime` which is part of the `containerData` struct is read from  `OnDemandHousekeeping` and written to in `housekeepingTick`. These could be running under different go routines and so need to be guarded by the `containerData` lock.

**Comment by iwankgb** [comment]
What version of cAdvisor are you using? Is this standalone process or part of kubelet (or any other application)?
