### ISSUE TITLE
How to collect memory/cache bandwidth usage using cAdvisor?

### ISSUE THREAD

**Issue by nfsp3k** [google/cadvisor#2797]
Hi,

I want to scrape memory/cache bandwidth usage by containers using cAdvisor on Kubernetes.
How can I do this?

My worker node has the flags cqm_mbm_total, cqm_mbm_local, and rdt_a set.
![image](https://user-images.githubusercontent.com/4262433/106857283-2b108d80-6703-11eb-9f5d-2d98a24e2401.png)

And resctrl is also mounted as follows.
![image](https://user-images.githubusercontent.com/4262433/106857331-4085b780-6703-11eb-8296-9908338ca436.png)

However, when I try to scrape stats by using the REST API url 'xxx.xxx.xxx.xxx:8080/api/v1.3/subcontainers', 
the result does not contain any metrics about memory/cache bandwidth usage.

I'm new to cAdvisor and I believe your response will be helpful to me.
My cAdvisor version is v0.30.2.

Thank you

**Comment by Creatone** [comment]
The Resctrl metrics were introduced in v0.37.0. Unfortunately only for "/" container (the entire machine).
#2793 PR adds metrics per container. I hope it'll be merged soon. Can you check if it's working for you?

**Comment by nfsp3k** [comment]
> The Resctrl metrics were introduced in v0.37.0. Unfortunately only for "/" container (the entire machine).
> #2793 PR adds metrics per container. I hope it'll be merged soon. Can you check if it's working for you?

Thanks for your reply, @Creatone. I'm going to check the PR.
