### ISSUE TITLE
How to calculate CPU usage in milli-core from the metrics collected by using API?

### ISSUE THREAD

**Issue by nfsp3k** [google/cadvisor#2802]
Hi,
I hope you are doing well :D 

I'd like to calculate CPU usage by myself from the metrics that are scraped through the API call to cAdvisor instance.
At first, I thought I can calculate CPU usage from the metrics, but I'm confused about how to do that.

I scraped the metrics by calling API `/api/v1.3/subcontainers` of the cAdvisor instance and the follows are a part of it:
![image](https://user-images.githubusercontent.com/4262433/107481187-247d8c80-6bc1-11eb-9c02-116b3b891773.png)
 **Figure 1: The CPU related metrics of the FIRST entry in the stat list.**

![image](https://user-images.githubusercontent.com/4262433/107481513-a53c8880-6bc1-11eb-8337-9b7c5799c184.png)
 **Figure 2: The CPU related metrics of the LAST entry in the stat list.**

I thought I can calculate the CPU usage of the container by subtracting the value `['cpu']['usage']['total']` of the last entry in the CPU stats from that of the first entry and dividing by the time they are over, which is 1 min 30 sec in this result.
= (12165267524487 - 12141912390914) / 90 sec = 259,501,484

However, it is totally different from the value shown in the output of the command `kubectl top pod`.
![image](https://user-images.githubusercontent.com/4262433/107481979-5fcc8b00-6bc2-11eb-99f0-e20b43e4dc03.png)

Did I do something wrong or is it fundamentally not possible to calculate it from the metrics scraped by the API call?
or should I use Prometheus?

Thank you!

**Comment by iwankgb** [comment]
Metric that you are looking for is exposed in `/api/v2.0/stats` endpoint. If you append name of you runtime and container ID to the path (e.g. `/api/v2.0/stats/docker/106e96e8ebfa430b27e2a229340b1651309fdd65e57e5ae81e6f7b2da8169354`) you will get stats for specific container.
Look for `cpu_inst` in field on JSON.

**Comment by nfsp3k** [comment]
Thank you for your reply, @iwankgb.

I got the result I wanted with a command, which is slightly different from your suggestion. (But, I don't know why. I'm currently using v0.33.0.) My command is as follows: `/api/v2.0/stats/106e96e8ebfa430b27e2a229340b1651309fdd65e57e5ae81e6f7b2da8169354?type=docker`

Thank you again, @iwankgb
