### ISSUE TITLE
no data for container_cpu_schedstat_runqueue_seconds_total

### ISSUE THREAD

**Issue by pradykaushik** [google/cadvisor#2808]
I'm running cadvisor version 0.36.0 on bare metal and am exposing the metrics to Prometheus.

Below is the configuration information.
```
-port 9090
-store_container_labels=false
-whitelisted_container_labels=<some labels>
-docker_only=true
```

I believe I don't need to do anything extra to be able to view `contianer_cpu_schedstat_runqueue_seconds_total` data. However, I don't see anything for that metric on Prometheus. Any reason why this might be?

**Comment by iwankgb** [comment]
@pradykaushik, can you update to latest version, please? It 0.38.8 released in last 24 hours.

**Comment by pradykaushik** [comment]
I updated to 0.38.8 and I still cannot see data for the following metrics.
1. `container_cpu_schedstat_runqueue_seconds_total`.
2. `container_llc_occupancy_bytes`.

**Comment by iwankgb** [comment]
`container_llc_occupancy_bytes` requires `resctrlfs` to be mounted and `resctrl` metrics to be enabled (they are disabled by default). `sched` metrics (that `container_cpu_schedstat_runqueue_seconds_total` is member of) are disabled by default too. See: https://github.com/google/cadvisor/blob/88892b0e8aeabfa369a516dc1e3528c32cf0c248/cmd/cadvisor.go#L83 for the list of metric families disabled by default.

**Comment by pradykaushik** [comment]
Ah gotcha. Thanks. I couldn't find this anywhere in the documentation. Would a PR that adds the list of metrics disabled by default to the documentation be accepted?
