### ISSUE TITLE
Getting container_cpu_load_average_10s as ZERO.

### ISSUE THREAD

**Issue by Siddharthav1** [google/cadvisor#2860]
Hello,
I am using the cadvisor to collect the container health data.Here, I am using the below command to run the cadvisor:

        sudo docker run --volume=/:/rootfs:ro --volume=/var/run:/var/run:ro --volume=/sys:/sys:ro -- 
        volume=/var/lib/docker/:/var/lib/docker:ro --volume=/dev/disk/:/dev/disk:ro --publish=8080:8080 --detach=true -- 
        name=cadvisor google/cadvisor:latest

But, the issue is I am getting the CPU and memory related data but it is faillig to collect the **"container_cpu_load_average_10s"** I am getting this value as **"zero"**. 

![image](https://user-images.githubusercontent.com/59814967/117007407-417cb400-ad07-11eb-9bc4-e7929318912f.png)

Can anybody suggest why this is happening here please.

regards,
Siddhartha V

**Comment by iwankgb** [comment]
See: https://github.com/google/cadvisor/issues/2858#issuecomment-834594776, please.
