### ISSUE TITLE
Cut the 0.40 (or 0.39.2) release to have cgroup v2 fixes

### ISSUE THREAD

**Issue by kolyshkin** [google/cadvisor#2878]
With an on-going work to make cgroupv2 a first-class citizen, can we please have a release with #2837 and #2839 (or their backports to 0.39) made? This is critical to have cgroupv2 tests running on kubernetes.

I'll be happy to open a backport PR to release-0.39 branch if we're not yet ready for 0.40.

**Comment by Creatone** [comment]
https://github.com/google/cadvisor/releases/tag/v0.39.2

Probably you need to wait for a little for gcr.io Image, I'm right @bobbypage?

**Comment by giuseppe** [comment]
Thanks for the release!  Opened a PR for Kubernetes: https://github.com/kubernetes/kubernetes/pull/102483

**Comment by bobbypage** [comment]
Thanks @Creatone for cutting the release. Sorry for delay on my side, I was OOO last week. I will publish a GCR image as well.
