### ISSUE TITLE
Docker Container names not showing up only Id

### ISSUE THREAD

**Issue by NITIN-BINDAL** [google/cadvisor#2888]
Hey community i have been trying to set up cadvisor on my staging server which have CentOS Linux 7 (Core) OS but unable to do so because container names are not coming up in the cadvisor although I am able to see other metrics like processes , cpu usage etc . I am running cadvsior with this command 

docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:ro \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/dev/disk/:/dev/disk:ro \
  --volume=/cgroup:/cgroup:ro \
  --volume=/var/run/docker.sock:/var/run/docker.sock:rw \
  --publish=8087:8080 \
  --name=cadvisor-n3 \
  --privileged=true \
  --device=/dev/kmsg \
  gcr.io/cadvisor/cadvisor:latest

In logs there is no error , logs are clear .

I don't know where I am going wrong I read the documentation and whatever they state regarding the configuration of CentOS based Linux I have added that as well in the command still no container names.

Docker version == 18.09.2 , build 6247962

Please help if anyone knows solution for this issue. Thanks in advance

**Comment by greatdora666** [comment]
Hi, have you resolved this issue?
