### ISSUE TITLE
sha256sum wrong for release v0.39.2

### ISSUE THREAD

**Issue by mpackard** [google/cadvisor#2899]
On release page for v0.39.2 it says:

SHA256 (cadvisor) = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

But when I download and run it:

$ sha256sum cadvisor 
65109ea14132bce91bb2a92dc70248c705ba26fb2a7d55e295bf4192940a396c  cadvisor

The sums are correct for other versions I tried.

**Comment by Creatone** [comment]
Thanks, I tried to do that this way:
```cadvisor | sha256sum```
