### ISSUE TITLE
missing gpu metrics

### ISSUE THREAD

**Issue by Nan2018** [google/cadvisor#2917]
I have a GKE cluster with nvidia k80 gpus but the accelerator related metrics are missing. Below are the cadvisor metrics from one of the nodes which has a nvidia/cuda pod running. None of `container_accelerator_duty_cycle`, `container_accelerator_memory_total_bytes` or `container_accelerator_memory_used_bytes` is present.
[metrics.txt](https://github.com/google/cadvisor/files/6939171/metrics.txt)

**Comment by eero-t** [comment]
Looking at your data file, there are GPU metrics [2] provided by: https://github.com/google/cadvisor/tree/master/nvm

Whereas the data you're asking for, is provided by: https://github.com/google/cadvisor/tree/master/accelerators

They depend on different things, most likely you're missing the dependencies the latter needs for querying the data.

As the dependent [1] project README states: https://github.com/mindprince/gonvml

It will work only if it can dlopen NVML at run-time (from your cAdvisor container).   In your cAdvisor log you should see: "Could not initialize NVML" warning telling that you haven't configured your cAdvisor pod correctly i.e. running it with Nvidia settings injecting NVML to the container.

---

[1] https://github.com/google/cadvisor/blob/master/accelerators/nvidia.go#L31

[2]
```
# HELP machine_nvm_avg_power_budget_watts NVM power budget.
# TYPE machine_nvm_avg_power_budget_watts gauge
machine_nvm_avg_power_budget_watts{boot_id="4299dbb6-9371-4969-8962-c6a7e32e8b67",machine_id="f0cf9a18aab743bd0189e7c87f24c574",system_uuid="f0cf9a18-aab7-43bd-0189-e7c87f24c574"} 0
# HELP machine_nvm_capacity NVM capacity value labeled by NVM mode (memory mode or app direct mode).
# TYPE machine_nvm_capacity gauge
machine_nvm_capacity{boot_id="4299dbb6-9371-4969-8962-c6a7e32e8b67",machine_id="f0cf9a18aab743bd0189e7c87f24c574",mode="app_direct_mode",system_uuid="f0cf9a18-aab7-43bd-0189-e7c87f24c574"} 0
machine_nvm_capacity{boot_id="4299dbb6-9371-4969-8962-c6a7e32e8b67",machine_id="f0cf9a18aab743bd0189e7c87f24c574",mode="memory_mode",system_uuid="f0cf9a18-aab7-43bd-0189-e7c87f24c574"} 0
```

**Comment by Nan2018** [comment]
Thanks @eero-t 

The metrics I got are from `api/v1/nodes/my-node/proxy/metrics/cadvisor`. According to this [answer](https://github.com/google/cadvisor/issues/2153#issuecomment-456902145), they are from the GKE built-in cadvisor. I also checked the logs of the cluster and didn't see anything related to NVML.

Should I set some node pool configurations, or any other potential solutions?

**Comment by eero-t** [comment]
> According to this answer, they are from the GKE built-in cadvisor.

Kubelet (k8s manager process on each node) imports cAdvisor code so that it can provide **a subset** of cAdvisor metrics.

Kubelet cAdvisor metrics are under same names as metrics exported by cAdvisor itself.  To get additional cAdvisor metrics, real cAdvisor service needs to run in your cluster, which is configured appropriately (NVML present in containers etc).

According to k8s documentation: https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#disable-accelerator-metrics
> The responsibility for collecting accelerator metrics now belongs to the vendor rather than the kubelet. Vendors must provide a container that collects metrics and exposes them to the metrics service (for example, Prometheus).

=>  I think you should ask about this from your cloud administrator (or Nvidia), for now your issue does not seem cAdvisor specific...

Disclaimer: I have not used GKE, nor Nvidia GPUs.

**Comment by Nan2018** [comment]
according to https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/, default value of `DisableAcceleratorUsageMetrics` is true since 1.20 beta. And my cluster is v1.20.8. Is this the reason?
