### ISSUE TITLE
--enable_metrics flag undefined

### ISSUE THREAD

**Issue by seeker89** [google/cadvisor#2928]
Hi,

I've just tried to run the latest docker image, and I've noticed that while both `disable` and `enable`-metrics are defined in [here](https://github.com/google/cadvisor/blob/master/cmd/cadvisor.go#L97-L98), the `enable_metrics` flag ends up being undefined:

```sh
$ docker run --rm -ti gcr.io/cadvisor/cadvisor:v0.40.0 --enable_metrics=memory
flag provided but not defined: -enable_metrics
...
```

Weirdly, the `disable_metrics` part works fine, and shows in the help message:

```sh
  -disable_metrics metrics
        comma-separated list of
```

**Comment by Creatone** [comment]
Hello, these changes are not in any release yet.
Here you have the difference between latest one and master:
https://github.com/google/cadvisor/compare/v0.40.0...master

**Comment by seeker89** [comment]
Gotcha, so that's literally only just landed here a few days ago - I was reading the docs, I can see that's been added through [this commit](https://github.com/google/cadvisor/commit/63d83787ce9054711547814230ac9a31e0d72697#diff-fff481275d537031749860ca2f44bcefe712995f705211587bc9d2d86654997f).

Thanks! I guess I can build from master in the meantime.
