### ISSUE TITLE
Start InfluxDB

### ISSUE THREAD

**Issue by alessioguglielmo** [google/cadvisor#293]
Hi,
How can I run cAdvisor with influxDB storage driver? Should I pass it as env option?
I'm on Docker 1.3.1 in UbuServer14

**Comment by rmanyari** [comment]
I'm having troubles writing to an external influx as well. 

Here is how I'm starting the container:

docker run   
  --volume=/:/rootfs:ro   
  --volume=/var/run:/var/run:rw   
  --volume=/sys:/sys:ro   
  --volume=/var/lib/docker/:/var/lib/docker:ro   
  --publish=8080:8080   
  --detach=true   
  --name=cadvisor   
  google/cadvisor:latest 
    -storage_driver=influxdb 
    -storage_driver_host=external_ip:8086 
    -storage_driver_db=cadvisor 
    -storage_driver_password=my_db_pass 
    -log_dir=/

The container is starting normally and I can get stats on the port 8080 but nothing is being written to Influx and the logs are empty. Thanks!

**Comment by vishh** [comment]
@rmanyari: Can you post logs from cadvisor?

**Comment by rmanyari** [comment]
Thanks for taking some time to help me debug this @vishh 

I looked this morning at the logs and found lots of these:

E0129 19:37:50.348249 00001 memory.go:94] failed to write stats to influxDb - Post http://the_right_ip:8086/db/cadvisor/series?u=root&p=the_right_password&time_precision=u: write tcp 104.131.19.134:8086: connection refused
E0129 19:37:54.365524 00001 memory.go:94] failed to write stats to influxDb - Post http://the_right_ip:8086/db/cadvisor/series?u=root&p=the_right_password&time_precision=u: write tcp 104.131.19.134:8086: connection timed out

What's curious is that if I take the same url and paste it into postman (tool to push http requests) everything works fine. Is it possible that cdavisor is trying to write too many series at the time and its overloading my influx at the other end? It's gathering data from a server that has ~350 containers running.

I also see some of this on the influx server:

Jan 29 14:38:53 influx kernel: [   75.579469] perf samples too long (2640 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
Jan 29 14:39:02 influx kernel: [   85.424844] perf samples too long (5024 > 5000), lowering kernel.perf_event_max_sample_rate to 25000
Jan 29 14:39:46 influx kernel: [  129.378845] perf samples too long (10034 > 10000), lowering kernel.perf_event_max_sample_rate to 12500
Jan 29 14:41:43 influx kernel: [  245.943875] perf samples too long (20011 > 20000), lowering kernel.perf_event_max_sample_rate to 6250

**Comment by vishh** [comment]
cadvisor batches writes to InfluxDB. The default batch duration is 1 minute
(`--storage_driver_buffer_duration`). I hope InfluxDB host:port is
accessible from inside the cadvisor container.

**Comment by vmarmol** [comment]
Closing this issue, feel free to file another issue if you run into trouble.
