### ISSUE TITLE
can't pull the image

### ISSUE THREAD

**Issue by Azertooth** [google/cadvisor#2949]
`Error response from daemon: manifest for gcr.io/cadvisor/cadvisor:v0.41.0 not found: manifest unknown: Failed to fetch "v0.41.0" from request "/v2/cadvisor/cadvisor/manifests/v0.41.0".`

**Comment by aleksey-ru52** [comment]
I suppese, you should use tag gcr.io/cadvisor/cadvisor:v0.41.0-containerd-fix-rc.2
Don't know why release page contains different links, github tag is - tag/v0.41.0-containerd-fix-rc.2

**Comment by bobbypage** [comment]
Image has been pushed!
