### ISSUE TITLE
v0.41.0 manifest/tag is missing on gcr

### ISSUE THREAD

**Issue by nightah** [google/cadvisor#2953]
It appears that the `v0.41.0` tag is missing from [GCR](https://console.cloud.google.com/gcr/images/cadvisor/GLOBAL/cadvisor) despite a release being made 4 days ago.

Not sure if this is due to failure in CI or otherwise but it would be great if we could re-push the tag.

**Comment by bobbypage** [comment]
Image has been pushed!
