### ISSUE TITLE
kubelet 1.23.0 (cAdvisor 0.43) panic on arm64 / Raspberry PI OS32

### ISSUE THREAD

**Issue by vescoc** [google/cadvisor#3027]
cadvisor 0.43 compiled for arm32 fails with panic for 64-bit misaligned access at line https://github.com/google/cadvisor/blob/release-v0.43/manager/container.go#L676 in Raspberry PI OS32 and 64-bit kernel (arm_64bits = 1).

In Raspberry PI OS32 and 32-bit kernels, access is allowed but results in a loss of performance.

For more information, please refer to https://www.kernel.org/doc/html/latest/arm/mem_alignment.html.

Possibile fix (to check): move `oomEvents` at the begging of `containerData` struct.

**Comment by vescoc** [comment]
#https://github.com/google/cadvisor/pull/3029

**Comment by iwankgb** [comment]
Closed in #3029
