### ISSUE TITLE
Provide ability to build a binary that doesn't depend on external JS/CSS files

### ISSUE THREAD

**Issue by mindscratch** [google/cadvisor#304]
When the cadvisor binary is built the [containers_html.go](https://github.com/google/cadvisor/blob/master/pages/containers_html.go#L22) depends on external dependencies. This causes issues when trying to run the cadvisor binary on hosts that don't have access to the Internet.

**Comment by onlyjob** [comment]
Is there a more elegant way to embed static resources? Perhaps serving .js and .css files from `/usr/share/cadvisor` instead of stitching resources straight into executable? Current approach strikes me as remarkably ugly (let alone unnecessary use of obfuscated/minified code).   :-(
