### ISSUE TITLE
Cut a release that uses runc/libcontainer v1.1

### ISSUE THREAD

**Issue by kolyshkin** [google/cadvisor#3055]
We need a release cut from master which has #3031 / #3038 (runc 1.1), due to API changes in runc/libcontainer.

This is needed to move kubernetes/kubernetes#107149 forward.

See discussion at https://github.com/google/cadvisor/pull/3048#issuecomment-1018895806 for more details.

**Comment by kolyshkin** [comment]
@bobbypage PTAL 🙏🏻

**Comment by bobbypage** [comment]
ack @kolyshkin, will cut a release this week

**Comment by kolyshkin** [comment]
@bobbypage a friendly poke ✋🏻

**Comment by bobbypage** [comment]
Thanks for the ping, cut a release! - https://github.com/google/cadvisor/releases/tag/v0.44.0
