### ISSUE TITLE
Metrics Endpoint not working when using url_base_prefix

### ISSUE THREAD

**Issue by samcro1967** [google/cadvisor#3140]
I have cadvisor 0.44.1 running successfully on http://osu.cadvisor:8104/cadvisor.  I am not able to get to http://osu.cadvisor:8104/cadvisor/metrics.  It automatically redirects me to http://osu.cadvisor:8104/cadvisor/containers/.  Trying to setup Prometheus and Grafana.  Prometheus is not able to scrape metrics from the containers page.  Not sure what I am missing.  Anyone else come across this and have a fix?

```
ts=2022-07-23T13:47:47.409Z caller=scrape.go:1332 level=debug component="scrape manager" scrape_pool=host target=http://192.168.1.104:8104/cadvisor/containers/ msg="Append failed" err="\"INVALID\" is not a valid start token"
```

**Comment by 249043822** [comment]
You should use http://osu.cadvisor:8104/metrics for prometheus

**Comment by samcro1967** [comment]
I finally got http://osu.cadvisor:8104/cadvisor/metrics working.  Ultimately had to restart the docker service.  Neither restarting cadvisor or removing it and re-adding it had any effect.
