### ISSUE TITLE
Docker plugin causes 5 second delay on startup when docker.socket doesn't exist

### ISSUE THREAD

**Issue by bwagner5** [google/cadvisor#3175]
If the docker.socket does not exist because another container runtime is being used, cadvisor incurs an additional 5 second latency when starting up due to the docker plugin's retry strategy (5 tries w/ a 1 second delay between attempts):

https://github.com/google/cadvisor/blob/master/container/docker/factory.go#L83  

It would be great if either:
1.  Plugins could be disabled if they are not being used maybe with a registered flag. 
2. Alternatively, if the plugin could initialize more gracefully like the others, this would help to expedite startups. 

Specifically, the Kubelet uses CAdvisor and this 5 second latency means that Kubernetes nodes have an additional 5 second latency before they can go to a Ready state. 

Here are some logs on a Kubelet startup. The logging below comes from CAdvisor though. notice the 5 second jump in log lines after  `Docker not connected: ...`. I confirmed with debug logs that [this](https://github.com/google/cadvisor/blob/master/container/docker/factory.go#L83) is the retry loop that is causing this.
```
16:44:00.576554   16259 manager.go:165] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct/system.slice/kubelet.service"
16:44:00.576659   16259 plugin.go:40] CRI-O not connected: Get "http://%2Fvar%2Frun%2Fcrio%2Fcrio.sock/info": dial unix /var/run/crio/crio.sock: connect: no such file or directory
16:44:00.576808   16259 plugin.go:68] Docker not connected: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
16:44:05.578997   16259 fs.go:131] Filesystem UUIDs: map[027092f5-b7f8-4b7a-8eb4-bb3417968c9b:/dev/nvme0n1p1]
16:44:05.579024   16259 fs.go:132] Filesystem partitions: map[/dev/nvme0n1p1:{mountpoint:/ major:259 minor:1 fsType:xfs blockSize:0} /dev/shm:{mountpoint:/dev/shm major:0 minor:21 fsType:tmpfs
```

I'd be happy to contribute a PR depending on which fix should be implemented (or maybe I'm missing an existing configuration to disable plugins, if so let me know)  :)

**Comment by dims** [comment]
oh, yes, please file a PR and ping me and/or @bobbypage

**Comment by dims** [comment]
@bwagner5 just so you know newest k8s releases does not even have the docker plugin:
https://github.com/kubernetes/kubernetes/blob/77bf2d1ade933ad5f7c78216cb4729f2cefd0e55/pkg/kubelet/cadvisor/cadvisor_linux.go#L30-L33

**Comment by bwagner5** [comment]
hmmm I'll have to trace the path where it gets included, but my tests are using K8s 1.22 and the docker plugin is still being loaded even though it doesn't appear to be included here: https://github.com/kubernetes/kubernetes/blob/release-1.22/pkg/kubelet/cadvisor/cadvisor_linux.go ....

**Comment by bwagner5** [comment]
ahh it's here https://github.com/kubernetes/kubernetes/blob/release-1.22/pkg/kubelet/cadvisor/cadvisor_linux_docker.go 

so should be removed in 1.24

**Comment by bwagner5** [comment]
looks like it can be unloaded with the docker-less build flag

**Comment by dims** [comment]
@bwagner5 yep

**Comment by dims** [comment]
There is no docker in our code base under vendor/ since https://github.com/kubernetes/kubernetes/pull/97252 so this problem does not exist anymore (GA'ed in 1.24)
