### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by zs-dima** [google/cadvisor#3190]
ARM architecture gain own popularity in server environment as well.
It is Oracle A1, Amazon M6g, Raspberry Pi and etc

Could be nice to add ARM support to the cAdvisor out of the box.

**Comment by maxpoirier** [comment]
Does this answers your concern?

https://github.com/google/cadvisor/releases/tag/v0.45.0

**Comment by bobbypage** [comment]
Yes, ARM was added in v0.45
