### ISSUE TITLE
Deploying Cadvisor as Daemonset on minikube cluster gives error (error: resource mapping not found for name: "cadvisor" namespace: "" from "STDIN": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1" ensure CRDs are installed first)

### ISSUE THREAD

**Issue by krishnashed** [google/cadvisor#3193]
Hi,

I'm trying to deploy Cadvisor on my minikube cluster, I'm referring to https://github.com/google/cadvisor/tree/master/deploy/kubernetes

I'm using cadvisorv0.45.0 as it is the latest 
Following the steps, and on running the command : kubectl kustomize deploy/kubernetes/base | kubectl apply -f - 

I get the error as 
![image](https://user-images.githubusercontent.com/60742358/199266863-6cf7f3b9-cc5f-439b-85d5-d54c87a23299.png)

Can someone please tell me how i can resolve this issue and deploy Cadvisor as a Daemon set ?

Thanks

**Comment by bobbypage** [comment]
+1, we should consider to migrate to PSA (https://github.com/google/cadvisor/blob/master/deploy/kubernetes/base/podsecuritypolicy.yaml#L2)

**Comment by krishnashed** [comment]
Thank you @Creatone  @bobbypage
