### ISSUE TITLE
drop nvml from cadvisor and k/k 

### ISSUE THREAD

**Issue by pacoxu** [google/cadvisor#3205]
[DisableAcceleratorUsageMetrics](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) is GAed in Kubernetes v1.25. So container.AcceleratorUsageMetrics will not be included anymore by kubelet.

See https://github.com/kubernetes/kubernetes/pull/114204#issuecomment-1332756032.

Another issue is opened to replace `mindprince/gonvml`.
- https://github.com/google/cadvisor/issues/3171

Link all other nvml related issues:
- https://github.com/google/cadvisor/issues/2279 
- https://github.com/google/cadvisor/issues/1842

**Comment by pacoxu** [comment]
/cc @dashpole 
Should we drop all code under https://github.com/google/cadvisor/tree/master/accelerators?

**Comment by dashpole** [comment]
Is it possible to keep it, but not include it in the go module imported by k/k?

**Comment by pacoxu** [comment]
https://github.com/google/cadvisor/pull/3206 will fix this.



> Some users may be using it with stand-alone cAdvisor

https://github.com/google/cadvisor/pull/3206#issuecomment-1334144474 @bobbypage  suggests:
> For cAdvisor users, we can recommend users to use https://github.com/NVIDIA/dcgm-exporter for accelerator metrics.

**Comment by pacoxu** [comment]
per https://github.com/google/cadvisor/pull/3206
