### ISSUE TITLE
cAdvisor tries determining unavailable fields for offline CPUs.

### ISSUE THREAD

**Issue by kishen-v** [google/cadvisor#3317]
When CPUs are marked as offline, certain fields such as physical_package_id and core_id are set to 0 which should have been skipped as they're unavailable under the`/sys/bus/cpu/devices/cpuX/topology` directory, and the existing testcases too expect the same behaviour.
>Note: CPUs were marked offline using the following command `echo 0 > /sys/bus/cpu/devices/cpu15/online`

**Expected behaviour**: 
The expected behaviour, based on logic and unit tests, is for cAdvisor to skip determining the fields for offline CPUs. However, this behaviour is not observed due to the construction of absolute paths based on the parameters sent, which can lead to construction of non-existent paths. 

___
**Observed behaviour:** 
In environments where node topology is used, the constructed path `/sys/devices/system/node/nodeX/online` does not exist. This leads to erroneously marking the CPU online due to the file's unavailability in the environment based on the existing design.
https://github.com/google/cadvisor/blob/137032c607fcdfee770f49f7294a23b1f61c8be9/utils/sysinfo/sysinfo.go#L214-L218

As a consequence of the above issue, warning log messages are raised related to missing files under the /cpuX/topology directory. 

https://github.com/google/cadvisor/blob/137032c607fcdfee770f49f7294a23b1f61c8be9/utils/sysfs/sysfs.go#L384-L388
Since the above logic returns true, the CPUs that are unavailable are not skipped but are also considered for retrieving information.
https://github.com/google/cadvisor/blob/137032c607fcdfee770f49f7294a23b1f61c8be9/utils/sysinfo/sysinfo.go#L428-L435
___
Since the path `/sys/bus/cpu/devices/online` does not exist , isCpuOnline function returns `false` along with the `no such file or directory` error.
https://github.com/google/cadvisor/blob/137032c607fcdfee770f49f7294a23b1f61c8be9/utils/sysfs/sysfs.go#L424-L428

`physical_package_id` and `core_id` are determined for CPUs that are marked offline, compared to the expected behaviour where it needs to be skipped.

https://github.com/google/cadvisor/blob/137032c607fcdfee770f49f7294a23b1f61c8be9/utils/sysfs/sysfs.go#L501
!isOnline && !os.IsNotExist(err) is not satisfied to skip determining fields for CPUs that are marked offline.
https://github.com/google/cadvisor/blob/137032c607fcdfee770f49f7294a23b1f61c8be9/utils/sysfs/sysfs.go#L506-L507

___
**Possible solution:** 
This issue can be mitigated by setting the `cpuOnlinePath` to specific file, which would enable the identification of the CPUs that are available/unavailable hence, suppressing the warning messages regarding the missing files under the CPU topology directory. This will avoid multiple warning messages raised in the case of large compute nodes and the associated noise in the logs.

Such as :
`W0523 13:54:11.121383 1403010 sysinfo.go:434] Cannot read core id for /sys/devices/system/node/nodeX/cpuX, core_id file does not exist, err: open /sys/devices/system/node/nodeX/cpuX/topology/core_id: no such file or directory`

`W0523 13:54:11.122672 1403010 sysfs.go:512] Cannot open /sys/bus/cpu/devices/cpuX/topology/core_id, assuming 0 for core_id of CPU X`

`W0523 13:54:11.122701 1403010 sysfs.go:518] Cannot open /sys/bus/cpu/devices/cpuX/topology/physical_package_id, assuming 0 physical_package_id of CPU X`

 I'm really looking forward to any suggestions or insights from the community :)

**Comment by iwankgb** [comment]
Closed in #3318.
