### ISSUE TITLE
Performance degradation of NFS after upgrading Kubernetes from 1.20 to 1.22

### ISSUE THREAD

**Issue by hyponet** [google/cadvisor#3349]
After upgrading our Kubernetes cluster from version 1.20 to 1.22, we have observed a version discrepancy, which is manifested in the form of a decrease in NFS performance. After some investigation, we suspect it might be related to this change: 
https://github.com/google/cadvisor/pull/2787

To provide a brief description of our environment, our cluster has nearly 10,000 Pods, all of which are using the same NAS service via PV. On a single node, we can have more than 400 nfs mountpoints. Currently, the metrics collection includes NFS mount points, leading to a large number of statfs operations and consequently, slow NFS metadata operations.

Would it be possible to adjust the metrics collection for mountpoints so that data is only collected once for the same device?

**Comment by fusida** [comment]
cc @bobbypage @gjkim42

**Comment by mowangdk** [comment]
related issue & pr: 

https://github.com/kubernetes/kubernetes/issues/98009

https://github.com/google/cadvisor/pull/2787

@pacoxu  PTAL

**Comment by pacoxu** [comment]
- kube 1.20 is using cadvisor v0.38.5.
 - kube 1.22 is using cadvisor v0.39.2.

https://github.com/kubernetes/kubernetes/blob/v1.20.0/go.mod#L56C29-L56C29
https://github.com/kubernetes/kubernetes/blob/v1.22.0/go.mod#L49

**Comment by chenk008** [comment]
For one nfs device, the information about used and available in different directory should be unified. For the same nfs device, cadvisor can stat nfs device once and reuse it's info in `GetFsInfoForPath`.
