### ISSUE TITLE
Set grafana alert on restarted containers

### ISSUE THREAD

**Issue by win5923** [google/cadvisor#3355]
Hi, I am using `Prometheus` , `Grafana` , `Cadvisor` to monitor docker containers status. I want to set up a `Grafana Alert` to detect if the same container fails to restart within 200 seconds and send an alert. However, I noticed that after the container restarts, cadvisor generates new metrics. How can I determine if the container is functioning normally after a restart?

![image](https://github.com/google/cadvisor/assets/56353753/a9cc268f-2103-4279-8496-e73a59d41e79)

The alert will generate a large number of errors due to `container_label_restartcount`, and it is inevitable that the container before the restart will exceed the time threshold since its metrics are distinct from those after the restart.

![image](https://github.com/google/cadvisor/assets/56353753/4ca39599-f2ad-4b7c-9780-de10e1fc3222)

Thanks in advance.

**Comment by iwankgb** [comment]
As far as I understand ID of the container remains the same. Would you be able to aggregate container metrics, select maximum `container_label_restartcount` and fire an alert of delta in a period of time is too high?

**Comment by win5923** [comment]
I came to this rule from https://stackoverflow.com/questions/41452930/how-can-i-alert-for-container-restarted/63782891#63782891
```
count by (instance, name) (count_over_time(container_last_seen{name!="", container_label_restartcount!=""}[15m])) - 1 >= 5
```
it can count unique records for each instance and name now.
thanks!
