### ISSUE TITLE
Missing binaries for v0.47.3

### ISSUE THREAD

**Issue by Neo2308** [google/cadvisor#3376]
Binaries are not attached for v0.47.3
But they were available for v0.47.2 (currently marked as latest)

Similar to https://github.com/google/cadvisor/issues/3338

**Comment by rrondeau** [comment]
@bobbypage maybe :) Thanks for your work !

**Comment by bobbypage** [comment]
Please use the latest release v0.49.1 - https://github.com/google/cadvisor/releases/tag/v0.49.1
