### ISSUE TITLE
Systemd Detection Does Not Work Inside a Docker Container

### ISSUE THREAD

**Issue by vmarmol** [google/cadvisor#342]
We don't mount /run inside the container. We can probably do detection by checking that the systemd cgroup hierarchy is mounted.

**Comment by bluecmd** [comment]
How is this currently expected to work? I'm running cAdvisor inside a docker container with systemd (https://gist.github.com/bluecmd/e9f00f813aa8891ada2be939d98e45ba)
This is how cAdvisor looks like for me: http://goo.gl/TTIr4l

Furthermore, the metrics are prefixed with the absolute docker path:
```
...
container_cpu_system_seconds_total{id="/"} 21716.47
container_cpu_system_seconds_total{id="/docker"} 4784.47
container_cpu_system_seconds_total{id="/docker/905e57d8fa7c9d69e5b1eef9ea9b8766f57fb3dd86e9c05a267d34e38d769635"} 414.4
container_cpu_system_seconds_total{id="/docker/905e57d8fa7c9d69e5b1eef9ea9b8766f57fb3dd86e9c05a267d34e38d769635/system.slice"} 405.09
container_cpu_system_seconds_total{id="/docker/905e57d8fa7c9d69e5b1eef9ea9b8766f57fb3dd86e9c05a267d34e38d769635/system.slice/aaautils.service"} 0.04
container_cpu_system_seconds_total{id="/docker/905e57d8fa7c9d69e5b1eef9ea9b8766f57fb3dd86e9c05a267d34e38d769635/system.slice/acpid.service"} 0
...
```
I'm not seeing how this is useful right now. What I would expect is that only things under the instance's cgroup root would be exported. Also that the container-local systemd is detected.
