### ISSUE TITLE
No docker images available for releases ≥ v0.48.0

### ISSUE THREAD

**Issue by rc5hack** [google/cadvisor#3427]
There are no docker images for [v0.48.0 and v0.48.1 releases](https://github.com/google/cadvisor/releases/) in [gcr.io/cadvisor/cadvisor](http://gcr.io/cadvisor/cadvisor) registry, which is mentioned in [Readme](https://github.com/google/cadvisor/blob/master/README.md).

Images should be uploaded to the registry, or readme file should be updated.

**Comment by heck-gd** [comment]
@bobbypage @Creatone Any insights into this? The container images are widely used for deploying cAdvisor.

**Comment by TomasVojacek** [comment]
Related to https://github.com/google/cadvisor/issues/3415

**Comment by rc5hack** [comment]
bump (3 months later)

**Comment by rc5hack** [comment]
some new images appeared in [gcr.io/cadvisor/cadvisor](http://gcr.io/cadvisor/cadvisor) registry, but 🤷🏻‍♂️ without tags:

```
gcr.io/cadvisor/cadvisor@sha256:60ad5223bb1342af3671426e6abff93e121fd7dd5a2396f77ab567ac8b3a08cc
gcr.io/cadvisor/cadvisor@sha256:81748289681673ebac21bb215b936042bdfe22aa031c4b7179712847e5112172
gcr.io/cadvisor/cadvisor@sha256:40b12c997895433d151fb090d446b5e9806e4de73234067abb05aa584b6f2217
gcr.io/cadvisor/cadvisor@sha256:c2691f64542b364a97db4613462663e4adf03e9e392813d348c6e7b4ca8ba440
gcr.io/cadvisor/cadvisor@sha256:8e083a232a61725aa79b2330b5483fd313c32aa948de3542254da018d73e7a4b
```

**Comment by Cub0n** [comment]
New cAdvisor 0.49.1 is available, see:
https://github.com/google/cadvisor/releases/tag/v0.49.1

**Comment by rc5hack** [comment]
new docker images [is now in registry](http://gcr.io/cadvisor/cadvisor), `latest` now is `0.49.1`, so problem solved.

closing.
