### ISSUE TITLE
Where is a static binary for standalone setup?

### ISSUE THREAD

**Issue by mammuthus** [google/cadvisor#3428]
From https://github.com/google/cadvisor/blob/master/docs/running.md

> [Standalone](https://github.com/google/cadvisor/blob/master/docs/running.md#standalone)
> cAdvisor is a static Go binary with no external dependencies. To run it standalone all you should need to do is run it! Note that some data sources may require root privileges. cAdvisor will gracefully degrade its features to those it can expose with the access given.
> 
> $ sudo cadvisor
> cAdvisor is now running (in the foreground) on http://localhost:8080/.

Where is this binary located?

**Comment by martadinata666** [comment]
to make it run like `$ sudo cadvisor` you will need to place `cadvisor` binary at either `/usr/local/bin/`, `/usr/bin/` or `/usr/sbin/`. Maybe this is common sense among linux users so not explained further.

**Comment by mammuthus** [comment]
@martadinata666 
> you will need to place cadvisor binary
You are right, but I couldn't find the binary.

**Comment by martadinata666** [comment]
download, rename to cadvisor, add executable bit, move to `/usr/bin`

**Comment by mammuthus** [comment]
Ah, I see it now. I checked the latest releases and noticed that binaries are available only for the released versions, not for pre-releases.
