### ISSUE TITLE
cadvisor:latest container tag is outdated

### ISSUE THREAD

**Issue by jjgmckenzie** [google/cadvisor#3481]
I had an issue with cgroupv2 detection; which appeared that it had been fixed from all the issues I could read, so I was convinced I was dealing with a regression, as I read several modern reported issues with the same problem while searching for the cause or a fix.

After a little too long debugging, I discovered that while I was using the container image ``gcr.io/cadvisor/cadvisor:latest`` - it's not the latest version - it appears to have been packaged in 2020. The solution was using ``gcr.io/cadvisor/cadvisor:v0.47.2`` instead; now everything  work fine. 

Example issues, I'm sure there's more:
https://github.com/google/cadvisor/issues/3468
https://github.com/grafana/alloy/issues/486

**Comment by rc5hack** [comment]
#3400

**Comment by cwangVT** [comment]
update `latest` container tag to v0.49.1
