### ISSUE TITLE
Latest release on github points to older version.

### ISSUE THREAD

**Issue by kannon92** [google/cadvisor#3484]
I noticed that github says the latest release is 0.47.0 and you have to look at the release page to see newer versions of it.

It would be nice to have 0.49 as the latest release on the page. And maybe mark 0.48 as a valid release (it was marked pre-release) but we used this in kube 1.29 AFAIK..

**Comment by bobbypage** [comment]
Fixed in https://github.com/google/cadvisor/releases/tag/v0.49.1
