### ISSUE TITLE
Missing docker. images in registry

### ISSUE THREAD

**Issue by ybizeul** [google/cadvisor#3489]
```
❯ docker pull gcr.io/cadvisor/cadvisor:v0.47.2
Error response from daemon: manifest for gcr.io/cadvisor/cadvisor:v0.47.2 not found: manifest unknown: Failed to fetch "v0.47.2" from request "/v2/cadvisor/cadvisor/manifests/v0.47.2".
❯ docker pull gcr.io/cadvisor/cadvisor:v0.49.0
Error response from daemon: manifest for gcr.io/cadvisor/cadvisor:v0.49.0 not found: manifest unknown: Failed to fetch "v0.49.0" from request "/v2/cadvisor/cadvisor/manifests/v0.49.0".
```

`cadvisor-amd64` seems to be there

**Comment by naashw** [comment]
temporary fix:

Check the architecture using "dpkg --print-architecture"
and use the appropriate folder.
https://console.cloud.google.com/gcr/images/cadvisor

Arm64 : gcr.io/cadvisor/cadvisor-arm64:v0.47.2
Amd64 : gcr.io/cadvisor/cadvisor-amd64:v0.47.2

**Comment by bobbypage** [comment]
This is fixed now, sorry about that, release publishing issues.

**Comment by icf20** [comment]
> https://console.cloud.google.com/gcr/images/cadvisor

got removed ?

![image](https://github.com/google/cadvisor/assets/17784575/d385e6d7-20b6-41b8-88c4-d9a14168a39a)
