### ISSUE TITLE
Docker tag v0.47.2 retroactively changed to other image

### ISSUE THREAD

**Issue by andoks** [google/cadvisor#3490]
We check that the hash for tagged images are not changed retroactively, but the v0.47.2 tag seemed to have changed this Saturday. Was that intentional?

[Docker image in question](https://console.cloud.google.com/gcr/images/cadvisor/global/cadvisor@sha256:e6c562b5e983f13624898b5b6a902c71999580dc362022fc327c309234c485d7/details)

It seems to have happened on the same day as v0.49.1 was released [list of all images](https://console.cloud.google.com/gcr/images/cadvisor/GLOBAL/cadvisor)

**Comment by bobbypage** [comment]
Yes, as part of the v0.49.1 due to some release issues we had to rebuild and repush the v0.47.2 tag. The image build should be the same.
