### ISSUE TITLE
Issue w/ SemVer tags (`v0.999-bobbpage`,`0.99-porterdavid`]

### ISSUE THREAD

**Issue by DazWilkin** [google/cadvisor#3491]
I have a Bash script that enumerates tags in the repo to determine that most recent SemVer version.

I believe this should return `v0.49.1` but the script fails because of the existence of:

+  [`v0.999-bobbpage`](https://console.cloud.google.com/gcr/images/cadvisor/global/cadvisor@sha256:ad910043713c057387f2fbd84a7b4c1588432da9f759a70ce0dfd4c2023fded7/details);
+ and potentially [`0.99-porterdavid`](https://console.cloud.google.com/gcr/images/cadvisor/global/cadvisor@sha256:71f47c59830014357838f4b995977b4b7dfc7ce20545708ad67452d1834c073c/details)

Am I incorrect in assuming that I could determine the most recent version this way?

**Comment by bobbypage** [comment]
These images were used for testing our build / release process; it has been removed.
