### ISSUE TITLE
How to expose the container_restart_count metric

### ISSUE THREAD

**Issue by lyz-code** [google/cadvisor#3584]
I want to monitor if a docker is stuck restarting. In [the past it existed a `container_restart_count`](https://github.com/google/cadvisor/issues/1312) (with a pretty issue number btw), I've tried activating [all metrics](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#metrics) and it still doesn't show.

Does anyone have a clue on how to activate it?

Thanks

**Comment by chengjoey** [comment]
https://github.com/google/cadvisor/blob/c15f44e578c77800b1b82a7bbb67614364f4aedc/container/docker/handler.go#L199-L203

Only adds restartcount label if it's greater than 0

check you container `docker inspect ${id} | grep -i restart`, see it whether greater than 0

**Comment by lyz-code** [comment]
thanks @chengjoey for your answer
