### ISSUE TITLE
RHEL7: cAdvisor fails to talk to Docker inside a container.

### ISSUE THREAD

**Issue by vmarmol** [google/cadvisor#379]
Fails to talk to Docker. I think it is failing to get the socket.

**Comment by vmarmol** [comment]
This issue is still present in the 0.8.0 candidate.

**Comment by pmorie** [comment]
@vmarmol Can you clarify the exact scenario here?  Is cAdvisor running in a container or running on the host and trying to connect to a docker daemon running in dind?

**Comment by vmarmol** [comment]
@pmorie this is when cAdvisor runs inside a Docker container. Maybe SELinux something?

**Comment by pmorie** [comment]
Cool, @vmarmol.  @derekwaynecarr and I were talking about the case where
cAdvisor runs in a container since that's necessary for the kubernetes
Kubelet to run in a container.

**Comment by vmarmol** [comment]
Kubelet would run into the same problem talking to Docker I imagine. They use the same library.

**Comment by furlongm** [comment]
Running cadvisor on Centos 7 in a docker container, and no other docker containers show up. There are at least 7 others running. I can see that stats for the cadvisor subcontainer though.

Maybe a red herring, but I noticed Centos has no /var/run/docker directory. Would that make a difference?

**Comment by furlongm** [comment]
Docker output on the host machine: http://pastebin.com/raw.php?i=xfABJTfK

None of the other containers seem to figure at all.

**Comment by vmarmol** [comment]
@furlongm I was able to reproduce the issue in a Docker container with CentOS 7. I was able to fix it by running with `--privilege`. I suspect the issue is related to SELinux. I will document that on RHEL7 and CentOS 7 users should use `--privilege`.

Let me know if this doesn't work for you.

**Comment by vmarmol** [comment]
Verified that this fixes RHEL 7.

**Comment by furlongm** [comment]
SELinux is disabled for me, so I don't think that is the issue.

--privilege was not accepted as a command line argument:

```flag provided but not defined: --privilege
See 'docker run --help'.```

See 9e7ce0dbf64b90b5e1a7f9c68e1e12778139e325

**Comment by furlongm** [comment]
@vmarmol actually even with SELinux disabled, cgroups mounted correctly, and `--privileged=true`, this still does not work for me. Still only seeing the cadvisor container. Can we re-open this issue? Happy to debug further.

**Comment by vmarmol** [comment]
@furlongm I suspect you're having a different issue. Can you open up another issue and provide the cAdvisor log (`--v=2` if you can) and the output of `/validate` on the cAdvisor UI?

**Comment by jerrykkkkk** [comment]
--privileged=true
