### ISSUE TITLE
Can I config the "/" container as physical host in container_hints.json

### ISSUE THREAD

**Issue by ahjdzx** [google/cadvisor#400]
Hi,

Can I config the "/" container as physical host in container_hints.json.

If I can, then how to config the full_path argument ?        

Merry X'mas!

**Comment by rjnagal** [comment]
@ahjdzx What information do you want to see for the physical host? I just added information about machine network stats to the root container. Is that the bit you are looking for?

**Comment by ahjdzx** [comment]
Really? I just want looking for the information about machine network stats. This is my container_hints.json
```
{
  "name": "Container Hints",
  "description": "Container hints file",
  "all_hosts": [
    {
      "network_interface": {
        "veth_child": "eth0",
        "veth_host": "veth28a464e"
      }
    }
  ]
}
```
but i can't found the network infomation from the cadvisor web page. Is that i am config wrong?

**Comment by rjnagal** [comment]
We haven't made an official release with the machine network stats? Can you try jnagal/cadvisor:canary image? It should show you root stats on the /containers page.

**Comment by vmarmol** [comment]
This is now in the official 0.8.0 release btw.

**Comment by ahjdzx** [comment]
@rjnagal @vmarmol Thank you very much!

**Comment by vmarmol** [comment]
Assuming this worked for you? Closing in that case :) feel free to re-open if that's not the case.
