### ISSUE TITLE
Influxdb page is a broken link

### ISSUE THREAD

**Issue by josh-devops-center** [google/cadvisor#411]
[Storage Drivers](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#storage-drivers) linked to [InfluxDB Instructions](https://github.com/google/cadvisor/blob/master/docs/docs/influxdb.md)

Also it would be helpful if there was an InfluxDB container available for a quickstart example.

**Comment by rjnagal** [comment]
Thanks for reporting @josh-devops-center. It makes sense to create a simple InfluxDB container with the default settings. We'll work on adding one.

**Comment by rjnagal** [comment]
Closing this as we fixed the link.
