### ISSUE TITLE
Can't see Memory and Network graphs

### ISSUE THREAD

**Issue by tpires** [google/cadvisor#416]
When using cAdvisor:0.7.0 or cAdvisor:0.7.1 it doesn't show memory total usage graph, usage breakdown bar, network throughput and errors graphs.

cAdvisor 0.6.2 works fine.

```bash
$ docker info
Containers: 8
Images: 226
Storage Driver: devicemapper
 Pool Name: docker-253:1-393380-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 8.749 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 12.07 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-431.20.3.el6.x86_64
Operating System: <unknown>
```

System
```bash
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.5 (Santiago)
$ uname -a
Linux server 2.6.32-431.20.3.el6.x86_64 #1 SMP Fri Jun 6 18:30:54 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
```
Launch cAdvisor with:
```bash
$ docker run --detach=true \
	--name cadvisor \
	-v /:/rootfs:ro \
	-v /var/run:/var/run:rw \
	-v /sys:/sys:ro \
	-v /var/lib/docker:/var/lib/docker:ro \
	-v /cgroup:/cgroup \
	-p 8080:8080 \
	--memory=1g \
	google/cadvisor:0.7.0
```

**Comment by rjnagal** [comment]
Can you provide the output for localhost:8080/validate?
Are you seeing missing stats for root, or all docker containers? 

Can you also grab the output for localhost:8080/api/v1.2/containers? Thanks.

**Comment by vmarmol** [comment]
Does the graph not show up or the whole memory section?

If only the graph doesn't show: Can you open up the JavaScript console in your browser and see if any errors show up? This sounds like something is breaking drawing the graph.

**Comment by tpires** [comment]
@rjnagal tested, it's working. thank you :)
