### ISSUE TITLE
cAdvisor does not return memory data on Debian

### ISSUE THREAD

**Issue by cwahl-Treeptik** [google/cadvisor#432]
I have had some troubles making cAdvisor work on Debian, especially returning data on the memory, and I wanted to share the solution! The use case is a [Docker based PaaS dedicated to Java/JEE applications] (http://cloudunit.fr/).

By default, the Cgroup memory controller is in the state missing on Debian, so cAdvisor does not collect the relevant data.

The solution simply consists in adding the line:
```bash
GRUB_CMDLINE_LINUX="cgroup_enable=memory"
```
to the file `/etc/default/grub`. Then, one has to run: `sudo update-grub2` and reboot.

[A more detailed article](http://blog.treeptik.fr/2014/12/cadvisor-sous-debian/) is available on our blog.

**Comment by vmarmol** [comment]
Thanks @cwahl-Treeptik! We've known about the issue but we should document it better. Let me add a pointer to these instructions to the docs.

**Comment by sathieu** [comment]
Note that the memory controller is enabled by default in Debian 9 (stretch):
```
linux (4.7.2-1) unstable; urgency=medium
  [...]
  * cgroups: Enable memory controller by default
  [...]

 -- Ben Hutchings <ben@decadent.org.uk>  Sun, 28 Aug 2016 15:56:10 +0100
```
