### ISSUE TITLE
Nested containers require 1-line patch

### ISSUE THREAD

**Issue by hinesmr** [google/cadvisor#450]
Hi All,

I'm running docker inside LXC. (Please don't ask why - I don't want a philosophical debate to erupt).
cAdvisor itself is running inside outer LXC container and monitoring the inner docker containers.

When cAdvisor starts up inside the outer LXC, it finds an inner docker cgroup located in:

/sys/fs/cgroup/cpu/lxc/outer_container_name/docker/inner_container_name

Instead of:

/sys/fs/cgroup/cpu/docker/inner_container_name

So, a 1-line patch seemed to fix this in container/docker/factory.go, in the function "IsDockerContainerName", by changing this:

return strings.HasPrefix(name, "/docker/")

To this:

return strings.Contains(name, "/docker/")

Seems to work fine on my system: Is this a reasonable request for a change?

**Comment by vmarmol** [comment]
No questions or judgement on your setup :)

Only thing I worry about that approach is that we could be tricked into marking some containers as Docker containers (arguably we could today, but less likely). I agree we need to have a better answer for this though. This sounds like a case we should be able to handle. Let me see if we can come up with something that works here too.

**Comment by rjnagal** [comment]
IMO, we should classify docker+lxc containers under raw handler. The logic we have for docker handler assumes libcontainer. We already capture the type of execdriver docker is using. 

We might do a better docker+lxc support, but going to raw handler seems like it will fix reporting for these containers, right?

**Comment by vmarmol** [comment]
@rjnagal I think he means that he runs docker+libcontainer under a top-level LXC container. He's running cAdvisor inside that same LXC container and wants it to work as expected.

**Comment by rjnagal** [comment]
Ah, sorry. I completely mis-read that :)

**Comment by hinesmr** [comment]
Right, exactly. Thanks for the consideration, guys.

**Comment by vmarmol** [comment]
Another possible option is that when we determine whether a container is a Docker container, we just parse the ID and ask Docker if it knows about the container. It may mean more communication with the Docker daemon, but shouldn't be much more latency at startup.

I believe this would work for your usecase too @hinesmr?

**Comment by hinesmr** [comment]
Yes, that would be great =).
