### ISSUE TITLE
cAdvisor from HEAD crashes while calculating cpu load

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#452]
Here is the stack trace:

I0120 04:55:23.919359 21096 cadvisor.go:150] Starting cAdvisor version: "0.8.0" on port 8080
panic: runtime error: slice bounds out of range

goroutine 66 [running]:
runtime.panic(0x8d0100, 0xf04b2f)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
bufio.(*Reader).Read(0xc208004f60, 0xc2080f8000, 0xf5, 0xf5, 0xfffffffffffffff0, 0x0, 0x0)
        /usr/local/go/src/pkg/bufio/bufio.go:184 +0x3b3
github.com/google/cadvisor/utils/cpuload.(*Connection).ReadMessage(0xc208117e30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vishnuk/go/src/github.com/google/cadvisor/utils/cpuload/conn.go:90 +0x168
github.com/google/cadvisor/utils/cpuload.getLoadStats(0xc208160014, 0xb, 0xc208117e30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vishnuk/go/src/github.com/google/cadvisor/utils/cpuload/netlink.go:228 +0x175
github.com/google/cadvisor/utils/cpuload.(*CpuLoadReader).GetCpuLoad(0xc2081371c0, 0xc20816ac00, 0x5a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vishnuk/go/src/github.com/google/cadvisor/utils/cpuload/cpuload.go:67 +0x2b8
github.com/google/cadvisor/manager.(*containerData).updateStats(0xc2081a8ea0, 0x0, 0x0)
        /home/vishnuk/go/src/github.com/google/cadvisor/manager/container.go:243 +0x1f5
github.com/google/cadvisor/manager.(*containerData).housekeepingTick(0xc2081a8ea0)
        /home/vishnuk/go/src/github.com/google/cadvisor/manager/container.go:205 +0x2d
github.com/google/cadvisor/manager.(*containerData).housekeeping(0xc2081a8ea0)
        /home/vishnuk/go/src/github.com/google/cadvisor/manager/container.go:167 +0x1d1
created by github.com/google/cadvisor/manager.(*containerData).Start
        /home/vishnuk/go/src/github.com/google/cadvisor/manager/container.go:60 +0x41

**Comment by rjnagal** [comment]
@vishh Can you try with the new head and see what errors are reported?

**Comment by vmarmol** [comment]
Closing, reopen if it resurfaces.

**Comment by rjnagal** [comment]
@kateknister This is the bug I was referring to. Please check if you can repro it when you re-enable cpu load.

**Comment by krallin** [comment]
Hey there,

(let me know if I should be opening a new issue).

Just got this error running cAdvisor 0.22.2. The trace is as follows:

```
panic: runtime error: slice bounds out of range

goroutine 125 [running]:
bufio.(*Reader).Read(0xc8201d0e40, 0xc820adc2d0, 0x10, 0x10, 0xa4a2a0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:214 +0x3c8
io.ReadAtLeast(0x7f12a57c6100, 0xc8201d0e40, 0xc820adc2d0, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7f12a57c6100, 0xc8201d0e40, 0xc820adc2d0, 0x10, 0x10, 0x10, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x62
encoding/binary.Read(0x7f12a57c6100, 0xc8201d0e40, 0x7f12a57c18e8, 0x14272d8, 0xa21220, 0xc820f77bc0, 0x0, 0x0)
        /usr/local/go/src/encoding/binary/binary.go:216 +0x1336
github.com/google/cadvisor/utils/cpuload/netlink.(*Connection).ReadMessage(0xc8204141e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/build/gopath/src/github.com/google/cadvisor/utils/cpuload/netlink/conn.go:88 +0x146
github.com/google/cadvisor/utils/cpuload/netlink.getLoadStats(0xc820390018, 0x39, 0xc8204141e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/build/gopath/src/github.com/google/cadvisor/utils/cpuload/netlink/netlink.go:231 +0x1b6
github.com/google/cadvisor/utils/cpuload/netlink.(*NetlinkReader).GetCpuLoad(0xc820402e70, 0xc820544550, 0x48, 0xc820399740, 0x5a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/build/gopath/src/github.com/google/cadvisor/utils/cpuload/netlink/reader.go:73 +0x33f
github.com/google/cadvisor/manager.(*containerData).updateStats(0xc820674960, 0x0, 0x0)
        /home/build/gopath/src/github.com/google/cadvisor/manager/container.go:508 +0x330
github.com/google/cadvisor/manager.(*containerData).housekeepingTick(0xc820674960)
        /home/build/gopath/src/github.com/google/cadvisor/manager/container.go:447 +0x2b
github.com/google/cadvisor/manager.(*containerData).housekeeping(0xc820674960)
        /home/build/gopath/src/github.com/google/cadvisor/manager/container.go:398 +0x29f
created by github.com/google/cadvisor/manager.(*containerData).Start
        /home/build/gopath/src/github.com/google/cadvisor/manager/container.go:94 +0x41
```

Is there anything I can do to help troubleshoot this?

Cheers,
