### ISSUE TITLE
Error launching the container

### ISSUE THREAD

**Issue by cjschroed** [google/cadvisor#454]
Status: Downloaded newer image for google/cadvisor:0.8.0
F0121 02:57:03.357816 00001 cadvisor.go:76] Failed to create a Container Manager: could not parse speed from -1 for device eth0
goroutine 16 [running]:
github.com/golang/glog.stacks(0x4c208091e00, 0x0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:726 +0xcc
github.com/golang/glog.(*loggingT).output(0xf17540, 0x4c200000003, 0x4c2080aa000)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:677 +0x243
github.com/golang/glog.(*loggingT).printf(0xf17540, 0x3, 0x9e07b0, 0x28, 0x7fda746b6ef0, 0x1, 0x1)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:635 +0x187
github.com/golang/glog.Fatalf(0x9e07b0, 0x28, 0x7fda746b6ef0, 0x1, 0x1)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:1033 +0x64
main.main()
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/cadvisor.go:76 +0x50b

My guess at the root cause:
The device eth0 does not have an IP address from DHCP and as a result the value of the eth0/speed file under /sys is -1. This prevents the manager from starting. The system has an IP address for eth1 and it's speed is 1000.
The system OS is CentOS 6.6, Docker version is 1.3.2.

**Comment by cjschroed** [comment]
More info: I gave eth0 a static IP, however it did not have a cable attached, thus no link state and no speed. :(

**Comment by vmarmol** [comment]
Sent out #455 to fix this. If you can test and verify from HEAD, we'd really appreciate it :)
