### ISSUE TITLE
Proposal : Add storage driver for graphite

### ISSUE THREAD

**Issue by ankushagarwal** [google/cadvisor#474]
Graphite is the most popular time series database storage out there and I really want to have a storage driver for graphite. Although I am not a Go expert, I can take a stab at the driver. I took a look the InfluxDB driver and it does not look very complex with just three interface methods to be implemented.

**Comment by vishh** [comment]
+1 for adding a graphite storage driver.

**Comment by rjnagal** [comment]
We'd be happy to accept a new driver and help with changes. We have been wanting to get Graphite in for a while, but never got around to it.

The other option is to make it a driver under heapster (github.com/GoogleCloudPlatform/Heapster) which helps in aggregating across all machines in a cluster. But, a storage driver in cAdvisor would be fine too.

**Comment by ankushagarwal** [comment]
Thanks for the support. I'll try to have something soon.

**Comment by sstarcher** [comment]
+1 let me know if you need any help testing it

**Comment by ankushagarwal** [comment]
I have some code ready to go in, but I want to understand the long term goal for storage driver config options from CLI.

Currently for influxdb, the options are 

-storage_driver_host
-storage_driver_db
-storage_driver_user
-storage_driver_password
-storage_driver_secure

As more and more storage drivers are added, these options will become harder to serve as common options for all the drivers. For example graphite needs a "graphite_prefix" config option.

I can try to fit graphite options using these options, or we can try to have separate options for each driver like what docker/machine does : https://github.com/docker/machine/blob/master/README.md

What are your thoughts on this?

**Comment by rjnagal** [comment]
I can think of two ways:
1. driver type prefixes like docker machine. I think its clean and is much easier to handle.
2. Use --type and --storage_config=file. We can provide a single config file with all the info. We'll parse the config file based on type.

I like 2 for conciseness. But I think there were some concerns on passing around files for deployment. If that is going to be inconvenient, let's go with 1.

**Comment by vmarmol** [comment]
+1 on @rjnagal's options 1

**Comment by rjnagal** [comment]
ok, 1 it is then. Take it away @ankushagarwal !

**Comment by ankushagarwal** [comment]
Cool. Then I will first refactor influxdb and bigquery config options in a PR and then open up another PR sometime next week to add a stable graphite driver.

**Comment by vishh** [comment]
How about a third option:
Separate storage drivers into separate binaries and run them as sidecars?
We can provide the common infrastructure required to implement such side
cars, and even build and ship them as part of a cadvisor release.

This frees cadvisor from any storage driver related issues. Any auth
required for storage drivers can be packed as part of a separate image
without having to wrap the base cadvisor image. It is even possible to
export different data to different endpoints without having to modify
cadvisor.

**Comment by vmarmol** [comment]
That is the approach that we've been advocating after the initial two
drivers were added. By sidecar @vishh means a Docker container running
alongside the cAdvisor container.

**Comment by ankushagarwal** [comment]
I like this idea much better. It decouples the core cAdvisor from storage driver issues. Versioning will be one major problem when storage drivers are integrated within cAdvisor.

**Comment by ankushagarwal** [comment]
Yup, just run another container which is linked to cAdvisor, uses its API and exports stats to a storage driver. With this approach, data can also be exported to multiple storage drivers with ease.

**Comment by lesaux** [comment]
@ankushagarwal I tried your graphite driver implementation and it seems to be working well!
I compiled from https://github.com/ankushagarwal/cadvisor/tree/graphite-driver
ran cadvisor with the following params:
-logtostderr -storage_driver="graphite" -storage_driver_host="192.168.0.61:2003" -storage_driver_db="graphite"  -allow_dynamic_housekeeping=false -housekeeping_interval=10s

and got the following output:
Num bytes written  590 590
Send shit to graphite  1426196507
Aliases :  [hopeful_mestorf 6001525f0e0e0430659f3831c66ce8d768274dddac71a5584fb3d5e3ec767db8]
graphite.1b78e27ac033.hopeful_mestorf.cpu_cumulative_usage 966125072 1426196507
graphite.1b78e27ac033.hopeful_mestorf.memory_usage 63438848 1426196507
graphite.1b78e27ac033.hopeful_mestorf.memory_working_set 31633408 1426196507
graphite.1b78e27ac033.6001525f0e0e0430659f3831c66ce8d768274dddac71a5584fb3d5e3ec767db8.cpu_cumulative_usage 966125072 1426196507
graphite.1b78e27ac033.6001525f0e0e0430659f3831c66ce8d768274dddac71a5584fb3d5e3ec767db8.memory_usage 63438848 1426196507
graphite.1b78e27ac033.6001525f0e0e0430659f3831c66ce8d768274dddac71a5584fb3d5e3ec767db8.memory_working_set 31633408 1426196507

Confirmed I was able to browse the graphs by using graphite-api + grafana.
It's a very good start for the graphite driver!

**Comment by lesaux** [comment]
In the meantime, I ship docker container metrics to graphite this way: https://github.com/lesaux/diamond-DockerContainerCollector

**Comment by esseti** [comment]
Hi all,
is there any update/tutorial on how to send the data to grphite? it could be enough to send it to local statsd daemon running on the same machine and then use the `write_graphite` option. but is it possible?

**Comment by iwankgb** [comment]
Closing very old issue. See #1458 regarding sending data to not yet implemented storaged.
