### ISSUE TITLE
Add a '/events' REST endpoint

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#480]
cAdvisor should expose an '/events' endpoint which can be used to export events like 'OOM kills', 'container creation/deletion' etc. Ideally this should be a Watch interface, instead of a pull based one. But we can start with a pull based API with an option to specify the time duration (e.x. last 'x' seconds).

**Comment by vishh** [comment]
@kateknister this might be something you can work on.

**Comment by rjnagal** [comment]
We can call this done with the v0.11.0

**Comment by chenjunsheng** [comment]
ok

**Comment by MattMattV** [comment]
This feature seems to be nice but one time again, no documentation to know how that works... :cry:
