### ISSUE TITLE
Define custom metric support for cAdvisor

### ISSUE THREAD

**Issue by rjnagal** [google/cadvisor#483]
Do we want to read in custom metrics from user and export these through our APIs? It would help a lot of use-cases in kubernetes. For derived stats, we would also need to define a notion of schedulable and non-schedulable stats. This will help us distinguish stats that are useful for scheduler vs ones useful for debugging and perf.

We can build a model similar to container hints to pick up new metrics. We'll somehow need the new metric endpoints to be accessible within cAdvisor container.

But before how, we would like to figure out what is it we need :) @vishh @vmarmol

**Comment by vmarmol** [comment]
Aren't custom metrics out of scope for cAdvisor? Or maybe I'm not sure what metrics you're mentioning :)

**Comment by vishh** [comment]
By custom metrics Rohit is referring to future resources that cadvisor will/might track. Examples: Storage, Network, special hardware

@rjnagal : Will we need derived stats for debugging and perf related metrics?

The resource type naming model for kubernetes is [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/resources.md#resource-types)

**Comment by vishh** [comment]
The main argument for an extensible API is that of making the rest of the system generic - in the case of kubernetes, whenever a new derived schedulable stats is exposed by cadvisor, and in-turn by kubelet, which is just a proxy as of now, the stats become immediately usable by the scheduler.

**Comment by rjnagal** [comment]
We only need derived stats for schedulable metrics. For these custom metrics, we need to be able to obtain a node-capacity total too, which isn't relevant for debug/perf stats.

 @vmarmol this is an off-shoot from discussion around #481 

k8 use case is:
1. A cluster provider plugs in custom metric for say their own storage device. These could be anything - even software licenses available for that node.
2. Without any changes, cAdvisor starts exposing derived stats for the new metric. Kubelet fwds these to statscollector and they are available to scheduler.
3. Without any modification, scheduler can schedule based on the new custom metric as long as we piped the capacity and usage fields through. 

This requires us to make at least the derived stats a generic map.

**Comment by vmarmol** [comment]
I think the offline discussion resulted in "we don't need this to be done in cAdvisor"? The discussion in #481 was separate from that.

**Comment by rjnagal** [comment]
yes. All interested parties have finally agreed. phew!

**Comment by fabiand** [comment]
@rjnagal @vmarmol Could someone elaborate on the reasons which were speaking against exporting additional metrics?
