### ISSUE TITLE
Investigate cpu usage for scraping diskio stats

### ISSUE THREAD

**Issue by rjnagal** [google/cadvisor#501]
There are many files and a lot of parsing. Internally, we do diskio stats scraping every 10s.
That might be the way to go.

**Comment by cboggs** [comment]
:+1: 
I noticed a pretty hefty load increase when I had Cadvisor running yesterday on a docker host with a couple TB of local storage, and a couple dozen du's running pretty much all the time. Stopped the Cadvisor container and the du's went away, and load returned to expected values.

Happy to gather more detailed stats if needed.

**Comment by vmarmol** [comment]
What version of cAdvisor were you running? Any way that you could get how much CPU cAdvisor was using? :) I don't doubt we're doing some silly things around this...

**Comment by jamshid** [comment]
Every time I try cadvisor, after a while I have to disable it because of high cpu usage (eg, see below). Likely the same `du` issue, saw du's in `top` briefly. I did a fresh docker pull today of google/cadvisor. 
```
$ docker ps -q | xargs docker stats
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
68e20776129f        0.00%               1.082 MiB/500 MiB   0.22%               452 KiB/46.16 KiB
7b31946e2c1e        638.20%             42 MiB/500 MiB      8.40%               21.02 MiB/516 MiB
8ab17fc74c77        3.47%               3.832 MiB/500 MiB   0.77%               8.042 KiB/648 B
...
$ docker ps -a | grep 7b31946e2c1e
7b31946e2c1e        google/cadvisor:latest                                                    "/usr/bin/cadvisor t   3 hours ago         Up 3 hours                     0.0.0.0:911->8080/tcp                                                                     buildenv_cadvisor_1

$ docker-machine ssh dev sudo top
Mem: 3650684K used, 402700K free, 0K shrd, 290K buff, 292K cached
CPU: 15.0% usr 78.1% sys  0.0% nic  6.3% idle  0.0% io  0.0% irq  0.3% sirq
Load average: 13.33 13.02 9.79 14/1423 6992
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
 2356   718 root     R     885m 22.3   7 70.4 /usr/bin/cadvisor true
 8833  8816 root     S    2470m 62.2   0  3.0 /usr/bin/java -Xms256m -Xmx1g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyF
14698 14688 root     S    2480m 62.5   4  2.6 /usr/bin/java -Xms256m -Xmx1g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyF
...

**Comment by ztl8702** [comment]
Same issue, waiting for answer.

**Comment by rjnagal** [comment]
There is no good cheap way to get disk usage from various docker storage drivers today.

Would it help if we added a flag to disable disk usage reporting per container? We can still report the full disks usage and free space. We can add an on-demand endpoint to retrieve diskspace info per container if required.

**Comment by ztl8702** [comment]
I thought reducing the frequency of checking should reduce CPU usage,
however after I set --housekeeping_interval=10s, cAdvisor still seemed to check every second.

**Comment by a86c6f7964** [comment]
i think that it would be nice to have a flag that will disable the disk checks for containers if anything just for debugging

**Comment by timstclair** [comment]
@a86c6f7964 We want to make cAdvisor more modular and configurable so that most stats can be disabled if desired. I'm planning to send out a design proposal in the next couple weeks.

**Comment by a86c6f7964** [comment]
FYI. I just ran strace on the 'du' that is running, and realized that the du for the cadvisor container disk usage itself is running over every single docker container for the entire system.

```
lstat("/var/lib/docker/overlay/e14e4f15e1673095fa6562703280ac11a85d8c0e58cbf469199ed6d29249b130/merged/rootfs/var/lib/docker/overlay/e1b4d58b9cae8953890ffdd493d1f84e751dc0b2b2649d2772b0354d5ced6a10/
```
this seems undesirable to me.

 Since 
```
--volume=/:/rootfs:ro
```

**Comment by vishh** [comment]
That's a bug. I will fix it soon! Good catch Cameron!

**Comment by jeremyeder** [comment]
@timothysc something to watch for...

**Comment by iwankgb** [comment]
Closing very old issue.
