### ISSUE TITLE
cadvisor Docker logs

### ISSUE THREAD

**Issue by rbrutgers** [google/cadvisor#503]
Hello,
    I think it would be very useful to display the tail logs of the containers on the UI as well.  What do you think?  Is this on the roadmap for this project?

**Comment by vmarmol** [comment]
Unfortunately, it's not on the roadmap and we probably won't add it. There are already quite a few projects working with logs and it is a big enough work area that it's not something we can go into lightly.

I don't think we're a full-features Docker UI (which is fine, it wasn't the initial goal :) ) so there are a bunch of stuff missing in that regard already.

**Comment by rbrutgers** [comment]
Ok, thanks.  Do you recommend any logging tools I could use in conjunction with cadvisor?  Or are there any ways to extract functionality of cadvisor to my own personal ui?

**Comment by vishh** [comment]
You can try using [fluentd](http://www.fluentd.org/guides/recipes/docker-logging).

**Comment by rbrutgers** [comment]
Ok thanks.
