### ISSUE TITLE
Error: not enough arguments in call to theConn.StartTransientUnit

### ISSUE THREAD

**Issue by knodir** [google/cadvisor#504]
Hello,

I am trying to use [Go client](https://github.com/google/cadvisor/tree/master/client) to get the status of my Docker instances. However, I get following error message when I execute 

`$ go get github.com/google/cadvisor/manager`
\# github.com/docker/libcontainer/cgroups/systemd
.gvm/pkgsets/go1.4/global/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:64: not enough arguments in call to theConn.StartTransientUnit
.gvm/pkgsets/go1.4/global/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:76: not enough arguments in call to theConn.StartTransientUnit
.gvm/pkgsets/go1.4/global/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:145: not enough arguments in call to theConn.StartTransientUnit

I have [Docker-maintained](https://docs.docker.com/installation/ubuntulinux/) Ubuntu package. Here is the output from `$ docker version`
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

The latest version of Go installed via [gvm](http://www.hostingadvice.com/how-to/install-golang-on-ubuntu/). Output from  `$ go version` is
go version go1.4 linux/amd64

Any help is appreciated,
Nodir.

**Comment by vishh** [comment]
'go get' will try to compile cadvisor. Try running 'go get -d
github.com/google/cadvisor'. To build cadvisor, you need to use 'godep' -
'godep go build github.com/google/cadvisor'.

Tip: Install 'godep' as follows: 'go get github.com/tools/godep'. Make sure
binaries inside 'GOBIN' are accessible

**Comment by knodir** [comment]
Thanks for the suggestion! Followed the steps, but still get the same error.

I think `StartTransientUnit()` of `dbus` type is being called incorrectly. The [current implementation](https://github.com/coreos/go-systemd/blob/master/dbus/methods.go#L136) of the `dbus.Conn.StartTransientUnit()` requires 4 arguments 

`func (c *Conn) StartTransientUnit(name string, mode string, properties []Property, ch chan<- string) (int, error)`

But libcontainer's [apply_systemd.go](https://github.com/docker/libcontainer/blob/master/cgroups/systemd/apply_systemd.go) is passing 2 arguments on line \#[64](https://github.com/docker/libcontainer/blob/master/cgroups/systemd/apply_systemd.go#L64), 3 arguments on line \#[76](https://github.com/docker/libcontainer/blob/master/cgroups/systemd/apply_systemd.go#L76), and varagrs on line \#[145](https://github.com/docker/libcontainer/blob/master/cgroups/systemd/apply_systemd.go#L145)

I am pretty sure cAdvisor is calling the old version of `StartTransientUnit()`, which was as following:

`func (c *Conn) StartTransientUnit(name string, mode string, properties ...Property) (string, error)`

Change history shows it was rewritten as the former one at "dbus: block on jobs only if provided non-nil channel" [commit](https://github.com/coreos/go-systemd/commit/b5b3eb9085bd12385de9313b5871455dc67af703#diff-b5b8384be79564335a3b50bcfed63e91L128) by [bcwaldon](https://github.com/bcwaldon) on Sep 25, 2014. 

Is there a quick way to fix this? I don't want to do a workaround and be incompatible with cAdvisor master. 

Btw: I suspected go1.4 version I am using and Docker using go1.4.1 might have something to do with these. But still get the same error after updating both to go1.4.1 Just in case, here is the output:

`$ go version`
go version go1.4.1 linux/amd64

`$ docker version`
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

Thanks,
Nodir.

**Comment by vmarmol** [comment]
Hi Nadir,

What is the output of `godep go build github.com/google/cadvisor`?

The function's signature may have changed but all of cAdvisor's dependencies are forked with Godep so those changes should not affect the build.

**Comment by knodir** [comment]
I get `godep: No Godeps found (or in any parent directory)` when I do `godep go build github.com/google/cadvisor` from `$HOME`.

Then I manually got into the folder by `cd $GOPATH/src/github.com/google/cadvisor` and run `godep go build ./` It run for 5-6 seconds and did not have any output. I thought "no output" means build is successful. Isn't it the case?

**Comment by vmarmol** [comment]
Sorry, we should have specified that you needed to be inside the cAdvisor repo for it to work. Yes, the build succeeded and the cAdvisor binary should we in you current working directory. Let us know if htat is not the case.

If you're looking for a Docker image, in the deploy directory there is a `build.sh` that creates a `google/cadvisor:canary` image for you.

**Comment by knodir** [comment]
Yes, I do get cAdvisor binary on CWD. But, I am not looking for a Docker image. I do have cAdvisor  running with other Dockers, and I am trying to retrieve the status information via [Go client](https://github.com/google/cadvisor/tree/master/client). 

I'm adopting code from [cadvisor/pages/containers.go](https://github.com/google/cadvisor/blob/master/pages/containers.go#L186) to retrieve current CPU, RAM, and other information. Code is definitely not complete, but I think I should be able to import `github.com/google/cadvisor/manager` to do something meaningful. Here is my code:

```go
package main
import ("fmt"
	"os"
	"github.com/google/cadvisor/pages"
	"github.com/google/cadvisor/manager"
)

func checkFail(msg string, err error, terminate bool) {
	if err != nil {
		fmt.Printf("%s: %s\n", msg, err)
		if terminate {
			os.Exit(0)
		}
	}
} 

func main() {
	containerName := "LONG_IMAGE_ID"
	request := info.ContainerInfoRequest{2}

	cont, err := manager.Manager.GetContainerInfo(containerName, &request)
	checkFail("Failed to get container", err, false)
	
	displayName := getContainerDisplayName(cont.ContainerReference)
	fmt.Println("\ndisplayName = ", displayName)
}
```

Which gives me following error message on `$ go run monitor.go`

```error
# github.com/docker/libcontainer/cgroups/systemd
src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:64: not enough arguments in call to theConn.StartTransientUnit
src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:76: not enough arguments in call to theConn.StartTransientUnit
src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:145: not enough arguments in call to theConn.StartTransientUnit
```

**Comment by vmarmol** [comment]
Ah I see, you're trying to connect and query a running cAdvisor. For that you will need to use the client as you mentioned. Don't use the `manager` or `pages/container.go` those are part of the implementation of cAdvisor and won't be quite useful outside of it. The client will query cAdvisor through the REST API and return the results. For your example you should be able to do something like this:

```Go
package main
import ("fmt"
    "os"
    "github.com/google/cadvisor/client"
)

func checkFail(msg string, err error, terminate bool) {
    if err != nil {
        fmt.Printf("%s: %s\n", msg, err)
        if terminate {
            os.Exit(0)
        }
    }
} 

func main() {
    containerName := "LONG_IMAGE_ID"
    request := info.ContainerInfoRequest{2}

    client, err := client.NewClient("http://<address of cAdvisor, localhost for local>:<port for cAdvisor, default is 8080>/")
    checkFail("Failed to get cAdvisor client", err, true)

    // Since we specifically want a Docker container, else use ContainerInfo().
    cont, err := client.DockerContainer(containerName, &request)
    checkFail("Failed to get container", err, false)

    displayName := getContainerDisplayName(cont.ContainerReference)
    fmt.Println("\ndisplayName = ", displayName)
}
```

What parts of `pages/container.go` were you interested in? It may make sense to break those appart. We've been moving away from code there and rather do most of the work in the JavaScript UI where we can be more dynamic.

**Comment by knodir** [comment]
Okay, it seems I quickly got distracted with nice looking web UI, and did not look at the data structures available at `info/container.go`. I think `info/container.go` suits my needs better than `pages/container.go`. I played with `ContainerInfo`, `ContainerStats`, `ContainerSpec` in `info/container.go` and they seem to provide everything I need. Here is the direction I'm headed now.

```go
func main() {
	dockClient, err := client.NewClient("http://localhost:8080/")
	checkFail("Could not create NewClient", err, false)	
	containerName := "LONG_IMAGE_ID"	
	request := info.ContainerInfoRequest{2}
	sInfo, err := dockClient.ContainerInfo("/docker/"+containerName, &request)
	checkFail("Could not get container info", err, false)

	fmt.Println("Name = ", sInfo.Name)
	fmt.Println("Aliases = ", sInfo.Aliases)
	spec := sInfo.Spec
	fmt.Println("HasCpu = ", spec.HasCpu)
	fmt.Println("nCpu = ", spec.Cpu)

	stats := sInfo.Stats
	fmt.Println("Timestamp = ", stats[0].Timestamp)
	fmt.Println("CpuStats = ", stats[0].Cpu)
}
```

Which outputs following:

```text
Name =  /docker/LONG_IMAGE_ID
Aliases =  [trusting_meitner LONG_IMAGE_ID]
HasCpu =  true
nCpu =  {1024 0 0-3}
Timestamp =  2015-02-16 01:41:58.741376674 +0000 UTC
CpuStats =  {{15846157 [6243279 1400997 3806319 4395562] 0 0} 0}
```

This is great, and cAdvisor is awesome. Thanks for the help, and good work on cAdvisor! I'm closing this issue.

Nodir.
