### ISSUE TITLE
v0.9.0 fails to start on Centos6

### ISSUE THREAD

**Issue by difro** [google/cadvisor#505]
Running v0.9.0 (latest at docker hub) on Centos6 fails with following error.
```
F0216 04:47:21.812981 00001 cadvisor.go:76] Failed to create a Container Manager: open /sys/class/net/bonding_masters/address: not a directory
goroutine 1 [running]:
github.com/golang/glog.stacks(0x4c2080ae700, 0x0, 0x0, 0x0)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:726 +0xcd
github.com/golang/glog.(*loggingT).output(0xf014a0, 0x4c200000003, 0x4c2080bae40)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:677 +0x24c
github.com/golang/glog.(*loggingT).printf(0xf014a0, 0x4c200000003, 0x9fe4d0, 0x28, 0x4c2080d3f38, 0x1, 0x1)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:635 +0x19c
github.com/golang/glog.Fatalf(0x9fe4d0, 0x28, 0x4c2080d3f38, 0x1, 0x1)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:1033 +0x64
main.main()
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/cadvisor.go:76 +0x5fe
```

/sys/class/net/ does contain a file called ```bonding_masters```
```
ls -l /sys/class/net/
...
lrwxrwxrwx 1 root root    0 2015-01-30 10:01 bond0 -> ../../devices/virtual/net/bond0
-rw-r--r-- 1 root root 4096 2015-01-30 10:01 bonding_masters
lrwxrwxrwx 1 root root    0 2015-01-30 10:01 docker0 -> ../../devices/virtual/net/docker0
```

Maybe should skip over non-directory, non-symlink files?

**Comment by rjnagal** [comment]
Thanks for reporting @difro. We should filter these out.

**Comment by pireslaert** [comment]
When is that going to be released  and be part of the docker image?

Cheers,

**Comment by vmarmol** [comment]
We've been waiting to release it as part of 0.10.0 but that has taken longer to get out than expected. We'll build a 0.9.1 with this fix tomorrow.

**Comment by pireslaert** [comment]
great!

Cheers

Sent from my BlackBerry 10 smartphone.
From: Victor Marmol
Sent: Tuesday, 24 February 2015 6:09 PM
To: google/cadvisor
Reply To: google/cadvisor
Cc: pireslaert
Subject: Re: [cadvisor] v0.9.0 fails to start on Centos6 (#505)


We've been waiting to release it as part of 0.10.0 but that has taken longer to get out than expected. We'll build a 0.9.1 with this fix tomorrow.

---

**Comment by vmarmol** [comment]
`google/cadvisor:0.10.0` was just pushed and should be available. It will go through our release testing and marked latest today/tomorrow.

**Comment by pireslaert** [comment]
is that part the latest docker image?

**Comment by vmarmol** [comment]
Just pushed to latest, you should see it now.

**Comment by pireslaert** [comment]
awesome, working now!

**Comment by vmarmol** [comment]
Awesome!
