### ISSUE TITLE
Storing Additional Metadata

### ISSUE THREAD

**Issue by Rob-Johnson** [google/cadvisor#508]
Hello,

Is there anyway I can attach arbitrary metadata to the rows/points stored by cadvisor?

We're using cadvisor to export container metrics from each of our application servers into Influxdb. Servers are grouped into clusters. What we'd like to do it store additional metadata, such as the cluster name, with each point cadvisor stores, so we can query stats by this additional metadata.

Does cadvisor allow for such a thing? If not, do you have any thoughts on how to solve the problem?

Thanks!

**Comment by vishh** [comment]
You might want to take a look at [heapster](https://github.com/GoogleCloudPlatform/heapster). It was built originally to collect data from all cadvisor nodes and attach arbitrary metadata. It might not work out-of-box for your use case, but it should not be too difficult to extend heapster to satisfy your use case.

**Comment by vmarmol** [comment]
Similar to what @vishh suggested, you can run a small daemon that queries cAdvisor and exports the data as you'd like. Heapster does this at the cluster level and is somewhat opinionated on how it looks to exports data. Depending on your goal that or your custom exported would work best.

**Comment by Rob-Johnson** [comment]
Thanks for your suggestions, I'll look at whether we can adapt Heapster for what we need.
