### ISSUE TITLE
Allow root url to be defined aka be nicer to reverse proxies

### ISSUE THREAD

**Issue by cburroughs** [google/cadvisor#513]
Right now cadvisor assumes it's in charge of `/` and uses absolute urls for everything.  This makes it difficult to put a reverse proxy infront and serve cadvisor from differnt urls.  For example, I'd like have Apache httpd listen on port 80, use ldap for ACLs, and then proxy `:80/cadvisor/`to cadvisor running on a port that's only on localhost.  Either (A) avoidance of absolute urls (B) allow some sort of 'CADVISOR_HTTP_ROOT'  (default: `/`) shoud work.

**Comment by tbleiker** [comment]
+1 for this feature :smile:

**Comment by schmichri** [comment]
+1
