### ISSUE TITLE
cadvisor with vanilla lxc, (i.e. not docker)

### ISSUE THREAD

**Issue by nstott** [google/cadvisor#551]
Is is possible to run cadvisor without docker, i.e. on raw lxc containers / rocket / etc

It seems like there are explicit checks that explicitly require docker, and It's not clear how to get around that

Thanks,

**Comment by rjnagal** [comment]
It should work without docker. There is a special docker handler endpoint
/docker where you won't see anything. cAdvisor will spew some errors that
it didn't find docker, but would continue on.

Please file an issue if you encounter any problems running without docker.

**Comment by nstott** [comment]
Thanks, I was confused by the docker message, I'll close this.
I think this is a problem with the cgroup mounts within the container.

```
E0228 02:18:32.494433 00099 cadvisor.go:81] Docker registration failed: unable to communicate with docker daemon: dial unix /var/run/docker.sock: no such file or directory.
F0228 02:18:32.495640 00099 cadvisor.go:86] Raw registration failed: failed to get cgroup subsystems: failed to find cgroup mounts.
goroutine 1 [running]:
github.com/golang/glog.stacks(0x4c20800b800, 0x0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:726 +0xcd
github.com/golang/glog.(*loggingT).output(0xf1c4c0, 0x4c200000003, 0x4c2080ee240)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:677 +0x24c
github.com/golang/glog.(*loggingT).printf(0xf1c4c0, 0x3, 0x9d7230, 0x1c, 0x4c208213f38, 0x1, 0x1)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:635 +0x19c
github.com/golang/glog.Fatalf(0x9d7230, 0x1c, 0x4c208213f38, 0x1, 0x1)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:1033 +0x64
main.main()
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/cadvisor.go:86 +0x833
```

**Comment by vmarmol** [comment]
@nstott the first error `Docker registration failed` means we didn't find the Docker daemon so we won't provide Docker-specific data. That's fine, we'll continue running without it.

The second error `Raw registration failed` means we couldn't find the cgroups. That one is not fine since we have no way to detect containers in that case. If you run into this  let us know and we have help debug.

**Comment by jhunthrop** [comment]
Did you ever resolve the issue of the cgroup mounts within the lxc container? I'm working through running cadvisor inside an lxc-container to provide metrics for all containers running on the host machine.

**Comment by dylode** [comment]
> Did you ever resolve the issue of the cgroup mounts within the lxc container? I'm working through running cadvisor inside an lxc-container to provide metrics for all containers running on the host machine, and I am hitting the same issue.

Did you solve this?

**Comment by nstott** [comment]
I'm not sure if we did resolve this, tbh.
as stated above, the key is managing to mount the cgroup filesystem
