### ISSUE TITLE
cAdvisor Plugins and PCP

### ISSUE THREAD

**Issue by simon3z** [google/cadvisor#562]
Reading https://github.com/GoogleCloudPlatform/kubernetes/issues/990 I saw:

> - cAdvisor plugin for collectd is still a WIP

Is this still the current design? Having pluggable cAdvisor backends?

If so I think we should start considering PCP as a possible backend: http://pcp.io/

**Comment by vmarmol** [comment]
There are currently two ways to export data from cAdvisor: backends or sidecars. Backends are compiled into cAdvisor and can be used natively. Sidecars are containers that run alongside cAdvisor and fetch data from it. They then push it to the desired backend. We've been advocating for sidecards recently. They're easier to maintain if someone doesn't volunteer to actively maintain the backend :)

**Comment by simon3z** [comment]
@vmarmol I thought that cAdvisor was pulling the data from the backends to expose it through its api, but from your description it seems the other way around: cAdvisor providing metrics for collectd/pcp.

If that's the case (cAdvisor providing metrics for collectd/pcp) does it mean that cAdvisor will be focused/specialized only on container metrics?

**Comment by rjnagal** [comment]
Collecting custom metrics is a goal for cAdvisor, but right now we do push to collectors like you said.
The plugin in roadmap is supposed to add cAdvisor data with all the stuff that collectd already collects and push it out to backend storage.

So you are right, there is no pull backend for cAdvisor right now.

**Comment by fche** [comment]
Is the medium-term goal to have data collectors that are peers to cadvisor send data to the same storage backend?  Or to have cadvisor participate in that pipeline as an intermediary?

**Comment by vmarmol** [comment]
@fche yes to collectors initially. Eventually cAdvisor will participate.

**Comment by fche** [comment]
Could you by any chance point this k8s/cadvisor neophyte at the appropriate integration interfaces as to how to be a peer to cadvisor?

**Comment by vmarmol** [comment]
For gathering data from cAdvisor the best thing is to use the [REST API](https://github.com/google/cadvisor/blob/master/docs/api.md) or the [Go client library](https://github.com/google/cadvisor/blob/master/docs/clients.md)

**Comment by fche** [comment]
@vmarmot, no, that's a separate thing.  We want to supplement the data from cadvisor, not consume data from it.

**Comment by vmarmol** [comment]
Ah I see what you mean. I'm guessing you'd like some way to get where cAdvisor is pushing data to? We don't have an interface for that today unfortunately.

**Comment by vmarmol** [comment]
An easy hack today is that however you configure cAdvisor you can configure your other collector. That would not require you to get any information from cAdvisor.

**Comment by fche** [comment]
@rjangal, can you confirm this advice?  i.e., to bypass cadvisor for collectd/pcp-type data supplementation?

**Comment by simon3z** [comment]
@vmarmol I think it would be beneficial is someone can explain what this meant:

> * Use collectd
>  * cAdvisor plugin for collectd is still a WIP

From: https://github.com/GoogleCloudPlatform/kubernetes/issues/990

/cc @vishh @lavalamp @thockin

What was the idea there?
What was the cAdvisor plugin for collectd going to do? Get metrics from collectd?

**Comment by vishh** [comment]
AFAIK cadvisor will be one of the plugins for collectd. collectd along with
other application metrics will also be able to export system resource usage
metrics exported by cadvisor.
What is your desired behavior? Are you thinking about having collectd
export per container metrics?

**Comment by vmarmol** [comment]
@simon3z as @vishh mentioned the original plan was to have collectd consume cAdvisor data and export that. I don't think that's a route we're currently pursuing.

**Comment by dashpole** [comment]
Storage driver discussion: #1458
