### ISSUE TITLE
Add Filtering list of subcontainers

### ISSUE THREAD

**Issue by rbanks74** [google/cadvisor#566]
It would be nice to have the subcontainers in a sorted order if possible by subcontainer name on the UI, as well as a search bar to quickly filter subcontainers by name.

**Comment by vmarmol** [comment]
The sort order of the containers should be fixes in 0.10.1 via #532. Are you finding that not to be the case? I will re-name this issue to deal with filtering.

**Comment by rbrutgers** [comment]
I see the issue, I'm running 0.9 :) .  But the filtering would be a nice touch too.  Thanks!
