### ISSUE TITLE
Integration test is flaky

### ISSUE THREAD

**Issue by rjnagal** [google/cadvisor#568]
The integration tests have lately been flaky. Sometimes the failure is related to docker daemon failing to create a container, or errors in rest api returns.

I tried running the test manually targeting our test machines, and it worked every time. I think the first thing would be to dump more state for docker and cadvisor when the test fails.

**Comment by vmarmol** [comment]
And retry the operations we see fail.

**Comment by iwankgb** [comment]
Closing very old issue.
