### ISSUE TITLE
open /sys/class/dmi/id/product_uuid: no such file or directory

### ISSUE THREAD

**Issue by nashasha1** [google/cadvisor#577]
I don't know why my EC2 ubuntu vm doesn't exist file -- /sys/class/dmi/id/product_uuid
so cadvisor crash when  getMachineInfo() was called.
will you handle this?

**Comment by rjnagal** [comment]
This is already fixed in head by #570. cAdvisor from head should work. We'll make a release with the fix soon.

**Comment by vmarmol** [comment]
@nashasha1 closing this issue since the fix is in and waiting a release. Feel free to file an issue if you run into any problems and thanks for reporting!
