### ISSUE TITLE
Make cAdvisor work on systemd systems 

### ISSUE THREAD

**Issue by rjnagal** [google/cadvisor#59]
This will fix some of the issues involved in running on systemd machines. Hopefully, this will make it work on all systemd machines.

I'll look through particular failures on CoreOS systems and add them here.

**Comment by kabudu** [comment]
@vmarmol Was a patch applied to cadvisor to ignore non-docker and non-root containers in systemd systems? I'm using the latest tag of google/cadvisor available on docker hub with CentOS Linux release 7.2.1511 and still seeing systemd containers appearing in the stats from cadvisor.

**Comment by vishh** [comment]
cAdvisor does not ignore any containers as of now.

**Comment by rjnagal** [comment]
--docker_only=true would filter cgroups to only report docker and root containers.

**Comment by andyxning** [comment]
> --docker_only=true would filter cgroups to only report docker and root containers.

This is really use to reduce the output from `stats/container` when used with heapster legacy kubelet source.
