### ISSUE TITLE
helpers.go is importing a package that does not exist

### ISSUE THREAD

**Issue by gouyang** [google/cadvisor#595]
"github.com/docker/libcontainer/network" in the import section is not existing any more, the network package is re-factoring into file "network_linux.go" in "github.com/docker/libcontainer" package.

**Comment by vmarmol** [comment]
cAdvisor uses [godep](https://github.com/tools/godep) so our dependencies area version in the "Godeps" directory. We haven't updated to the latest libcontainer and probably will soon. We have some instructions about cAdvisor building [here](https://github.com/google/cadvisor/blob/master/docs/build.md), let us know if you run into any trouble with those.

Closing this issue for now, but feel free to open new issues if you run into trouble.
