### ISSUE TITLE
Allow subfolder hosting, stop using absolute paths

### ISSUE THREAD

**Issue by runningman84** [google/cadvisor#596]
There is a cool container called frontdoor:
https://registry.hub.docker.com/u/clue/frontroute/

Cadvisor doesn't work good with it. The css stuff is lost due to aabsolute paths in the cadvisor html code.

**Comment by yeasy** [comment]
Any progress on this?

Seems the latest version still does not work.

**Comment by timstclair** [comment]
Not that I know of, but patches are welcome!
