### ISSUE TITLE
cadvisor won't start dockerized

### ISSUE THREAD

**Issue by Snapbug** [google/cadvisor#601]
I wanted to enable prometheus support for cadvisor, which doesn’t appear to be in the latest/beta/canary builds available from the docker registry (the /metrics endpoint redirects to /containers/ causing an error when prometheus scrapes it).

I cloned the repository (changeset: a973ddb) and used the deploy/build.sh script to build and generate the docker image. However running the generated image resulted in:

    FATA[0000] Error response from daemon: Cannot start container <hash>: no such file or directory

I tracked this down to the fact that cadvisor uses cog features, and at least in my environment this links against glibc, whereas the alpine image cadvisor is based off for the docker image uses musl, [related docker-alpine issue](https://github.com/gliderlabs/docker-alpine/issues/12)

Reverting [this change to the Dockerfile](https://github.com/google/cadvisor/commit/e69432f5db51d3dfa25781384c3902e7f0f57d6d#diff-2a33e645dffdb8c6e5dc53153fc455a6) fixes the issue as the old base image contains glibc

Not sure how this should progress: there must have been a reason to switch to alpine, in which case there needs to be an updated build script/instructions, or switch back to busybox.

**Comment by vmarmol** [comment]
Yes you're right, looks like I didn't get this sufficiently :P will revert that tomorrow. Thanks for catching and reporting! There is an issue out for using the docker builds in or integration tests, but we're not there yet.
