### ISSUE TITLE
I0327 19:18:36.727089 00001 storagedriver.go:92] No backend storage selected

### ISSUE THREAD

**Issue by roldancer** [google/cadvisor#616]
Hi All,
    I'm trying to execute cAdvisor in an Redhat Atomic Host (GA), I got the following error, any idea?

I0327 19:18:36.727089 00001 storagedriver.go:92] No backend storage selected
log: exiting because of error: log: cannot create log: open /tmp/cadvisor.23777f6a4bd2.root.log.INFO.20150327-191836.1: permission denied

I'm using the following parameters:

docker run -ti --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8080:8080  --name=cadvisor google/cadvisor:latest

**Comment by roldancer** [comment]
Hi All, if I run the container in previleded mode, it works OK .... any  idea ?

docker run -d --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8080:8080  --name=cadvisor --privileged=true google/cadvisor:latest

**Comment by vmarmol** [comment]
@roldancer it looks like cAdvisor is not able to write to its log files. For some reason it is unable to open a file in the container's /tmp. Since it is an Atomic host, it sounds like an SELinux thing.

To prove that theory, can you try running without privileged with `--logtostderr`:

```
docker run -ti --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8080:8080 --name=cadvisor google/cadvisor:latest --logtostderr
```

**Comment by roldancer** [comment]
Hi @vmarmol, your theory is correct, cadvisor work OK with parameter "--logtostderr".

Many thanks for your help

**Comment by roldancer** [comment]
Hi @vmarmol, I found a new error when using the parameter "--logtostderr", containers are not discovered, this is the cadvisor's log, I think SELinux is restricting some operations ...


W0327 20:26:14.555638 00001 handler.go:534] Error while processing event ("/var/lib/docker/devicemapper/mnt/623abb2aa2cfd323fadd29f02f9f84d266c91a7a7a778999c7fec3441753427d/rootfs/rootfs/sys/fs/cgroup/cpu,cpuacct/system.slice/NetworkManager-dispatcher.service": 0x40000200 == IN_DELETE|IN_ISDIR): inotify_rm_watch: invalid argument
W0327 20:26:14.556464 00001 handler.go:534] Error while processing event ("/var/lib/docker/devicemapper/mnt/623abb2aa2cfd323fadd29f02f9f84d266c91a7a7a778999c7fec3441753427d/rootfs/rootfs/sys/fs/cgroup/blkio/system.slice/NetworkManager-dispatcher.service": 0x40000200 == IN_DELETE|IN_ISDIR): inotify_rm_watch: invalid argument
W0327 20:26:33.556400 00001 handler.go:534] Error while processing event ("/cpuacct.usage": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cpuacct.usage"
W0327 20:26:33.556505 00001 handler.go:534] Error while processing event ("/cpuacct.usage_percpu": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cpuacct.usage_percpu"
W0327 20:26:33.556546 00001 handler.go:534] Error while processing event ("/cpuacct.stat": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cpuacct.stat"
W0327 20:26:33.556577 00001 handler.go:534] Error while processing event ("/cpu.shares": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cpu.shares"
W0327 20:26:33.556626 00001 handler.go:534] Error while processing event ("/cpu.cfs_quota_us": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cpu.cfs_quota_us"
W0327 20:26:33.556692 00001 handler.go:534] Error while processing event ("/cpu.cfs_period_us": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cpu.cfs_period_us"
W0327 20:26:33.556728 00001 handler.go:534] Error while processing event ("/cpu.stat": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cpu.stat"
W0327 20:26:33.556758 00001 handler.go:534] Error while processing event ("/cpu.rt_runtime_us": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cpu.rt_runtime_us"
W0327 20:26:33.556789 00001 handler.go:534] Error while processing event ("/cpu.rt_period_us": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cpu.rt_period_us"
W0327 20:26:33.556824 00001 handler.go:534] Error while processing event ("/tasks": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/tasks"
W0327 20:26:33.556881 00001 handler.go:534] Error while processing event ("/cgroup.procs": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cgroup.procs"
W0327 20:26:33.556914 00001 handler.go:534] Error while processing event ("/notify_on_release": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/notify_on_release"
W0327 20:26:33.556947 00001 handler.go:534] Error while processing event ("/cgroup.event_control": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cgroup.event_control"
W0327 20:26:33.556976 00001 handler.go:534] Error while processing event ("/cgroup.clone_children": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cgroup.clone_children"
W0327 20:26:33.557011 00001 handler.go:534] Error while processing event ("/var/lib/docker/devicemapper/mnt/623abb2aa2cfd323fadd29f02f9f84d266c91a7a7a778999c7fec3441753427d/rootfs/rootfs/sys/fs/cgroup/cpu,cpuacct/system.slice/NetworkManager-dispatcher.service": 0x40000200 == IN_DELETE|IN_ISDIR): inotify_rm_watch: invalid argument
W0327 20:26:33.557048 00001 handler.go:534] Error while processing event ("/blkio.reset_stats": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.reset_stats"
W0327 20:26:33.557082 00001 handler.go:534] Error while processing event ("/blkio.throttle.read_bps_device": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.throttle.read_bps_device"
W0327 20:26:33.557111 00001 handler.go:534] Error while processing event ("/blkio.throttle.write_bps_device": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.throttle.write_bps_device"
W0327 20:26:33.557169 00001 handler.go:534] Error while processing event ("/blkio.throttle.read_iops_device": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.throttle.read_iops_device"
W0327 20:26:33.557203 00001 handler.go:534] Error while processing event ("/blkio.throttle.write_iops_device": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.throttle.write_iops_device"
W0327 20:26:33.557237 00001 handler.go:534] Error while processing event ("/blkio.throttle.io_service_bytes": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.throttle.io_service_bytes"
W0327 20:26:33.557267 00001 handler.go:534] Error while processing event ("/blkio.throttle.io_serviced": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.throttle.io_serviced"
W0327 20:26:33.557300 00001 handler.go:534] Error while processing event ("/blkio.weight_device": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.weight_device"
W0327 20:26:33.557328 00001 handler.go:534] Error while processing event ("/blkio.weight": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.weight"
W0327 20:26:33.557360 00001 handler.go:534] Error while processing event ("/blkio.leaf_weight_device": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.leaf_weight_device"
W0327 20:26:33.557389 00001 handler.go:534] Error while processing event ("/blkio.leaf_weight": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.leaf_weight"
W0327 20:26:33.557421 00001 handler.go:534] Error while processing event ("/blkio.time": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.time"
W0327 20:26:33.557456 00001 handler.go:534] Error while processing event ("/blkio.sectors": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.sectors"
W0327 20:26:33.557514 00001 handler.go:534] Error while processing event ("/blkio.io_service_bytes": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_service_bytes"
W0327 20:26:33.557951 00001 handler.go:534] Error while processing event ("/blkio.io_serviced": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_serviced"
W0327 20:26:33.558015 00001 handler.go:534] Error while processing event ("/blkio.io_service_time": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_service_time"
W0327 20:26:33.558066 00001 handler.go:534] Error while processing event ("/blkio.io_wait_time": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_wait_time"
W0327 20:26:33.558094 00001 handler.go:534] Error while processing event ("/blkio.io_merged": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_merged"
W0327 20:26:33.558170 00001 handler.go:534] Error while processing event ("/blkio.io_queued": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_queued"
W0327 20:26:33.558237 00001 handler.go:534] Error while processing event ("/blkio.time_recursive": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.time_recursive"
W0327 20:26:33.558287 00001 handler.go:534] Error while processing event ("/blkio.sectors_recursive": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.sectors_recursive"
W0327 20:26:33.558319 00001 handler.go:534] Error while processing event ("/blkio.io_service_bytes_recursive": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_service_bytes_recursive"
W0327 20:26:33.558353 00001 handler.go:534] Error while processing event ("/blkio.io_serviced_recursive": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_serviced_recursive"
W0327 20:26:33.558384 00001 handler.go:534] Error while processing event ("/blkio.io_service_time_recursive": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_service_time_recursive"
W0327 20:26:33.558417 00001 handler.go:534] Error while processing event ("/blkio.io_wait_time_recursive": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_wait_time_recursive"
W0327 20:26:33.558460 00001 handler.go:534] Error while processing event ("/blkio.io_merged_recursive": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_merged_recursive"
W0327 20:26:33.558495 00001 handler.go:534] Error while processing event ("/blkio.io_queued_recursive": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/blkio.io_queued_recursive"
W0327 20:26:33.558532 00001 handler.go:534] Error while processing event ("/tasks": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/tasks"
W0327 20:26:33.558564 00001 handler.go:534] Error while processing event ("/cgroup.procs": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cgroup.procs"
W0327 20:26:33.558591 00001 handler.go:534] Error while processing event ("/notify_on_release": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/notify_on_release"
W0327 20:26:33.558621 00001 handler.go:534] Error while processing event ("/cgroup.event_control": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cgroup.event_control"
W0327 20:26:33.558648 00001 handler.go:534] Error while processing event ("/cgroup.clone_children": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cgroup.clone_children"
W0327 20:26:33.558686 00001 handler.go:534] Error while processing event ("/var/lib/docker/devicemapper/mnt/623abb2aa2cfd323fadd29f02f9f84d266c91a7a7a778999c7fec3441753427d/rootfs/rootfs/sys/fs/cgroup/blkio/system.slice/NetworkManager-dispatcher.service": 0x40000200 == IN_DELETE|IN_ISDIR): inotify_rm_watch: invalid argument
I0327 20:27:05.634734 00001 manager.go:511] Destroyed container: "/system.slice/NetworkManager-dispatcher.service" (aliases: [], namespace: "")

**Comment by vmarmol** [comment]
Yeah cAdvisor tries to look at a lot of places and sometimes we can't without being root. SELinux restricts some of that. This looks like our container detection inotify is failing. We still manually check every minute so containers should show up (do they?) after ~1min.

I'll take a closer look later today, these errors shouldn't be happening anyways.

**Comment by roldancer** [comment]
Many thanks for your help,

**Comment by vmarmol** [comment]
Sorry for the long delay @roldancer! This looks like a similar problem to #333. We either have a bug in the delete path or SELinux is unhappy (since both see this with SELinux). If you disable SELinux, so you see those log lines?

**Comment by dashpole** [comment]
closing since issue was solved
