### ISSUE TITLE
Feature Request: Alert (e.g. email) when container restarts/crashes/fails/etc

### ISSUE THREAD

**Issue by joelchen** [google/cadvisor#621]
Hi cAdvisor Team,

Thank you for building a containers monitoring system for the open source community.

I would like to request the feature of alerting (e.g. email via Gmail) when something happens to each container. Please advise if this is the right place to request such a feature, and whether there are already open source systems that alert users of containers' health which is usable on CoreOS.

Thank you.

Warmest Regards,
Joel

**Comment by vmarmol** [comment]
Hi @joelchen,

cAdvisor may be a bit too low level on the stack for alerting and the like. What we've seen others do is have cAdvisor export data to monitoring systems that can graph, visualize, and alert on that data. It brings more flexibility and scales better for clusters. One that I've heard use a lot recently is [Prometheus](http://prometheus.io/) You should be able to get that setup in CoreOS

**Comment by fabxc** [comment]
Yes, this is way beyond the scope of cAdvisor. The main purpose is exposing container metrics for consumption by a monitoring system further up the stack.

Is there disagreement on this or can this feature request be closed?
