### ISSUE TITLE
cadvisor/client does not work on CoreOS

### ISSUE THREAD

**Issue by knodir** [google/cadvisor#631]
Hi,

I'm using `github.com/google/cadvisor/client` to monitor Dockers running on CoreOS machine. My code works on Ubuntu but fails with:
`Could not get container info [...] failed to get container [...] unknown container [...]` 
error on CoreOS. Here is my monitoring application code:

```go
package main

import ("log"
	"github.com/google/cadvisor/client"
)

func main() {
	cadvisorClient, err := client.NewClient("http://localhost:8080/")
	log.Fatal("Could not create NewClient")

	containerName := "2da04ca875d0..."
	request := info.ContainerInfoRequest{NumStats: 1}

	fullContName := "/docker/"+containerName
	cInfo, err := cadvisorClient.ContainerInfo(fullContName, &request)
	log.Fatal("Could not get container info", err, true)
	fmt.Println("\ncInfo =", cInfo)
}
```

Which gives me following error message:

```shell
Could not get container info: request "http://localhost:8080/api/v1.2/containers/docker/2da04ca875d0..." failed with error: "failed to get container \"/docker/2da04ca875d0...\" with error: unknown container \"/docker/2da04ca875d0...\"" 
```

Is this known problem? Looking through previous issues, I came across issue #59 which mentions about the raw driver. I don't know what raw driver is. Does that help to resolve my problem?

Thanks,
Nodir.

**Comment by rjnagal** [comment]
The `container` endpoint looks for containers under the specified cgroup path - in your case /docker/2da.... This is the right path under ubuntu and other non-systemd systems, but not for systemd machines like CoreOS.

You are better off using the `docker` endpoint which will work for both type of machines. The following snippet works on both machines:

```
package main

import (
        "fmt"
        "github.com/google/cadvisor/client"
        info "github.com/google/cadvisor/info/v1"
        "log"
)

var (
        cont = "ef5ab94e8257868f117f942ef004097e0a415a2c66502ce6aeb74f58c55fdeba"
)

func main() {
        cadvisorClient, err := client.NewClient("http://localhost:8080/")
        if err != nil {
                log.Fatal("Could not create NewClient")
        }

        request := info.ContainerInfoRequest{NumStats: 1}

        cInfo, err := cadvisorClient.DockerContainer(cont, &request)
        if err != nil {
                log.Fatalf("Could not get container info: %v", err)
        }
        fmt.Println("\ncInfo =", cInfo)
}
```

**Comment by knodir** [comment]
This worked, thanks @rjnagal!

**Comment by chenjunsheng** [comment]
haodi
