### ISSUE TITLE
Journalctl should be runnable from inside the Docker container

### ISSUE THREAD

**Issue by pbhavsar211** [google/cadvisor#645]
Trying to run cadvisor on mac using boot2docker. mentioned issues is found while identifying docker logs cadvisor

**Comment by vmarmol** [comment]
Does cAdvisor exit? That should be a recoverable error and should only degrade what information we provide.

Is the system a systemd system btw?

**Comment by pbhavsar211** [comment]
no cAdvisor is still running. can you please explain "Is the system a systemd system?"

**Comment by vmarmol** [comment]
I guess I'm asking if you're running Systemd as your init system (I am not super familiar with what boot2docker runs). The error is benign, although we should try to get to the bottom of it and get OOM support on your specified platform.

**Comment by furlongm** [comment]
Also getting this issue on Centos 7 (with systemd on the main system, and journalctl available on the main system).

The error message is from within the cadvisor docker container and it is the only message returned by docker logs cadvisor.

Should journalctl be installed in the docker container?

**Comment by vmarmol** [comment]
Yes, although we'll need to test how systemd access works within a container. Will change the issue's title to reflect that.

**Comment by amos6224** [comment]
Also getting this issue on boot2docker even after i upgrade.

**Comment by radcheb** [comment]
+1

**Comment by cgswong** [comment]
I'm on CoreOS 647.2.0 and getting the error below when running cAdvisor (Google Docker image) in a fleet/systemd unit:

```
Jun 09 13:55:41 stluengtst03.monsanto.com docker[22924]: I0609 13:55:41.040406 00001 manager.go:151] Version: {KernelVersion:4.0.1 ContainerOsVersion:Buildroot 2014.02 DockerVersion:1.5.0 CadvisorVersion:0.14.0}
Jun 09 13:55:41 stluengtst03.monsanto.com docker[22924]: I0609 13:55:41.137500 00001 factory.go:220] System is using systemd
Jun 09 13:55:41 stluengtst03.monsanto.com docker[22924]: I0609 13:55:41.140705 00001 factory.go:228] Registering Docker factory
Jun 09 13:55:41 stluengtst03.monsanto.com docker[22924]: I0609 13:55:41.143247 00001 factory.go:64] Registering Raw factory
Jun 09 13:55:41 stluengtst03.monsanto.com docker[22924]: I0609 13:55:41.348053 00001 manager.go:930] Started watching for new ooms in manager
**Jun 09 13:55:41 stluengtst03.monsanto.com docker[22924]: E0609 13:55:41.348260 00001 manager.go:217] Failed to start OOM watcher, will not get OOM events: exec: "journalctl": executable file not found in $PATH**
Jun 09 13:55:41 stluengtst03.monsanto.com docker[22924]: I0609 13:55:41.348930 00001 manager.go:230] Starting recovery of all containers
Jun 09 13:55:41 stluengtst03.monsanto.com docker[22924]: I0609 13:55:41.456439 00001 manager.go:235] Recovery completed
Jun 09 13:55:41 stluengtst03.monsanto.com docker[22924]: I0609 13:55:41.510994 00001 cadvisor.go:90] Starting cAdvisor version: "0.14.0" on port 8080
```

cAdvisor remains up and running.

**Comment by vmarmol** [comment]
cAdvisor degrades its OOM support in these cases (it does not record OOMs), but should otherwise function as expected.

Not sure what the right answer is here, we probably don't want to include our own journalctl in the Docker image. We may end up mounting it from the host.

**Comment by trinitronx** [comment]
Just a hint:  It's probably good to gracefully degrade here, and not require `journalctl` because older distro versions (e.g.: CentOS / RHEL 6) do not have `systemd` or `journalctl`.

**Comment by vmarmol** [comment]
We do today, although we always assume that if systemd is present so will
journalctl. Let us know if that's not the case :)

**Comment by trinitronx** [comment]
@vmarmol:  To answer [your question earlier in the thread][4]. boot2docker does not have `systemd` or `journalctl` installed.  boot2docker is based on [Tiny Core Linux][1].  A [quick look at this wiki page][2] tells me that it's using the tried and true `inittab` / `/etc/init.d` / [SysV-style init][3] process.  So no systemd there.

[1]: http://distro.ibiblio.org/tinycorelinux/
[2]: http://wiki.tinycorelinux.net/wiki:the_boot_process
[3]: https://en.wikipedia.org/wiki/Init
[4]: https://github.com/google/cadvisor/issues/645#issuecomment-92510068

**Comment by trinitronx** [comment]
My thoughts are that this is "not a bug"...    It appears that @pbhavsar211 just may have not understood that `boot2docker` is not using `systemd` as it's init system.  It also is good to know that the message: 

> Failed to start OOM watcher, will not get OOM events: exec: "journalctl": executable file not found in $PATH

Is really just a warning and that `cAdvisor` gracefully degrades.

Perhaps really there is a hidden desire for a feature request here to add OOM-watcher support for old SysV-style init systems?

**Comment by rjnagal** [comment]
I think the message should not say "Failed to..."  and not be an error :)

The message should make clear that we are degraded gracefully. I'll add a
fix.

**Comment by trinitronx** [comment]
Seems that some folks are running into this on CentOS 7 and CoreOS... but my intuition tells me that they're probably not running the container in a way that makes the host's `journalctl` available inside the container.

**Comment by cgswong** [comment]
How should the image be run such that `journalctl` from the CoreOS host is made available to the container please? Below is my Docker run statement:

`
docker run --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker:/var/lib/docker:ro --publish=8080:8080 --name=%p google/cadvisor:latest --logtostderr -storage_driver=influxdb -storage_driver_host=stluengtst03.monsanto.com:8086 -storage_driver_db=cadvisor -storage_driver_user=root -storage_driver_password=root
`

**Comment by trinitronx** [comment]
After investigating a bit, I found that it appears the [`oomparser` already tries to look at `/var/log/messages` and `/var/log/syslog` files first, then falls back to trying `systemd`][1].   Seems that there is no bug here.

However, when I attempted to start the cadvisor container with `-v /var/log/messages:/var/log/messages:ro`, or with `-v /var/log:/var/log:ro`, the `/var/log/messages` file was not available inside the container.  Something else going on here that I'm missing?

[1]: https://github.com/google/cadvisor/blob/d1f21bb2fd951e1d9f8e03e9dee47698457f4fd3/utils/oomparser/oomparser.go#L189-L211
[2]: https://docs.docker.com/userguide/dockervolumes/

**Comment by vmarmol** [comment]
@trinitronx was the file available on the machine? The volume mounting of `/var/log` should work.

**Comment by aecolley** [comment]
Mounting the host's /var/log onto the container's /var/log fails (at least, on docker 1.6.2 and centos 6.6). The container's /var/log is a symlink to /tmp for some reason, and the mounted directory fails to appear. The same thing obstructs mounting /var/log/messages directly (not that you'd want to do that), as the file is quickly unlinked mysteriously.

I resorted to docker run ... --entrypoint=/bin/sh google/cadvisor:0.16.0 -c 'ln -s -f /rootfs/var/log/messages /var/log/messages && exec /usr/bin/cadvisor'

All of this is, strictly speaking, irrelevant. The original problem behind this bug report is that cadvisor chooses the less helpful of two possible error messages when it fails to find a kernel log file and then fails to run journalctl. If you fix that error, you can close this bug. I'll then file the centos issues in a new bug report.
