### ISSUE TITLE
errors out running on ubuntu 15.04 machine

### ISSUE THREAD

**Issue by paulczar** [google/cadvisor#666]
```
$ docker run \
>   --volume=/:/rootfs:ro \
>   --volume=/var/run:/var/run:rw \
>   --volume=/sys:/sys:ro \
>   --volume=/var/lib/docker/:/var/lib/docker:ro \
>   --publish=8080:8080 \
>   --detach=true \
>   --name=cadvisor \
>   google/cadvisor:latest
ec7ae802836e362f50fab8897d85c1fad6e50029d8456e5018a17e87ea32af34
        
pczarkowski@fileserver:~$ docker logs cadvisor
panic: close of closed channel

goroutine 13 [running]:
github.com/godbus/dbus.(*Conn).Close(0x4c2081059e0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/godbus/dbus/conn.go:178 +0x62
github.com/godbus/dbus.(*Conn).inWorker(0x4c2081059e0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/godbus/dbus/conn.go:334 +0x10be
created by github.com/godbus/dbus.(*Conn).Auth
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/godbus/dbus/auth.go:118 +0xe84

goroutine 1 [runnable]:
fmt.(*ss).getRune(0x4c2081e8000, 0x4c200000066)
	/usr/lib/google-golang/src/fmt/scan.go:220
fmt.(*ss).token(0x4c2081e8000, 0x1, 0xb35408, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/fmt/scan.go:472 +0x5d
fmt.(*ss).convertString(0x4c2081e8000, 0x73, 0x0, 0x0)
	/usr/lib/google-golang/src/fmt/scan.go:832 +0x11b
fmt.(*ss).scanOne(0x4c2081e8000, 0x73, 0x8280a0, 0x4c2081f3c50)
	/usr/lib/google-golang/src/fmt/scan.go:989 +0x1132
fmt.(*ss).doScanf(0x4c2081e8000, 0xa37eb0, 0x17, 0x4c2081ad758, 0x8, 0x8, 0x5, 0x0, 0x0)
	/usr/lib/google-golang/src/fmt/scan.go:1161 +0x373
fmt.Fscanf(0x7fc77dfe91e8, 0x4c2081bf890, 0xa37eb0, 0x17, 0x4c2081ad758, 0x8, 0x8, 0x7fc77dfd64b0, 0x0, 0x0)
	/usr/lib/google-golang/src/fmt/scan.go:145 +0xc0
fmt.Sscanf(0x4c2081d6500, 0xa0, 0xa37eb0, 0x17, 0x4c2081ad758, 0x8, 0x8, 0x8, 0x0, 0x0)
	/usr/lib/google-golang/src/fmt/scan.go:117 +0xcb
github.com/docker/docker/pkg/mount.parseInfoFile(0x7fc77dfe7fb0, 0x4c208034030, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo_linux.go:61 +0x69d
github.com/docker/docker/pkg/mount.parseMountTable(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo_linux.go:39 +0x135
github.com/docker/docker/pkg/mount.GetMounts(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mount.go:8 +0x4c
github.com/docker/libcontainer/cgroups.FindCgroupMountpoint(0x9f72f0, 0x3, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/libcontainer/cgroups/utils.go:19 +0x5a
github.com/google/cadvisor/container/docker.func·001()
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/container/docker/factory.go:62 +0x50
sync.(*Once).Do(0x100a9c0, 0xb35778)
	/usr/lib/google-golang/src/sync/once.go:44 +0xd4
github.com/google/cadvisor/container/docker.UseSystemd(0x4c208189c50)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/container/docker/factory.go:70 +0x36
github.com/google/cadvisor/container/docker.Register(0x7fc77dfeed40, 0x4c2080c2180, 0x7fc77dfed3b0, 0x4c20814f2e0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/container/docker/factory.go:217 +0x887
github.com/google/cadvisor/manager.New(0x4c2080c6480, 0x7fc77dfe9168, 0x100a940, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/manager/manager.go:139 +0xa20
main.main()
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/cadvisor.go:69 +0x454

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1001b00)
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
created by github.com/golang/glog.init·1
	/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/google-golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [syscall]:
os/signal.loop()
	/usr/lib/google-golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/google-golang/src/os/signal/signal_unix.go:27 +0x35
```

**Comment by vmarmol** [comment]
Hi @paulczar I'm guessing this happens consistently? Could you run cAdvisor with the flags: `--logtostderr --v=4` and provide the logs once more?

It seems that the crash is on a dbus call which we only do to check systemd. I may try to get my hands on a 15.04 VM as well.

**Comment by frioux** [comment]
I can repro it as well; here's what I get:

```
I0428 15:16:37.709945 00001 storagedriver.go:92] No backend storage selected
I0428 15:16:37.710220 00001 storagedriver.go:94] Caching %d stats in memory60
I0428 15:16:37.710441 00001 manager.go:105] cAdvisor running in container: "/system.slice/docker-6489e42b05cf5e27eda698ee17fb3782948d30fbaa3cfa4503812df9c608687a.scope"
I0428 15:16:37.720195 00001 fs.go:87] Filesystem partitions: map[/dev/mapper/tungsten-home:{mountpoint:/rootfs/home major:252 minor:1} /dev/sda1:{mountpoint:/rootfs/boot major:8 minor:1} /dev/mapper/t
ungsten-root_x64:{mountpoint:/rootfs major:252 minor:4} /dev/mapper/tungsten-games:{mountpoint:/rootfs/games major:252 minor:3}]
E0428 15:16:37.731583 00001 machine.go:267] Failed to get system UUID: open /sys/class/dmi/id/product_uuid: no such file or directory
I0428 15:16:37.731756 00001 machine.go:223] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0428 15:16:37.731846 00001 manager.go:126] Machine: {NumCores:2 CpuFrequency:2933000 MemoryCapacity:8238407680 MachineID: SystemUUID: BootID:304919a0-724a-4b52-abd2-d20669a649fa Filesystems:[{Device:
/dev/sda1 Capacity:238787584} {Device:/dev/mapper/tungsten-root_x64 Capacity:27345022976} {Device:/dev/mapper/tungsten-games Capacity:21003628544} {Device:/dev/mapper/tungsten-home Capacity:8996602675
2}] DiskMap:map[8:16:{Name:sdb Major:8 Minor:16 Size:80026361856 Scheduler:deadline} 8:32:{Name:sdc Major:8 Minor:32 Size:150039945216 Scheduler:deadline} 252:0:{Name:dm-0 Major:252 Minor:0 Size:84137
73824 Scheduler:none} 252:2:{Name:dm-2 Major:252 Minor:2 Size:322122547200 Scheduler:none} 252:4:{Name:dm-4 Major:252 Minor:4 Size:27917287424 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:500107
862016 Scheduler:deadline} 252:1:{Name:dm-1 Major:252 Minor:1 Size:91536490496 Scheduler:none} 252:3:{Name:dm-3 Major:252 Minor:3 Size:21474836480 Scheduler:none} 252:5:{Name:dm-5 Major:252 Minor:5 Si
ze:136365211648 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:00:23:ae:7a:96:20 Speed:100 Mtu:1500} {Name:lxcbr0 MacAddress:9e:93:dd:cc:f2:23 Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:8238407
680 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:
1}]}] Caches:[]}]}
I0428 15:16:37.734790 00001 manager.go:133] Version: {KernelVersion:3.13.0-34-generic ContainerOsVersion:Buildroot 2014.02 DockerVersion:1.6.0 CadvisorVersion:0.11.0}
panic: close of closed channel

goroutine 18 [running]:
github.com/godbus/dbus.(*Conn).Close(0x4c2080b3560, 0x0, 0x0)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/godbus/dbus/conn.go:178 +0x62
github.com/godbus/dbus.(*Conn).inWorker(0x4c2080b3560)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/godbus/dbus/conn.go:334 +0x10be
created by github.com/godbus/dbus.(*Conn).Auth
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/godbus/dbus/auth.go:118 +0xe84

goroutine 1 [runnable]:
fmt.(*stringReader).Read(0x4c208029e00, 0x4c2080cbfd0, 0x1, 0x4, 0x1, 0x0, 0x0)
        /usr/lib/google-golang/src/fmt/scan.go:90
io.ReadAtLeast(0x7fedca1c7610, 0x4c208029e00, 0x4c2080cbfd0, 0x1, 0x4, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/google-golang/src/io/io.go:298 +0xf1
io.ReadFull(0x7fedca1c7610, 0x4c208029e00, 0x4c2080cbfd0, 0x1, 0x4, 0x1, 0x0, 0x0)
        /usr/lib/google-golang/src/io/io.go:316 +0x6d
fmt.(*readRune).readByte(0x4c2080cbfb0, 0x40e665, 0x0, 0x0)
        /usr/lib/google-golang/src/fmt/scan.go:341 +0x142
fmt.(*readRune).ReadRune(0x4c2080cbfb0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/google-golang/src/fmt/scan.go:357 +0x5d
fmt.(*ss).ReadRune(0x4c208120000, 0x4c200000000, 0x0, 0x0, 0x0)
        /usr/lib/google-golang/src/fmt/scan.go:201 +0xe5
fmt.(*ss).getRune(0x4c208120000, 0x4c200000065)
        /usr/lib/google-golang/src/fmt/scan.go:221 +0x28
fmt.(*ss).token(0x4c208120000, 0x1, 0xb1e6c8, 0x0, 0x0, 0x0)
        /usr/lib/google-golang/src/fmt/scan.go:472 +0x5d
fmt.(*ss).convertString(0x4c208120000, 0x73, 0x0, 0x0)
        /usr/lib/google-golang/src/fmt/scan.go:832 +0x11b
fmt.(*ss).scanOne(0x4c208120000, 0x73, 0x81d340, 0x4c208090430)
        /usr/lib/google-golang/src/fmt/scan.go:989 +0x1132
fmt.(*ss).doScanf(0x4c208120000, 0xa24370, 0x17, 0x4c2080dd758, 0x8, 0x8, 0x6, 0x0, 0x0)
        /usr/lib/google-golang/src/fmt/scan.go:1161 +0x373
fmt.Fscanf(0x7fedca1c7610, 0x4c208029e00, 0xa24370, 0x17, 0x4c2080dd758, 0x8, 0x8, 0x7fedca1b5000, 0x0, 0x0)
        /usr/lib/google-golang/src/fmt/scan.go:145 +0xc0
fmt.Sscanf(0x4c20802b720, 0x50, 0xa24370, 0x17, 0x4c2080dd758, 0x8, 0x8, 0x80, 0x0, 0x0)
        /usr/lib/google-golang/src/fmt/scan.go:117 +0xcb
github.com/docker/docker/pkg/mount.parseInfoFile(0x7fedca1c6fb0, 0x4c208124250, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo_linux.go:61 +0x69d
github.com/docker/docker/pkg/mount.parseMountTable(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo_linux.go:39 +0x135
github.com/docker/docker/pkg/mount.GetMounts(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mount.go:8 +0x4c
github.com/docker/libcontainer/cgroups.FindCgroupMountpoint(0x9e4bb0, 0x3, 0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/libcontainer/cgroups/utils.go:19 +0x5a
github.com/google/cadvisor/container/docker.func·001()
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/container/docker/factory.go:55 +0x50
sync.(*Once).Do(0xfec938, 0xb1ea38)
        /usr/lib/google-golang/src/sync/once.go:44 +0xd4
github.com/google/cadvisor/container/docker.UseSystemd(0x4c208028990)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/container/docker/factory.go:63 +0x36
github.com/google/cadvisor/container/docker.Register(0x7fedca1c9a70, 0x4c208148000, 0x7fedca1c80b8, 0x4c20813aac0, 0x0, 0x0)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/container/docker/factory.go:211 +0x887
github.com/google/cadvisor/manager.New(0x4c20810a1c0, 0x7fedca1c7f48, 0xfec8b8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/manager/manager.go:138 +0xa20
main.main()
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/cadvisor.go:69 +0x454

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xfe3ae0)
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
created by github.com/golang/glog.init·1
        /usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/google-golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [syscall]:
os/signal.loop()
        /usr/lib/google-golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/google-golang/src/os/signal/signal_unix.go:27 +0x35
```

Not to sound like I'm stating the obvious here, but I'd guess it's a kernel setting; /sys/class/dmi/id/product_uuid doesn't exist on my system.

**Comment by vmarmol** [comment]
Thanks @frioux! That error is [not fatal](https://github.com/google/cadvisor/blob/master/manager/machine.go#L267). The panic is in the dbus library we're using. I think this is the first version of Ubuntu to come with a systemd? Maybe something is a-typical about it (or we just need to update our dbus library).

Will dig more into this. Thanks for reporting!

**Comment by frioux** [comment]
Yep, it is the very beginning of systemd support for ubuntu.  Might be interesting to see if Debian jessie has the same problem, as they just added systemd too (and it's likely the same.)

**Comment by mnuessler** [comment]
Having the same problem (also using Ubuntu 15.04). Container exits. Any updates on this, by any chance?

**Comment by vmarmol** [comment]
Sorry, haven't had time to spin up a VM with the new Ubuntu since I mainly use public clouds...Will try to get to this soon.

**Comment by wololock** [comment]
I have the same issue on the Ubuntu 15.04 server. Here are the details:

    docker-compose run cadvisor

The output:

	panic: close of closed channel

	goroutine 13 [running]:
	github.com/godbus/dbus.(*Conn).Close(0x4c2080cd7a0, 0x0, 0x0)
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/godbus/dbus/conn.go:178 +0x62
	github.com/godbus/dbus.(*Conn).inWorker(0x4c2080cd7a0)
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/godbus/dbus/conn.go:334 +0x10be
	created by github.com/godbus/dbus.(*Conn).Auth
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/godbus/dbus/auth.go:118 +0xe84

	goroutine 1 [runnable]:
	syscall.Syscall(0x0, 0x6, 0x4c208200000, 0x1000, 0xf52, 0x1000, 0x0)
		/usr/lib/google-golang/src/syscall/asm_linux_amd64.s:21 +0x5
	syscall.read(0x6, 0x4c208200000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/lib/google-golang/src/syscall/zsyscall_linux_amd64.go:860 +0x6e
	syscall.Read(0x6, 0x4c208200000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/lib/google-golang/src/syscall/syscall_unix.go:136 +0x58
	os.(*File).read(0x4c2081fe000, 0x4c208200000, 0x1000, 0x1000, 0x7f6f4811f188, 0x0, 0x0)
		/usr/lib/google-golang/src/os/file_unix.go:191 +0x5e
	os.(*File).Read(0x4c2081fe000, 0x4c208200000, 0x1000, 0x1000, 0x875680, 0x0, 0x0)
		/usr/lib/google-golang/src/os/file.go:95 +0x91
	bufio.(*Scanner).Scan(0x4c208202000, 0x4c208239050)
		/usr/lib/google-golang/src/bufio/scan.go:180 +0x688
	github.com/docker/docker/pkg/mount.parseInfoFile(0x7f6f48117fb0, 0x4c2081fe000, 0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo_linux.go:48 +0x1f0
	github.com/docker/docker/pkg/mount.parseMountTable(0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mountinfo_linux.go:39 +0x135
	github.com/docker/docker/pkg/mount.GetMounts(0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/docker/pkg/mount/mount.go:8 +0x4c
	github.com/docker/libcontainer/cgroups.FindCgroupMountpoint(0xa315b0, 0x3, 0x0, 0x0, 0x0, 0x0)
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/docker/libcontainer/cgroups/utils.go:19 +0x5a
	github.com/google/cadvisor/container/docker.func·001()
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/container/docker/factory.go:62 +0x50
	sync.(*Once).Do(0x1060c38, 0xb7c998)
		/usr/lib/google-golang/src/sync/once.go:44 +0xd4
	github.com/google/cadvisor/container/docker.UseSystemd(0x4c2080d51f0)
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/container/docker/factory.go:70 +0x36
	github.com/google/cadvisor/container/docker.Register(0x7f6f4811ee80, 0x4c208078180, 0x7f6f4811d330, 0x4c208111c10, 0x0, 0x0)
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/container/docker/factory.go:219 +0x887
	github.com/google/cadvisor/manager.New(0x4c2080c05c0, 0x7f6f481190f8, 0x1060bb8, 0x0, 0x0, 0x0, 0x0)
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/manager/manager.go:145 +0xa76
	main.main()
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/cadvisor.go:69 +0x454

	goroutine 5 [chan receive]:
	github.com/golang/glog.(*loggingT).flushDaemon(0x1057ce0)
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
	created by github.com/golang/glog.init·1
		/usr/local/google/home/vmarmol/go/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7

	goroutine 17 [syscall, locked to thread]:
	runtime.goexit()
		/usr/lib/google-golang/src/runtime/asm_amd64.s:2232 +0x1

	goroutine 11 [syscall]:
	os/signal.loop()
		/usr/lib/google-golang/src/os/signal/signal_unix.go:21 +0x1f
	created by os/signal.init·1
		/usr/lib/google-golang/src/os/signal/signal_unix.go:27 +0x35

Kernel:

	$ uname -a
	Linux sd-77353 3.19.0-16-generic #16-Ubuntu SMP Thu Apr 30 16:09:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Dmesg:

	[113246.872573] aufs au_opts_verify:1612:docker[24990]: dirperm1 breaks the protection by the permission bits on the lower branch
	[113246.923451] aufs au_opts_verify:1612:docker[24990]: dirperm1 breaks the protection by the permission bits on the lower branch
	[113246.976977] aufs au_opts_verify:1612:docker[25601]: dirperm1 breaks the protection by the permission bits on the lower branch
	[113246.991649] device veth737ddc2 entered promiscuous mode
	[113246.991685] IPv6: ADDRCONF(NETDEV_UP): veth737ddc2: link is not ready
	[113247.015784] eth0: renamed from veth4bf4b54
	[113247.030776] IPv6: ADDRCONF(NETDEV_CHANGE): veth737ddc2: link becomes ready
	[113247.030791] docker0: port 17(veth737ddc2) entered forwarding state
	[113247.030794] docker0: port 17(veth737ddc2) entered forwarding state
	[113247.076121] audit: type=1107 audit(1432224892.577:85): pid=684 uid=105 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/DBus" interface="org.freedesktop.DBus" member="Hello" mask="send" name="org.freedesktop.DBus" pid=32599 label="docker-default" peer_label="unconfined"
	 exe="/usr/bin/dbus-daemon" sauid=105 hostname=? addr=? terminal=?'
	[113247.102955] docker0: port 17(veth737ddc2) entered disabled state
	[113247.103865] device veth737ddc2 left promiscuous mode
	[113247.103868] docker0: port 17(veth737ddc2) entered disabled state
	[113247.446419] device veth7bd7d56 entered promiscuous mode
	[113247.446451] IPv6: ADDRCONF(NETDEV_UP): veth7bd7d56: link is not ready
	[113247.446453] docker0: port 17(veth7bd7d56) entered forwarding state
	[113247.446456] docker0: port 17(veth7bd7d56) entered forwarding state
	[113247.475658] eth0: renamed from vethfe713ef
	[113247.495000] IPv6: ADDRCONF(NETDEV_CHANGE): veth7bd7d56: link becomes ready
	[113247.546881] audit: type=1107 audit(1432224893.049:86): pid=684 uid=105 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/DBus" interface="org.freedesktop.DBus" member="Hello" mask="send" name="org.freedesktop.DBus" pid=32636 label="docker-default" peer_label="unconfined"
	 exe="/usr/bin/dbus-daemon" sauid=105 hostname=? addr=? terminal=?'
	[113247.583168] docker0: port 17(veth7bd7d56) entered disabled state
	[113247.584160] device veth7bd7d56 left promiscuous mode
	[113247.584163] docker0: port 17(veth7bd7d56) entered disabled state
	[113248.018194] device veth5aaa735 entered promiscuous mode
	[113248.018224] IPv6: ADDRCONF(NETDEV_UP): veth5aaa735: link is not ready
	[113248.018226] docker0: port 17(veth5aaa735) entered forwarding state
	[113248.018228] docker0: port 17(veth5aaa735) entered forwarding state
	[113248.039857] eth0: renamed from veth78b60ba
	[113248.055183] IPv6: ADDRCONF(NETDEV_CHANGE): veth5aaa735: link becomes ready
	[113248.104497] audit: type=1107 audit(1432224893.605:87): pid=684 uid=105 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/DBus" interface="org.freedesktop.DBus" member="Hello" mask="send" name="org.freedesktop.DBus" pid=32666 label="docker-default" peer_label="unconfined"
	 exe="/usr/bin/dbus-daemon" sauid=105 hostname=? addr=? terminal=?'
	[113248.131444] docker0: port 17(veth5aaa735) entered disabled state
	[113248.132402] device veth5aaa735 left promiscuous mode
	[113248.132405] docker0: port 17(veth5aaa735) entered disabled state

I'm not the Ubuntu user, but this apparmor=DENIED thing looks suspicious. I heard that people had some problems with docker due to this AppArmor thing. What do you think about it?

**Comment by vmarmol** [comment]
Just got a system up and running and verified the issue. Will look into fixing it. Interestingly, it only happens inside a container.
