### ISSUE TITLE
fatal: reference is not a tree: 4ea9039ff269fc8675409df7f1a192c94eab2f52

### ISSUE THREAD

**Issue by nashasha1** [google/cadvisor#668]
src/github.com/docker/libcontainer; git checkout 4ea9039ff269fc8675409df7f1a192c94eab2f52
fatal: reference is not a tree: 4ea9039ff269fc8675409df7f1a192c94eab2f52
godep: restore: exit status 128

when run godep restore got this error.
anyone got same error?

**Comment by vmarmol** [comment]
@nashasha1 I run the same thing and I get the expected result:

```
$ git checkout 4ea9039ff269fc8675409df7f1a192c94eab2f52
HEAD is now at 4ea9039... Add ChargeProcess to Container API.
```

Do you have the latest version of libcontainer?

**Comment by vmarmol** [comment]
Actually, now that I look around I see that this is a non-existing commit that I have :) Letme rebase cAdvisor and re-do the godeps. Thanks for reporting!
