### ISSUE TITLE
Document output format of storage backends

### ISSUE THREAD

**Issue by vmarmol** [google/cadvisor#681]

**Comment by matschaffer** [comment]
For anyone who comes looking in the short term here's a dump from the initial "kick-the-tires" attempt I just did: https://gist.github.com/matschaffer/328e891e0ebc1eeb9705

Also I thought it was worth mention that the current design could have some issues [the influx 0.8](http://influxdb.com/docs/v0.8/advanced_topics/schema_design.html) docs recommend encoding most of the metadata into the series name.

The current approach would probably require a fair bit of queries like `where machine = '...'` which apparently requires a range scan.

Also here's a screenshot which may be easier for folks to use to scan the structure:

![screen shot 2015-05-28 at 10 46 17 am](https://cloud.githubusercontent.com/assets/690/7851295/1c73f5ac-0528-11e5-8ee8-8c99bfd271df.png)

**Comment by vmarmol** [comment]
The current output schema could use some love. Recommendations are welcomed :)

**Comment by dashpole** [comment]
closing as outdated.  Feel free to reopen if anyone wants to take this up.
