### ISSUE TITLE
Set docker container name and meta data as prometheus labels

### ISSUE THREAD

**Issue by discordianfish** [google/cadvisor#688]
cadvisor supports exposing metrics for prometheus consumption. Right now it only sets the container ID as a label but it would be useful to also set the container name and potential meta data[1] as labels.

1) https://docs.docker.com/userguide/labels-custom-metadata/

**Comment by MrMMorris** [comment]
yes please! I need to be able to differentiate containers as I don't name them and docker labels seems ot be the best way to do it :smile:

**Comment by timpoultney** [comment]
+1 here.

**Comment by jimmidyson** [comment]
Think docker container name & labels are now in the prometheus exposed metrics. Can this be closed?

**Comment by discordianfish** [comment]
Awesome, then it can be closed!

**Comment by Colstuwjx** [comment]
I have some docker envs which need to inject as prom labels, how to achieve that?
It seems that we need a more flexible way to determine prom labels...

**Comment by Colstuwjx** [comment]
I have been checked the [source code](https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L660), and found that cadvisor will set some default labels, and envs are already exist.

BTW,  I also found that there is a `ContainerSpec` struct to determine the container metadata, but the env will be [whitelist](https://github.com/google/cadvisor/blob/359ef5b1008bb0497cbcb843829356782ab8875d/info/v2/container.go#L81)? How to setup these configs? 

I cannot find any documentation about this, and I suggest `docker inspect` result should have a simple  way to inject as part of `ContainerSpect`.
