### ISSUE TITLE
cadvisor fails to run with docker 1.6.1

### ISSUE THREAD

**Issue by timechanter** [google/cadvisor#701]
With the upstream change in libcontainer to stop mounting of /sys the cadvisor images fail with 

Message: "/var/lib/docker/overlay/039ada59885bfb9c5c8521a6670f18c043d7ebad98cc5383145bd311b5bec53c/merged/sys" cannot be mounted because it is located inside "/sys"

see https://github.com/docker/libcontainer/commit/3c25c9b9cfc97ac342b4eba74248ef48a7e51743

**Comment by vmarmol** [comment]
Hmmm two things to try if you have the time :)
- Don't mount `/sys` (but leave `/`)
- Run with `--privileged`

**Comment by shahriarb** [comment]
I'm experiencing this issue as well .
@vmarmol I've tested your suggestion : 

- Don't mount /sys (but leave /)  :  It will raise this error 
docker: Invalid bind mount: destination can't be '/'

- Run with --privileged   : It will raise this error : 
System error: "/var/lib/docker/aufs/mnt/89d25450b19ef9abfaa56ee9bb5389b9a2bdfccee2ebb4d6fdc68505f78d659c/sys" cannot be mounted because it is located inside "/sys" 

Any other suggestion or fix ?

**Comment by vmarmol** [comment]
This appears to be a bug in Docker 1.6.1. Talking with them to see if there will be a 1.6.2 that fixes it. Libcontainer was already patched.

**Comment by vmarmol** [comment]
For now, you can remove the `/sys` mount (but leave the `/`) and it should work for most stats. A few (like network) will be missing.

**Comment by prologic** [comment]
Same issue here:

```#!bash
Status: Downloaded newer image for google/cadvisor:latest
Cannot start container 18d3d8ffd585d81cce22a24f8f207dec04075867b0b4a5801a177f3dca110549: [8] System error: "/var/lib/docker/devicemapper/mnt/18d3d8ffd585d81cce22a24f8f207dec04075867b0b4a5801a177f3dca110549/rootfs/sys" cannot be mounted because it is located inside "/sys"
```

**Comment by prologic** [comment]
Is there an upstream Docker issue we can cross-link to for reference?

**Comment by jumanjiman** [comment]
> Is there an upstream Docker issue we can cross-link to for reference?

https://github.com/docker/docker/issues/13097

**Comment by prologic** [comment]
Beautiful :)

**Comment by vmarmol** [comment]
Update: docker/docker#13133

**Comment by prologic** [comment]
Sweet :) Can't wait!

**Comment by rjnagal** [comment]
Verified with 1.6.2-rc1 :+1:

**Comment by prologic** [comment]
:+1:

**Comment by vmarmol** [comment]
Docker 1.6.2 has been released! Closing this issue. Thanks everyone for reporting!
