### ISSUE TITLE
Show blkio stats in cAdvisor UI

### ISSUE THREAD

**Issue by huikang** [google/cadvisor#702]
Hi, 
In the cadvisor UI, I can only see CPU, memory, and network tr/tx per container. But there is not blkio stats.

In the influxdb, I see the following metrics, 
time    sequence_number fs_usage    cpu_cumulative_usage    tx_bytes    fs_limit    tx_errors   memory_working_set  rx_bytes    machine rx_errors   memory_usage    fs_device   container_name

How can I enable blkio stats for the containers using cadvisor? Thanks.

**Comment by vmarmol** [comment]
We don't show blkio in the UI. Arguably we should. We'll use this bug to track adding that to the UI.

Thanks for reporting! It's useful for us to know what features people want.

**Comment by rjnagal** [comment]
@anushree-n this is another good issue to work on for learning the UI setup.

**Comment by iwankgb** [comment]
Closing very old issue.
