### ISSUE TITLE
How to enable load stats

### ISSUE THREAD

**Issue by jzy1688** [google/cadvisor#714]
When I get docker container stats form API 2.0, the "has_load" label is set to false. How can I enable the load stats?

**Comment by vmarmol** [comment]
You'll need to set `--enable_load_reader=true` when you run cAdvisor. Be warned though, this may cause instability in cAdvisor which is why we don't have it on by default. We've observed periodic crashes when it is enabled and have been looking into them.

**Comment by jzy1688** [comment]
Thanks

**Comment by vmarmol** [comment]
Closing, feel free to open an issue if you run into any trouble.

**Comment by Shinzu** [comment]
even if i set `--enable_load_reader=true` the 'has_load' label is still set to false:

```
/ # cadvisor --version
cAdvisor version 0.14.0
/ # ps
PID   USER     COMMAND
    1 root     /usr/bin/cadvisor --enable_load_reader=true
```
