### ISSUE TITLE
cadvisor support for Power (ppc64) platforms

### ISSUE THREAD

**Issue by bpradipt** [google/cadvisor#725]
Currently cadvisor fails to run on Power servers due to differences w.r.to /proc/cpuinfo output and location of system UUID data.  
I have two small fixes to get cadvisor running on Power servers. I was wondering whether to send one PR with fix for both the issues or different PRs ? Would really like to get the community's thoughts on the same.
For reference, here are the two commits in my private tree 
https://github.com/bpradipt/cadvisor/commit/7f43a62ab694478a558afc00706771271f16005d
https://github.com/bpradipt/cadvisor/commit/a8eb38c39b7c0bd9bf6d308b5821d3f7c82c48c9

**Comment by rjnagal** [comment]
Smaller PRs are always better. I'd go with 2.

And thanks for adding the Power support!

**Comment by bpradipt** [comment]
Thanks @rjnagal. I have created two PRs #730 and #731. Please review and provide your comments

**Comment by bpradipt** [comment]
Thanks @rjnagal for the review. I'm closing the issue now since the patches have been merged.
