### ISSUE TITLE
Export ContainerSpec to StorageDrivers

### ISSUE THREAD

**Issue by mboussaa** [google/cadvisor#740]
How can we calculate the CPU% per core ? and Memory%?

NB: I am using influxdb web ui to execute queries 

Example: 
my request on InfluxDB is like that (to get the %cpu)
select container_name, (derivative(cpu_cumulative_usage)/1000000000)/4 from stats where container_name='containero0' and time>now()-15m group by time(2s)

ERROR: Value cannot be evaluated for type &{derivative 10 [0xc208082a00] <nil> false}

**Comment by vmarmol** [comment]
To get a graph of cores used we usually do something like this:

```
select derivative(cpu_cumulative_usage) from stats where container_name='mysql' limit 600 group by time(2s)
```

Which (outside of the `/4`) looks like yours. Not quite sure what the error is about...Is it unhappy about selecting a derivative and something else, or doing the math on top of the derivative?

**Comment by vmarmol** [comment]
As far as percentages. We don't expose either limit today so it is hard to determine percentages :(

**Comment by mboussaa** [comment]
I divided by the total number of cores in my machine which is 4. I followed the discussion here https://github.com/google/cadvisor/issues/679 . 
And to answer your question, doing the math on top of the derivative causes the error

**Comment by vmarmol** [comment]
Thanks @mboussaa! I will re-purpose this issue to add the spec to InfluxDB.

**Comment by mboussaa** [comment]
So far, cAdvisor can only report raw data is in billionths of a core is it right?

**Comment by vmarmol** [comment]
Yes, the data is exported in nanoseconds used.

**Comment by mboussaa** [comment]
for the memory, it is the same thing?

**Comment by vmarmol** [comment]
Memory is exported in bytes, we also don't push the spec today.

**Comment by mboussaa** [comment]
Any progress on this issue ?

**Comment by vmarmol** [comment]
Unfortunately no, we're working on refactoring how StorageDrivers are handled before we tackle this.

**Comment by mboussaa** [comment]
`select derivative(cpu_cumulative_usage) from stats where container_name='execution'`
calculate the derivative over all time stamp ? Because it shows only one derivative value

**Comment by vishh** [comment]
Don't you have to group by time?

**Comment by mboussaa** [comment]
according to this https://github.com/google/cadvisor/issues/679#issuecomment-99529852

**Comment by dashpole** [comment]
this issue is blocked on #1458 for now

**Comment by iwankgb** [comment]
Storage drivers are officially considered obsolete (per #1458).
