### ISSUE TITLE
e2e fails regularly due to flaky streaming event test

### ISSUE THREAD

**Issue by rjnagal** [google/cadvisor#742]
Seen this failure a few times now.

F0528 18:29:33.270429 27713 runner.go:190] Error 0: command "godep" ["go" "test" "github.com/google/cadvisor/integration/tests/..." "--host" "cadvisor-ubuntu-precise" "--port" "8080"] failed with error: exit status 1 and output: "--- FAIL: TestStreamingEventInformationIsReturned (37.08s)\n\tevent_test.go:54: timeout happened before destruction event was detected for container \"4c7cd7429474f63b41b98fde913f6aefe9e92a12ea05f97bb8352a83c2c00c85\"\nFAIL\nFAIL\tgithub.com/google/cadvisor/integration/tests/api\t102.787s\nok  \tgithub.com/google/cadvisor/integration/tests/healthz\t3.428s\ngodep: go exit status 1\n"

**Comment by dashpole** [comment]
havent seen this recently.  Feel free to reopen if anyone encounters this.
