### ISSUE TITLE
Recognize --net=host

### ISSUE THREAD

**Issue by vmarmol** [google/cadvisor#749]
When a Docker container runs with `--net=host` cAdvisor still shows network stats for the container (which are empty so we show 0).

**Comment by vmarmol** [comment]
@ananyakumar this is a good one to start with. It should touch a bunch of cAdvisor and all in Go :)

**Comment by AnanyaKumar** [comment]
A clarification: do we want to remove the network stats panel from the cAdvisor GUI when Docker containers are run with --net=host? Or do we want to find a way to profile the container's network throughput even when it's run with --net=host?

**Comment by vmarmol** [comment]
We'd just like to remove the data from showing up. In the UI and the API.

**Comment by michaelarnauts** [comment]
Not sure if it has been changed over the years, but the current behavior seems to return the hosts network usage (what makes sense since the container is using the host network, but isn't what I was expecting ofcourse).

**Comment by iwankgb** [comment]
Closing very old issue.

**Comment by legitYosal** [comment]
> Not sure if it has been changed over the years, but the current behavior seems to return the hosts network usage (what makes sense since the container is using the host network, but isn't what I was expecting ofcourse).

Im not sure either but it seems it returns some not valid data not related to the process running in the container, I have a td-agent container which has a usage of 10 MB of data based on cadvisor, although it is on a per seconds MB rate
