### ISSUE TITLE
unable to start cadvisor in fedora 20 as well as RHEL 7

### ISSUE THREAD

**Issue by Yashu5** [google/cadvisor#752]
Hi , few days back I was able to start cadvisor on Fedora 20 , which was working perfectly fine. But suddenly I am getting below in logs, have testest in RHEL 7 also but the same issue. Is it a bug or do i need to make extra configuration, dont know what is going wrong now......

I0605 06:52:19.615061 00001 storagedriver.go:100] No backend storage selected
I0605 06:52:19.615921 00001 storagedriver.go:102] Caching stats in memory for 2m0s
I0605 06:52:19.616645 00001 manager.go:123] cAdvisor running in container: "/system.slice/docker-43aaf0072ba7b49abcbf93ebfeee2ae3a32789800ffed3639c04a6830223e7c1.scope"
I0605 06:52:19.621557 00001 fs.go:88] Filesystem partitions: map[/dev/mapper/docker-202:1-130952-43aaf0072ba7b49abcbf93ebfeee2ae3a32789800ffed3639c04a6830223e7c1:{mountpoint:/ major:253 minor:2} /dev/xvda1:{mountpoint:/etc/resolv.conf major:202 minor:1}]
E0605 06:52:19.625801 00001 machine.go:268] Failed to get system UUID: open /sys/class/dmi/id/product_uuid: no such file or directory
I0605 06:52:19.625953 00001 machine.go:224] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0605 06:52:19.626108 00001 manager.go:144] Machine: {NumCores:1 CpuFrequency:1800001 MemoryCapacity:618795008 MachineID: SystemUUID: BootID:a650ed47-ddc6-4a2d-bc7d-03340f4de74c Filesystems:[{Device:/dev/mapper/docker-202:1-130952-43aaf0072ba7b49abcbf93ebfeee2ae3a32789800ffed3639c04a6830223e7c1 Capacity:10434699264} {Device:/dev/xvda1 Capacity:5254643712}] DiskMap:map[202:1:{Name:xvda1 Major:202 Minor:1 Size:5368709120 Scheduler:cfq} 253:0:{Name:dm-0 Major:253 Minor:0 Size:107374182400 Scheduler:none} 253:1:{Name:dm-1 Major:253 Minor:1 Size:10737418240 Scheduler:none} 253:2:{Name:dm-2 Major:253 Minor:2 Size:10737418240 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:0a:bd:f4:c1:ca:af Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:618795008 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]}]}
I0605 06:52:19.627487 00001 manager.go:151] Version: {KernelVersion:3.11.10-301.fc20.x86_64 ContainerOsVersion:Buildroot 2014.02 DockerVersion:Unknown CadvisorVersion:0.14.0}
E0605 06:52:19.629099 00001 manager.go:186] Docker container factory registration failed: unable to communicate with docker daemon: dial unix /var/run/docker.sock: permission denied.
I0605 06:52:19.634579 00001 factory.go:64] Registering Raw factory
I0605 06:52:19.635424 00001 manager.go:930] Started watching for new ooms in manager
E0605 06:52:19.635947 00001 manager.go:217] Failed to start OOM watcher, will not get OOM events: exec: "journalctl": executable file not found in $PATH
I0605 06:52:19.638355 00001 manager.go:230] Starting recovery of all containers
I0605 06:52:19.686534 00001 manager.go:235] Recovery completed
I0605 06:52:19.732792 00001 cadvisor.go:90] Starting cAdvisor version: "0.14.0" on port 8080

Thanks a lot! yash

**Comment by vmarmol** [comment]
@Priyanka5 it looks like cAdvisor started fine from the log, but does not have Docker support. Is that the problem you're observing?

**Comment by Priyanka5** [comment]
@vmarmol yeah but docker is running fine, i am able to run other containers on the same machine.

**Comment by vmarmol** [comment]
@Yashu5 can you try running the container with `--privileged=true`? We've seen some instances of Fedore/RHEL needing that due to SELinux.

**Comment by Yashu5** [comment]
its working now thanks

**Comment by vmarmol** [comment]
Awesome! I added a note to the docs. Will close this issue, feel free to open another if you run into any problems.
