### ISSUE TITLE
Consider adding network capacity 

### ISSUE THREAD

**Issue by rjnagal** [google/cadvisor#754]
Typically network capacity can be read from:
$ cat /sys/class/net/eth0/speed 
1000

or ethtool through ioctls:
$ ethtool eth0
Settings for eth0:
    Supported ports: [ TP ]
    ...
    Speed: 1000Mb/s

This won't work for virtual interfaces as the real speed doesn't make sense.

For cloud providers, we can get use throttle limits as capacity.

eg. on GCE, the egress cap is 2 Gbits/second per core to a max of 10 Gbits/second. Shared core machine types get 1Gbits/second cap [ Source: https://cloud.google.com/compute/docs/networking]

AWS doesn't document it, but the cap seems to be tied to instance types:
small 250 mbps
large 500 mbps
xlarge 1000 mbps
[ Source: http://serverfault.com/questions/460755/bandwidth-limits-for-amazon-ec2]

Another option is to provide a measurement tool to generate a profile that cadvisor can consume. I'd rather not go there yet.

We can use what info we have to build a network capacity model. It should work for GCE and bare-metal. 
If it is interesting, others might contribute.

**Comment by vmarmol** [comment]
We can probably piggyback off of work on #760.

/cc @AnanyaKumar

**Comment by iwankgb** [comment]
Closing very old issue.
