### ISSUE TITLE
Detect if running in a cloud provider and get instance type

### ISSUE THREAD

**Issue by vmarmol** [google/cadvisor#760]
We'd like this as a library (others will consume this too we imagine) and as part of the `MachineSpec` in cAdvisor. We should be able to provide
- What cloud provider we're running in (if at all)
- What instance type we're running on

At least initially we can do this with GCE. It looks like we just need to ask the Metadata service. So within a GCE instance:

```
$ curl "http://metadata.google.internal/computeMetadata/v1/instance/machine-type" -H "Metadata-Flavor: Google"
```

It'd be nice to be able to do this in AWS as well. Looks like they have an `instance-type` in their metadata as well:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

@AnanyaKumar you can work on this initially :)

**Comment by AnanyaKumar** [comment]
Thanks for identifying a great issue for me to get some experience in Go and the cAdvisor dev workflow! I have a (short) outline of what I plan to do, and a couple of clarifications on what we expect out of this feature.

What we want:
Module that detects what cloud provider we're on (for now, GCE and AWS)
Machine info data structures should contain cloud provider info
http://localhost:8080/api/v1.3/machine should should show cloud provider info
(Should the GUI show cloud provider information?)

Outline:
- Make a new module cloudproviderinfo in utils
- Add a unit test with a fake for the cloudproviderinfo module
- Add constants cloudproviderinfo.GCE, cloudproviderinfo.AWS, cloudproviderinfo.OTHER
- Add a function (and helper functions) that gets cloud provider name and instance type
- Modify machine info/attribute structures in both v1 and v2 to add a cloudProvider and instanceType field (I wasn't 100% sure if both versions need to be changed, but I'd guess they do)
- manager/machine.go getMachineInfo should populate and return info

Is this roughly what you had in mind in terms of what the cloud provider detection feature involves? I'm going to start by implementing the module.

**Comment by rjnagal** [comment]
@AnanyaKumar that sounds mostly right.

- we can do all of it in v2.0 api. We don't need to duplicate it in two places.
- we'll also need cloudprovider.BAREMETAL. We can look up some h/w info to check if we are on bare-metal.
- Don't worry about the GUI, just add it to the API. Some day, we'll do a "machine" page for cAdvisor. This info can show up there.

Let me know if you have other questions.

**Comment by AnanyaKumar** [comment]
Cool, thanks @rjnagal !

**Comment by dashpole** [comment]
Instance type is included in the v2 api.
