### ISSUE TITLE
Installation Requirements (Go)

### ISSUE THREAD

**Issue by AnanyaKumar** [google/cadvisor#761]
I just installed cAdvisor on my personal Ubuntu (Trusty) machine, and came across a few issues. In particular, cAdvisor did not compile with the gccgo compiler that was installed on my machine. I used "sudo apt-get install golang", however this installed an older version of Go (1.2). Some of cAdvisor's dependencies require newer versions of the golang compiler.

The error messages were somewhat cryptic, and took some time to trace (e.g. "could not find package encodings"). Should we add a FAQ/requirements section that specifies the version of Go that cAdvisor requires? 

Also, like other Google projects written in Go (e.g. Kubernetes), we might want to direct the user to the Go installation page (https://golang.org/doc/install) and remind them to follow the setup instructions in (https://golang.org/doc/code.html).

**Comment by vmarmol** [comment]
Yes, we should add the suggestions you mentioned. We tend to work from the latest stable, so Go 1.4 as of now. Not sure about 1.3, but 1.2 is definitely "too old".

**Comment by vmarmol** [comment]
@AnanyaKumar would you like to document the requirements in the building docs page? :)

**Comment by rjnagal** [comment]
+1 send a PR :)

**Comment by AnanyaKumar** [comment]
Sure, I'll send a PR after I'm done with the net=host issue!
