### ISSUE TITLE
volume can not be mounted

### ISSUE THREAD

**Issue by fanfuxiaoran** [google/cadvisor#766]
Run as run.md in ubuntu 14.04 and docker 1.19,the result is:

Cannot start container fcc434fdb28a699edb9c96b574a331c07717d845530689ca0f07489b5c73d78a:  System error: "/var/lib/docker/aufs/mnt/fcc434fdb28a699edb9c96b574a331c07717d845530689ca0f07489b5c73d78a/sys" cannot be mounted because it is located inside "/sys"

**Comment by vmarmol** [comment]
Are you running Docker `1.6.1`? This sounds like it is the case. This version had a bug where this mounting was not allowed. Unfortunately the only fix is to upgrade to `1.6.2+` :-\

**Comment by fanfuxiaoran** [comment]
My Docker is 1.7.0-dev

**Comment by wpbgent** [comment]
Same issue with docker 1.7.0-dev

**Comment by dashpole** [comment]
closing since this is outdated.
