### ISSUE TITLE
Fail to Deploy via Rancher

### ISSUE THREAD

**Issue by sjkeerthi** [google/cadvisor#773]
Hi I am trying to deploy the cAdvisor via Rancher. 

My Docker sits on CentOS 7.x with Docker 1.6.0.

I passed cAdvisor via Rancher using below options still container didn't start I could not see any error regarding the failures.

 docker run 
  --volume=/:/:ro (Since CentOs 7.x) I tried both the way /:/ & /:/rootfs:ro
  --volume=/var/run:/var/run:rw 
  --volume=/sys:/sys:ro 
  --volume=/var/lib/docker/:/var/lib/docker:ro 
  --publish=8080:8080 
  --detach=true 
  --name=cadvisor 
  google/cadvisor:latest
--privileged=true

Kindly let me know what I am missing here.

**Comment by rjnagal** [comment]
I think you are missing "--volume=/cgroup:/cgroup:ro"

From https://github.com/google/cadvisor/blob/master/docs/running.md (for CentOS):

You may need to run the container with --privileged=true and --volume=/cgroup:/cgroup:ro \ in order for cAdvisor to monitor Docker containers.

Let us know if that works.

**Comment by sjkeerthi** [comment]
In that case my cgroup is not under the /cgroup since its CentOS 7.x its under /sys/fs/cgroup even in that case do you want me to still point volume=/cgroup:/cgroup:ro

**Comment by vmarmol** [comment]
In that case just do: `--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro` although that should be done with `/sys`... Can you run cAdvisor with: `--logtostderr --v=4` and provide the stdout?

**Comment by dashpole** [comment]
closing as outdated
