### ISSUE TITLE
Cadvisor and systemd

### ISSUE THREAD

**Issue by ynnt** [google/cadvisor#779]
Hello,

I'm using cadvisor to monitor docker containers on debian 8 which use systemd as init system
Also I see system services such as sshd or mdadm.
Example:
`
container_memory_working_set_bytes{id="/system.slice/docker-3f7eba3c3b2a63c8bbba4f679ca2d2ba704b501890c112218dbdfaa66e2a8041.scope",name="admiring_newton"} 0

container_memory_working_set_bytes{id="/system.slice/docker-576a59ee026bf956a550cf1cd2beb42c1859a3ae44b110b5fbc504cf2127395d.scope",name="cadvisor"} 0
container_memory_working_set_bytes{id="/system.slice/docker-6fcea541f42e9de0778f5e543b145a0e9a845048fabc66829e045ddf276820b5.scope",name="graylog-web-ui"} 0

container_memory_working_set_bytes{id="/system.slice/docker-7b66c376e6db9bfd000fe750a9dd7c6f97b2a86b3eac852fb8aab3a970a4f37f.scope",name="sinopia"} 0

**Comment by vmarmol** [comment]
Hi @a-pastushenko, do you mean that you now see those services (as containers) or that you no longer do? Systemd runs everything inside containers so you should expect to see the different services reported by cAdvisor.

**Comment by a-pastushenko** [comment]
I see other services now but it's ok

Oh, sorry, I figured out that I didn't fill issue text.

My primary question is why do I see null values about docker containers.

**Comment by vmarmol** [comment]
@a-pastushenko where do you see these null values?

**Comment by a-pastushenko** [comment]
127.0.0.1:8080/metrics

**Comment by a-pastushenko** [comment]
Also in the cAdvisor web page there are 0 values for RAM usage

**Comment by vmarmol** [comment]
Hmmm can you post screenshots or example text dumps? Unsure what exactly us returning null values.

**Comment by a-pastushenko** [comment]
http://pastebin.com/raw.php?i=TGjFCX5a

**Comment by dashpole** [comment]
We have fixed a number of systemd related issues recently.  If anyone is still having issues running with systemd on the latest release, please open a new issue.
