### ISSUE TITLE
Network metrics (e.g. rx_bytes, tx_bytes) for docker containers are equal

### ISSUE THREAD

**Issue by kenzodeluxe** [google/cadvisor#782]
When using the /api/v1.2/containers/ endpoint, all is fine (for the host system).
Using /api/v1.2/docker/, for all of the containers the metrics stay the same, e.g.

(iterating over all containers)
```
{u'tx_dropped': 0, u'rx_packets': 1026803, u'name': u'veth414fb30', u'rx_bytes': 170955847, u'tx_errors': 0, u'interfaces': [{u'tx_dropped': 0, u'rx_packets': 1026803, u'name': u'veth414fb30', u'rx_bytes': 170955847, u'tx_errors': 0, u'rx_errors': 0, u'tx_bytes': 170955847, u'rx_dropped': 0, u'tx_packets': 1026803}], u'rx_errors': 0, u'tx_bytes': 170955847, u'rx_dropped': 0, u'tx_packets': 1026803}
{u'tx_dropped': 0, u'rx_packets': 327157, u'name': u'vethb18e390', u'rx_bytes': 93013218, u'tx_errors': 0, u'interfaces': [{u'tx_dropped': 0, u'rx_packets': 327157, u'name': u'vethb18e390', u'rx_bytes': 93013218, u'tx_errors': 0, u'rx_errors': 0, u'tx_bytes': 93013218, u'rx_dropped': 0, u'tx_packets': 327157}], u'rx_errors': 0, u'tx_bytes': 93013218, u'rx_dropped': 0, u'tx_packets': 327157}
{u'tx_dropped': 0, u'rx_packets': 0, u'name': u'', u'rx_bytes': 0, u'tx_errors': 0, u'rx_errors': 0, u'tx_bytes': 0, u'rx_dropped': 0, u'tx_packets': 0}
```

Can easily be seen in the web frontend, too.

**Comment by vmarmol** [comment]
Thanks for reporting @kenzodeluxe! Just verified the behavior and will look into a fix.

**Comment by vmarmol** [comment]
Fixed by #783

**Comment by kenzodeluxe** [comment]
Would it be possible to release a new version including the fix?

**Comment by vmarmol** [comment]
Will work on a release today :)

**Comment by kenzodeluxe** [comment]
Seems this one didn't make it into 0.16.0 - any ETA when this can be expected?
Thanks!

**Comment by vmarmol** [comment]
Huh, this really should have made it to 0.16.0 (at least as far as we know it did). Are you not seeing the fix when you run it?

**Comment by kenzodeluxe** [comment]
Sorry - I didn't find it in the list of fixed items and hence thought it didn't make it. Tried, metrics aren't mirrored anymore. Looking into some showing up as 0 now :)
Thanks!

**Comment by kenzodeluxe** [comment]
0 was caused by host mode which makes sense.
