### ISSUE TITLE
Are disk io specific metrics supposed to work?

### ISSUE THREAD

**Issue by kenzodeluxe** [google/cadvisor#791]
I'm trying to figure out how to get useful data from:
```
(...)["stats"][0]["diskio"]["io_serviced"]
(...)["stats"][0]["diskio"]["io_service_bytes"]
(...)["stats"][0]["filesystem"]["io_time"] 
```
etc. When looping over the results and running dd inside the container at the same time, the values either don't change at all, or just a little every now and then.
Are those supposed to work on a per container basis?

Thanks!

**Comment by kenzodeluxe** [comment]
Found https://github.com/docker/libcontainer/issues/165.

**Comment by mboussaa** [comment]
https://github.com/docker/libcontainer/issues/165 does not work

**Comment by vmarmol** [comment]
Must have been the recent move of libcontainer to runc that broke the link.
The issue mentioned that stats only work if you use the cfq io scheduler.
