### ISSUE TITLE
Add support for ipoib devices

### ISSUE THREAD

**Issue by hookenz** [google/cadvisor#792]
I run my cluster of docker hosts with Infiniband and IPoIB alongside regular gigabit ethernet.  Unfortunately, the only interface showing is the gigabit ethernet.  The majority of traffic is on ib0 which doesn't show for some reason.

I'd like to get this going, but I can't get cadvisor to build for some reason.

**Comment by vmarmol** [comment]
The code that does the detection is here if you're interested: https://github.com/google/cadvisor/blob/master/utils/sysinfo/sysinfo.go#L87

What problems are you running into building cAdvisor? Some help is available here: https://github.com/google/cadvisor/blob/master/docs/build.md

Outside of that, what is the output of `ls /sys/class/net` on those machines? That is how we find our about network interfaces today.

**Comment by hookenz** [comment]
Hi @vmarmol ,

The output of ls /sys/class/net is:

```
docker0 en01 ib0 lo veth16589f3 veth428c6db
```
It turns out I had gccgo-go installed instead of golang-go 1.4.  

Basically, nothing in the GetNetworkAdapters code looks broken for IB as far as I can tell.  But I'll take a closer look.

**Comment by hookenz** [comment]
@vmarmol - I figured out the issue.  While the output of /sys/class/net shows the ib0 device, it wasn't appearing in the UI.  This is because it's not seen in the namespace of the docker image that is running cadvisor.

My solution is to start it with --volume=/sys:/sys:ro

**Comment by vmarmol** [comment]
Did you not get stats with the /sys volume but without --net=host? I would have expected that to work.

**Comment by hookenz** [comment]
@vmarmol -hmm, actually I realise the CoreOS instructions are the issue.

I've changed my cadvisor.service file to contain:

docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest

The key being to pass -volume=/:/rootfs:ro.  That fixes the issue where I also had the process list missing.

**Comment by vmarmol** [comment]
Thanks @hookenz! That seems like the command on the README, or is there any documentation you think we need to update and make it easier to understand?

**Comment by hookenz** [comment]
@vmarmol - Looks like I was following the heapster docs which are perhaps outdated in that section.  But ensuring the rootfs mount is present fixes it.

**Comment by rjnagal** [comment]
Thanks @hookenz We'll update heapster documentation.
