### ISSUE TITLE
Cadvisor fails to write stats to influxDB

### ISSUE THREAD

**Issue by mboussaa** [google/cadvisor#794]
Hi,
Cadvisor fails to write stats into influxDB

Here the logs:
![capture d ecran 2015-07-02 a 19 58 23](https://cloud.githubusercontent.com/assets/5878565/8483984/0d1c49f4-20f5-11e5-881f-5accffa94063.png)

I am starting Cadvisor like this:
docker run      --volume=/:/rootfs:ro      --volume=/var/run:/var/run:rw      --volume=/sys:/sys:ro      --volume=/var/lib/docker/:/var/lib/docker:ro      --publish=8080:8080      --detach=true      --name=cadvisor   --restart=always    google/cadvisor:latest   --logtostderr    -storage_driver=influxdb     -storage_driver_host=10.0.0.22:8086 -storage_driver_db=cadvisorDB

I am starting influxDB like this: 
docker run   -d --name=influxdb  -p 8083:8083   -p 8086:8086 --restart=always       -expose 8090   --expose 8099   tutum/influxdb

When I execute a sample request on InfluxDB like this "select \* from stats" it shows:
ERROR: {"error":"error parsing query: found STATS, expected identifier at line 1, char 15

Thank you for help.

**Comment by jmaitrehenry** [comment]
Hi,

You are using influxdb v0.9 that is not currently supported by cadvisor, see #743.
You can use influxdb 0.8 just by using tutum/influxdb:0.8.8

**Comment by mboussaa** [comment]
Thank you for your answer. I changed the image however now, when I create a new database on influxDB. I get this message:
![capture d ecran 2015-07-02 a 20 36 22](https://cloud.githubusercontent.com/assets/5878565/8484865/4079952c-20fa-11e5-8c9c-20b766bde598.png)

**Comment by jmaitrehenry** [comment]
It's really look like you use influxdb 0.9 and not 0.8 because on the 0.8.8 web ui, when you create a database you have Shard Spaces box, but it's more a problem with influxdb than cadvisor IMO.  

I juste made a test with by running influxdb with:
    docker run -d --name=influxdb -p 8083:8083 -p 8086:8086 --restart=always -expose 8090 --expose 8099 tutum/influxdb

And with a force refresh (remove my browser cache).

**Comment by mboussaa** [comment]
Ok so the solution is to clear the web browser cache. 
You can close this issue.
Thank you for your help

**Comment by svenmueller** [comment]
is influxdb 0.9.x still not supported by cadvisor?

**Comment by marcellodesales** [comment]
@svenmueller I tested a PR and it is now supported...  https://github.com/google/cadvisor/pull/1040#issuecomment-176015272 

I built an image to help others at https://hub.docker.com/r/marcellodesales/google-cadvisor/... I will maintain it until the team releases a new version with it.

**Comment by vishh** [comment]
FYI: google/cadvisor:v0.20.5 should include support for InfluxDB v0.9

**Comment by marcellodesales** [comment]
@vishh I did not verify it :S Well that's nice then I will remove my image... thanks!

**Comment by marcellodesales** [comment]
@vishh I see the image works! 

```
influxdb_1     | [http] 2016/02/05 19:25:47 172.17.0.2 - root [05/Feb/2016:19:25:47 +0000] POST /write?consistency=&db=cadvisor&precision=&rp= HTTP/1.1 204 0 - cAdvisor/0.20.5 41f62cc0-cc3e-11e5-8007-000000000000 24.01661ms
```

However, the `latest` tag is not pointing to the `v0.20.5` version. What's the process to update the tag?

```
$ docker images | grep cadvisor
google/cadvisor                                           v0.20.5                       cb4f76a7607a        46 hours ago        43.12 MB
cadvisor                                                  040bdd3                       b6495090befb        8 days ago          36.52 MB
cadvisor                                                  9aa348f                       96c542aa43c7        8 days ago          43.11 MB
google/cadvisor                                           latest                        cec6ac4b467e        10 days ago         36.46 MB
```

**Comment by vishh** [comment]
In general, we don't believe in the `latest` tag. But if you are relying on
it, we can update that tag as well.

On Fri, Feb 5, 2016 at 11:33 AM, Marcello de Sales <notifications@github.com

**Comment by vishh** [comment]
I have updated the `latest` tag to point to v0.20.5.

**Comment by marcellodesales** [comment]
@vishh Although I can definitely agree with your point, most documentation I found uses the the tag `latest`... It confuses a lot of users, including myself... It since there was not Git Tag on this merge request, it is hard to find which version this is released...

Could you guys please tag the merge as part of the release process, in case the `docker latest` tag is not used? that would simplify and help users finding features...!

Thanks a lot!

**Comment by dashpole** [comment]
closing since this issue is resolved
