### ISSUE TITLE
cadvisor within a docker container doesn't want to show any processes

### ISSUE THREAD

**Issue by hookenz** [google/cadvisor#795]
It seems that cadvisor run inside a container can't get the visibility it needs to fill out the processes list.

I'm sure there will be a way around it, but the recommended fleet file for CoreOS doesn't do it.
Also, as I pointed out in a previous issue, infiniband devices are missing.  In fact, only eth0 would be shown.  I've worked around that by using --net=host.  

I can't seem to get process list though and I'm not sure passing through proc is the right thing to do.

**Comment by hookenz** [comment]
The cadvisor.service file suggested for CoreOS is missing:

--volume=/:/rootfs:ro

Which fixes all these problems.

**Comment by vmarmol** [comment]
Is there a ` cadvisor.service` in the repo?

**Comment by hookenz** [comment]
My mistake!  I was using a config file found under the heapster documentation.  You're all good.
No I don't see a cadvisor.service file in the repo.
