### ISSUE TITLE
Cadvisor without Gui Just to Serve as API

### ISSUE THREAD

**Issue by kgrvamsi** [google/cadvisor#805]
Hello,

Do cadvisor have a option where it can be used as a api server to fetch the data without any Gui interface?

Thanks,
Vamsi

**Comment by rjnagal** [comment]
You can just ignore the gui as it should not take up much resources if you don't hit it. Is there a specific problem with the gui for your usecase?

We currently don't have a way to disable it.

**Comment by kgrvamsi** [comment]
so here are my requirements 

1)To gather the server metrics and container metrics and use a centralized dashboard where i can project those from the dashboard we are building .

So inorder not to make use of the gui we would like to use the API way of fetching the metrics.

Thanks

**Comment by rjnagal** [comment]
oh, you can just use the cadvisor api for that: https://github.com/google/cadvisor/blob/master/docs/api.md

no need to disable gui.

**Comment by kgrvamsi** [comment]
so there is no possibility  in not running the cadvisor as a web application ?

**Comment by vmarmol** [comment]
We don't have a knob for it today, and we're wondering what the usecase is for running the API but not the UI. The UI just hits the API anyways :)

**Comment by dashpole** [comment]
Closing since it is inactive

**Comment by eero-t** [comment]
> We don't have a knob for it today, and we're wondering what the usecase is for running the API but not the UI. The UI just hits the API anyways :)

One of the use-cases could be security.  For WebUI there seem to be options for protecting it:
```
  -http_auth_file string
    	HTTP auth file for the web UI
  -http_auth_realm string
    	HTTP auth realm for the web UI (default "localhost")
  -http_digest_file string
    	HTTP digest file for the web UI
  -http_digest_realm string
    	HTTP digest file for the web UI (default "localhost")
```
but what about other endpoints?

* /validate/ endpoint supports remote fingerprinting of host as it offers kernel (and docker) version information
* /api/v1.x/ endpoint shows all metrics, also ones that have user has explicitly disabled from the command line

(Only WebUI & Prometheus endpoints seem to respect metrics disabling, API and e.g. `-storage_driver stdout` do not.)

**Comment by finkr** [comment]
In order to block the UI, I have started cAdvisor with `--http_auth_file /dev/null`.

The UI is blocked (require password), but the /metrics page for Prometheus is available.
