### ISSUE TITLE
error requesting influxdb

### ISSUE THREAD

**Issue by mboussaa** [google/cadvisor#806]
Hi all,
To start here my docker-compose.yml:
![capture d ecran 2015-07-09 a 10 40 44](https://cloud.githubusercontent.com/assets/5878565/8591272/5db62d80-2627-11e5-924f-6d05f74ce78f.png)

When I request influxdb with a sample query, it shows graphs and data table. However in the console I am getting this:
<img width="956" alt="capture d ecran 2015-07-09 a 10 38 14" src="https://cloud.githubusercontent.com/assets/5878565/8591299/9e497a64-2627-11e5-9a53-05f3bb9044e3.png">

In the meanwhile, with grafana 2.0 (I would like to use this version), I added the data source and I could access to stats table and define my query in the metric tab. However, there is a bug some where because the graph is not updating. Grafana people say that it is either a bug from cadvisor or influxdb. I reported this issue here: https://github.com/grafana/grafana/issues/2310
Here a screenshot of grafana:
![capture d ecran 2015-07-09 a 10 41 07](https://cloud.githubusercontent.com/assets/5878565/8591405/5bdaefb8-2628-11e5-83da-5291b8e6de49.png)

Any Idea about this issue?

**Comment by vmarmol** [comment]
Hmmm does it ever update? Only way it could be an issue on cAdvisor is if it didn't push the data. Can we find the data in InfluxDB when this happens? We should also check the cAdvisor logs to see if we had any problems pushing the data.

**Comment by ciuncan** [comment]
Could this issue be related? https://github.com/google/cadvisor/issues/808

**Comment by dashpole** [comment]
Closing as outdated.  Please open a new issue with repros on a new release if this problem persists.
