### ISSUE TITLE
Export CPU utilization per core

### ISSUE THREAD

**Issue by mboussaa** [google/cadvisor#807]
Having one core for example, I got 0.6 cores usage of my CPU using cadvisor UI. That means 60% of CPU utilization? 

How can I request InfluxDB to show cpu_cumulative_usage of 1 core (0, 1, 2 or 3) ? because I am running a container on CPU 0 (I set ressources constaint with --cpuset=0) and want to access to the cpu utilization for only that core

Thank you

**Comment by vmarmol** [comment]
Unfortunately we don't export the per-core usage to InfluxDB today. Is that the requested feature?

Since you're binding to only 1 core, the total utilization should be equivalent though

**Comment by mboussaa** [comment]
Yes. In fact I am running a container with ressources limitation. For instance, my container runs on cpu 0 and 1 (--cpuset=0,1) so the "cpu_cumulative_usage" in influxdb refers to which core ? mean of cpu 0 and 1?
For example, my machine has 4 cores: 
%CPU0=90%
%CPU1=100%
%CPU1=0%
%CPU2=0%
How are you calculating cpu_cumulative_usage?

Thanks in advance.

**Comment by vmarmol** [comment]
The kernel exports per-CPU usage as well as usage aggregated over all cores. We only export the aggregate CPU usage. We can use this bug to track exporting per-CPU usage as well.

**Comment by mboussaa** [comment]
Any advance on Exporting CPU utilization per core to InfluxDB?

**Comment by vishh** [comment]
+1 for the feature. Unfortunately the core team doesn't have enough cycles
for working on this feature. A PR will be much appreciated!

**Comment by iwankgb** [comment]
Closing very old issue.
