### ISSUE TITLE
support to interactive with ELK

### ISSUE THREAD

**Issue by kerwin** [google/cadvisor#809]
It will be great to have support of ELK stack, so that cadvisor can push data to logstash or elasticsearch

**Comment by BrickXu** [comment]
I think you should send the metrics to the buffer, like MQ or DB, then use ELK consumer it later.

**Comment by cteyton** [comment]
I think you should continue the discussion here :  #634

**Comment by dashpole** [comment]
closing since we have an elasticsearch storage driver.  #1575 adds "logstash" equivalent capabilities.
