### ISSUE TITLE
Cadvisor logging. Not enough disk space.

### ISSUE THREAD

**Issue by GregoryKutuzov** [google/cadvisor#813]
It seems that glog doesn't support log file overwriting. There is no way to set max log size. This may lead to filling the entire free space of a disc when cadvisor runs in debug mode.

So, I see several ways to deal with it:
1) We could start cron job to remove old log files but it need to be documented in cadvisor docs.
2) Implement this feature in cadvisor itself or glog framework

**Comment by mikedanese** [comment]
I would suggest using logrotate. glog is closed for features and it seems like overkill to include in cadvisor.

http://linux.die.net/man/8/logrotate

**Comment by dashpole** [comment]
agreed.  Logrotate, or other third party rotation mechanisms are recommended.
