### ISSUE TITLE
New situation, to export data to a native file

### ISSUE THREAD

**Issue by zenlinTechnofreak** [google/cadvisor#824]
I think it is necessary to porvide the data(cadvisor provide) to a native file in the native host.
People who are familiar with the linux OS should be used to read data in a native file on os.  by the way, it is also a request for my project.
So, I want to do the developing the function , and also, once I have done that ,  wiill new a PR to the cadvisor.
Acturally, I have go throught the source cod of the cadvisor, but also so confused by how to use the restful API to do that, So , can anyone tell me how to start or do that?

Could anyone help me, thanks very much.

By the way, thanks to @vmarmol , u have fixd my question last time in the mail list group.

**Comment by zenlinTechnofreak** [comment]
@vmarmol , If I want to realize to export data to the native file on system,  how can I do ,plz do me some favour, thank u very much.

**Comment by vmarmol** [comment]
Are you suggesting to export the stats to something like a CSV file? That's certainly possible, you can add a new StorageDriver that does so. You can look at other drivers for examples: https://github.com/google/cadvisor/blob/master/storage/

**Comment by zenlinTechnofreak** [comment]
@vmarmol , we want to get the final resut(such as the output of the /metrics on localhost:8080/metrics), but not only the stats, but the caculate result of the stats. is the StorageDrivers support the final result, or just the stats?

**Comment by vmarmol** [comment]
What calculated result are you looking for? `/metrics` just exports the raw metrics.

**Comment by zenlinTechnofreak** [comment]
OK, I am going to have go through it. @vmarmol  thx.

**Comment by zenlinTechnofreak** [comment]
@vmarmol , Just as you say, the /metrics just exports the raw metrics, I want the final result like the web localhost:8080/containers show, have final total usage of cpu, fingure out the occupy usage of the containers to  the whole system.
and I just trying to find out where to do the caculation via the raw metrics for the final result, if u can help me?

**Comment by vmarmol** [comment]
Sadly we don't export those stats today. We compute them in JavaScript today here:

https://github.com/google/cadvisor/blob/master/pages/static/containers_js.go

We could maybe expose them, but different people will want different things so we've gone with letting the users compute it today.

**Comment by dashpole** [comment]
closing as inactive
