### ISSUE TITLE
Remote API CPU usage in percentage

### ISSUE THREAD

**Issue by emijoon** [google/cadvisor#832]
Is there anyway that I can get total cpu usage of each container in percentage through the REST API? I couldn't find it in the documentation.

**Comment by vmarmol** [comment]
Not directly, but you can calculate it.

If 100% == 1 core:

```
// Get usage over the time period
UsageInCores = (end.Usage - start.Usage) / (end.Time - start.Time)
```

If 100% == the whole machine:

```
UsageInCores / NumCores (from /machine)
```

**Comment by Naresht-vedams** [comment]
@vmarmol 
I tried **localhost:4194/api/v1.3/events/start_time** but it is showing nothing.
Could you provide the REST API url..?

**Comment by dashpole** [comment]
Container start time is a [field in ContainerSpec](https://github.com/google/cadvisor/blob/master/info/v2/container.go#L69).  You can use container start time, and 0 to find long run average cpu usage, or use a previous measurement for average usage over a smaller time period.
