### ISSUE TITLE
No processes listed on centos systems except in /

### ISSUE THREAD

**Issue by aecolley** [google/cadvisor#843]
The ps on Centos6 (procps version 3.2.8) formats the CGROUP column differently from the ps used on Ubuntu (procps-ng version 3.3.9). It has no subsystem number (so no ":" before the subsystem name) and entries are separated by ";" instead of ",".

The cgroupPathRegExp in manager/container.go should be changed to reflect it. I suggest ".*?\\w:(/[^,;]*)[,;].*".

**Comment by aecolley** [comment]
Mangled by markdown. Let me try one more time: `".*?\\w:(/[^,;]*)[,;].*"`

**Comment by rjnagal** [comment]
Thanks for reporting @aecolley. The regex looks okay. Feel free to send a CL, or I'll do it soonish :)
We'll cut a new release within a week

**Comment by rjnagal** [comment]
verified on centos6.
