### ISSUE TITLE
Add support for rkt

### ISSUE THREAD

**Issue by yifan-gu** [google/cadvisor#858]
Hey guys, 
I'd like to help cadvisor to support rkt. One driven reason for this is @yujuhong is going to use the event stream to watch pod/container creation, deletion, etc. events, which should help [kubelet to scale better](https://github.com/kubernetes/kubernetes/issues/12540).

Create this issue to track the progress.

**Comment by yujuhong** [comment]
Thanks! :)

**Comment by rjnagal** [comment]
Thanks @yifan-gu 

Can you add some details on ways to inspect rkt containers?

- Query to figure out if a given container name was created by rkt.
- Getting any container spec / config? We get resource limits from cgroups, but network setting etc needs to come from the container provider - an equivalent of docker inspect.
- Any event stream for rkt container events?
- Equivalent of labels
- Way to list containers created by rkt.
- Any way to get filesystem limits and usage, if applicable.
- nice to have: Way to know what images are being used by a container, and what rkt images exist on the machine.

**Comment by yifan-gu** [comment]
@rjnagal Thanks for the heading up!

For many of the things you listed, such as listing containers, images, getting networking settings. We are planning to provide rkt APIs for them.

To get started, I plan to have cadvisor to recognize the cgroups of rkt containers. With machined 216+, containers with one pod created by rkt should have cgroups live under `machine.slice/machine-rkt*`, for example:
 `machine.slice/machine-rkt\x2d6813e16e\x2dd2c3\x2d45af\x2db28c\x2dce8abc2d3488.scope/system.slice/etcd.service
`
But I am not sure what do you mean by `Equivalent of labels`?

**Comment by rjnagal** [comment]
@yifan-gu By label, I meant if there's a way to add metadata (in image or runtime) for a rkt container, we would want a way to api to discover it.

**Comment by yifan-gu** [comment]
> @yifan-gu By label, I meant if there's a way to add metadata (in image or runtime) for a rkt container, we would want a way to api to discover it.

Currently the metadata can be only added into the `annotation` of [image manifest](https://github.com/appc/spec/blob/master/spec/aci.md#image-manifest-schema) or rkt [pod manifest](https://github.com/appc/spec/blob/master/spec/pods.md#pod-manifest-schema) before the pod is launched. But there is no way to read/write them from outside of the rkt pod after it's launched.

**Comment by yifan-gu** [comment]
@rjnagal I'm not very clear of the use case for api to discover labels. Could you give me an example ?

**Comment by yifan-gu** [comment]
FWIW, I talked with @jonboulle offline, and we don't have strong reason against this. It's just we haven't decided the semantics and haven't implemented it yet.

**Comment by rjnagal** [comment]
@yifan-gu That sounds ok. Our meta-data use-case should not be a blocker for rkt support. Let us know what you need from us.

**Comment by yifan-gu** [comment]
Status: I kinda found myself forking/execing rkt cli to get container list, status again just like in kubelet. So I decided to implement coreos/rkt#1208 first to smooth my life :)

**Comment by yujuhong** [comment]
Just FYI, I've decided to not use the cadvisor event stream, and instead adopt docker event stream for my proposal.  The reason is that after receiving a containerStopped event from cadvisor, if you do `docker ps` immediately, the container would still show up. Since kubelet relies on `docker ps` to get a list of running containers in syncing, I cannot use this without significantly rewriting kubelet.

**Comment by yifan-gu** [comment]
@yujuhong ok, makes sense. where is your branch you are working on?

**Comment by f0** [comment]
@yifan-gu  any news on this?

**Comment by yifan-gu** [comment]
@f0 Status: rkt have api service already, so we can start integration. But this is not my top priority now since we use individual event stream for individual runtime now.

**Comment by yujuhong** [comment]
@yifan-gu, we still need cadvisor to collect containers stats for rkt, and that should be at a higher priority.

**Comment by feiskyer** [comment]
@yifan-gu @yujuhong Any updates on this? I'm working on cAdvisor collectors for hyper, though cAdvisor is not so easy to extend to a new container runtime.

**Comment by vishh** [comment]
We might have to define Pod level APIs in cAdvisor. We wish to do this even
for the Docker runtime. We can probably start with hyper Pod support.

**Comment by feiskyer** [comment]
@vishh Glad to hear this, I think we must simplify the introduction of new container runtimes first for cAdvsior, and then it is much easier to add new Pod level APIs.

Do you have any plan to decouple the API from docker and make container runtime configurable?

**Comment by vishh** [comment]
@feiskyer: I have some idea, but I don't have the time to work on it now. Do you have some spare cycles to work on it? If so, I can help with the design.

**Comment by feiskyer** [comment]
@vishh Can you post the idea? I'm working on integration cAdvisor with Hyper.

**Comment by vishh** [comment]
@feiskyer, @timstclair will be able to help you. He is working on separating cAdvisor from kubelet.

**Comment by sjpotter** [comment]
Hey, in order to try to get rkt working with cadvisor, I've started looking at manager and want to isolate the docker code from the interface.  What I want to do is copy the majority of the implementation code to a new package "docker" and have the manager's functions call the docker impelementations functions.  

We can then implement a rkt implementation as well and have some smarts in the main manager to select which runtime we care about (or both).  

the main niggle is that some of the API calls seems docker specific (but really aren't), I don't see a way to make it generic at this point in time w/o breaking the API so going to leave them the same.

thoughts?

**Comment by vishh** [comment]
The Docker specific APIs can be a no-op on hosts that don't run docker.
Are there any generic APIs that require docker though?

**Comment by sjpotter** [comment]
@vishh when I said docker specific APIs I didn't meant that they were specific to docker but that they were named specific to docker.

ala

	// Gets all the Docker containers. Return is a map from full container name to ContainerInfo.
	AllDockerContainers(query *info.ContainerInfoRequest) (map[string]info.ContainerInfo, error)

	// Gets information about a specific Docker container. The specified name is within the Docker namespace.
	DockerContainer(dockerName string, query *info.ContainerInfoRequest) (info.ContainerInfo, error)

and

	// Get status information about docker.
	DockerInfo() (DockerStatus, error)

	// Get details about interesting docker images.
	DockerImages() ([]DockerImage, error)

i can imagine these being genericized but not without breaking the API

Also in the fs portion (not there yet just noticed it before)


    const (
    	LabelSystemRoot   = "root"
    	LabelDockerImages = "docker-images"
    )

In general the logic is needed for rkt as well but the APIs makes it appear docker specific when its not.  sorry if I wasn't clear.

**Comment by sjpotter** [comment]
a first step: https://github.com/google/cadvisor/pull/1049

the APIs are still docker named in a docker specific way, should think about a way to rev them?

**Comment by euank** [comment]
Are we happy enough with the rkt support we have that we should close this issue and track any remaining problems as new issues (e.g. there's a PR open for improved testing which can track that)?

**Comment by warmchang** [comment]
2 years age: https://www.cncf.io/blog/2019/08/16/cncf-archives-the-rkt-project/
