### ISSUE TITLE
Always current fetch VersionInfo instead of caching at creation time

### ISSUE THREAD

**Issue by pwittrock** [google/cadvisor#862]
VersionInfo is read and permanently cached when the manager is created.  If docker is started after the manager is create, then the version will always be "Unknown".  This case may be encountered when cAdvisor is started in the same program that initializes the docker daemon / container bridge.

Proposed fix: Never cache the VersionInfo and always do a live read.

**Comment by vishh** [comment]
#860

**Comment by rjnagal** [comment]
fixed by #860
