### ISSUE TITLE
please support InfluxDB v0.9

### ISSUE THREAD

**Issue by onlyjob** [google/cadvisor#878]
Please support current release of InfluxDB. [InfluxDB promises to be good](https://github.com/influxdb/influxdb#an-open-source-distributed-time-series-database):

>Going forward, the 0.9.x series of releases will not make breaking API changes or breaking changes to the underlying data storage.

**Comment by rjnagal** [comment]
Thanks for reporting @onlyjob 

It's being addressed in #800

**Comment by GeertJohan** [comment]
@onlyjob Note: It sais 0.9.x, not x.y.z
