### ISSUE TITLE
Support TCP statistics for host and containers

### ISSUE THREAD

**Issue by f0** [google/cadvisor#889]
Hi,

is it possible to support tcp statistics from /proc/net/tcp and /proc/net/tcp6, for both the machine, and containers (when they have their own network stack)?

regards f0

**Comment by vishh** [comment]
Yes. Can you file an issue against cAdvisor?

**Comment by f0** [comment]
hm , I thought this issue is against  cAdvisor.  Can u point me to the correct place?

**Comment by vishh** [comment]
@f0: My bad, I read this issue via email and I misread the source.

**Comment by vishh** [comment]
@f0: Will you be able to post a PR for this?

**Comment by f0** [comment]
@vishh i can try it

**Comment by f0** [comment]
@vishh   should info v1 and v2 supported? i see only v1 imported

**Comment by vishh** [comment]
I'd recommend updating just v2. By import what are you referring to?

**Comment by jimmidyson** [comment]
Out of interest, what tcp statistics from `/proc/net/tcp` are you interested in?

**Comment by f0** [comment]
@vishh  in lbcontainer/helper only info from v1 are imported
@jimmidyson  e.g how many connections in state Established or Listen ..

**Comment by jimmidyson** [comment]
@f0 Sounds good!

**Comment by f0** [comment]
@vishh  ok a working prototype is finished (for the api), maybe you can take a look at  https://github.com/f0/cadvisor  and give some feedback

I also had some trouble with the ap iv1, v2 transistion, atm its only working for v1
