### ISSUE TITLE
please support ssl or other kinds of authorization

### ISSUE THREAD

**Issue by Oscarzhao** [google/cadvisor#894]
when i use kubelet (cadvisor inside), i want to visit the cadvisor (4194) port from a remote host securely and not from master (via /api/v1/proxy/nodes/{name}/{path:*} ) , so ssl or other type of authorization is a need, thx

**Comment by jimmidyson** [comment]
When embedded inside a kubelet I'd rather see cadvisor exposed under something like `/cadvisor` on the kubelet port & totally disabling the separate cadvisor port, thereby reusing the kubelet cert & auth.

Alternatively we could add in the same TLS & auth stuff to cadvisor that I added to heapster yesterday, but that would then also require those config options adding to the kubelet to enable it, not too keen on that personally.

Thoughts @vishh?

**Comment by rjnagal** [comment]
+1 to what @jimmidyson said. Many users embed cadvisor into their own products - kubernetes/kubelet being one of them. I'd prefer if we don't add non-trivial auth handling in cadvisor which might conflict or bypass settings for the wrapper. AFAIK, kubelet is in process of  disabling cadvisor port and using kubelet as a proxy for all cadvisor data.

**Comment by jimmidyson** [comment]
I've submitted a PR for that - kubernetes/kubernetes#14556

**Comment by vishh** [comment]
+1 to Rohit's comments. Until we have a kubelet API that can expose all the
data that cadvisor provides, we might have to expose an endpoint like
`/cadvisor`.

**Comment by jimmidyson** [comment]
That's exactly what I've done in the referenced PR :)

**Comment by vishh** [comment]
I think this issue can be closed now. Feel free to re-open if you think otherwise @Oscarzhao.
