### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by nashasha1** [google/cadvisor#911]
"imports github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar: cannot find package "github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar""

I met this error when I built it (restore).

It was ok a few days ago. But today it is not work anymore.

Anyone got the same error?

**Comment by jimmidyson** [comment]
Are you building with `godep go build `? There's a Makefile now in project root so you should be able to do a simple `make` now BTW.

**Comment by nashasha1** [comment]
Yes. I got this error when I run `godep restore` ! Even I use `make` to build, it still need this package, am I right?

**Comment by jimmidyson** [comment]
You don't need to do a godep restore to build cadvisor. godep vendors all required packages locally. So unless you're looking to add/update/remove any dependencies you don't need to run godep restore.

make or godep go build should suffice.

**Comment by nashasha1** [comment]
Thanks @jimmidyson . I was building it in a new vm. So I had to restore it. The point is this package disappear. I don't know why. You can try `go get` it, I think you will get the same error.

**Comment by jimmidyson** [comment]
I'll check this later but even when building in a new workspace, you shouldn't need to do a restore. godep configures your GOPATH to use the vendored dependencies. One downside is that godep means that cadvisor is not go gettable, or at least not buildable directly from go get. godep go build or make after cloning should work fine though.

**Comment by jimmidyson** [comment]
So this builds fine on a clean env with `godep go build` or `make` but `godep restore` doesn't work as you mentioned. Looks like some manual editing to the godeps config.

**Comment by nashasha1** [comment]
Thanks@jimmidyson  `godep go build` work well!

**Comment by jimmidyson** [comment]
Oh great!

The problem with `godep restore` is that it can't handle packages being deleted from source repos. In this case, the docker repo has deleted that package & that's messing up godep.

@vishh What do you think about upgrading docker dependencies?
