### ISSUE TITLE
subcontainers??

### ISSUE THREAD

**Issue by wulonghui** [google/cadvisor#914]
For cAdvisor, there are two types of container:
- raw
- docker

as I understand, the container here is kind of general theory, we can the machine, the process is a container. 
But confused with subcontainers, what's the meaning and function??

**Comment by timstclair** [comment]
I assume you're asking about the [SubcontainersInfo](https://github.com/google/cadvisor/blob/master/client/client.go#L99) in the client? You can think of it as the recursive version of ContainerInfo. For example calling `SubcontainersInfo` on the root container, will return info on all containers.

**Comment by alculquicondor** [comment]
What sets that hierarchy? is it through the cgroups or some kind of label?
