### ISSUE TITLE
non-free color profile IEC61966-2.1 in `logo.png`

### ISSUE THREAD

**Issue by onlyjob** [google/cadvisor#915]
`logo.png` uses non-free (prohibited modification) colour profile _IEC61966-2.1_, see  http://www.color.org/srgbprofiles.xalter#v2

**Comment by vmarmol** [comment]
I...I...I'm sorry I have no idea what that means :)

I did make the logo though!

**Comment by onlyjob** [comment]
If you run `exiftool logo.png` you'll see (among other parameters):

~~~~
Profile Copyright               : Copyright (c) 1998 Hewlett-Packard Company
Profile Description             : sRGB IEC61966-2.1
Profile Name                    : sRGB IEC61966-2.1
~~~~

This means that your graphics editor saved image with embedded non-free colour profile.
You can remove ICC profile using command `exiftool -icc_profile"-<=" logo.png` or convert it using GIMP (Image --> Mode --> Convert to Color Profile).

**Comment by onlyjob** [comment]
Thanks, @vishh. :-)
