### ISSUE TITLE
cadvisor leaks goroutines when running with latest go-dockerclient

### ISSUE THREAD

**Issue by yujuhong** [google/cadvisor#925]
go-dockerclient now (https://github.com/fsouza/go-dockerclient/commit/163268693e2cf8be2920158b59ef438fc77b85e2) saves and reuses the connection. `cadvisor.GetVersionInfo` creates a new docker client each time, causing the connection leakage. 

See https://github.com/kubernetes/kubernetes/issues/15805#issuecomment-148963658 for details.

**Comment by vishh** [comment]
@yujuhong: Thanks for reporting the issue. Are you working on a fix, or shall I pick this up?

**Comment by jimmidyson** [comment]
@vishh Should be a simple fix - don't mind picking it up if you don't have time.

**Comment by vishh** [comment]
Go for it! Thanks!

**Comment by yujuhong** [comment]
Hmm...I just checked the cadvisor code and it seems every container handler uses its own docker client as well. Not only does that waste the resource, cadvisor never gets to close the connection even after the container terminates.

I think our options are:
 1. Submit a patch to go-dockerclient to allow closing the connection.
 2. Refactor cadvisor to reuse the same docker client for all "docker" containers (similar to kubelet's model).

Option 2 seems reasonable, but it seems go-dockerclient is not particularly thread-safe (e.g., struct field [unixHTTPClient](https://github.com/fsouza/go-dockerclient/blob/master/client.go#L677) is not guarded by any sync primitive). 

Thoughts? @jimmidyson @vishh

**Comment by vishh** [comment]
Docker interactions in cAdvisor needs to be refactored. It is currently
messy. I'm in favor of option `2` since it helps with the refactoring in
general.
cAdvisor performs read-only operations. From that perspective, will
thread-safety be an issue?

**Comment by jimmidyson** [comment]
As far as I can see, it's not the caller's responsibility to close the docker client. The client returns unmarshalled responses so it should be the docker client that closes the response body?

This looks like a bug in the docker client to me. Creating the docker client multiple times is wasteful, but shouldn't leak anything. We should tidy that up but I don't see it fixing the problem unless I'm missing something.

The unixHTTPClient shouldn't need to guarded - `http.Client` and & `http.Transport` are safe for concurrent use by multiple goroutines as documented.

**Comment by jimmidyson** [comment]
I seem to remember this being an issue somewhere else, perhaps in Prometheus. I seem to remember that you should close the response body even if `Do` returns an error. Stuff like this (https://github.com/fsouza/go-dockerclient/blob/af9789bbd78acf3e279274caa54682185eb7ed33/misc.go#L14-L17):

```
resp, err := c.do("GET", "/version", doOptions{})
if err != nil {
	return nil, err
}
defer resp.Body.Close()
```

Should actually be:

```
resp, err := c.do("GET", "/version", doOptions{})
defer resp.Body.Close()
if err != nil {
	return nil, err
}
```

**Comment by yujuhong** [comment]
> The unixHTTPClient shouldn't need to guarded - http.Client and & http.Transport are safe for concurrent use by multiple goroutines as documented.

I meant the initialization of the unixHTTPClient, since you could have both goroutines thinking it's `nil` and attempt to creates a new client...

**Comment by jimmidyson** [comment]
Forget what I said before, totally wrong about the closing body thing I mentioned above.

**Comment by jimmidyson** [comment]
Ah OK I understand what you're saying about the guards around the creation of the `unixHTTPClient` now. Yes that would be required.

**Comment by yujuhong** [comment]
HTTP client uses persistent connection by default, and unless we explicitly request the connection to be closed after the request. In this case, for performance reasons, I think a persistent connection is better for cadvisor anyway :-) 

@vishh @jimmidyson, I am not that familiar with the codebase, could you give an estimate how long would it take to refactor cadvisor? If it's going to take a while, I'd prefer reverting the go-dockerclient version bump since kubernetes HEAD is pretty messed up as of now.

**Comment by jimmidyson** [comment]
@yujuhong Just pushed #930 which should fix it.
