### ISSUE TITLE
How do we know cadvisor is working?

### ISSUE THREAD

**Issue by prasadnh** [google/cadvisor#928]
Hi,

I am new to this...trying to set cadvisor to see all our docker containers info. i see advisor docker process when I do docker ps. But don't see any logs or info.  

When I run curl localhost:8080 I get below message...no clue:(

curl localhost:8080
<a href="/containers/">Temporary Redirect</a>.

Can somebody help me to fix this?
I use ubuntu OS.

Thanks,
Prasad

**Comment by vishh** [comment]
Try opening http://localhost:8080 in your browser.

**Comment by prasadnh** [comment]
thanks for quick response... tried browser too... shows blank page.

**Comment by vishh** [comment]
Can you run cAdvisor with `--logtostderr` flag ?

**Comment by prasadnh** [comment]
i see this

ubuntu@ip-10-201-5-134:~$ docker logs -f cadvisor
I1020 00:25:55.967297 00001 storagedriver.go:111] No backend storage
selected
I1020 00:25:55.967348 00001 storagedriver.go:113] Caching stats in memory
for 2m0s
I1020 00:25:55.967421 00001 manager.go:127] cAdvisor running in container:
"/docker/44a8e7c9ac4941579f2afbcdf391cb79c5de81fb9e0317aa10361570fa1c96f9"
I1020 00:25:55.971370 00001 fs.go:93] Filesystem partitions:
map[/dev/disk/by-uuid/e1d70192-1bb0-461d-b89f-b054e45bfa00:{mountpoint:/rootfs
major:202 minor:1} /dev/xvdb:{mountpoint:/rootfs/mnt major:202 minor:16}]
I1020 00:25:56.724075 00001 machine.go:49] Couldn't collect info from any
of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I1020 00:25:56.724177 00001 manager.go:158] Machine: {NumCores:4
CpuFrequency:2500042 MemoryCapacity:15770574848 MachineID:
SystemUUID:EC2C6E40-B180-2157-4650-36A78FC5F6DB
BootID:08726c62-c50e-48ca-bd6c-851e9842080e
Filesystems:[{Device:/dev/disk/by-uuid/e1d70192-1bb0-461d-b89f-b054e45bfa00
Capacity:42127835136} {Device:/dev/xvdb Capacity:39490912256}]
DiskMap:map[202:0:{Name:xvda Major:202 Minor:0 Size:42949672960
Scheduler:deadline} 202:16:{Name:xvdb Major:202 Minor:16 Size:40256929792
Scheduler:deadline}] NetworkDevices:[{Name:eth0
MacAddress:02:93:d9:92:29:41 Speed:0 Mtu:9001}] Topology:[{Id:0
Memory:15770574848 Cores:[{Id:0 Threads:[0 2] Caches:[{Size:32768 Type:Data
Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified
Level:2}]} {Id:1 Threads:[1 3] Caches:[{Size:32768 Type:Data Level:1}
{Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}]
Caches:[{Size:26214400 Type:Unified Level:3}]}] CloudProvider:Unknown
InstanceType:Unknown}
I1020 00:25:56.725213 00001 manager.go:165] Version:
{KernelVersion:3.13.0-62-generic ContainerOsVersion:Buildroot 2014.02
DockerVersion:1.8.1 CadvisorVersion:0.18.0}
I1020 00:25:56.852462 00001 factory.go:234] Registering Docker factory
I1020 00:25:56.856547 00001 factory.go:89] Registering Raw factory
I1020 00:25:57.144390 00001 manager.go:998] Started watching for new ooms
in manager
W1020 00:25:57.144673 00001 manager.go:234] Could not configure a source
for OOM detection, disabling OOM events: exec: "journalctl": executable
file not found in $PATH
I1020 00:25:57.159663 00001 manager.go:247] Starting recovery of all
containers
I1020 00:25:57.207300 00001 manager.go:252] Recovery completed
I1020 00:25:57.233508 00001 cadvisor.go:94] Starting cAdvisor version:
"0.18.0" on port 8080


On Mon, Oct 19, 2015 at 4:57 PM, Vish Kannan <notifications@github.com>
wrote:

> Can you run cAdvisor with `--logtostderr` flag ?
>
> On Mon, Oct 19, 2015 at 4:40 PM, prasadnh <notifications@github.com>
> wrote:
>
> > thanks for quick response... tried browser too... shows blank page.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/cadvisor/issues/928#issuecomment-149377736>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/cadvisor/issues/928#issuecomment-149379885>.
>



-- 
Thanks,
Prasad

**Comment by vishh** [comment]
I suspect you haven't exposed port 8080 from the cadvisor container on to
your host.

**Comment by prasadnh** [comment]
I think i tried different options like port farwarding to 80 which is open
in our network and also tried --port option.

I don't see any issues when i do port farwarding for influxdb or  grafana...

On Mon, Oct 19, 2015 at 5:35 PM, Vish Kannan <notifications@github.com>
wrote:

> I suspect you haven't exposed port 8080 from the cadvisor container on to
> your host.
>
> On Mon, Oct 19, 2015 at 5:33 PM, prasadnh <notifications@github.com>
> wrote:
>
> > i see this
> >
> > ubuntu@ip-10-201-5-134:~$ docker logs -f cadvisor
> > I1020 00:25:55.967297 00001 storagedriver.go:111] No backend storage
> > selected
> > I1020 00:25:55.967348 00001 storagedriver.go:113] Caching stats in memory
> > for 2m0s
> > I1020 00:25:55.967421 00001 manager.go:127] cAdvisor running in
> container:
> >
> "/docker/44a8e7c9ac4941579f2afbcdf391cb79c5de81fb9e0317aa10361570fa1c96f9"
> > I1020 00:25:55.971370 00001 fs.go:93] Filesystem partitions:
> >
> >
> map[/dev/disk/by-uuid/e1d70192-1bb0-461d-b89f-b054e45bfa00:{mountpoint:/rootfs
> > major:202 minor:1} /dev/xvdb:{mountpoint:/rootfs/mnt major:202 minor:16}]
> > I1020 00:25:56.724075 00001 machine.go:49] Couldn't collect info from any
> > of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
> > I1020 00:25:56.724177 00001 manager.go:158] Machine: {NumCores:4
> > CpuFrequency:2500042 MemoryCapacity:15770574848 MachineID:
> > SystemUUID:EC2C6E40-B180-2157-4650-36A78FC5F6DB
> > BootID:08726c62-c50e-48ca-bd6c-851e9842080e
> >
> Filesystems:[{Device:/dev/disk/by-uuid/e1d70192-1bb0-461d-b89f-b054e45bfa00
> > Capacity:42127835136} {Device:/dev/xvdb Capacity:39490912256}]
> > DiskMap:map[202:0:{Name:xvda Major:202 Minor:0 Size:42949672960
> > Scheduler:deadline} 202:16:{Name:xvdb Major:202 Minor:16 Size:40256929792
> > Scheduler:deadline}] NetworkDevices:[{Name:eth0
> > MacAddress:02:93:d9:92:29:41 Speed:0 Mtu:9001}] Topology:[{Id:0
> > Memory:15770574848 Cores:[{Id:0 Threads:[0 2] Caches:[{Size:32768
> Type:Data
> > Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified
> > Level:2}]} {Id:1 Threads:[1 3] Caches:[{Size:32768 Type:Data Level:1}
> > {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified
> Level:2}]}]
> > Caches:[{Size:26214400 Type:Unified Level:3}]}] CloudProvider:Unknown
> > InstanceType:Unknown}
> > I1020 00:25:56.725213 00001 manager.go:165] Version:
> > {KernelVersion:3.13.0-62-generic ContainerOsVersion:Buildroot 2014.02
> > DockerVersion:1.8.1 CadvisorVersion:0.18.0}
> > I1020 00:25:56.852462 00001 factory.go:234] Registering Docker factory
> > I1020 00:25:56.856547 00001 factory.go:89] Registering Raw factory
> > I1020 00:25:57.144390 00001 manager.go:998] Started watching for new ooms
> > in manager
> > W1020 00:25:57.144673 00001 manager.go:234] Could not configure a source
> > for OOM detection, disabling OOM events: exec: "journalctl": executable
> > file not found in $PATH
> > I1020 00:25:57.159663 00001 manager.go:247] Starting recovery of all
> > containers
> > I1020 00:25:57.207300 00001 manager.go:252] Recovery completed
> > I1020 00:25:57.233508 00001 cadvisor.go:94] Starting cAdvisor version:
> > "0.18.0" on port 8080
> >
> >
> > On Mon, Oct 19, 2015 at 4:57 PM, Vish Kannan <notifications@github.com>
> > wrote:
> >
> > > Can you run cAdvisor with `--logtostderr` flag ?
> > >
> > > On Mon, Oct 19, 2015 at 4:40 PM, prasadnh <notifications@github.com>
> > > wrote:
> > >
> > > > thanks for quick response... tried browser too... shows blank page.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/google/cadvisor/issues/928#issuecomment-149377736
> > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/google/cadvisor/issues/928#issuecomment-149379885
> >.
> > >
> >
> >
> >
> > --
> > Thanks,
> > Prasad
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/cadvisor/issues/928#issuecomment-149385354>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/cadvisor/issues/928#issuecomment-149385572>.
>



-- 
Thanks,
Prasad

**Comment by prasadnh** [comment]
Right...worked now...Thanks for the help

**Comment by kuoshin** [comment]
I have the same problem....Can you tell me how to fix this problem ?  thanks
