### ISSUE TITLE
Unmarshalling error when `AdditionalGroups` field in libcontainer config.go is out of sync with Docker

### ISSUE THREAD

**Issue by pmorie** [google/cadvisor#929]
I discovered during implementation of supplemental group support in Kubernetes that `AdditionalGroups` field has diverged between Docker and cadvisor:

* [version in cadvisor](https://github.com/google/cadvisor/blob/master/Godeps/_workspace/src/github.com/docker/libcontainer/configs/config.go#L87)
* [version in Docker](https://github.com/docker/docker/blob/master/vendor/src/github.com/opencontainers/runc/libcontainer/configs/config.go#L148)

When cadvisor tries to read the config laid down by a Docker that vendors a different version of the config, an unmarshalling error occurs.

This hasn't been an issue so far in Kubernetes because we haven't used the `AdditionalGroups` field in the docker API yet.  How has this kind of change been handled in the past?  It seems like cadvisor has to be able to parse whatever Docker might lay down.

**Comment by jimmidyson** [comment]
@pmorie Do you know what version of Docker the type of `AdditionalGroups` was changed in? Wondering if we can just update cadvisor's config to string & forget about handling old format.

**Comment by jimmidyson** [comment]
Fixed in #930 by bumping libcontainer again. I wouldn't worry about the old format as it didn't look like it worked properly anyway.
