### ISSUE TITLE
Docker Containers with memory limits do not appear in cadvisor

### ISSUE THREAD

**Issue by kansoA** [google/cadvisor#931]
When running a docker container with the memory limit flag set, it does not appear in cadvisor list of containers:
For example : "docker run --name UBUNTU -it -m 30M ubuntu:latest /bin/bash" UBUNTU will not appear in cadvisor unless you terminate it, and run again without the "-m 30M" 

I am running cadvisor on Ubuntu 14.04.

**Comment by jimmidyson** [comment]
Hey @kansoA - I've tested with master & this seems to be working properly. If you could try with master & re-open if this issue still happens for you.
