### ISSUE TITLE
Support overlayfs

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#932]
#926 adds support for docker image storage partition discovery with a device mapper storage backend. We need to add support for Overlayfs. This is a requirement for Kubernetes v1.1 to work on OS distros that use Overlayfs as the default storage backend driver.

cc @yifan-gu cc @dchen1107

**Comment by jimmidyson** [comment]
What distros use overlayfs as default?

**Comment by vishh** [comment]
AFAIK CoreOS does.

**Comment by yifan-gu** [comment]
cc @crawford @jonboulle
