### ISSUE TITLE
Cut 0.19 release for Kubernetes 1.1 release

### ISSUE THREAD

**Issue by dchen1107** [google/cadvisor#935]
I want to the new release includes:

* Compute fs usage for docker containers less often. #910
* Support devicemapper storage for docker images dir #926
* Docker client update including reuse #930

cc/ @jimmidyson @vishh

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/issues/15805

**Comment by jimmidyson** [comment]
@vishh What's the process for a release? I don't have access to docker hub for cadvisor but can tag & add github release if necessary.

**Comment by jimmidyson** [comment]
@dchen1107 This will be a 0.19.1 release of cadvisor as I've previously tagged 0.19.0 (already in k8s). I'll cut this release today when I find out if there are any nuances I'm not aware of & will get a PR in for updating the cadvisor godeps in k8s.

**Comment by jimmidyson** [comment]
Found high CPU as explained in #938 - holding off on release until this has been looked at.

**Comment by dchen1107** [comment]
Thanks for status updates here.

**Comment by amcrn** [comment]
#938 was closed, but I don't see any 0.19.x releases on docker hub: https://hub.docker.com/r/google/cadvisor/tags/ . is there a different bug holding up the push?

**Comment by vishh** [comment]
I pushed a docker image based on 0.19.3 tag. Can you try that out Auston?

**Comment by amcrn** [comment]
@vishh wow, that was fast! pulled, ran, and looks good. thanks a bunch!

**Comment by jimmidyson** [comment]
Closing.
