### ISSUE TITLE
Available filesystem space reported incorrectly for device mapper storage driver.

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#944]
This issue is specific to reporting docker image filesystem usage.
`available` space is currently calculated based on the capacity of the device mapper pool device, instead of the capacity of the underlying device/partition that the pool device is using. Relevant code [here](https://github.com/google/cadvisor/blob/master/fs/fs.go#L390).
Since the pool device can be of arbitrary size, calculate available space based on the pool device size is incorrect.
In the case of other storage drivers, the underlying partition size is used by default. This can potentially include usage of that partition for purposes other than disk.
I recommend reverting most of the changes in #926 and instead just identify the partition that holds the pool device and use vfs stats instead.

Relevant Issue: #920
cc @jimmidyson @dchen1107

**Comment by jimmidyson** [comment]
I assume you're talking about devicemapper loopback? Vfs stat doesn't work for devicemapper thinpool lvm (the preferred production use for performance reasons). So I would not revert the change but rather extend the check for loopback devicemapper to use the underlying partition info.

Any thoughts @ncdc?

**Comment by vishh** [comment]
Just to clarify, will the current behavior work when a real device is used
instead of loopback?

**Comment by jimmidyson** [comment]
It certainly should, yes. At least on my machine :)

**Comment by vishh** [comment]
Ok :)
When using real volumes instead of loopback, will the size of the pool
device correspond to the size of the data volume or the sum of data and
metadata volumes?

Disclaimer: My understanding of dm driver is very limited.

**Comment by jimmidyson** [comment]
Disclaimer: so is mine.

It should report on the whole pool.

**Comment by ncdc** [comment]
@vishh @jimmidyson there is still apparently an issue with devicemapper :frowning: 

#926 added code that sets `fsInfo.labels[LabelDockerImages]` to the devicemapper device correctly. Unfortunately, after that, we have `fsInfo.addLabels(context)`, which calls `updateDockerImagesPath`, which ends up replacing the previously set value with the device that corresponds to `/`, at least in my testing.

Here is some debugging output:

```
I0121 13:15:24.588091    1235 manager.go:131] cAdvisor running in container: "/"
I0121 13:15:24.682259    1235 fs.go:112] Filesystem partitions: map[/dev/sda1:{mountpoint:/boot major:8 minor:1 fsType: blockSize:0} vg_vagrant-docker--pool:{mountpoint: major:253 minor:3 fsType:devicemapper blockSize:1024} /dev/mapper/vg_vagrant-lv_root:{mountpoint:/ major:253 minor:0 fsType: blockSize:0}]

source= vg_vagrant-docker--pool
mountpoint=
v= /var/lib/docker/devicemapper
v= /var/lib/docker/btrfs
v= /var/lib/docker/aufs
v= /var/lib/docker/overlay
v= /var/lib/docker/zfs
v= /var/lib/docker
v= /var/lib
v= /var
v= /

source= /dev/mapper/vg_vagrant-lv_root
mountpoint= /
v= /var/lib/docker/devicemapper
v= /var/lib/docker/btrfs
v= /var/lib/docker/aufs
v= /var/lib/docker/overlay
v= /var/lib/docker/zfs
v= /var/lib/docker
v= /var/lib
v= /var
v= /
i= vg_vagrant-docker--pool
mnt=
overriding with source= /dev/mapper/vg_vagrant-lv_root

source= /dev/sda1
mountpoint= /boot
v= /var/lib/docker/devicemapper
v= /var/lib/docker/btrfs
v= /var/lib/docker/aufs
v= /var/lib/docker/overlay
v= /var/lib/docker/zfs
v= /var/lib/docker
v= /var/lib
v= /var
v= /

&fs.RealFsInfo{partitions:map[string]fs.partition{"/dev/mapper/vg_vagrant-lv_root":fs.partition{mountpoint:"/", major:0xfd, minor:0x0, fsType:"", blockSize:0x0}, "/dev/sda1":fs.partition{mountpoint:"/boot", major:0x8, minor:0x1, fsType:"", blockSize:0x0}, "vg_vagrant-docker--pool":fs.partition{mountpoint:"", major:0xfd, minor:0x3, fsType:"devicemapper", blockSize:0x400}}, labels:map[string]string{"docker-images":"/dev/mapper/vg_vagrant-lv_root", "root":"/dev/mapper/vg_vagrant-lv_root"}}
```

In `updateDockerImagesPath`, because there is no mountpoint associated with the devicemapper pool, when it sees the source that corresponds to /, it ends up overriding the previously set value. I wonder if we just need to short-circuit if we know it's devicemapper and not call this function.

**Comment by ncdc** [comment]
This seems to fix it:

```diff
diff --git a/fs/fs.go b/fs/fs.go
index 32acef5..ed67ff7 100644
--- a/fs/fs.go
+++ b/fs/fs.go
@@ -117,14 +117,21 @@ func NewFsInfo(context Context) (FsInfo, error) {

 func (self *RealFsInfo) addLabels(context Context) {
        dockerPaths := getDockerImagePaths(context)
+       deviceMapper := false
+       for _, p := range self.partitions {
+               if p.fsType == "devicemapper" {
+                       deviceMapper = true
+               }
+       }
        for src, p := range self.partitions {
                if p.mountpoint == "/" {
                        if _, ok := self.labels[LabelSystemRoot]; !ok {
                                self.labels[LabelSystemRoot] = src
                        }
                }
-               self.updateDockerImagesPath(src, p.mountpoint, dockerPaths)
-               // TODO(rjnagal): Add label for docker devicemapper pool.
+               if !deviceMapper {
+                       self.updateDockerImagesPath(src, p.mountpoint, dockerPaths)
+               }
        }
 }
```

**Comment by ncdc** [comment]
> When using real volumes instead of loopback, will the size of the pool
device correspond to the size of the data volume or the sum of data and
metadata volumes?

```
sudo docker info
Containers: 2
Images: 6
Storage Driver: devicemapper
 Pool Name: vg_vagrant-docker--pool
 Pool Blocksize: 524.3 kB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 529.5 MB
 Data Space Total: 27.58 GB
 Data Space Available: 27.05 GB
 Metadata Space Used: 151.6 kB
 Metadata Space Total: 33.55 MB
 Metadata Space Available: 33.4 MB
```

Here's what cadvisor reports (with the patch above applied):

```
[]v2.FsInfo{v2.FsInfo{Device:"vg_vagrant-docker--pool", Mountpoint:"", Capacity:0x66c000000, Available:0x64c700000, Usage:0x1f900000, Labels:[]string{"docker-images"}}}
```

Translated, Capacity=27581743104, Available=27052212224, Usage=529530880. Those #s look like they align with the Data values above.

**Comment by jimmidyson** [comment]
Thanks @ncdc. Patch looks OK. You want to submit a PR or I can do it?

**Comment by ncdc** [comment]
@jimmidyson I'll submit, thanks!

**Comment by ncdc** [comment]
@jimmidyson do we need to do anything re "So I would not revert the change but rather extend the check for loopback devicemapper to use the underlying partition info." ?

**Comment by vishh** [comment]
Ideally yes. We should support loopback dm devices as well.

**Comment by ncdc** [comment]
I realized my patch blindly sets deviceMapper to true regardless of the partition label - I'm updating it to only do this if the device for LabelDockerImages matches the loop var. It'll be in my PR.

**Comment by ncdc** [comment]
@vishh I'll apply my patch to another VM I have that's using loopback and see what it reports. If it's incorrect, would you like the fix in the same PR or a separate one?

**Comment by vishh** [comment]
Sorry for the delay. Been busy with the release. @ncdc: Have you fixed devicemapper support for both loopback and real device?

**Comment by ncdc** [comment]
@vishh yes

**Comment by vishh** [comment]
Awesome. Thanks @ncdc!

**Comment by clemSeveillac** [comment]
Hi folks, I didn't find this useful `available` disk space metrics in the cadvisor `/metrics` output (but just in `/api/v2.0/storage?label=docker-images`), does that mean we cannot scrap this via prometheus?
