### ISSUE TITLE
Once in a while docker stats   0 B/0 B             0.00%               0 B/0 B

### ISSUE THREAD

**Issue by kode1100-dev** [google/cadvisor#946]
Hi,

I created a script to append the docker stats every N minutes by cron job to a file. I find for some containers, I'm running 5, that I get a lot of good data mixed in with the occasional   0 B/0 B . That data was collected every minute. Each container seems to have this issue and some more and some less.

93f855007340        0.10%               653.5 MB/8.375 GB   7.80%               2.714 MB/159.3 MB
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
93f855007340        0.00%               0 B/0 B             0.00%               0 B/0 B
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
93f855007340        0.13%               653.6 MB/8.375 GB   7.80%               2.714 MB/159.3 MB

The containers were not shutdown and had been running for a period of 4 days during the stats collection.
Any known reasons why that would occur? 

Thanks
Alex

**Comment by jimmidyson** [comment]
Fyi `docker stats` is a docker command, unrelated to cadvisor. If you have a problem with `docker stats` then you'll need to raise that in the docker repo.
