### ISSUE TITLE
Handle non-init systemd process

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#947]
If systemd is not running as the init daemon, docker does not use it for container cgroup management. However, cAdvisor on the other hand, assumes docker is using systemd even if it is not the init daemon.

There seems to be use cases for running systemd as a regular non-init process :)

cAdvisor needs to handle this scenario.

**Comment by andyzheng0831** [comment]
cc/ @andyzheng0831

**Comment by andyzheng0831** [comment]
It will be great if we can fix this issue soon and make it merged in next k8s release post 1.1

**Comment by dyema** [comment]
Regardless of whether systemd is init or not, I think it's desirable for cAdvisor to support the configuration where systemd is not managing cgroups for docker containers.

**Comment by andyzheng0831** [comment]
@vishh May I ask about the status of bug? As we already cut k8s 1.1.1 release, would it possible for us to speed up fixing this issue, so that this will unblock our effort ASAP.

**Comment by vishh** [comment]
#960 is out for review. Once that is merged, I can cherry-pick that into
K8s v1.1 branch.

**Comment by dashpole** [comment]
closing via #960
