### ISSUE TITLE
Canary Dockerfile fails with error about thin-provisioning-tools

### ISSUE THREAD

**Issue by pwittrock** [google/cadvisor#948]
Building the deploy/canary/Dockerfile fails.  Error message:

>Status: Image is up to date for golang:latest
 ---> a17b1b1adcfc
Step 1 : MAINTAINER vmarmol@google.com
 ---> Running in 574865a057f2
 ---> 397f6d04d136
Removing intermediate container 574865a057f2
Step 2 : RUN apt-get install -y git thin-provisioning-tools
 ---> Running in 7304a9b2dbdf
Reading package lists...
Building dependency tree...
Reading state information...
[91mE: Unable to locate package thin-provisioning-tools
[0mThe command '/bin/sh -c apt-get install -y git thin-provisioning-tools' returned a non-zero code: 100
Build step 'Docker Build and Publish' marked build as failure
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] Skipped based on build state FAILURE
Finished: FAILURE

**Comment by vishh** [comment]
[This patch](https://github.com/google/cadvisor/commit/8e63ba34fe397f1bcf61e2c7be9c7518c84d42eb) caused the issue. IIUC, `thin-provisioning-tools` is a package name specific to alpine linux. I have posted a fix.
