### ISSUE TITLE
Can't start cAdvisor in docker v1.9

### ISSUE THREAD

**Issue by feiskyer** [google/cadvisor#956]
```
# sudo docker run   --volume=/:/rootfs:ro   --volume=/var/run:/var/run:rw   --volume=/sys:/sys:ro   --volume=/var/lib/docker/:/var/lib/docker:ro   --publish=8080:8080   --detach=true   --name=cadvisor   google/cadvisor:latest

Error response from daemon: Relabeling of / is not allowed
```

**Comment by jimmidyson** [comment]
This works fine for me on Fedora 23. Is this still happening for you? What distro are you using?

**Comment by feiskyer** [comment]
I'm using CentOS 7

**Comment by jimmidyson** [comment]
Can you run with `--privileged` please?

And are you using the rpm from docker repo or from centos official repo?

**Comment by feiskyer** [comment]
Finally found it's the problem of selinux. I can start cAdvisor properly when shuting down selinux.

Thanks @jimmidyson

**Comment by jimmidyson** [comment]
@feiskyer FYI - https://bugzilla.redhat.com/show_bug.cgi?id=1275554
