### ISSUE TITLE
sanitizing metric dimension

### ISSUE THREAD

**Issue by jchauncey** [google/cadvisor#958]
For example the image isn't particularly useful but the version is. So it would be great if that was separated into its own dimension. The other one is the container name. Certain platforms create some what unique container names (`mycontainer_v2.web.1` `mycontainer_v2.web.2`) for instance. It would be great if we could have a way to supply a regular expression to parse out the information we didnt want. In this case I would like my metrics to have the container name `mycontainer.web` (with version being an added dimension).

I specifically need this for the Prometheus exporter but think it could be valuable for all metrics being sent.

**Comment by vishh** [comment]
If the prometheus exporter where to be a standalone buddy container, I
think these use cases will be easier to handle. The buddy can query
cadvisor periodically and expose prometheus metrics in any manner, without
requiring changes to cadvisor.

On Tue, Nov 10, 2015 at 4:44 PM, Jonathan Chauncey <notifications@github.com

**Comment by jimmidyson** [comment]
You can already add a regex to extract labels from container names (https://github.com/google/cadvisor/blob/master/http/handlers.go#L91-L95). We do this in the kubelet. Currently this can only be done by embedding cadvisor & registering the cadvisor & prometheus http handlers there.

The other option is to use Prometheus relabelling to extract container name to labels.

**Comment by grobie** [comment]
With https://github.com/google/cadvisor/pull/1429 you have full control about the attached labels. This issue should be solved now @timstclair.

**Comment by dashpole** [comment]
closing via [comment](https://github.com/google/cadvisor/issues/958#issuecomment-241561435)
