### ISSUE TITLE
Add devicemapper container fs usage

### ISSUE THREAD

**Issue by vishh** [google/cadvisor#959]
We need to add support for calculating the container's root filesystem usage, with devicemapper docker storage driver.

One way to achieve this will be to enter docker daemon's mount namespace and then run a `stat -f` on container's rootfs mount. 
For example,

``` sh
nsenter -m -t `pidof docker` stat -f /var/lib/docker/devicemapper/mnt/<containerID>/rootfs/
```

nsenter requires a fork+exec, which is a mild annoyance. We can either run the above mentioned command periodically for every container and parse the output, or busybox cadvisor to fork+exec itself to enter docker's mount ns and output the usage of all running container's via a pipe. 

@rhvgoyal @mrunalp: Are there any other options?

**Comment by jimmidyson** [comment]
Another option is to do this with `dmsetup` as we did with the docker pool storage.

**Comment by vishh** [comment]
I couldn't get that to work for the container. Can you post an example?

**Comment by mrunalp** [comment]
@vishh I think the second option might be better so you can have a long running process that is in docker's mount namespace and communicate over a pipe.

**Comment by jimmidyson** [comment]
This was discussed in https://github.com/google/cadvisor/issues/920#issuecomment-148815756.

Something like this _may_ work:

```
DM_DEV=docker inspect -f '{{.GraphDriver.Data.DeviceName}}' <containerID>
DM_STATUS=`dmsetup status $DM_DEV`
DM_USED_SECTORS=`echo $DM_STATUS| cut -d' ' -f 4`
DM_USED_BYTES=`expr $DM_USED_SECTORS \* 512`
DM_TOTAL_SECTORS=`echo $DM_STATUS| cut -d' ' -f 5`
DM_TOTAL_BYTES=`expr $DM_TOTAL_SECTORS \* 512`
echo $DM_USED_BYTES / $DM_TOTAL_BYTES
```

I'm not 100% sure on the used bytes figure tbh.

**Comment by jimmidyson** [comment]
Would `nsenter`ing docker's pid ns require cadvisor to run in the host ns? Does that have any implications when running cadvisor in a container?

**Comment by vishh** [comment]
@jimmidyson: I don't think so. It will require a fork+exec though.

**Comment by vishh** [comment]
@jimmidyson: Can you verify if the `dmsetup` based approach? If that works, that will be much much better.

**Comment by jimmidyson** [comment]
I'd have to defer to someone who knows more about devicemapper tbh. @rhvgoyal @mrunalp opinions welcome on best approach.

**Comment by jchauncey** [comment]
What about using [gopsutil](https://github.com/shirou/gopsutil)? Specifically using [this](https://github.com/shirou/gopsutil/blob/master/disk/disk_unix.go)

**Comment by rhvgoyal** [comment]
I just checked with thin pool developers and they think using nr_mapped from thin device status line to figure out how many blocks are mapped is fine. That will tell how many blocks in thin pool are in use.

There is a possibility total size calculated here is more than reported by statfs() but this is the real
space used.

**Comment by rhvgoyal** [comment]
@jimmidyson for total sectors, instead of field 5, it might be better to use field 2. As per `man dmsetup` section `TABLE FORMAT` second field is `num_sectors'. Last field is highest mapped sector and not the number of sectors.

**Comment by rhvgoyal** [comment]
@vishh If cadvisor is running inside a container, will it even see the docker pid to be able to do nsenter? I am assuming no. I guess if it shares the pid namespace with host, then it should be fine.

**Comment by jimmidyson** [comment]
AFAIK cadvisor won't be sharing pid ns with host as this can lead to zombie processes. pid 1 in container so gets reaped properly.

**Comment by vishh** [comment]
@jimmidyson: will you be able to work on devicemapper support?

**Comment by jimmidyson** [comment]
@rhvgoyal Forgot to say thanks for the update on dmsetup - so... thanks!

@vishh Maybe early next week, yes.

**Comment by rhvgoyal** [comment]
@jimmidyson can you elaborate a bit more on why sharing pid namespace with host is a problem for cadvisor. If cadvisor is reaping children properly that should continue to work. And if it does not and when cadvior exits, I am assuming all these children will be re-parented to pid 1 of host (systemd) and will be reaped. Is that not the case. Am I missing something?

**Comment by jimmidyson** [comment]
Previously discussed in https://github.com/google/cadvisor/issues/822#issuecomment-135811901

**Comment by vishh** [comment]
cAdvisor surfaces the writable layer usage for docker containers. I hope that the `dmsetup` based logic mentioned here includes only the writable layer. Including image storage isn't helpful because, images are being shared.

**Comment by rhvgoyal** [comment]
@vishh above dmsetup based magic will include size of both unerlying image as well as writable layer. It is not writable layer only.

Dm developers had mentioned to me that if I really wanted writable layer, I can do following.

- Take metadata snapshot from thin pool.
- Do thin_delta
- Parse output and calculate usage.

I have not tried it but something along above lines should give us writable layer usage. Its not trivial though.

**Comment by vishh** [comment]
Hmm.. From an end user perspective, knowing how local storage is being
consumed will definitely help. The fact that image layers are accounted as
part of every container that uses those layers will be confusing for end
users.

**Comment by rhvgoyal** [comment]
I agree that having an easy way to figure out how much space a thin device is using which is unshared from its parent is probably a useful information. But we don't seem to have that functionality available right now. @cc jthornber

**Comment by rhvgoyal** [comment]
CC @jthornber

**Comment by jthornber** [comment]
I'm working on a thin_ls tool for you that should be released in the next couple of weeks.

**Comment by jimmidyson** [comment]
@jthornber Sounds great!

**Comment by vishh** [comment]
Awesome!

**Comment by vishh** [comment]
@jthornber: Has your tool been released?

**Comment by jthornber** [comment]
Working on it atm

**Comment by pwittrock** [comment]
@jthornber FS metrics device mapper support is blocked on this.  Do you have any updates?

**Comment by jthornber** [comment]
Yes, release 0.6.0.

https://github.com/jthornber/thin-provisioning-tools/releases.  The tool you're after is called 'thin_ls'

**Comment by vishh** [comment]
@jimmidyson @rhvgoyal: will one of you be able to integrate @jthornber's `thin_ls` tool?

**Comment by vishh** [comment]
FYI: If we can get this in anytime soon, we can provide disk usage tracking for device mapper in Kube v1.2.

**Comment by vishh** [comment]
@jthornber: When will the [alpine package for thin provisioning tools](https://pkgs.alpinelinux.org/package/testing/x86/thin-provisioning-tools) be updated to include your new tool?

**Comment by jthornber** [comment]
I've no idea, they're very of of date.

**Comment by vishh** [comment]
cc @ncdc

**Comment by ncdc** [comment]
@eparis @smarterclayton we'll need to see about getting a newer version of the RPM that has @jthornber's tools in it for Fedora/Centos/RHEL 7 (I am not at my desk and don't remember the package name offhand).

**Comment by sjenning** [comment]
device-mapper-persistent-data is the name of the package in Fedora

**Comment by vishh** [comment]
FYI: cAdvisor running as a docker container will need an alpine linux
package of that utility.

**Comment by sjenning** [comment]
I can verify that thin_ls is a viable way to do this:

```
[root@cadvisor devicemapper]# docker run -d busybox sleep 1000
fdd91d353daf764c9a9868faeca21a3d5baa12b928e5d16c9cda939d18d72ea5
[root@cadvisor devicemapper]# docker exec -ti fdd91d353daf764c9a9868faeca21a3d5baa12b928e5d16c9cda939d18d72ea5 /bin/sh
/ # dd if=/dev/zero of=/zeroes bs=1M count=10
10+0 records in
10+0 records out
10485760 bytes (10.0MB) copied, 0.016788 seconds, 595.7MB/s
/ # exit
[root@cadvisor devicemapper]# docker inspect fdd91d353daf764c9a9868faeca21a3d5baa12b928e5d16c9cda939d18d72ea5
...
"GraphDriver": {
        "Name": "devicemapper",
        "Data": {
            "DeviceId": "768",
...
[root@cadvisor devicemapper]# thin_ls -o DEV,EXCLUSIVE metadata | grep 768
768     11MiB <-- this is the stat we are looking for
```

RHEL is at v0.5.5 for device-mapper-persistent-data so it needs an update to at least v0.6.0.

Not sure about Alpine.

**Comment by sjenning** [comment]
This is a little more tricky than I first thought.

thin_ls does not work against live metadata.  The metadata needs to be snapshotted so it can be examined if it is live.

```
dmsetup message /dev/mapper/fedora-docker--pool 0 "reserve_metadata_snap"
```

Then thin_ls will work.  After thin_ls is run, the snapshot needs to be released

```
dmsetup message /dev/mapper/fedora-docker--pool 0 "release_metadata_snap"
```

This is a pretty heavyweight operation to do each time cadvisor queries the container size.

**Comment by rhvgoyal** [comment]
@sjenning right, currently you can not run thin_ls on live metadata. How did you conclude that reserving and releasing metadata snapshot is heavyweight operation.

**Comment by sjenning** [comment]
@rhvgoyal true, it doesn't seem to be heavyweight; just multi-step.  That is what I should have said.

**Comment by jthornber** [comment]
To calculate the number of exclusive blocks thin ls has to walk all the
meta data. A very slow process, so taking a meta data snap is not going to
add much relatively.

**Comment by ncdc** [comment]
@jthornber how long does it take to create the metadata snapshot so it can be used with thin_ls?

**Comment by jthornber** [comment]
A millisecond?

**Comment by ncdc** [comment]
@jthornber oh, so it's super fast? Is it available as soon as we finish calling `dmsetup message` or is it possible that there's a bit of a delay? I'm trying to make sure we can avoid a race condition where we send the `reserve_metadata_snap` message and then try to use `thin_ls` before the snapshot is ready.

**Comment by jthornber** [comment]
It will be available before the message completes.

**Comment by ncdc** [comment]
Sounds like there's no chance for a race. Great, thanks!

**Comment by sjenning** [comment]
Patch to update alpine thin-provisioning-tools package:
http://lists.alpinelinux.org/alpine-devel/5211.html

WIP for per-container dm thin stats:
https://github.com/sjenning/cadvisor/commit/cb00c4edc46974147fed9ff84b0330da062bc256

**Comment by sjenning** [comment]
Alpine Linux patch for thin-provisioning-tools package got pushed upstream
https://github.com/alpinelinux/aports/commit/1d40a0754c1eb42b01b8f87938e30723e70f554c

Not sure when the next rebuild is; monitoring:
https://pkgs.alpinelinux.org/packages?name=thin-provisioning-tools

**Comment by pmorie** [comment]
PR: #1204

**Comment by ravilr** [comment]
@sjenning @ncdc couldn't  find latest version of device-mapper-persistent-data-0.6* in RHEL7/CentOS7 repos. Do you know who can help disting this? Thanks.

**Comment by ncdc** [comment]
@vishh @timstclair we can close this now that 1204 is in, right?

@ravilr I'll check and see if I can get an ETA for when the newer RPMs will be available.

**Comment by timstclair** [comment]
I believe so. @pmorie is there anything left?

**Comment by pmorie** [comment]
I need to do a follow-up to check for thin_ls, that should be it.

**Comment by dashpole** [comment]
This appears to be resolved.  Please reopen if there is any more work to be done for this.
