### ISSUE TITLE
Export RSS size in /metrics

### ISSUE THREAD

**Issue by guoshimin** [google/cadvisor#975]
The metric exported as container_memory_usage_bytes includes page cache. It would be nice if cadvisor also exported the RSS size, which is often more interesting.

**Comment by jimmidyson** [comment]
Can you explain a bit more? Have to admit to not knowing this area very well, but how is RSS more interesting/useful? FYI we delegate collection of this to libcontainer to be consistent with `docker stats` but I don't mind if we have to do our own processing if cadvisor users have different requirements.

**Comment by f0** [comment]
@jimmidyson  RRS does not include the FS Cache, so its the real stack size for applications

**Comment by vishh** [comment]
+1. RSS is indeed useful.

**Comment by guoshimin** [comment]
@jimmidyson Page cache uses otherwise unused regions of memory. When the system is under memory pressure, page cache entries can be evicted without killing the process to which the page cache is attributed to.

**Comment by jimmidyson** [comment]
@guoshimin Thanks for the explanation - now I understand :) Certainly very useful - any chance you could submit a PR for it?

**Comment by guoshimin** [comment]
Yeah, happy to do it.

**Comment by jimmidyson** [comment]
That would be great - let us know if you need any pointers to get started.

**Comment by dqminh** [comment]
Not only rss but i think that all statistics from memory.stat should also be exposed. They are very helpful in many cases.

@jimmidyson @vishh wdyt ? Do we worry about exposing too many metrics by default without knobs for turning them off ?

**Comment by vishh** [comment]
We already expose a lot of metrics. As long as the cost for acquiring these
metrics isn't high, I think adding them is fine by me.

**Comment by dqminh** [comment]
>  As long as the cost for acquiring these metrics isn't high, I think adding them is fine by me.

Right, then i think its fine. We already have them in memory metrics, we just need to expose them to the world.

**Comment by guoshimin** [comment]
I prepared two branches, one (https://github.com/guoshimin/cadvisor/tree/icanhazrss) exposes only RSS, whereas the other (https://github.com/guoshimin/cadvisor/tree/exposeall) exposes all the metrics in memory.stat, of which I'm counting 31 on my system. I think exposing them all is better, but it does increase the size of /metrics page by about 50%. Please advise what's the best path forward.

**Comment by dqminh** [comment]
I would be fine with exposing all of them.
