### ISSUE TITLE
Kafka storage support for cAdvisor

### ISSUE THREAD

**Issue by arichardet** [google/cadvisor#980]
I'm currently looking to contribute by adding storage support with Apache Kafka. My plan is to use [Shopify's Kafka library, sarama] (https://github.com/Shopify/sarama). Do any contributors find an issue bringing in this library? Please advise.

**Comment by timstclair** [comment]
I believe this was fixed by https://github.com/google/cadvisor/pull/1033 (thanks!). Please reopen if that is not correct.
