### ISSUE TITLE
Does cadvisor support range selection?

### ISSUE THREAD

**Issue by xautjzd** [google/cadvisor#988]
I have googled and read some cadvisor docs, but can't find any words about performance data range selection.For example, get the latest 10 mins of cpu data, Is there any way to  resolve it?  Now I can get the default latest 1 mins data via API：/api/v1.0/containers/<absolute container name>,but I want to get an range  performance data via passing parameters start_time & end_time. 

Please give me some advise if you know. Thanks very much in advance.

**Comment by vishh** [comment]
cAdvisor supports `start` and `end` times. Look [here](https://github.com/google/cadvisor/blob/master/info/v1/container.go#L100). You will have to POST a json query object though.

**Comment by xautjzd** [comment]
@vishh I'm very happy to get your answer, Thank you!  But I can't still understand how to use. Can you give me an POST example?

I have try to post like this, but failed:
```
POST /api/v1.0/containers/{containerId}

{Start: "xxxx", End: "xxxx"}

or 

{ContainerInfoRequest : {Start:"xxx", End:"xxx"}}
```

**Comment by dashpole** [comment]
Post is different with any language.  From the command line you could do:
`curl -H "Content-Type: application/json" -X POST -d '{"key":"value"}' IP:PORT/ENDPOINT`
