### ISSUE TITLE
cadvisor fails to unmarshal container config with Docker 1.8.3

### ISSUE THREAD

**Issue by jimmidyson** [google/cadvisor#989]
Not sure if it happens with other versions prior to Docker 1.9, but since the merge of #966 to update runc container config fails to unmarshal properly. The problem is with this commit opencontainers/runc@c6e406af243fab0c9636539c1cb5f4d60fe0787f, turning certain fields e.g. https://github.com/opencontainers/runc/commit/c6e406af243fab0c9636539c1cb5f4d60fe0787f#diff-6318b8edda382c370345a4cb18e70b95R70 from string to slice.

@afein Would you be able to try to fix up?

**Comment by afein** [comment]
I will not have the time to actually dig into this in detail any time soon.

We can revert #966 and I can resubmit the Godep bump PR with the exact version of runc that corresponds to Docker 1.8.3. Would that be an adequate fix?

**Comment by jimmidyson** [comment]
Understand about time constraints. Thanks for replying.

I don't want to revert it as it will break with Docker >= 1.9 so need to come up with a way to handle it all, probably a custom Unmarshal function or something. I'll see if I can come up with something soon-ish.

**Comment by carmark** [comment]
@jimmidyson 

I have a simple fix, it works well after basic test.  I will submit a PR later when I do more test.

**Comment by jimmidyson** [comment]
@carmark awesome! Feel free to submit a PR now so we can help review, test, etc if you want.
