### ISSUE TITLE
Documentation of Go client is a bit broken

### ISSUE THREAD

**Issue by MattMattV** [google/cadvisor#997]
Links to ContainerInfo struct are broken
Description is now outdated since ContainerInfo is storing not only an int but an int and 2 time.Time

Maybe more examples or explanations or updating would be nice to understand how to use it.

**Comment by MattMattV** [comment]
bump

**Comment by vishh** [comment]
@timstclair: Can you handle this issue?

**Comment by timstclair** [comment]
Sure. I can work on this after k8s 1.2 is cut.

**Comment by timstclair** [comment]
Fixed the main issues. I agree that there is a large issue with the documentation and examples as a whole, but I'm going to close this for now.
